### ISSUE TITLE
Items in double when starred 

### ISSUE THREAD

**Issue by lascapi** [stefan-niedermann/nextcloud-notes#1023]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
A note starred is duplicated in the list view

**To Reproduce**
1. Go to 'All the Notes'
2. Click on a star not activated
3. Scroll a bit
4. See error: the note is starred and not

**Expected behavior**
Only the starred should be here

**Screenshots**
x | x | x
--- | --- | ---
![Screenshot_20210105-183501](https://user-images.githubusercontent.com/6562527/103679964-cf2cda80-4f85-11eb-9d03-096281ee25ba.png) | ![Screenshot_20210105-183517](https://user-images.githubusercontent.com/6562527/103679979-d48a2500-4f85-11eb-916b-1386044b6d7c.png) | ![Screenshot_20210105-183529](https://user-images.githubusercontent.com/6562527/103679986-d6ec7f00-4f85-11eb-8d88-7ecbf51e2f03.png)
![Screenshot_20210105-183539](https://user-images.githubusercontent.com/6562527/103679990-d8b64280-4f85-11eb-9ec1-b3fffd54d9c5.png) | ![Screenshot_20210105-183602](https://user-images.githubusercontent.com/6562527/103679994-d9e76f80-4f85-11eb-8bde-5857e456d6cc.png)

**Smartphone:**
 - Nextcloud Notes-Version (android app): 2.18.1
 - F-Droid or Play Store: F-Droid
 - Android-Version: 7
 - Device: Nexus5

**Server**
 - Nextcloud version: 19.0.4
 - Nextcloud Notes version (server app): 3.6.4

Thank you very much for your work guys and happys new year! :)

**Comment by stefan-niedermann** [comment]
Is fixed on the `master` branch and will be shipped with the next version.
