### ISSUE TITLE
Add an Activity or Shortcut to make a New Note

### ISSUE THREAD

**Issue by 0cwa** [stefan-niedermann/nextcloud-notes#1026]
I'm try to automate creating a new note in my launcher (Nova) so I can quickly jot down things I need to remember.   Adding this would also allow Tasker automation functionality.
You could automatically create the note for the default account selected and/or ~~enable another shortcut to allow changing your selected account~~ _(not necessary b/c of the move function)_

![Screenshot_20210106-173541_Nova_Launcher](https://user-images.githubusercontent.com/1490936/103848204-ef23d300-5045-11eb-8d26-99e2947448b7.png)
![Screenshot_20210106-173350_Nova_Launcher](https://user-images.githubusercontent.com/1490936/103848207-f0550000-5045-11eb-8324-a23cb9cce096.png)

**Comment by stefan-niedermann** [comment]
Hmm, there are already *lots* of create shortcuts:

- A shortcut when pressing long on the main launcher
- A tile for the quick settings of Android (pull down status bar)
- A widget which imediately creates a note

Why can't you utilize one of them? I personally don't like a second launcher for the app in the drawer. It will be confusing, even if we use a different launcher icon.

**Comment by 0cwa** [comment]
Sorry, I wasn't clear enough, I was not suggesting a second icon in the drawer.
The first photo is of Nova Settings > Gestures > (specific gesture) > Shortcuts (Apps to launch and Nova action ls also visible as options)
The second photo is of: Nova Settings > Gestures > (specific gesture) > Shortcuts > Activities
All the shown activities (second photo of previous post) just open up Nextcloud Notes.  Compare that to tasks.org (shown below) which allows me to select from a variety of activities including "Create new task".  I select that activity and I can add a task instantly.  I think what nova considers "shortcuts" and what you consider a shortcut are not the same because very few apps show up in the shortcut screen in nova, but all do in the activity subscreen, mostly with something along the lines of .MainActivity and a few other things.
This is more of an under-the-hood integration enhancement.
![Screenshot_20210107-005041_Nova_Launcher](https://user-images.githubusercontent.com/1490936/103885088-95da9480-5083-11eb-9430-ba2b6686cdab.png)
![Screenshot_20210107-005046_Nova_Launcher](https://user-images.githubusercontent.com/1490936/103885090-96732b00-5083-11eb-8bd1-90e1b358a9a8.png)

**Comment by 0cwa** [comment]
Sorry, I wasn't clear enough, I was not suggesting a second icon in the drawer.
The first photo is of Nova Settings > Gestures > (specific gesture) > Shortcuts (Apps to launch and Nova action ls also visible as options)
The second photo is of: Nova Settings > Gestures > (specific gesture) > Shortcuts > Activities
All the shown activities (second photo of previous post) just open up Nextcloud Notes.  Compare that to tasks.org (shown below) which allows me to select from a variety of activities including "Create new task".  I select that activity and I can add a task instantly.  I think what nova considers "shortcuts" and what you consider a shortcut are not the same because very few apps show up in the shortcut screen in nova, but all do in the activity subscreen, mostly with something along the lines of .MainActivity and a few other things.
This is more of an under-the-hood integration enhancement.

![Screenshot_20210107-010041_Nova_Launcher](https://user-images.githubusercontent.com/1490936/103885337-f5d13b00-5083-11eb-911b-79594a75d1e8.png)

![Screenshot_20210107-005046_Nova_Launcher](https://user-images.githubusercontent.com/1490936/103885090-96732b00-5083-11eb-8bd1-90e1b358a9a8.png)

**Comment by stefan-niedermann** [comment]
Have you tried to use `EditActivity`? When no arguments are passed to it, it will work as "`CreateActivity`". Internally we also use `EditActivity` for creating new notes.

**Comment by 0cwa** [comment]
When I use`EditActivity` I get the following error:

```
App Version: 2.17.1
App Version Code: 2017001
App Flavor: fdroid

Files App Version Code: 30140190

---

OS Version: 4.19.110-proton-v1.1-37803-g5b97da71f4cd(eng.dragon.20201215.231811)
OS API Level: 30
Device: bramble
Manufacturer: Google
Model (and Product): Pixel 4a 5G (bramble)

---

java.lang.RuntimeException: Unable to start activity ComponentInfo{it.niedermann.owncloud.notes/it.niedermann.owncloud.notes.edit.EditNoteActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at it.niedermann.owncloud.notes.edit.EditNoteActivity.launchReadonlyNote(EditNoteActivity.java:192)
	at it.niedermann.owncloud.notes.edit.EditNoteActivity.launchNoteFragment(EditNoteActivity.java:99)
	at it.niedermann.owncloud.notes.edit.EditNoteActivity.onCreate(EditNoteActivity.java:58)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	... 11 more

`````

**Comment by stefan-niedermann** [comment]
I dug into the code and it seems like Nova starts the Activity with the action `Intent.ACTION_VIEW`. This makes the Notes app think, that one wants to open a file with it (which is not given and therefore crashes).

However, i don't see any chance to fix this on our side, because a `Intent.ACTION_VIEW`, well... starts a viewer :smile: 
Sounds reasonable?

You should open a feature request upstream (at Nova) to allow to modify the Intent action to something more appropriate like `Intent.ACTION_INSERT_OR_EDIT` or maybe even a complete custom action like `com.nova.action.quicklaunch` or so.

**Comment by stefan-niedermann** [comment]
Closing because the Notes app already allows a creation by intent and this issue has to be fixed in the mentioned launcher.

**Comment by 0cwa** [comment]
Here, this is what they wrote me when I notified them, I didn't know what to say :/

```
 Hello,

 The activities shortcut is just to launch activities, it's up to the app in question for how they handle it (if at all) or what they do. If they want to send custom intents they should use something like Tasker for that.
```

**Comment by stefan-niedermann** [comment]
Well, what should i answer to this? It unfortunately changes nothing on the problem, that they only support to launch activities woth `Intent.ACTION_VIEW` and it doesn't sound like they want to make this behavior configurable.

This is a pitty, but there is a semantic difference between *viewing* and *editing* something. And this is nothing ideologistic but it has real effects: the `Intent.ACTION_VIEW` is used to distinguish between notes which are opened in a readonly mode (for example open plain text files from a file manager) and those which shall be edited. So there is nothing on the Notes apps side which we can do from my point of view.

I'd suggest to give `Tasker` a try as the Nova team suggested to close the gap.
