### ISSUE TITLE
Save page title when sharing from browser

### ISSUE THREAD

**Issue by skazi0** [stefan-niedermann/nextcloud-notes#1032]
**Is your feature request related to a problem? Please describe.**
When saving links as notes using Chrome's share feature the only content pasted to the note is the link. This is also used for title of the note and the filename when note is stored. This makes my "Links" category folder very hard to read (to humans at least).

**Describe the solution you'd like**
Most sharing targets (SMS, WhatsApp, etc) grab the page title followed by the link in second line. This should work correctly with "automatic titles" in nextcloud-notes (i.e. the page title should go to the note title and file name while the link should only be in the content).
It might be optional if there is some strong reason for current behavior.

**Describe alternatives you've considered**
I considered setting up some cronjob which would go over the saved link files, curl then addresses, grep the titles and rename the files :o)

**Additional context**
n/a

**Comment by stefan-niedermann** [comment]
Nice idea. Will be shipped with `v3.1.0` :slightly_smiling_face:
