### ISSUE TITLE
Automatic Formatting

### ISSUE THREAD

**Issue by Mossy93** [stefan-niedermann/nextcloud-notes#1039]
Hello,
I would love to see automatic formatting like you can find in many other markdown editors. Automatic continuation of lists, automatic bracketing, etc.
I think this would make the app much more usable for those of us who are trying to share our cloud with our less techie family members.
Thank you

**Comment by stefan-niedermann** [comment]
Lists as well as checklists are automatically continued already - when pressing `Enter` a new list item appears. If not, i need you to fill in the complete issue template (which is there for a reason 😉 )

**Comment by Mossy93** [comment]
Okay. I did not know they were supposed to continue. I will create an issue ticket for you.
