### ISSUE TITLE
Instant sync after change / faster sync

### ISSUE THREAD

**Issue by hyperglow** [stefan-niedermann/nextcloud-notes#1043]
I have no idea if this has been discussed before. 
For me what is really missing in the app is the instant sync with the server after changes have been done in a note. Or at least after a few seconds or when saving the note. When I checked this right the smallest sync rhythm is 15 minutes now. That is quite a long time in my opinion.

**Comment by stefan-niedermann** [comment]
Both is given. Notes are synced after after closing it abd every 5 seconds while editing it.

The background synchronization is an addition to avoid conflicting edits in case one opens and edits a note wuicker than the latest state can be fetched from the server.

**Comment by hyperglow** [comment]
Wonderful! I had the feeling! Maybe this could be mentioned in the settings menu near the sync setting. Or simply that the background sync is something extra. Thanks for the good work!

**Comment by stefan-niedermann** [comment]
Thanks for the kind words :)

Maybe i remove the background sync settings UI in the future and make the background sync implicit. Users shouldn't care about synchronization stuff, they just expect their notes to be up to date. :shrug:
