### ISSUE TITLE
in-note search

### ISSUE THREAD

**Issue by moshpirit** [stefan-niedermann/nextcloud-notes#106]
Would be adding a searcher inside the note (for long notes) a good idea?

Eg: I have a huge Markdown note for activism with links and descriptions. 

This would be very useful but I also understand that might be not a very used feature for other people.

Note: commented on #19

**Comment by jancborchardt** [comment]
Yeah, definitely. Simply a search icon in the top right next to the »more« icon just as in the main view would be good. :)

Then it’s search-as-you-type and the first result is directly focused. And the results placement could be highlighted in the scrollbar area (like Chrome does for example) to have a sense of placement.

**Comment by moshpirit** [comment]
Or even inside the menu if you want a simple aesthetic, I don't mind.

I don't use Chrome (or anything from Google) but I think I get what you say; the top bar became something like this:

- back button
- searcher
- last/next word as ↑↓ buttons

Right?

**Comment by jancborchardt** [comment]
Yup, that as well.

**Comment by geniusupgrader** [comment]
What is the status of this feature request?

**Comment by stefan-niedermann** [comment]
It has low priority for me but Pull Requests are welcome of course :-)

I provide 20,-€ for a working PR if someone is willing to take this.

**Comment by stefan-niedermann** [comment]
(i will hate myself for this, but:) how many can you eat at the conf? :laugh:

**Comment by mario** [comment]
I will give you one chance to edit your answer :D

**Comment by stefan-niedermann** [comment]
Your turn :)

**Comment by mario** [comment]
Replace with wine and done! :D

**Comment by stefan-niedermann** [comment]
Awaiting your PR ;-)

**Comment by stefan-niedermann** [comment]
#400
