### ISSUE TITLE
UX: Clearing local cache removes locally entered notes (add warning)

### ISSUE THREAD

**Issue by pasniak** [stefan-niedermann/nextcloud-notes#1068]
Please add reminder (in red!) that clearing storage (in Oh No dialogbox) will delete all notes not yet pushed to cloud.  I lost locally entered notes when trying to make my phone's notes sync.

<string name="error_dialog_tip_clear_storage">You can clear the storage by opening the app info and selecting Storage → Clear storage.</string>

**Comment by stefan-niedermann** [comment]
I agree and added a warning. It will be contained beginning with version `v3.1.4`.
