### ISSUE TITLE
Search Functionality

### ISSUE THREAD

**Issue by okkine** [stefan-niedermann/nextcloud-notes#1069]
First, let me say that I'm LOVING this app. Infinitely better than Google Keep. 

I have, however, noticed a minor annoyance when searching a note for a specific word/phrase. 

It seems that it starts search the document from the moment you type the first character. For example, if you're searching for"apartment", as soon as you type "a", it freezes while it searches for every word with an "a", then does it the same for "ap", then "apa", all the way down the line. This can cause it to freeze for a minute or two on an older phone like mine. 

It's not an urgent issue, but it would be nice to have the search feature wait until you hit a button before it begins the search. 

Out of curiosity, are there any plans for a NextCloud Calendar app? I'd LOVE to be able to ditch Google Calendar as well.

**Comment by stefan-niedermann** [comment]
How many notes do you have (count and total file size)?

> Out of curiosity, are there any plans for a NextCloud Calendar app? I'd LOVE to be able to ditch Google Calendar as well.

Use https://apps.nextcloud.com/apps/calendar and synchronize with https://play.google.com/store/apps/details?id=at.bitfire.davdroid

**Comment by stefan-niedermann** [comment]
@okkine [ping](https://github.com/stefan-niedermann/nextcloud-notes/issues/1069#issuecomment-782918027)

**Comment by okkine** [comment]
> @okkine [ping](https://github.com/stefan-niedermann/nextcloud-notes/issues/1069#issuecomment-782918027)

Oh! Didn't even see your reply! 

The file I'm having problems with is 64 kB. Not big, but a lot bigger than the rest of the notes. 

At the time of my original post, I only had the one note. Currently I have 46 notes in 11 folders, with a total size of 157 kB. 

It's not a show stopper, or anything. I just have to one big file, and it's still infinitely better than Google Keep. But still a bit of an annoyance. 

Thanks

**Comment by stefan-niedermann** [comment]
> it would be nice to have the search feature wait until you hit a button before it begins the search.

I'm afraid that the proposed solution will enhance the UX in one special edge case (huge note + weak device) while it will be a worse UX for everyone else. That's not an option for me, sorry.

There is a timeout before a new search gets triggered (`50ms`) which is a compromise that can be fulfilled by a quick typer without a large delay for everyone else - maybe you can try to stay below this limit to avoid unnecessary searches.

Of course, if you have an idea for a quicker search algorithm, a Pull Request will be welcome, but honestly, 64k are equal to **~17 Din A4 pages of text** - that's not the primary target of the Notes app which is actually meant for having shopping lists, small reminders or something like that, not writing books :laughing: 

If you have other suggestions how to improve the situation without negative impact for the majority of the users, just comment it here, i will happily listen and maybe we find a better solution :).
