### ISSUE TITLE
Notes visible during unlock

### ISSUE THREAD

**Issue by vzsze** [stefan-niedermann/nextcloud-notes#1070]
**Android version:** 10 and 11

**Device**: Samsung Galaxy S10

**System language**: German

**App version:** v3.1.3

**App source:** F-Droid

**Steps to reproduce:**
  1. open the app
  2. List of notes or last opened note is visible for a moment.
  3. Unlock with fingerprint appears. List of notes or last opened note is still visible in the background.

**Comment by stefan-niedermann** [comment]
Duplicate of #927
