### ISSUE TITLE
File format in the cloud.

### ISSUE THREAD

**Issue by nightingale-m** [stefan-niedermann/nextcloud-notes#1073]
It would be better if notes that are created through applications were in Markdown format, not .txt.  So it would be possible to edit Markdown files with other editors.

**Comment by stefan-niedermann** [comment]
You can change the file format in the web UI. At the bottom left in the settings section there's you can choose it.

![grafik](https://user-images.githubusercontent.com/4741199/109300313-a367fb80-7836-11eb-9511-4867ebafa0a5.png)

**Comment by Ged296123** [comment]
Can this option be accessed in the Android app? In other words, can the Android app save notes as .md files instead of .txt files?
