### ISSUE TITLE
Adding "last edited" as another sorting method.

### ISSUE THREAD

**Issue by hyperglow** [stefan-niedermann/nextcloud-notes#1074]
It would be great to have another sorting method for the notes to always have the notes which were recently edited at the top of the notes list.

**Comment by stefan-niedermann** [comment]
There already is this option. You can sort notes by last modified date or by alphabet. Use the icon next to your avatar to toggle between the two modes.

![Screenshot_20210302-211237_Nextcloud_Notizen](https://user-images.githubusercontent.com/4741199/109708702-068dc100-7b9c-11eb-9175-a0e28bc08c71.png)

**Comment by hyperglow** [comment]
I saw and used this icon, but my notes get sorted after "date created" or "alphabetical". I will give it another try...

**Comment by hyperglow** [comment]
Yes its totaly fine. Dont know what I saw. Sorry for stealing your time again :(

**Comment by stefan-niedermann** [comment]
No problem 🙂
