### ISSUE TITLE
Markdown difficulties

### ISSUE THREAD

**Issue by jslawler** [stefan-niedermann/nextcloud-notes#1086]
Using markdown on a portable device can be quite cumbersome, not to mention the learning curve for non-technical people, are there any plans in future to have buttons for things such as bold, italics, tick boxes, etc?

**Comment by stefan-niedermann** [comment]
Hi, please see [here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-arent-there-any-buttons-to-apply-formatting) 🙂
