### ISSUE TITLE
Option to see how many characters or/and words the note has

### ISSUE THREAD

**Issue by moshpirit** [stefan-niedermann/nextcloud-notes#1087]
On Nextcloud website version we can see in "Details" how many words and characters the note has, but this feature isn't on Nextcloud Notes. I'd love to have an option to see this in real-time. I don't think it should be difficult to implement, I imagine it like this (it can be in any other edge of the screen or even disappear when scrolling):

![bitmap](https://user-images.githubusercontent.com/7888062/110955935-675e8b80-834a-11eb-8b74-da45d7a3a305.png)

**Comment by Cui-Yusong** [comment]
Hello, I have an idea.
Is it possible to add a  function at the excerpt of the main page that shows the number of words in the text? In this way, the user can know the approximate word count of the article before browsing.

**Comment by stefan-niedermann** [comment]
Closing in favor of https://github.com/stefan-niedermann/nextcloud-notes/issues/1277 - this is nothing i plan to implement on the edit screen, but while redesigning the note details screen, we can add this information there.
