### ISSUE TITLE
Line spacing

### ISSUE THREAD

**Issue by karlprieb** [stefan-niedermann/nextcloud-notes#1089]
**Is your feature request related to a problem? Please describe.**

I feel that the spacing between the lines are to small and it make my readability experience poor
on both edit and preview views.

**Describe the solution you'd like**

Add an option to set a line spacing value or select between some predefined values.

**Comment by stefan-niedermann** [comment]
Yes, i agree that we should increase the line spacing, but we should find a sane value instead of providing an option for it.

I think we should make 3-4 screenshots with different values (maybe 100% - 150%) and post them here to compare them and ask a few Nextcloud designers what they prefer.

Do you want to contribute a Pull Request? 🙂

**Comment by karlprieb** [comment]
I don't know nothing about android, but I can try ;)

**Comment by stefan-niedermann** [comment]
**Preview Mode**

100% | 110% | 120% | 130%
--- | --- | --- | ---
![preview-1](https://user-images.githubusercontent.com/4741199/111866923-174a7f00-8971-11eb-9500-5e92b7b4e880.png) | ![preview-1 1](https://user-images.githubusercontent.com/4741199/111866929-1ca7c980-8971-11eb-855f-4cf00905fc9d.png) | ![preview-1 2](https://user-images.githubusercontent.com/4741199/111866934-229daa80-8971-11eb-898d-30e600b921a4.png) | ![preview-1 3](https://user-images.githubusercontent.com/4741199/111866974-5c6eb100-8971-11eb-882a-099543809361.png)



**Edit Mode**

100% | 110% | 120% | 130%
--- | --- | --- | ---
![edit-1](https://user-images.githubusercontent.com/4741199/111866939-27625e80-8971-11eb-9051-7d20853f5a8d.png) | ![edit-1 1](https://user-images.githubusercontent.com/4741199/111866942-29c4b880-8971-11eb-9f92-2656ac443fb7.png) | ![edit-1 2](https://user-images.githubusercontent.com/4741199/111866946-2b8e7c00-8971-11eb-98b6-a1265a7e065a.png) | ![edit-1 3](https://user-images.githubusercontent.com/4741199/111866972-5678d000-8971-11eb-834b-dc602292e713.png)

**Comment by stefan-niedermann** [comment]
Would like to hear some opinion from @jancborchardt and @nimisha-vijay :slightly_smiling_face:

**Comment by marcelklehr** [comment]
IMHO, 110%-120% looks best :heart:

**Comment by karlprieb** [comment]
Thank you @stefan-niedermann :)

**Comment by stefan-niedermann** [comment]
Okay, i also think both, 110% and 120% look good, so let's go for 115% for now. :slightly_smiling_face: 

Will be shipped with `v3.2.4`.
