### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by CamZie** [stefan-niedermann/nextcloud-notes#1095]
**Describe the bug**
502 Bad Gateway error on the Nextcloud Notes app on Android, when synchronising notes.

Notes can be synchronised from the phone to the web interface, but not the other way round.

This seems to only affect users that had been created before upgrading to Nextcloud version 20.0.7 from the latest 19.

**To Reproduce**
1. Create new note on the NC web interface
2. Open the 'Nextcloud Notes App on Android and try to synchronise
4. Sync fails with 502 error

**Expected behavior**
Synchronising notes using the Notes apps should work without any errors

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.2.2 and 3.2.3
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Samsung & BQ Aquaris

**Server**
 - Nextcloud version: 20.0.7
 - Nextcloud Notes version (server app): 4.0.3 and 4.0.4

**Stacktrace**

Nextcloud log
```
2021/03/18 13:19:14 [error] 2427#2427: *2828510 FastCGI sent in stderr: "PHP message: [owncloud][PHP][3] {"Exception":"Error","Message":"hex2bin(): Hexadecimal input string must have an even length at /var/www/nextcloud/lib/private/Security/Crypto.php#125","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"hex2bin(): Hexadecimal input string must have an even length","/var/www/nextcloud/lib/private/Security/Crypto.php",125,{"authenticatedCiphertext":"*** sensitive parameter replaced ***","password":"***REMOVED SENSITIVE INFORMATION***","parts":[null,null,null],"partCount":3}]},{"file":"/var/www/nextcloud/lib/private/Security/Crypto.php","line":125,"function":"hex2bin","args":[null]},{"file":"/var/www/nextcloud/lib/private/Encryption/Keys/Storage.php","line":303,"function":"decrypt","class":"OC\\Security\\Crypto","type":"->","args":["***sensitive parameters replaced***"]},{"file":"/var/www/nextcloud/lib/private/Encryption/Keys/Storage.php","line":104,"function":"getKey","class":"OC\\Encryption\\Keys\\Storage","type":"->...


2021/03/18 13:19:14 [error] 2427#2427: *2828510 upstream sent too big header while reading response header from upstream, client: ***REMOVED SENSITIVE INFORMATION***, server: ***REMOVED SENSITIVE INFORMATION***, request: "GET /index.php/apps/notes/api/v1/notes?pruneBefore=0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "***REMOVED SENSITIVE INFORMATION***"
```

Device log
```
App Version: 3.2.2
App Version Code: 3002002
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.141-20194519(A415FXXU1BTK5)
OS API Level: 29
Device: a41
Manufacturer: samsung
Model (and Product): SM-A415F (a41xx)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException:
HTTP request failed with HTTP status-code: 502
    at
com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
    at
com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
    at
it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
    at
it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
    at
it.niedermann.owncloud.notes.persistence.NotesClientV1.getNotes(NotesClientV1.java:31)
    at
it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:435)
    at
it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:349)
    at
it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
    at android.os.AsyncTask$3.call(AsyncTask.java:378)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
    at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

    at
com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
    at
com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
    at
com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
    at
com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
    at android.os.Binder.execTransactInternal(Binder.java:1056)
    at android.os.Binder.execTransact(Binder.java:1029)
```

**Comment by stefan-niedermann** [comment]
Well that's a strange one. What's in the server log? HTTP status codes >= 500 basically say, that the error happened at the server. Does the Web UI work?

**Comment by stefan-niedermann** [comment]
@korelstar any idea?

**Comment by korelstar** [comment]
This looks like a server-side error. The stack trace ("Nextcloud log") seems to be about storage encryption. However, it is not complete. It looks like it is taken from your web servers error log. Please provide also a log excerpt from the original `nextcloud.log`. You can find it in your Nextcloud's data directory.

Please also provide some more information about your server configuration: do you use encryption? Which exactly? Which storage do you use? Does the notes web app work? Can you access all (!) files using the files app? ...

**Comment by stefan-niedermann** [comment]
Closing [because of missing feedback](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed) and not related to the Android client.

**Comment by CamZie** [comment]
Thank you for the answers and sorry for the late feedback.

We were trying to reproduce the problem again but the synchronisation with the Notes apps suddenly works without making any further changes..

**Comment by support-criegerde** [comment]
Same issue:
App Version: 4.1.0 RC1
App Version Code: 40010051
App Flavor: fdroid

Files App Version Code: 30250090 (PROD)

---

OS Version: 5.10.157-android13-4-00002-g0eacbbcce3d5-ab9881766(10204971)
OS API Level: 33
Device: panther
Manufacturer: Google
Model (and Product): Pixel 7 (panther)

---

java.lang.Exception: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```


Nextcloud:
- App: notes: 4.8.0
- Nextcloud Release 26.0.3

**Comment by support-criegerde** [comment]
no sync from nor sync to Nextcloud possible anymore.
When opening the document within Nextcloud the content is deleted!
