### ISSUE TITLE
Option to Enable/Disable Screenshot Within the app

### ISSUE THREAD

**Issue by aaronhatesregex** [stefan-niedermann/nextcloud-notes#1098]
**Is your feature request related to a problem? Please describe.**

It would be great if you can add an option in the settings to prevent screenshot via `FLAG_SECURE` or something like that to add a bit more security. It's ok to not make that default but paranoids like me would love to have such option.

**Describe the solution you'd like**

Add this option in the settings

**Describe alternatives you've considered**

Not implement it at all since a malicious attacker can find another way or simply bypass it to get my bullshit notes.

**Comment by stefan-niedermann** [comment]
I have currently no plans to implement this, but a proper Pull Request will be accepted.

> Not implement it at all since a malicious attacker can find another way or simply bypass it to get my bullshit notes.

Made my day 😆

**Comment by aaronhatesregex** [comment]
> I have currently no plans to implement this, but a proper Pull Request will be accepted.

Sadly I dunno much about Java/Kotlin for now, but I'll keep this issue open in case some nerd shows up and slashes in my face with the proper code to compose a PR. Or feel free to close it due to inactivity after some time.

> ... made my day

Then I assume it's working as intended 🤣

**Comment by stefan-niedermann** [comment]
Ah screw it, it was very little work, so i just added it. Benefit for some people, so why not.

Will be shipped with `v3.3.0`.
