### ISSUE TITLE
[Question] "Password protection" under Security

### ISSUE THREAD

**Issue by aaronhatesregex** [stefan-niedermann/nextcloud-notes#1099]
**Is your feature request related to a problem? Please describe.**

The option "password protection" actually uses device credentials (PIN, pattern, fingerprint...) from what I see in #354, instead of an "app password" (which is available in Nextcloud app). So when a user usually unlocks the device with methods other than password, the description becomes kind of weird.

**Describe the solution you'd like**

Name it "App lock (Beta)" and add "Device credential" in the line below (which currently says "Beta").

**Describe alternatives you've considered**

Rename it to "Lock with device credential", "Protection using device credential" or something like that to make it more accurate. But it may be too long for an one-line description.

**Comment by stefan-niedermann** [comment]
Valid point :) I will adjust the text.

**Comment by stefan-niedermann** [comment]
Will be in `v3.2.4` - Might take some time though until all the translations are adjusted, so don't wonder if it's still the old wording in other languages for some time.
