### ISSUE TITLE
Widget background luminosity & transparency

### ISSUE THREAD

**Issue by pancan21** [stefan-niedermann/nextcloud-notes#1100]
Hello guys thank for developing the app!

Since the last update the widget doesn't have a dark transparant background anymore. Therefore it is not merging nicely with the rest of the homescreen. Secondly the white color disables all power saving features regarding the luminosity on OLED screens.

I would like to have an option that triggers light/dark mode also for the widget colors. And that there is a true black mode instead of a gray as dark mode available (because of OLED). If possible I would like to be able to choose the transparency for the widget as well.

I already changed inside the app to "dark mode" but that doesn't affect the widget.

Thanks in advance! Let me know if I can contribute in meaningful way without knowledge in android development :)

**Comment by stefan-niedermann** [comment]
Please read [here](https://github.com/stefan-niedermann/nextcloud-notes/issues/1090#issuecomment-798942023) and [here](https://github.com/stefan-niedermann/nextcloud-notes/issues/1093#issuecomment-800512052).
