### ISSUE TITLE
When creating a note named "2021-03-24 - Example title", the separator dash is removed

### ISSUE THREAD

**Issue by falzonv** [stefan-niedermann/nextcloud-notes#1104]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

- When creating a note with a filename having the format <code>2021-03-24 - Example note title</code>, the dash (-) between the date and the note title is removed and the file is displayed and saved as <code>2021-03-24 Example note title</code>.
- As long as they are not modified, existing notes keep their correct filename but the separator dash is not displayed anymore. On editing and saving the note, the dash is also removed from the filename.
- Using the renaming feature to add the dash does not work (it is removed again on saving).
- Everything works as expected with the Notes app on the server, this issue with the dash happens only in the Android app.
- This bug appeared after upgrading from v3.1.4 to v3.2.2.

**To Reproduce**
1. Create a new note
2. Give it the title <code>2021-03-24 - Example note title</code>
3. Move back to the list of all notes to save
4. The note is now named <code>2021-03-24 Example note title</code> (without the separator dash)
5. Checking on the server, the file have also been saved without the separator dash

**Expected behavior**

The filename should stay as entered by the user.
In this particular case, the dash between the date and the note title should not be removed.

**Screenshots**

Not applicable (well, it could be but I guess the description is clear enough so let's not waste servers space ;-)).

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.2.2 (bug appeared right after upgrade from 3.1.4)
 - F-Droid or Play Store: F-Droid
 - Android-Version: 8.1
 - Device: Motorola G5 Plus

**Server**
 - Nextcloud version: 17.0.10
 - Nextcloud Notes version (server app): 3.6.4

**Stacktrace**

Not applicable.

**Additionnal comments**

Thank you very much for providing this awesome application!

**Comment by stefan-niedermann** [comment]
Well described issue, thanks for that 🙂 

I guess it's happening while we try to remove markdown from the title. Probably it is considered as a list item. Will check this.

**Comment by falzonv** [comment]
Hello,

Browsing the commits before v3.2.2 with your hypothesis in mind, it seems the bug was introduced in 4119a926eaf6113373c87fab4b52a342696f11f7.

- In <code>NoteUtil.java</code>, there was the following change:
```
---  final String trimmedTitle = removeMarkdown(title.trim());
+++  final String trimmedTitle = removeMarkdown(replaceCheckboxesWithEmojis(title.trim()));
```

- And in <code>MarkdownUtil.java</code>, the line <code>s = s.replace(listType.listSymbolWithTrailingSpace, "");</code>

Maybe none of them is the culprit, but at first look that seems promising ;-)
*Note: I do not feel familiar enough with the code to suggest a PR that would solve the issue without breaking something else.*

Best regards.

**Comment by Cui-Yusong** [comment]
I have an idea which will roughly solve the bug while ensuring that Markdown syntax is handled.
Since the Markdown syntax is mostly at the beginning of each sentence, it is only necessary to determine whether the Markdown syntax exists at the beginning of the title, without removing the special characters in the middle of the title.This allows us to process the Markdown syntax without accidentally removing any special characters that the user wants to type.

**Comment by falzonv** [comment]
Indeed, this looks fine!
Thank you for the follow-up :-)

**Comment by stefan-niedermann** [comment]
Fixed in `v3.4.1` :slightly_smiling_face:

**Comment by falzonv** [comment]
Great, thank you very much!

**Comment by falzonv** [comment]
Hello,

This is to inform you that I installed v3.4.1 yesterday and that the dash is now allowed as expected, thank you again!

However, here are two additional remarks:

1/ Not sure if this is related but it may worth a check from your side: now when I create a note where the first line is a title (starting with one or several "#"), these "#" characters are also included in the filename.

1. Create a new note
2. Write "## Test" on the first line
3. Move back to the list of all notes to save
4. The note is now named "## Test" (with the markdown characters, expected result would be only "Test")
5. Checking on the server, the file have also been saved with the "#" characters (didn't even know it was possible!)

=> Tell me if you want that I create a separate issue for this bug ;-)

---

2/ Previously I wrote *"As long as they are not modified, existing notes keep their correct filename but the separator dash is not displayed anymore"* and this was only partially true.
=> After the update to v3.4.1, the dashes from not modified notes did not reappeared while they were present when checking on server side. My understanding is now that dashes were removed from all the notes in the client internal database so it was not only a display glitch (hopefully, for some unclear reason, it was not synchronized with server).
=> This was easily solved by clearing all data from the Notes application and adding my Nextcloud account again.

Best regards.

**Comment by stefan-niedermann** [comment]
> Tell me if you want that I create a separate issue for this bug ;-)

Yes, please.

Regarding the second topic: It affects only notes where the title is touched again. We currently do not know whether a title has been generated automatically from the first line or has been changed manually, so a migration is not possible - or at least it is so complex, that the risc of losing custom titles isn't justified in my opinion.

**Comment by falzonv** [comment]
Hello,

Ok, thank you for the explanation.

For the "#" bug, a separate issue is now created as #1205.

Best regards.
