### ISSUE TITLE
Device security not very secure

### ISSUE THREAD

**Issue by zynexiz** [stefan-niedermann/nextcloud-notes#1113]
After activating device security, the app ask for (in my case) authentication from my fingerprint. Although this is very good for securing access to the app, it still actually shows the notes before authentication is done (just somewhat dimmed down). If you fx have credit card number, passwords or other sensitive info there, someone can still access the information. 

The app should present a blank screen, or some other information before access is granted, like the behavior in the password manager as an example.

**Comment by stefan-niedermann** [comment]
Duplicate of #927
