### ISSUE TITLE
Unable to sync after selecting an account

### ISSUE THREAD

**Issue by janvonde** [stefan-niedermann/nextcloud-notes#1122]
**Describe the bug**
I updated to the latest version 3.0.0 from Google play this morning. When opening the app I was asked to choose an account for syncing. I selected one and cliicked OK. Then I was asked to allow access for Nextcloud Notes to the account. I chose "Accept".  Now a window with an error message was shown.

**To Reproduce**
1. Open Nextcloud Notes
2. Select an account for sync
3. Allow Access

**Expected behavior**
That syncing actually works and my notes appear as before ;-)

**Screenshots**
![one](https://user-images.githubusercontent.com/1824559/114136417-f12e5400-990a-11eb-9cc9-afc3ff2a851f.jpg)
![two](https://user-images.githubusercontent.com/1824559/114136425-f4294480-990a-11eb-8992-c7694bc630db.jpg)
![three](https://user-images.githubusercontent.com/1824559/114136434-f68b9e80-990a-11eb-9075-7576c3af2ac4.jpg)

**Smartphone:**
- App Version: 3.3.0
- App Version Code: 3003000
- App Flavor: play
- Files App Version Code: 30160052

**Server**
 - Nextcloud version: 20.0.9
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**
```
b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by stefan-niedermann** [comment]
Can you please check `v3.3.1`? I just published it at the Play Store beta channel, it might take some time until it is visible for you.

**Comment by janvonde** [comment]
I'll give it a try once it is visible for me and give you an update in ticket :+1:

**Comment by janvonde** [comment]
@stefan-niedermann works like a charm. Thanks for the quick response and bugfix! :smile:

**Comment by stefan-niedermann** [comment]
Yep, my bad 😜
