### ISSUE TITLE
no sync

### ISSUE THREAD

**Issue by brandtkjones** [stefan-niedermann/nextcloud-notes#1133]
It all of the sudden quit syncing.
Using Davx5 for Nextcloud sync 
LineageOS
Was working yesterday. Below is the bug report.

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.19.125-perf+(eng.root.20210411.020659)
OS API Level: 30
Device: OnePlus8T
Manufacturer: OnePlus
Model (and Product): KB2003 (OnePlus8T_EEA)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

```
Guidelines for submitting issues:

* Bug reports which do not fill the complete issue template will be closed.
* Please have a look at our [FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md)
* Please search the existing issues first, it's likely that your issue was already reported or even fixed.
* This repository is *only* for issues within the Nextcloud Notes Android app
-->
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

**To Reproduce**
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: 
 - Android-Version: 
 - Device: 

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by stefan-niedermann** [comment]
https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516

**Comment by brandtkjones** [comment]
Nice answer douchebag

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by stefan-niedermann** [comment]
Well, next time use the search function as stated in the issue template which you ignored or have a look at the pinned issues first.
Now go ahead and have fun with this open source app which you got for free on F-Droid.
