### ISSUE TITLE
notes app crashes after account selection

### ISSUE THREAD

**Issue by olegkrutov** [stefan-niedermann/nextcloud-notes#1148]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Crash before enter

**To Reproduce**
0. Install nextcloud from f-droid (and it works)
1. Install Notes app from f-droid
2. Open it 
3. Select an account
4. Crash

**Expected behavior**

Running app with notes synchronized

**Screenshots**

**Smartphone (please complete the following information):** 

see dump below

 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: 
 - Android-Version: 
 - Device: 

**Server**
 - Nextcloud version: 18.0.3
 - Nextcloud Notes version (server app): 

**Stacktrace**

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.4.192-perf+(V12.0.2.0.QFGRUXM)
OS API Level: 29
Device: lavender
Manufacturer: Xiaomi
Model (and Product): Redmi Note 7 (lavender_ru)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
See https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516
