### ISSUE TITLE
Error when adding Nextcloud account

### ISSUE THREAD

**Issue by hannesknutsson** [stefan-niedermann/nextcloud-notes#1149]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Can not add my nextcloud account to the app.
When picking my account I just get a big error message (pasted below)

**To Reproduce**
Install app
Place single note widget on home screen
Pick already logged in Nextcloud account

**Expected behavior**

A list of my notes should appear and i should be able to pick which one will be displayed in the widget

**Screenshots**

![Screenshot_20210414-193008_Nextcloud_Notes](https://user-images.githubusercontent.com/33489566/114753658-04508200-9d58-11eb-8e87-dacec7a6b99f.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.3.0
 - F-Droid or Play Store: F-Droid
 - Android-Version: 10
 - Device: Xiaomi Mi 9T (codename davinci)

**Server**
 - Nextcloud version: 20.0.8
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**
```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.213-LineageOS-gd263581e554a(eng.root.20210327.114801)
OS API Level: 29
Device: davinci
Manufacturer: Xiaomi
Model (and Product): Mi 9T (davinci)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
Please see here: https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516
