### ISSUE TITLE
Error when trying to access Nextcloud account - Synchronisation failed b.b.a.a.c.c

### ISSUE THREAD

**Issue by Teilkasko** [stefan-niedermann/nextcloud-notes#1152]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
Due to a change of my local network IP address I had to remove the old Nextcloud account from my phone and to create a new one pointing to the new IP address of the server. After having successfully connected to the new account from my phone and being able to access my data from within the Nextcloud app I tried to access the same account from within the Nextcloud notes app.

Without having an account set, upon starting the Nextcloud notes app it prompts me to select the Nextcloud account it shall use. I select my account and then the Nextcloud app asks me if I wish to grant the Nextcloud notes app access to the selected account. After clicking on `Approve` the notes app throws the error: `Synchronisation failed: b.b.a.a.c.c`

I tried to clear the cache and delete the app data but it did not solve the problem.

**To Reproduce**
1. Start Nextcloud notes app without having an Nextcloud account configured
2. Select desired Nextcloud account
3. Enter Nextcloud app PIN 
4. Allow Nextcloud notes app to access Nextcloud account from Nextcloud app
5. See error

**Expected behavior**
Access Notes stored in Nextcloud

**Screenshots**
![image](https://user-images.githubusercontent.com/31203844/114780478-fa824b00-9d66-11eb-9dfb-ec9cd20bcec5.png)

![image](https://user-images.githubusercontent.com/31203844/114780581-21408180-9d67-11eb-81f0-5dbdb4571f44.png)

![image](https://user-images.githubusercontent.com/31203844/114780631-31f0f780-9d67-11eb-8d1b-1fb8e89ced64.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.3.0
 - F-Droid or Play Store: F-Droid
 - Android-Version: 7.1.2
 - Device: XT1635-02 (Motorola Moto Z Play)

**Server**
 - Nextcloud version: 21.0.1
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**
```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 3.18.63-NPL26.118-20-gb5f9dfc4553(0c361fe81e)
OS API Level: 25
Device: addison
Manufacturer: motorola
Model (and Product): XT1635-02 (Moto Z Play)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i()
	at b.b.a.a.d.e.c()
	at it.niedermann.owncloud.notes.persistence.p.e()
	at it.niedermann.owncloud.notes.persistence.i.a()
	at it.niedermann.owncloud.notes.main.MainActivity.C0()
	at it.niedermann.owncloud.notes.main.MainActivity.D0()
	at it.niedermann.owncloud.notes.main.l.run()
	at java.lang.Thread.run(Thread.java:761)

```

**Comment by stefan-niedermann** [comment]
Upgrade to the latest available version `3.3.1`, where this issue has been fixed.
