### ISSUE TITLE
Capitalize keyboard when inserting new item in list

### ISSUE THREAD

**Issue by majjejjam** [stefan-niedermann/nextcloud-notes#1156]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

When adding a new item to a list (through hitting the return key whilst editing a list) you would expect the keyboard to shift capitalization. That way the next item would start with a capital letter, without you having to press the shift key.

**Describe the solution you'd like**

I'd like for the keyboard to shift capitalization when adding a new item to a list. 

**Describe alternatives you've considered**

The alternative would be to keep the behavior present (i.e. manual capitalization).

**Comment by stefan-niedermann** [comment]
As far as i know this is nothing that an app has influence to. As far as i know, this is only the job ob the corresponding keyboard app and i am not aware of any way to achieve this feature request within the Notes app.

Do you have other information and can tell me which API can be used to achieve this?

**Comment by stefan-niedermann** [comment]
Closing because my latest information is, that it is impossible to fix this in the Notes app. Will reopen of course if someone wants to start a PR or knows how this can technically be implemented.
