### ISSUE TITLE
Please tell me the code to display noteslist in dashboard via a widget

### ISSUE THREAD

**Issue by saurav475** [stefan-niedermann/nextcloud-notes#1159]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

**To Reproduce**
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: 
 - Android-Version: 
 - Device: 

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by stefan-niedermann** [comment]
This is the repository of **Notes Android**. I guess you will have more luck when asking in the [server apps repository](https://github.com/nextcloud/notes/issues/) when you are talking about the dashboard stuff.
