### ISSUE TITLE
Sync error: `b.b.a.a.c.c`

### ISSUE THREAD

**Issue by LulzLoL231** [stefan-niedermann/nextcloud-notes#1163]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

When try to select nextcloud account, app show error about synchronization.

**To Reproduce**
1. Open fresh installed app.
2. Choice your nextcloud account.
3. Give Notes access to your account from Nextcloud App.

**Expected behavior**

Full synchronization of my notes

**Screenshots**

**Server**
 - Nextcloud version: 21.0.1
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**
```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.1.18-g9ad0c34(C10B402)
OS API Level: 24
Device: HWFRD
Manufacturer: HUAWEI
Model (and Product): FRD-L19 (FRD-L19)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i()
	at b.b.a.a.d.e.c()
	at it.niedermann.owncloud.notes.persistence.p.e()
	at it.niedermann.owncloud.notes.persistence.i.a()
	at it.niedermann.owncloud.notes.main.MainActivity.C0()
	at it.niedermann.owncloud.notes.main.MainActivity.D0()
	at it.niedermann.owncloud.notes.main.l.run()
	at java.lang.Thread.run(Thread.java:776)

```

**Comment by stefan-niedermann** [comment]
Just update to 3.3.1
