### ISSUE TITLE
l10n: Text string for account deletion and synchronization

### ISSUE THREAD

**Issue by Valdnet** [stefan-niedermann/nextcloud-notes#1175]
Does this text string:
https://github.com/stefan-niedermann/nextcloud-notes/blob/ac114f21c6ed0df62425b578c1b2a744927b7576/app/src/main/res/values/strings.xml#L305-L306
is it correctly worded?

Maybe it should look like this:

- Removing the account %1$s will also delete **irrecoverable** one unsynchronized change irrecoverable.
- Removing the account %1$s will also delete **irrecoverable** %2$d unsynchronized changes irrecoverable.

Translator's report from Transifex.

**Comment by stefan-niedermann** [comment]
>    Removing the account %1$s will also delete **irrecoverable** one unsynchronized change irrecoverable.
>    Removing the account %1$s will also delete **irrecoverable** %2$d unsynchronized changes irrecoverable.

I guess you mean:

>    Removing the account %1$s will also delete **irrecoverable** one unsynchronized change ~~irrecoverable~~.
>    Removing the account %1$s will also delete **irrecoverable** %2$d unsynchronized changes ~~irrecoverable~~.

?

**Comment by Valdnet** [comment]
@stefan-niedermann Yes. That's what I meant 😉. When reconstructing the sentence, I copied it instead of cutting and pasting it.
