### ISSUE TITLE
Just updated nextcloud notes, and the app no longer loads anything

### ISSUE THREAD

**Issue by benwaffle** [stefan-niedermann/nextcloud-notes#1182]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

When opening the app, it immediately throws the error

**To Reproduce**
1. Update to 3.4.0
2. Open app

**Expected behavior**
App works normally

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.0
 - F-Droid or Play Store: fdroid
 - Android-Version: 10
 - Device: oneplus 7 pro

**Server**
 - Nextcloud version: 21.0.1.1
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**
```
App Version: 3.4.0
App Version Code: 3004000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.117-perf-g77a0c0f8a59c(eng.root.20210328.005239)
OS API Level: 29
Device: OnePlus7Pro
Manufacturer: OnePlus
Model (and Product): OnePlus 7 Pro (OnePlus7Pro)

---

com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Account not found in nextcloud files app
	at com.nextcloud.android.sso.AccountImporter.getSingleSignOnAccount(AccountImporter.java:192)
	at com.nextcloud.android.sso.helper.SingleAccountHelper.getCurrentSingleSignOnAccount(SingleAccountHelper.java:53)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$2$MainActivity(MainActivity.java:165)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$ZhWE-Elp2gTqL_Z3Kyw5s_28StU.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by benwaffle** [comment]
Also: the main nextcloud app works just fine. I can see all of my files.

**Comment by stefan-niedermann** [comment]
> The only change I can think that may have affected this was switch from Device Credentials to None under App passcode setting in nextcloud files

Nah, this shouldn't be an issue.

Have you already tried to remove the account from the Notes app and add it again? (Unsynchronized notes will get lost, so make a backup if you have one)

**Comment by benwaffle** [comment]
I can't access Notes settings to remove the account. Should I try clearing the app data?

**Comment by stefan-niedermann** [comment]
> I can't access Notes settings to remove the account.

According to the error message, the app did not crash. Why are you not able to remove the account? (You need to click on the avatar icon in the top right, not the settings).

>  Should I try clearing the app data?

Yes, please.

**Comment by benwaffle** [comment]
when i click on the avatar, nothing happens and nothing shows up

**Comment by stefan-niedermann** [comment]
Hmm. Yeah, try to clear the storage of the Notes app please.

**Comment by benwaffle** [comment]
clearing the app storage and re-setting it up fixed it 👍🏻

**Comment by stefan-niedermann** [comment]
Thanks, and sorry for the inconveniences. I'll close this issue as i have no idea how i possibly should be able to reproduce it - feel free to reopen if it occurs again :slightly_smiling_face:
