### ISSUE TITLE
fix the bug for the function insertLink() in MarkdownUtil

### ISSUE THREAD

**Issue by Cui-Yusong** [stefan-niedermann/nextcloud-notes#1186]
The insertLink() function has some problems when during with special cases.
When selectionStart is equal to selectionEnd, the function's performance is not as excepected.
For example, when want to insert link between the word, the function should auto add a blank. And when want to inset link in the work, the function should recognize the character's boundaries.

**Comment by Cui-Yusong** [comment]
This issue is the one I'm fixing, but I still have some questions about the return value of this insertLink() function.

```java
// Add link with clipboardUrl to normal text
builder = new SpannableStringBuilder("Lorem ipsum dolor sit amet.");
assertEquals(33, MarkdownUtil.insertLink(builder, 6, 11, "https://example.com"));
assertEquals("Lorem [ipsum](https://example.com) dolor sit amet.", builder.toString());
```

The return value of the upper one is 33, which is behind the example.com.

```
// TODO Add link with clipboardUrl to empty selection in word
builder = new SpannableStringBuilder("Lorem ipsum dolor sit amet.");
assertEquals(18, MarkdownUtil.insertLink(builder, 14, 14, "https://example.de"));
assertEquals("Lorem ipsum [dolor](https://example.de) sit amet.", builder.toString());
```

So, why is this one's return value not be 38, which is behind the example.de (the same as the first one)?

**Comment by Cui-Yusong** [comment]
I'm quite sorry about this question, and I've already fixed insertLink()'s other TODO.
This is the last TODO in this test.
Thanks very much for your answer. : )

**Comment by stefan-niedermann** [comment]
You are absolutely right, it makes more sense to put the cursor at position `38`. Adjust the test 🙂
