### ISSUE TITLE
Add support for the ability to lock your notes or app via biometrics

### ISSUE THREAD

**Issue by bruhdev1290** [stefan-niedermann/nextcloud-notes#1188]
**Is your feature request related to a problem? Please describe.**
 NO

**Describe the solution you'd like**

**Describe alternatives you've considered**
Possibly a pin login instead of a biometric login if the user prefers to lock their note or their app 

**Additional context**
i would like this feature as you can lock your notes or the app via the iOS notes app it would be nice to have this feature.

**Comment by stefan-niedermann** [comment]
The notes app allows to protect the notes with the same credentials you are using for your lockscreen - a separate locking mechanism is not planned.
If you phone is locked via fingerprint, the app will also be unlocked via fingerprint. If your phone is unlocked via pattern, the app will also be unlocked via pattern.

The setting is only visible if screen lock is configured in your Android settings.

Please note that the app locking is [still considered as a beta](https://github.com/stefan-niedermann/nextcloud-notes/issues/927).

**Comment by stefan-niedermann** [comment]
setting | unlock
--- | ---
![grafik](https://user-images.githubusercontent.com/4741199/116782471-a034fa00-aa89-11eb-8bc9-7bafc1d6410d.png) | ![grafik](https://user-images.githubusercontent.com/4741199/116782443-7f6ca480-aa89-11eb-90e8-c3bec3b2e32f.png)
