### ISSUE TITLE
Crash on start after update to versions 3.4.0, 3.4.1 - Konto in der Nextcloud App nicht gefunden

### ISSUE THREAD

**Issue by jfsgithub2020** [stefan-niedermann/nextcloud-notes#1192]
Until about 2 weeks ago (sorry, not very specific), I cannot use the notes app anymore. Nextcloud itself works flawlessly all the time on the android phone and in the browser.

Here is the crash log I received before the version as of today (3.4.0) and after the update to 3.4.1

The only idea from my side is a certificate issue. I am using Let's Encrypt certs but still get acceptance problems
with e.g. DAVx5 etc. As I said, nextcloud app works.

If I can supply anything else, let me know what.

Joachim

```
----------------------------------------------------------------------------

App Version: 3.4.1
App Version Code: 3004001
App Flavor: fdroid

Files App Version Code: 30150190
------------------------------------------------
OS Version: 3.18.71-perf-g4870138(2395)
OS API Level: 27
Device: bardock-pro
Manufacturer: bq
Model (and Product): Aquaris X Pro (bardock-pro)
------------------------------------------------
com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
at com.nextcloud.android.sso.AccountImporter.getSingleSignOnAccount(AccountImporter.java:192)
at com.nextcloud.android.sso.helper.SingleAccountHelper.getCurrentSingleSignOnAccount(SingleAccountHelper.java:53)
at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$2$MainActivity(MainActivity.java:167)
at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$ZhWE-Elp2gTqL_Z3Kyw5s_28StU.run(Unknown Source:2)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by stefan-niedermann** [comment]
Have you already tried to clear the storage and reimport your account [as described in the FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error)?

**Comment by jfsgithub2020** [comment]
Sorry, didn't read the FAQ as the app directly told me to report the issue. Yep, deleting the complete data (not the cache) and then reconnecting to the nextcloud account did the trick. Thx for the super fast reply!

**Comment by stefan-niedermann** [comment]
Yeah, the FAQ was also linked in the issue template which you ignored successfully 😅

Glad to hear that it works again, i'll have a look at the issue though. Maybe there's a bug which i haven't seen yet 🤷
