### ISSUE TITLE
Enhence the markdown manage process in the removeMarkdown()

### ISSUE THREAD

**Issue by Cui-Yusong** [stefan-niedermann/nextcloud-notes#1212]
Hello, after reading your discussion on the issue about handling markdown, I would like to do the following with the function remove Markdown().
Instead of the original process, I will use the markdown render as you've mentioned before to utilize the markdown text (without adding any new dependencies of course).
With this kind of process, there would not have issues like handling # in the title or something like that. Do you think it is feasible?
Thanks very much 😄

**Comment by stefan-niedermann** [comment]
Sure, go on 😄
