### ISSUE TITLE
App menu for dark theme

### ISSUE THREAD

**Issue by Valdnet** [stefan-niedermann/nextcloud-notes#1215]
For dark theme in the application menu some text strings are invisible (black font color).

![obraz](https://user-images.githubusercontent.com/47037905/118131899-622bc480-b3ff-11eb-9030-a514276c7e8d.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.1
 - F-Droid or Play Store: F-Droid
 - Android-Version: 10

**Comment by AlpAcA0072** [comment]
It seems that we only set the context like [`label_all_notes`](https://github.com/stefan-niedermann/nextcloud-notes/blob/d541ca921b66790182cf7f798fd1955e6e8012e1/app/src/main/res/values/strings.xml#L6) to the dark mode. Instead, we should set all the other context like [`action_trashbin`](https://github.com/stefan-niedermann/nextcloud-notes/blob/d541ca921b66790182cf7f798fd1955e6e8012e1/app/src/main/res/values/strings.xml#L11). However, I don't know where to change it.
@stefan-niedermann , could you please give some advice?

**Comment by stefan-niedermann** [comment]
Using the context of the view in favor of the application context to retrieve the color seems to fix the issue - sorry @AlpAcA0072 but while investigating the issue, it was quite easy to directly resolve it.

@Valdnet fix will be in `v3.4.3`
