### ISSUE TITLE
Nextcloud account not found in Nextcloud app

### ISSUE THREAD

**Issue by vzsze** [stefan-niedermann/nextcloud-notes#1222]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Nextcloud Notes App stopped working on my tablet, after installing a new version of Nextcloud App or Nextcloud Notes App or Android (I don't know what triggered the bug). The error message is "Synchronisierung fehlgeschlagen: Konto in der Nextcloud App nicht gefunden..."

Deinstalling and reinstalling the apps did not fix the issue. Importing accounts is not possible.

The app is still working fine on my phone.

**To Reproduce**
1. (Install and configure nextcloud app)
2. (Install nextcloud Notes App)
3. Start Nextcloud Notes App

**Expected behavior**

1. Show a list of notes.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.2
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Samsung Galaxy Tab 5e

**Server**
 - Nextcloud version: 21.0.1
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**
```
App Version: 3.4.2
App Version Code: 3004002
App Flavor: fdroid

Files App Version Code: 30160090

---

OS Version: 4.9.227-21312903(T725XXU2DUD7)
OS API Level: 30
Device: gts4lv
Manufacturer: samsung
Model (and Product): SM-T725 (gts4lveea)

---

com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
	at com.nextcloud.android.sso.AccountImporter.getSingleSignOnAccount(AccountImporter.java:192)
	at com.nextcloud.android.sso.helper.SingleAccountHelper.getCurrentSingleSignOnAccount(SingleAccountHelper.java:53)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$2$MainActivity(MainActivity.java:170)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$ZhWE-Elp2gTqL_Z3Kyw5s_28StU.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment]
Hi, please proceed as [described in our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error), we have a dedicated section about this error type 🙂
