### ISSUE TITLE
Cannot add widgets and sync fails upon trying to add

### ISSUE THREAD

**Issue by pixincreate** [stefan-niedermann/nextcloud-notes#1231]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Cannot add widgets to home screen. And gets a notification indicating the sync has failed.

**To Reproduce**
1. Go to 'Widgets' from home screen.
2. Click on 'Nextcloud notes widgets'
3. Click n Drag to 'home screen'
4. See error in the app and the widget vanished!

**Expected behavior**

I should be allowed to add widgets that exist already.

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.3
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Nokia 6.1 Plus LineageOS

**Server**
 - Nextcloud version: 3.16.0
 - Nextcloud Notes version (server app): mark.nl.tab.digital

**Stacktrace**
```
App Version: 3.4.3
App Version Code: 3004003
App Flavor: fdroid

Files App Version Code: 30160090

---

OS Version: 4.4.192-black_caps+(14)
OS API Level: 30
Device: DRG_sprout
Manufacturer: HMD Global
Model (and Product): Nokia 6.1 Plus (Dragon_00WW)

---

java.lang.Exception: {"errorType":"Error"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:160)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment]
> I should be allowed to add widgets that exist already.

Implies that you have been able to add a widget once. Is this assumption correct?

Can you at least tell which of the widget is this about? There are three different widgets.

> See error in the app and the widget vanished!

Is there any related error in your Nextclouds server log?

I can not reproduce the issue and though i am using Lineage OS myself, i can not support you without more information.

Maybe you can confirm that the issue is reproducible on another device (family or friends)? Ideally you could provide a logcat by running the app from Android Studio?

Have you tried to completely uninstall and reinstall the app?
Does this also hapoen with another launcher? (I guess you are using trebuchet?)

**Comment by pixincreate** [comment]
The 2 widgets just vanish away and takes me to the app which shows a toast notification "synchronisation failed".  
No server logs has been created either. I reinstalled the app and found the same issue.  
I dunno about launcher because, I'm using Customised OnePlus Launcher from Sluffy on telegram.(flashed with magisk).   
I've no friends/family members who use Nextcloud unfortunately, but I did install it my another phone and found similar results. 1x1 widget worked pretty perfectly. But the other 2 3x2 sized widgets didn't. Instead, they instantly opened the app.

**Comment by stefan-niedermann** [comment]
I do not really understand why you do not choose a category when the app prompts you to select one - or why you did not select a single note when the app asks you which one to display...?

**Comment by pixincreate** [comment]
Oh. May be lack of knowledge and misunderstanding has resulted in creating this issue.  
Anyway thanks for clarification.  
I'd thought that tapping and dragging that widget would be a ready to go note where I can read and edit instantaneously whenever needed and didn't even know only saved now can be added.  
Closing this issue, thanks again for thrwoing some light on it.

**Comment by stefan-niedermann** [comment]
Glad to hear that we could clarify this 🙂 Since you have been the first of more than 10k users who asked this question, i doubt we have a serious issue here, though i will think whether we can give a better hint that the user is supposed to choose something here 😄
