### ISSUE TITLE
Account not found ("Konto in der Nextcloud App nicht gefunden")

### ISSUE THREAD

**Issue by upost** [stefan-niedermann/nextcloud-notes#1240]
Suddenly the app stopped working, it doesn't show my notes anymore. I'm quite sure it worked one or two days before and I updated nothing.

Infos given by app:
App Version: 3.4.3

App Version Code: 3004003

App Flavor: fdroid

Files App Version Code: 30160090

\---

OS Version: 3.18.79+(1611623943)

OS API Level: 27

Device: Gigaset*GS270*plus

Manufacturer: Gigaset

Model (and Product): GS270 plus (GS270_plus)

\---

com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden

	at com.nextcloud.android.sso.AccountImporter.getSingleSignOnAccount(AccountImporter.java:192)

	at com.nextcloud.android.sso.helper.SingleAccountHelper.getCurrentSingleSignOnAccount(SingleAccountHelper.java:53)

	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$2$MainActivity(MainActivity.java:170)

	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$ZhWE-Elp2gTqL*Z3Kyw5s*28StU.run(Unknown Source:2)

	at java.lang.Thread.run(Thread.java:764)`

I noticed that on the server, the directory appdata_occ1xxxx/text had **vanished**. Nextcloud itself wasn't able to show or create any textfile on the web interface. I have no idea where the directory has gone. Anyway, I recreated it and then Nextcloud was luckily able to create and edit textfiles again, but Notes still gives the above error.

I cannot even tap the account symbol and the menu is empty. I could try to reinstall, but I keep the situation for now in case you want me to text anything.

Nextcloud App is working.  Version is 3.16.0.

Nextcloud is working. Version is 20.0.8.

Any ideas?

**Comment by stefan-niedermann** [comment]
aplease try to clear the storage of both, the Notes Android and the Nextcloud Android app as [described here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error). 

> the directory appdata_occ1xxxx/text had vanished. Nextcloud itself wasn't able to show or create any textfile on the web interface.

Looks more like some aftermaths of environment related issues than something we actually need to investigate deeper. If the issue persists, feel free to reopen filling the complete issue template 🙂

**Comment by upost** [comment]
Thank you. Clearing app data of the Notes app helped.
