### ISSUE TITLE
content can be seen even if app is locked

### ISSUE THREAD

**Issue by Cyanic76** [stefan-niedermann/nextcloud-notes#1245]
App loads content before asking for fingerprint unlocking, allowing everyone to see few notes even if app is locked

![app](https://cdn.discordapp.com/attachments/807525317593268234/849537460257292308/Screenshot_20210602-083810.png)

i'm using nextcloud notes v3.4.4

**Comment by stefan-niedermann** [comment]
Please use the 🔍 search function before opening new issues.

Duplicate of #927

**Comment by Cyanic76** [comment]
OK, I'm sorry
