### ISSUE TITLE
Plus sign in file name does not work

### ISSUE THREAD

**Issue by splitt3r** [stefan-niedermann/nextcloud-notes#1248]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
I have a note file with a `+` sign in its name. The Nextcloud notes app simply ignores the sign. It works in the Nextcloud Android app and the notes server app.

**To Reproduce**
1. Create a Note on the server side with a `+` in the file name (e.g. `test + test.md`
2. Open the Nextcloud Notes app
3. The file will be shown as `test test.md`

**Expected behavior**
The app should show the full file name.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.2.5
 - F-Droid or Play Store: Play
 - Android-Version: 10
 - Device: OnePlus 6

**Server**
 - Nextcloud version: 20
 - Nextcloud Notes version (server app): most recent

**Comment by stefan-niedermann** [comment]
This is by intention.
```
+ Foo
```

is interpreted as a list according to the commonmark specification, just like

```
* Foo
- Bar
```

You can also try it here on GitHub which also handles `+` signs as a list:

+ Item

The title is supposed to strip all markdown. Using `Foo + Bar` as title will work, using `+ Foo` will strip it therefore, as it is handeled as a list item.

**Comment by splitt3r** [comment]
That was fast 😄 but why do you need to strip markdown there? Isn't it possible to exclude the filename from the Markdown rendering? In that case you wouldn't have to strip the markdown parts from it.

Anyway i of course get your point here. But it is a bit strange that the behaviour deffers between the differen frontends.

**Comment by stefan-niedermann** [comment]
- It's simply easier to read a title if there is no markdown punctuation in it
- Many notes start with a `#` which looks awkward
- Keeping markdown punctuation destroys sorting by title alphabetically

an a few other reasons 😉 We kept the punctuation a long time ago, but noone was really happy with it and then we decided, also based on user feedback, to remove it.

**Comment by splitt3r** [comment]
Thanks for the additional context. Makes sense.
