### ISSUE TITLE
Change view of grid

### ISSUE THREAD

**Issue by Valdnet** [stefan-niedermann/nextcloud-notes#1254]
**To Reproduce**

1. Select "Settings" from the menu.
2. Select "Grid view".
3. Rotate the smartphone screen horizontally.
4. Turn the smartphone back vertically.
5. Exit the application settings (use the "Back" button of the smartphone's system navigation).
6. Hide the application menu by dragging it.

The notes view does not change. Only after exiting the application and restarting. This also happens when I want to set from grid view to list view.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.5
 - F-Droid or Play Store: F-Droid 
 - Android-Version: 10

**Comment by stefan-niedermann** [comment]
Strange - can't reproduce this... the settings is applied and rotating the device does not revert it in any way on my device... i'll try this on a few emulated devices...

**Comment by stefan-niedermann** [comment]
Nope, tried on a physical Android 11 device, an emulated Android 11 device and an emulated Android 5 device - works as expected.

Let's keep the issue open for a while, if someone else experiences this issue, we can have a closer look.

**Comment by Valdnet** [comment]
@stefan-niedermann This is only done when you press the "Back" button of the smartphone's system navigation in step 5 😉.

I corrected the reproduction steps.

**Comment by stefan-niedermann** [comment]
Doesn't make any difference here though... :slightly_frowning_face:

**Comment by Valdnet** [comment]
@stefan-niedermann I refined the last step 5 and added 6.

5. Exit the application settings (use the "Back" button of the smartphone's system navigation).
6. Hide the application menu by dragging it.

Maybe this can help you recreate the problem 😉.

I noticed that when exiting the application settings via the "Back" system button, the application window is not refreshed (no reloading) as it is when exiting through the application arrow button.

**Comment by thgoebel** [comment]
I can reproduce it on Notes 3.4.10, Android 11 (Lineage 18.1), OnePlus  5 and latest master (24b24139), Android 11, OnePlus 7.
Two points (I think) are crucial: a) rotate the screen to landscape and back again to portrait while your're still in the settings and b) use the navigation back button or the back swipe on Android 11.

If you throw in two log statements a la `Log.d("BUG", "onResume");` in onCreate and onResume you'll see that for some reason when you use the toolbar up arrow to return from the settings, onCreate is called. But when you use the system back navigation then only onResume is called. Which explains why the grid view is not correctly initialised.

If you don't do the rotation in the settings and just swipe/press system-nav-back, it seems that MainActivity's onResume is called, but then in addition onCreate is also called followed by a second onResume. Weird.

**Comment by stefan-niedermann** [comment]
The `MainActivity` is supposed to [completely recreate itself](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/main/MainActivity.java#L657-L665) in case something fundamental has changed in the settings - for example changing the theme or [the grid view mode](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/preferences/PreferencesFragment.java#L50) :thinking:.

**Comment by thgoebel** [comment]
Hm, maybe the rotation change (which causes the PreferenceActivity to be destroyed and recreated) causes this to be lost, resulting in wrong resultCode.

**Comment by stefan-niedermann** [comment]
That makes sense. I have been able to reproduce the issue now.

Probably it's enough to save the result code on `onSaveInstanceState` or use a `ViewModel` to store it. I will have a look when i have a bit more time.

**Comment by stefan-niedermann** [comment]
Yep, using a `ViewModel` lets survive the configuration change successfully. Fix will be shipped with `v3.4.11` :slightly_smiling_face: Thanks for the hints.

**Comment by Valdnet** [comment]
@stefan-niedermann @thgoebel Thanks for solving the puzzle and making the fix 🥇. I am waiting for a new version 😉.
