### ISSUE TITLE
Feature Request: Local mode (uses local synchronized notes folder) and will avoid SSL problems

### ISSUE THREAD

**Issue by mark-orion** [stefan-niedermann/nextcloud-notes#126]
I suggest a simple feature that would solve most of the authentication problems with self-signed certificates: A local mode that does not use any server connection at all. Because OwnCloud-Notes is file based, the main OwnCloud sync client can be used to sync the notes - no need for another account. The notes app only needs a way to point to the right notes folder.

**Comment by stefan-niedermann** [comment]
Nice idea, i just have concerns about where the server app will go - currently there are feature requests about labels and images and at least labels can not be mapped to a file based note... lets wait and see what happens at server

**Comment by stefan-niedermann** [comment]
I have currently no plans to move from the notes API to the WebDAV API, sorry.
Reason: The notes API does and will provide more and more features like categories which can not all be handled via WebDAV.

Though pull requests or hints how to solve the problem with self signed certs are very welcome and when i have more time, i will ask some devs of the nextcloud app how they are doing it.
