### ISSUE TITLE
Synchronization failed over and over

### ISSUE THREAD

**Issue by Nimitay** [stefan-niedermann/nextcloud-notes#1261]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

When I open the app the synchronization fails most of the time and gives me this error. 

 

> 
```
App Version: 3.4.8
App Version Code: 3004008
App Flavor: fdroid

Files App Version Code: 30160190

---

OS Version: 4.14.199-g548ba7616dc6-ab7185844(7246365)
OS API Level: 30
Device: sunfish
Manufacturer: Google
Model (and Product): Pixel 4a (sunfish)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.UnknownErrorException: Read timed out
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**To Reproduce**
1.Open app
2. Unlock with credentials 
3. Synchronization trys and fails
4. Gives me error

**Expected behavior**
No error and synchronization works

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.8
 - F-Droid or Play Store: fdroid 
 - Android-Version: 11
 - Device: Pixel 4a

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Hi @Nimitay

i just added a [dedicated section to our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#unknownerrorexception-read-timed-out). You should try to remove your account (after backing up unsynchronized changes) and import it again with the proposed procedure of the FAQ.

Besides that there ain't much more i can recommend you. Feel free to reopen if after performing those steps the error still appears with more information (how many notes do you have? how big are the changed notes? how big are all notes together? ....)

Regards
Stefan
