### ISSUE TITLE
Handle existing notes when changing URL or username

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#127]
(Enhancement)

If there are any notes on the user's device and the user wants to change the URL or username in the settings, ask whether to
1. copy notes to new account, or to
2. purge existing notes (warn if there are unsynchronized changes).

Both cases are reasonable, since a user may want to migrate to a new account and keep the data (1.), migrated the data already (2.) or wants to use another new/existing account (2.). However, the current behavior could be unexpected (unsynchronized notes are copied and the others are purged).

The implementation is easy: for 1., the status for all notes have to be set to `LOCAL_EDITED`, for 2., the database has to be cleared (warn if there are any notes with `status=LOCAL_EDITED`). More difficult is the UI for this. I would display a radio button or switch on the settings activity, above of the submit button. Where and when to display the warning?

**Comment by fxedel** [comment]
+1

**Comment by stefan-niedermann** [comment]
Hm... i agree that 2. is indeed a useful behavior, while i disagree that the first solution make sense.
If you are switching to another server, you usually will copy all files, too. Since the notes are stored by the server app as normal files, they will move. Now you have to consider that the notes are getting new IDs what will cause all notes are being recreated with new IDs and all notes will be duplicated.

By the way: The status has to be set to `LOCAL_CREATED`, wouldn't it? If we use `LOCAL_EDITED` the app will crash because we are trying to edit a not exisiting notes (since they will have new IDs)

**Comment by korelstar** [comment]
Of course, (1.) was only intended for the case that the user has not copied his files to the new server. Maybe he/she is not able to do this, but wants to keep the existing notes.

If you really want to implement (2.) only (without the option for 1.), the user has to be asked or warned, that the notes are to be removed at the client.

`LOCAL_CREATED` is deprecated. The app automatically (re-)adds a note, if editing fails because the server does not know the note (see https://github.com/stefan-niedermann/OwnCloud-Notes/blob/aa33b89927101c44d50215a5996dbf2a014c5346/app/src/main/java/it/niedermann/owncloud/notes/persistence/NoteServerSyncHelper.java#L227). However, for (1.) it would be better to also set `remoteId` to `null` in order to preserve overwriting of another note, that has the same ID on the new server.

**Comment by schaarsc** [comment]
this relates to #171

**Comment by stefan-niedermann** [comment]
I think it's time to rethink this topic from scratch.

While the app now supports multiple NC servers, maybe an approach like "move to another account" in the 3-dots-menu or an correspondenting bulk action (multi select) would fit better?

The use-case would be, that a NC server gets lost (deleted, terminated, resigned). The user can now still manage his notes on the app (with repeating toasts) and would be able to smoothly migrate all the notes to another account.

Moving would be as easy as changeing the `account-id`, resetting the `remote-id` and setting the `status` to `LOCAL_EDITED`.

What do you think @korelstar ? You raised the issue in the first place.

**Comment by korelstar** [comment]
I think the functionality "move to another account" should definitely be implemented, this is very useful. Using as bulk action is perfect.

However, just changing the account-id wouldn't be sufficient, since the next synchronization on the old account would bring the note back. You would have to add a new db entry for the new account (with `status=LOCAL_EDITED`) and set the old entry to `status=LOCAL_DELETED` (or the other way around).

Regarding the original issue: You're right, it seems to be obsolete now.

**Comment by stefan-niedermann** [comment]
Closing in favor of https://github.com/stefan-niedermann/nextcloud-notes/issues/655
