### ISSUE TITLE
Notes created via Android's "Share Link" feature are not synced

### ISSUE THREAD

**Issue by teatreeoilchocolate** [stefan-niedermann/nextcloud-notes#1272]
**Describe the bug**

Notes created via Android's share feature are not synced. Settings "Background-Sync" in app turned on will not solve the problem.

**To Reproduce**
1. Go to 'Browser of your choice'
2. Navigate to a website you like to share
3. Choose "Share Link"
4. Select "Nextcloud Note" (New Note)
5. Touch back-button (Triangle in OS-Menu at the bottom)
6. Continue browsing and repeat from point 2 as often as you like
7. Open Nextcloud-Notes
8. See that the links/notes are created
9. Go to Nextcloud-Server
10. See that links/notes are not present

**Expected behavior**
Notes created via the "Share link" feature are treated just like any other note(edited or new) and synced automatically.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.10
 - F-Droid or Play Store: F-Droid (with no Gapps or similar G-Framework)
 - Android-Version: LineageOS 18.1(Android 11)
 - Device: Oneplus 5T

**Server**
 - Nextcloud version: 21.0.2 (corresponding debian/apache2-based docker image, PHP7.4)
 - Nextcloud Notes version (server app): 3.5.1

**Additional Information**
I am not an Android developer, but from what I gather, the notes created this way(share link) behave just like regular notes, I can edit them, their timestamp is updated and they are synced to the server, so the information is not lost, but due to the reordering based on the timestamp it is rather confusing to sync them this way, especially when there is  a chance of overlooking some. 
The ability to sync notes automatically when creating them in the app, without "share link", leads me to believe that this is not a problem related to the server-side. I first thought I had the same problem as https://github.com/stefan-niedermann/nextcloud-notes/issues/761 , but that problem was due to an unusually high DB-load. After the end of that surge, the problem ,as described, persisted and no other spike in DB-load was caused.

**Comment by stefan-niedermann** [comment]
Indeed, i can confirm this. As a workaround until this bug has heen fixed, change the note after adding (for example by adding a space character or mark / unmark it as favorite) so it will get synchronized in the next cycle. Thanks for the report!
