### ISSUE TITLE
Outline support? Like the one in MarkdownX

### ISSUE THREAD

**Issue by dasfsadfaf** [stefan-niedermann/nextcloud-notes#1273]
**Is your feature request related to a problem? Please describe.**
Sometimes a note is very big. A outline view helps a lot.

**Describe the solution you'd like**
A outline view helps a lot.  Like the one in MarkdownX

**Describe alternatives you've considered**
none

**Comment by renfenghuan** [comment]
Another man requested the same feature a long time ago, but without reply.
https://github.com/stefan-niedermann/nextcloud-notes/issues/1060#issue-805973782

**Comment by renfenghuan** [comment]
Well, I'm working on it by myself. Looks like not so hard to implement. Maybe I'll start a pull request soon.

**Comment by renfenghuan** [comment]
Done, see https://github.com/stefan-niedermann/nextcloud-notes/pull/1274

**Comment by stefan-niedermann** [comment]
@ghost why did you close this issue and the PR? We haven't merged it yet?
