### ISSUE TITLE
Checkboxes using an uppercase X can not be toggled

### ISSUE THREAD

**Issue by accountForIssues** [stefan-niedermann/nextcloud-notes#1276]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Some external editors use an uppercase `[X]` when checking a checkbox. This causes weird issues while editing the same note using the android notes app.

**To Reproduce**
1. Use either only `[X]` for check boxes or a mixture of `[X]` and `[x]` among other unchecked ones.
2. Try to check the unchecked boxes.
3. Issue

**Expected behavior**

The box that needs to be toggled has to be toggled leaving others untouched.

**Screenshots**

https://user-images.githubusercontent.com/52367365/122960496-c12c1400-d383-11eb-91f5-bd15442197c0.mp4

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.10
 - F-Droid or Play Store: F-Droid
 - Android-Version: 10
 - Device: Samsung S9+

**Server**
 - Nextcloud version: 21.0.2
 - Nextcloud Notes version (server app): 

**Comments**
I have verified that using only lowercase `[x]` solves this but it'd be a good idea to support both `[x]` and `[X]`.

**Comment by stefan-niedermann** [comment]
Thanks for the report! The fix will be shipped in version `3.4.11`.
