### ISSUE TITLE
Search field does not immediately focus

### ISSUE THREAD

**Issue by thgoebel** [stefan-niedermann/nextcloud-notes#1282]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

The search field in the main screen does immediately focus when clicking on the search bar.
The keyboard only comes up upon clicking the search bar a second time.

**To Reproduce**
1. Click on the search bar in the MainActivity ("Search all notes")
2. Click again on the search bar (that now displays the EditText)
3. See the keyboard coming up.

**Expected behavior**

The keyboard should come up and the EditText should focus upon the first tap on the search bar (the one that transforms the bar from the MaterialCard-look into an EditText).
Much like the search in a details screen.

**Screenshots**

n/a

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.10
 - F-Droid or Play Store: F-Droid
 - Android-Version: Android 11 / Lineage 18.1
 - Device: OnePlus 5 (cheeseburger)

**Server**
 - Nextcloud version: n/a
 - Nextcloud Notes version (server app): n/a

**Stacktrace** n/a

**Comment by stefan-niedermann** [comment]
Fix will be shipped in `v3.4.11` - thanks for the report :slightly_smiling_face:
