### ISSUE TITLE
compact codeblocks 

### ISSUE THREAD

**Issue by markushub** [stefan-niedermann/nextcloud-notes#1296]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

Creating and watching notes with sourcecode blocks takes vertical space for empty lines. 

Currently an additional empty line is necessary before a codeblock (only in edit mode)

e.g.

    ## Listing1 with empty line

    ```
    #! /bin/bash
    echo "codeblock"
    ```

**Describe the solution you'd like**

    ## Listing2 without empty line should also be a codeblock
    ```
    #! /bin/bash
    echo "codeblock"
    ```

**Describe alternatives you've considered**

switch to preview mode detects both as codeblock

**Additional context**

I'm on v3.4.11.

And in preview mode maybe the vertical space could be reduced less then a complete empty line.

Maybe it's just an parsing issue.

Thank you for the great android app. I daily use it.

**Comment by stefan-niedermann** [comment]
Hi @markushub :wave:,

the rendering is done by `Markwon`, so i'd like to ask you to open this issue upstream: https://github.com/noties/Markwon/issues/new

It is nothing that we can directly influence in the Notes app.

Regards

**Comment by stefan-niedermann** [comment]
PS.: Since they request the version of `Markwon`: Notes currently uses `4.6.2` of `Markwon` which is also the latest published release of `Markwon`.
