### ISSUE TITLE
New account: java.lang.NullPointerException: Attempt to invoke virtual method 'int it.niedermann.owncloud.notes.persistence.entity.Account.getColor()' 

### ISSUE THREAD

**Issue by rugk** [stefan-niedermann/nextcloud-notes#1305]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

When I connect a new account via the Nextcloud app I get the following error.

**To Reproduce**

```

App Version: 3.4.11

App Version Code: 3004011

App Flavor: fdroid

Files App Version Code: 30160190

---

OS Version: 4.9.218-perf+(05131326)

OS API Level: 29

Device: FP3

Manufacturer: Fairphone

Model (and Product): FP3 (FP3)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'int it.niedermann.owncloud.notes.persistence.entity.Account.getColor()' on a null object reference
	at it.niedermann.owncloud.notes.main.MainViewModel.postCurrentAccount(MainViewModel.java:121)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$0$MainActivity(MainActivity.java:177)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$herSCsajIfxGZk6iBYSe7-CVE7Q.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: 
 - Android-Version: 
 - Device: 

**Server**
 - Nextcloud version: 22.0.0.11 (server), 3.16.1 (Android app)
 - Nextcloud Notes version (server app): 4.1.0, I double-checked it is enabled, as the error message tells me

There was no server request at that time, so it does not actually contact the server.

**Stacktrace**
see above

**Comment by rugk** [comment]
Hmm got a strange similar error with Nextcloud Talk, it claims the app is not installed on the server… :thinking:

**Comment by stefan-niedermann** [comment]
@rugk which appe are you using for taking Notes? Nextcloud Notes Android works **only** in combination with the [Notes](https://apps.nextcloud.com/apps/notes) app - Not QuickNotes, not NextNotes, not SimpleNotes, not anything else. Do you have installed the correct app?

Have you already tried to clear the storage of your app as [described here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#tokenmismatchexception-and-all-others)?

**Comment by rugk** [comment]
> Nextcloud Notes version (server app): 4.1.0

It is the correct app.

**Comment by rugk** [comment]
Clearing the storage solved the thing thanks!

It was the same account, just under a new domain, so I deleted the old account in the Notes app and re-imported it. :slightly_smiling_face:

**Comment by stefan-niedermann** [comment]
Perfect, thanks for the feedback! :)
