### ISSUE TITLE
Check/Uncheck not possible, when indented

### ISSUE THREAD

**Issue by IngoBelka** [stefan-niedermann/nextcloud-notes#1311]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

I made a checklist with indentation like this:

- [ ] first
- [ ] second
- - [ ] second first
- - [ ] second second

**To Reproduce**
1. make a list like above
2. try to check or uncheck an item
3. try it onesmore
4. uncheck or check wan't work proper or doesn't

**Expected behavior**

Uncheck/check should work. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.11
 - F-Droid or Play Store: F-Droid
 - Android-Version: 9, 10
 - Device: Huawei MediaPad 5, Xiaomi Mi 9T

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Because this is not a valid check list. There are additional dashes (`-`) at the nested items which do not belong there.

Your sample:

```
- [ ] first
- [ ] second
- - [ ] second first
- - [ ] second second
```

Valid checklist:

```
- [ ] first
- [ ] second
  - [ ] second first
  - [ ] second second
```

**Comment by IngoBelka** [comment]
> Because this is not a valid check list. There are additional dashes (`-`) at the nested items which do not belong there.
> 
> Your sample:
> 
> ```
> - [ ] first
> - [ ] second
> - - [ ] second first
> - - [ ] second second
> ```
> 
> Valid checklist:
> 
> ```
> - [ ] first
> - [ ] second
>   - [ ] second first
>   - [ ] second second
> ```

Thanks for clarification 😀
