### ISSUE TITLE
Bug by building apk

### ISSUE THREAD

**Issue by Twenty4marc** [stefan-niedermann/nextcloud-notes#1317]
error: cannot access EditText
public class MarkwonMarkdownEditor extends AppCompatEditText implements MarkdownEditor {
       ^
  class file for android.widget.EditText not found

**Comment by stefan-niedermann** [comment]
App building works reproducibly fine - (see [pipeline](https://github.com/stefan-niedermann/nextcloud-notes/runs/3312343216?check_suite_focus=true)).

**Comment by Twenty4marc** [comment]
I cant build apk :((((

**Comment by stefan-niedermann** [comment]
Then use the built apk from the Play Store, from F-Droid or from the build pipeline 🤷 

Sorry, but i have no time to provide this kind of low level support for custom builds. This is a plain Android project which requires no configuration and runs with Android Studio Arctic Fox out of the box. Try clearing your caches and restart your IDE.
