### ISSUE TITLE
Internet availability may not be being verified in project

### ISSUE THREAD

**Issue by amazuerar** [stefan-niedermann/nextcloud-notes#1319]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Dear Developer!

My name is Alejandro Mazuera-Rozo, I am a PhD Student at Universidad de los Andes, and at Università della Svizzera italiana. I am part of a research on the usage of network libraries within android apps. As a result of this we identified that there is a missing validation of Internet availability within the project which is needed since some network operations are being performed in the application. 

**To Reproduce**

Not applicable since this issue was found by performing a static analysis on source code

**Expected behavior**

As you might know, a device may be connected to a network but may not have Internet connection. Therefore it is recommended for the app to identify whether the device is connected to a network having Internet connectivity before performing a network operation.

In order to address this issue we recommend you to:

1. Obtain representation of the capabilities of an active network, they are typically obtained through `NetworkCallback#onCapabilitiesChanged(Network, NetworkCapabilities)` or `ConnectivityManager#getNetworkCapabilities(Network)`
2. See: https://developer.android.com/reference/android/net/NetworkCapabilities
3. See: https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_INTERNET
4. See: https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_VALIDATED

**Screenshots**

N/A

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app):  N/A
 - F-Droid or Play Store:  N/A
 - Android-Version:  N/A
 - Device:  N/A

**Server**

N/A

**Stacktrace**

N/A

**Comment by stefan-niedermann** [comment]
Internet availability is checked before performing a synchronization in [`NotesRepository`](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesRepository.java#L159) by registering a `BroadcastReceiver`.
