### ISSUE TITLE
Network Type may not be being verified in project

### ISSUE THREAD

**Issue by amazuerar** [stefan-niedermann/nextcloud-notes#1320]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Dear Developer!

My name is Alejandro Mazuera-Rozo, I am a PhD Student at Universidad de los Andes, and at Università della Svizzera italiana. I am part of a research on the usage of network libraries within android apps. As a result of this we identified that there is a missing validation of the network type within the project which is needed since some network operations are being performed in the application. 

**To Reproduce**

Not applicable since this issue was found by performing a static analysis on source code

**Expected behavior**

As you might know, a device can have various types of network connections. For the full list of possible network types, see https://developer.android.com/reference/android/net/ConnectivityManager. Therefore it is recommended for the app to identify the type of network available before performing a network operation.

In order to address this issue we recommend the following resources:

1. https://developer.android.com/training/basics/network-ops/managing
2. https://developer.android.com/training/efficient-downloads/connectivity_patterns
3. https://developer.android.com/reference/android/net/NetworkCapabilities 
4. Applications should use `NetworkCapabilities#hasTransport` or `requestNetwork(android.net.NetworkRequest, android.net.ConnectivityManager.NetworkCallback)` to request an appropriate network.

**Screenshots**

N/A

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app):  N/A
 - F-Droid or Play Store:  N/A
 - Android-Version:  N/A
 - Device:  N/A

**Server**

N/A

**Stacktrace**

N/A

**Comment by stefan-niedermann** [comment]
Network type (Wi-Fi vs. mobile data) is checked in [`NotesRepository#updateNetworkStatus`](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesRepository.java#L907).
