### ISSUE TITLE
Internet availability may not be being verified in methods

### ISSUE THREAD

**Issue by caev03** [stefan-niedermann/nextcloud-notes#1322]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
Dear Developer!

My name is Camilo Escobar, I am a PhD Student at Universidad de los Andes, Colombia. I am part of a research on the usage of network libraries within android apps. As a result of this we have identified some code locations that might have a missing validation of Internet availability, validation that is needed since some network operations are being performed within some methods.

**To Reproduce**
N/A

**Expected behavior**
As you might know, a device may be connected to a network but may not have Internet connection. Therefore it is recommended for the app to identify whether the device is connected to a network having Internet connectivity before performing a network operation.

In order to address this issue we recommend you to visit:

    https://developer.android.com/reference/android/net/NetworkCapabilities
    https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_INTERNET
    https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_VALIDATED

**Snapshots** (Potential Code Location missing Internet connectivity validation)

https://github.com/stefan-niedermann/nextcloud-notes/blob/3c95434b2080f6cd1500b54ee805a04596cb9e69/app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesServerSyncTask.java#L111-L125

**Smartphone (please complete the following information):**
N/A

**Server**
N/A

**Stacktrace**
N/A

**Comment by stefan-niedermann** [comment]
`pushLocalChanges()` is executed within the `run()` method of `NotesServerSyncTask`. The network connectivity is checked in `NoteRepository#scheduleSync` (see the `isSyncPossible()` check before creating the `NotesServerSyncTask` instance and calling the `run()` method.

The `isSyncPossible` flag is updated within `updateNetworkStatus()` which is called by a `BoradcastReceiver` called `networkReceiver` that is registered in the constructor of `NotesRepository`.

Let me know if i missed something, but as far as i can see, the network connectivity is checked properly.
