### ISSUE TITLE
Network type may not be being verified in method

### ISSUE THREAD

**Issue by caev03** [stefan-niedermann/nextcloud-notes#1324]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Dear Developer!

My name is Camilo, I am a PhD Student at Universidad de los Andes, Colombia. I am part of a research on the usage of network libraries within android apps. As a result of this we identified that there is a missing validation of network type within a method since some network operations are being performed in it. As you might know, a device can have various types of network connections. For the full list of possible network types, see https://developer.android.com/reference/android/net/ConnectivityManager. Therefore it is recommended for the app to identify the type of network available before performing a network operation.

Note: Wi-Fi is typically faster. Also, mobile data is often metered, which can get expensive. A common strategy for apps is to only fetch large data if a Wi-Fi network is available.

In order to address this issue we recommend you to visit:

1. https://developer.android.com/training/basics/network-ops/managing
2. https://developer.android.com/training/efficient-downloads/connectivity_patterns

**To Reproduce**
N/A

**Expected behavior**
N/A

**Snapshot** (Potential Code Location without Network type validation)

https://github.com/stefan-niedermann/nextcloud-notes/blob/a38fcd1210d8a0c46921e82012a8f312a23a2199/app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesServerSyncTask.java#L111-L125

**Smartphone (please complete the following information):**
N/A

**Server**
N/A

**Stacktrace**

**Comment by stefan-niedermann** [comment]
See https://github.com/stefan-niedermann/nextcloud-notes/issues/1322#issuecomment-917380672

Note that `updateNetworkStatus()` respects the `syncOnlyOnWifi` setting.
