### ISSUE TITLE
Adding timestamp inside a note / templating a note

### ISSUE THREAD

**Issue by AlfredEVOL** [stefan-niedermann/nextcloud-notes#1333]
it would be great if the notes had a header with the timestamp.
i use one on my pc with the header being `"_$(date +"%Y-%b-%d-%R")_"`

Or it would also be good if there were templates(user defined) for notes , tho things like date might require some work

**Comment by stefan-niedermann** [comment]
Well that's a kind of feature which would also need to be implemented in the server side app as the Android app follows the feature scope of the server app.

I'd suggest to [request your feature there](https://github.com/nextcloud/notes/issues/new?assignees=&labels=needs+discussion%2C+feature+request&template=feature_request.md&title=) therefore and **if** it gets implemented, we can reopen this discussion.
