### ISSUE TITLE
Feature request: add an icon-like widget that simply takes you to the note

### ISSUE THREAD

**Issue by SamuXzX** [stefan-niedermann/nextcloud-notes#1346]
**Is your feature request related to a problem? Please describe.**

I'd like to have some notes accessible from my launcher, buy I'm not satisfied with the widgets we already have: form my usage the list-one needs lots of space and tapping on a line of text isn't as comfortable as tapping on an icon in the launcher, while the single note widget we already have gets a strange look if I resize it to occupy only one square in the launcher and it containts text that gets cut.
I don't need to be able to read the note in the homescreen, just to open it in fewer taps than possible. Surely I can simply enter the app and quickly reach the note, but I hope you understand with me that this simple widget could be useful and comfortable for every user.

**Describe the solution you'd like.**

May we start creating this widget, design would be the hardest part to think of. If the widget consists only of an 1x1 icon in the launcher, it surely would need to have the title of the note at the bottom like every app in the launcher. As for the icon itself, maybe we can think of a default image, similar to the icon of nextcloud-notes, or something that identifies the note itself, like the first character of the title.

**Describe alternatives you've considered.**

Alternativerly, we could create a widget similar to the list one, but where the notes get shown like icons, which could resemble a dock in the launcher. I think this solution wouldn't be as flexible as letting the user use single icons with the positioning sistem integrated in his launcher.

**Comment by stefan-niedermann** [comment]
Or you just use the <kbd>Pin to homescreen</kbd> feature :wink: 

_ | _ | _
--- | --- | ---
![grafik](https://user-images.githubusercontent.com/4741199/133050318-babc9133-7b3e-4857-8967-0971ca75b5f1.png) | ![grafik](https://user-images.githubusercontent.com/4741199/133050333-c9f69f35-7a7f-4bd0-9f72-2a0159356419.png) | ![grafik](https://user-images.githubusercontent.com/4741199/133050739-6fa69de3-9084-4d73-939d-9863c4eee564.png)

**Comment by SamuXzX** [comment]
My bad... I just learned it xD

**Comment by stefan-niedermann** [comment]
Well, it was just a quick idea to use the `ShortcutManagerCompat` instead of the default one, pitty that it didn't work.

Thanks for your feedback, i will likely not invest much time to work on this feature especially since it only affects Android versions which aren't even supported by Google anymore. Though i will accept a Pull Request if someone wants to pick this up.
