### ISSUE TITLE
Ordered list always be 1 on home screen widget

### ISSUE THREAD

**Issue by JahidFariz** [stefan-niedermann/nextcloud-notes#1356]
Incorrect Ordered case with nested quotes

Test case on android version 5.1
Input:

1. List_1
> list 1 description 

2. List_2
> list 2 description 

3. List_3
> list 3 description

Output on Home screen Widget

1. List_1
> list 1 description 

1. List_2
> list 2 description 

1. List_3
> list 3 description 

![Screenshot_2021-09-28-10-08-35-26](https://user-images.githubusercontent.com/50825690/135024174-97080d13-efe0-450f-a0c1-ff5698975a6a.png)

**Comment by stefan-niedermann** [comment]
Please fill out the issue template, it is there [fir a reason](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed).

**Comment by stefan-niedermann** [comment]
@JahidFariz please fill out the complete issue template. Versions across Play Store and alternative app stores like F-Droid vary. The requested information is not to boss you around but needed to provide proper support.

**Comment by stefan-niedermann** [comment]
Closing due to missing response.
