### ISSUE TITLE
Categories created in web UI are not shown in Android app

### ISSUE THREAD

**Issue by binarydad** [stefan-niedermann/nextcloud-notes#1358]
Running NC 20.0.12 and Notes 4.0.4. The Android app is v3.4.11. When editing existing notes to add a category, I see them display on the left on the web UI, but do not show on the app. I've deleted cache and force closed the app, but they do not show. 

I'm able to create categories in the app and they display on the web UI, but I cannot add more notes to that category (it seems to only push one-way from the app to the web UI). Thanks.

**Web UI:**
![image](https://user-images.githubusercontent.com/1760607/135322754-7f9db7b0-fefc-4759-a7f5-c1e282952ae7.png)
![image](https://user-images.githubusercontent.com/1760607/135322822-d5ab292d-5b77-4596-b01c-b49c300d84e5.png)

**App:**
![Screenshot_20210929-135304_Nextcloud Notes](https://user-images.githubusercontent.com/1760607/135322844-075c9d46-5759-4e64-829b-0f6bc1ed10a3.jpg)
![Screenshot_20210929-135243_Nextcloud Notes](https://user-images.githubusercontent.com/1760607/135322857-75c120d7-3915-4ff1-8447-2ecdb8cfd3ae.jpg)

**Comment by stefan-niedermann** [comment]
Indeed, that's reproducible. As a workaround just type in the same category label on your android device again (`Work` in your case).

It will then appear as suggestions if you want to set it for another note.

**Comment by stefan-niedermann** [comment]
Will be fixed in `3.4.14`, thanks for the report!
