### ISSUE TITLE
Create settings for listing of notes: toggles for grouping by time/letter, placing starred at the top

### ISSUE THREAD

**Issue by myuseraccount** [stefan-niedermann/nextcloud-notes#1365]
I preferred a much earlier version of the app, which did not break up the notes list with headings for time edited or letter of the alphabet.  I would also like a separate toggle to turn on and off the placing of starred notes at the top.  Basically, I would really like to be able to see as many note titles on the screen at once as possible without scrolling.  If the time or letter grouping label could be in a narrow column on the left, that would be a good compromise, to not waste lines and make it quicker to get to the title I'm looking for.  But I never look for those headings, I always look for a note by title.

I have considered downgrading to a much older version of the app, but I suspect it will eventually be incompatible with my server if I keep it updated.  The OwnNotes app has a simpler note list that I prefer, but that also will likely become incompatible (if it isn't already).

**Comment by stefan-niedermann** [comment]
Sorry, but i do not have plans to implement a setting to disable the section headers nor to *not* keep favorites at the top.

However we plan to implement a [compact mode](https://github.com/stefan-niedermann/nextcloud-notes/issues/1151) which will hide excerpt and category and provide therefore more visible notes at the screen. I will consider to also reduce the spacing of the section headers when i implement this - maybe this is enough for your needs.

The Notes server still is compatible to API v0.2 (which is marked as *deprecated* though), so even the very first release of this Android app should be compatible with the latest Notes server app. Some feature will of course not work or be slower.
