### ISSUE TITLE
i18n: Explanation of the text string "Play"

### ISSUE THREAD

**Issue by Valdnet** [stefan-niedermann/nextcloud-notes#1369]
Context please: is "play" a noun or a verb?

https://github.com/stefan-niedermann/nextcloud-notes/blob/5d35ed7de8657efa5d36dce534bce5ec265adc9f/app/src/main/res/values/strings.xml#L163

_Reported in Transifex by the translator._

**Comment by stefan-niedermann** [comment]
It is meant as a noun

**Comment by Valdnet** [comment]
Thanks for the clarification 😉.

**Comment by CafeTango** [comment]
Thanks! I'll translate it in the context of "theatre/drama" then.

**Comment by stefan-niedermann** [comment]
Well the app allows to edit and display markdown, for example

```
# Headline

[Link to Google](https://google.de)
```

Those characters are called `Markdown` and the syntax is specified (for example one needs a <kbd>Space</kbd> between the `#` and the actual headline).

A link with <kbd>Space</kbd> characters is invalid according to the [commonmark specification](https://commonmark.org/) and can therefore not be rendered. This means:

```
[Link to image](https://example.com/My fancy image.png)
```

will *not* work as it is invalid markdown while

```
[Link to image](https://example.com/My%20fancy%20image.png)
```

will be correct. Does that help or do you have any suggestions about the wording to describe this circumstances?

**Comment by stefan-niedermann** [comment]
@Valdnet i changed the wording a bit in https://github.com/stefan-niedermann/nextcloud-notes/commit/5c5c9d7329c1bee26ce16babbc3aeba272878128 - what do you think?

**Comment by Valdnet** [comment]
To avoid translation errors, I think it should be capitalized. This will certainly be the case in the Polish translation.

**Comment by stefan-niedermann** [comment]
I capitalized it 🙂 Thanks
