### ISSUE TITLE
Handle internationalization

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#14]
Currently translations are only available for English and German. I think we should open a transifex-repo for translations. If anyone speaks another language native, he is welcome to create a pull-request until this is done.

**Comment by jancborchardt** [comment]
Yeah, maybe we should even move this repo as »owncloud/notes-android« to the main ownCloud organization on Github to more easily handle translation and contributions. What do you think @stefan-niedermann?

cc @DeepDiver1975 @Henni @Raydiation

**Comment by pejakm** [comment]
There's also https://weblate.org.

**Comment by jancborchardt** [comment]
@pejakm we already use Transifex for the whole of ownCloud since the beginning: https://www.transifex.com/projects/p/owncloud/

**Comment by pejakm** [comment]
@jancborchardt I'm aware of this, I'm a member of Serbian translation team for ownCloud. But I missed your comment (sorry!) about moving this project to `owncloud` organization. In this case it would be akward not to use Transifex.

**Comment by jancborchardt** [comment]
@pejakm ah cool, thank you for your translation work then! :)

**Comment by pejakm** [comment]
@stefan-niedermann I forgot to report that [few lines](https://github.com/stefan-niedermann/OwnCloud-Notes/blob/master/app/src/main/res/values/strings.xml#L47) in default strings are in German instead of in English. :)

**Comment by stefan-niedermann** [comment]
ah thanks, will fix this ;) and thanks for your updated translation.

**Comment by korelstar** [comment]
Currently, there are still rather few languages available for this app and for many strings the translations are missing. Therefore, Transifex is still an interesting approach in order to improve this situation. It would be cool, if the @nextcloud-bot would take care of this repository, too. In that case, strings are automatically provided to Transifex and translation are automatically imported back to this app.

@stefan-niedermann Even if you don't want to migrate this project to the `nextcloud` organization, it seems that *somebody* can configure the @nextcloud-bot to use an external repository (I've seen this somewhere else). However, I don't know who would do that. What do you think?

**Comment by jancborchardt** [comment]
cc @MorrisJobke @LukasReschke about the Transifex configuration ^ :)

**Comment by MorrisJobke** [comment]
> @stefan-niedermann Even if you don't want to migrate this project to the nextcloud organization, it seems that somebody can configure the @nextcloud-bot to use an external repository (I've seen this somewhere else). However, I don't know who would do that. What do you think?

somebody === me ;)

**Comment by MorrisJobke** [comment]
@stefan-niedermann Could you add @nextcloud-bot as contributor? Is it then allowed to directly push to master (protected branches need to be disabled or there needs to be an exception for admins and nextcloud-bot added as admin).

**Comment by stefan-niedermann** [comment]
Well, i would be fine with moving the repository to nextcloud :) I have no idea  who is allowed to make this decision @jancborchardt @MorrisJobke.

But before moving i would like to release v0.10.0 which will contain many improvements like inline editing and nextcloud theme colors.

**Comment by MorrisJobke** [comment]
> Well, i would be fine with moving the repository to nextcloud :) I have no idea who is allowed to make this decision @jancborchardt @MorrisJobke.

Fine by me, but for the transifex integration it doesn't make a difference (beside that I would have the admin rights to set it up from a permission point of view)

**Comment by stefan-niedermann** [comment]
> Could you add @nextcloud-bot as contributor?

Done :)

**Comment by MorrisJobke** [comment]
> Done :)

now I need to know where you put the original strings and where I should put the translations. Maybe have at our android app and how it is handled there: 

- the english version (we use as translation source) is in `res/values`: https://github.com/nextcloud/android/tree/master/res/values
- all translations are in `res/values-LANGUAGE_CODE`: french for example in `res/values-fr` https://github.com/nextcloud/android/tree/master/res/values-fr

**Comment by stefan-niedermann** [comment]
We use the same schema: `res/values` and `res/values-LANGUAGE_CODE`, e. g. the english version is here: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/res/values/strings.xml
Please note that we have besides the `strings.xml` file a `plurals.xml`-file (one for each language), e. g. the english version: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/res/values/plurals.xml

**Comment by MorrisJobke** [comment]
> We use the same schema: res/values and res/values-LANGUAGE_CODE, e. g. the english version is here: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/res/values/strings.xml
> Please note that we have besides the strings.xml file a plurals.xml-file (one for each language), e. g. the english version: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/res/values/plurals.xml

Let me see how I can integrate both :) Thanks

**Comment by MorrisJobke** [comment]
Tested and works - runs now everyday at roughly 2 am (UTC+1) https://github.com/stefan-niedermann/nextcloud-notes/commit/16796eadf6eef8e20686bbb396bcb3ddfe5e90d7

(I copied the de to de_DE too - don't know if this matters, but just in case).
