### ISSUE TITLE
Undo for "Swipe to delete"

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#144]
It is possible to delete notes with a swipe action - but one could accidently delete a note, so there should be a undo-option just like in mail apps.

**Comment by korelstar** [comment]
Ouch! I didn't know that this is that dangerous! I just found multiple notes under "deleted files" in my ownCloud, that I didn't want to delete. I didn't even notice that I delete these note, when I deleted them -- which was apparently due do the swipe action.

I wasn't ever a friend of this "swipe to delete/edit" thing. But without notification and undo feature, this is really bad. I definitely recommend to deactivate this feature -- at least until there is an undo function.

**Comment by stefan-niedermann** [comment]
Well, i thought about it but i like this feature really ;) And notes are not *really* deleted since you can recover them from trashbin if you accidently hit one. At least in Google Play Store release notes i mentioned that there is no undo-function yet.
Do you have a clue how to implement an undo-button while swiping? If i knew it i would have implemented it of course yet.....

**Comment by korelstar** [comment]
I think the state of the art is using a "snackbar":
https://material.google.com/components/snackbars-toasts.html
https://developer.android.com/reference/android/support/design/widget/Snackbar.html

But I haven't implemented it yet.
