### ISSUE TITLE
Manual reordering of lists via handles

### ISSUE THREAD

**Issue by nbsmokee** [stefan-niedermann/nextcloud-notes#1440]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

In order to reorder bullet lists, I have to cut/paste lines which is somewhat annoying, especially on a mobile phone

**Describe the solution you'd like**

It would be very convenient if I could write down a list (say, a shopping list) and reorder the entries afterwards by dragging them to the desired location via handles that are displayed to the side of each bullet/check box. The handles could also be sensitive in the horizontal direction to control indentation, but that's not my main concern.

**Describe alternatives you've considered**

**Additional context**

**Comment by stefan-niedermann** [comment]
I also think this feature can be quite useful. However even the most simple default implementation¹ will require quite some heavy work, as currently the complete note is only a rendered piece of text.

I have currently no plans to implement this as i am missing time and ideas about how to achieve this in a proper way, though i will happily merge a Pull Request that implements this in a proper and reusable way (-> This means it must be implemented in the [`nextcloud-commons`](https://github.com/stefan-niedermann/nextcloud-commons/) library).

If someone wants to pick this up some

- ideas for approaches i played around:
  - Split the rendered `TextView` to a list of `TextView` and list items
  - Of course the markdown rendering is destructive, so one must match the `nth` rendered checkbox with the `nth` checkbox in the source to perform the move action in the source. This is already done for toggling checkboxes, so maybe there can some parts be reused
- ¹ further considerations for a proper implementation:
  - Checkboxes can be nested within a checkbox list, a plain list and a mixed list in any depth
  - One note can contain `n` lists with any content between then
  - Checkboxes can be within a codeblock

Sorry that I don't have better news for you, but maybe my points above can make you relate to where the issues are and that it ain't "that simple".

Closing this issue not as "won't fix" but as "won't fix myself".

**Comment by rik-shaw** [comment]
Now that this is a nextcloud core app (?) I wonder if this issue could be re-opened. Maybe some others have some thoughts about how to tackle this. Apps like quillpad (https://github.com/quillpad/quillpad) can do this when connected to the notes, but there may be some sync bugs... Still worth a look?
