### ISSUE TITLE
HTML visible in About page

### ISSUE THREAD

**Issue by samwilson** [stefan-niedermann/nextcloud-notes#1449]
HTML is visible in the About page:

![Capture+_2022-01-18-16-56-57.png](https://user-images.githubusercontent.com/213655/149904132-778de08b-4cba-4832-b868-5ad657064c1a.png)

**Comment by stefan-niedermann** [comment]
Can you tell me, which language and locale are you using exactly?

**Comment by samwilson** [comment]
Sorry, I should've said: English (Canada)

**Comment by rakekniven** [comment]
Hello @stefan-niedermann just checked Transifex and no existing translation does contain html anymore.

**Comment by stefan-niedermann** [comment]
Alright, it looks like the same issue we had some time ago: If a language has covered the translated strings below a certain percentage, the bot will stop copying it to transifex (I believe the intention is to avoid translations where only a few words are actually translated and the rest is in the fallback language).

I remove all obviously outdated translations (https://github.com/stefan-niedermann/nextcloud-notes/commit/320d8d20a160db1ad6f7451d4874e8f8e5161d1d).

@samwilson in your personal case this should lead to a fallback to the next best language (english) in `3.4.19`. Thanks for the report. I'll talk to Tobi to see whether we can change the behavior of the bot in the future.

**Comment by samwilson** [comment]
Great, thanks. And thanks for such a speedy response! This app is great.
