### ISSUE TITLE
Editing notes from Desktop Sync Client creates "File could not be synced" error

### ISSUE THREAD

**Issue by MillironX** [stefan-niedermann/nextcloud-notes#1451]
> Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

## Describe the bug

Editing notes that have been uploaded from the Nextcloud desktop sync client will result in a "File could not be synced due to an error" in the Nextcloud desktop sync client

## To Reproduce

1. Setup the Desktop sync client on one or more computers
2. Create a new note on the Desktop computer

    ```bash
     echo "# Note From Desktop\n\nThe quick brown fox..." >> ~/Nextcloud/Notes/"Note From Desktop.txt"
    ```

3. In the server Notes app, click "+ New Note," and type

    ```markdown
    # Note From Server App

    The quick brown fox...
    ```

4. In the Notes app on the phone, pull down to synchronize notes
5. For both notes created above, open the note in the Notes app on the phone and add the text "Does this work?" and press the back button to save and synchronize the note

    ![Editing the note](https://user-images.githubusercontent.com/25492070/150226001-2b7dd264-dfab-4654-b8cb-890522f4a348.jpeg)
    
6. Wait for the change to be propagated to the Desktop sync client
7. **Bonus**: Edit "Note From Server.txt" on the Desktop computer, then repeat steps 5-6, and the error will be thrown for both files

## Expected behavior

The files

- ~/Nextcloud/Notes/Note From Server App.txt
- ~/Nextcloud/Notes/Note From Desktop.txt

should both say "Does this work?" as their last line on the Desktop computer. Note that if the edits in step 5 are made from within the Server app or another Desktop computer, then the expected behavior is observed. 

## Actual behavior

The Desktop sync client reports 

```plaintext
Note From Desktop.txt could not be synced due to an error
```

Examining the error report in the settings dialog reveals

```plaintext
Note/Note From Desktop.txt: The downloaded file does not match the checksum, it will be resumed <CHECKSUM> != <CHECKSUM>
```

The server app reflects the correct state of the files, however.

## Screenshots

![Nextcloud Notification](https://user-images.githubusercontent.com/25492070/150223707-e7062d78-3fc8-425c-8a8c-b21928e95a6e.png)

![Nextcloud Settings Dialog](https://user-images.githubusercontent.com/25492070/150224478-261cd00a-f7d1-417b-8ffe-fbb6830774d5.png)

## Smartphone (please complete the following information)

 - Nextcloud Notes-Version (android app): 3.4.18
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11 (LineageOS 18.1-20220104-microG-guacamole)
 - Device: OnePlus 7 Pro (GM1917/Guacamole)

## Server

 - Nextcloud version: 21.0.1
 - Nextcloud Notes version (server app): 4.2.0

**Comment by stefan-niedermann** [comment]
Hello and thank you very much for the very well described issue!

First of all, I doubt that this issue is actually *caused* by the Notes Android app - at least I can not imagine it 😉, therefore:

Are you able to reproduce this issue also, when you create the note from a Deskrop client, but **edit** it with the Notes server app?

**Comment by MillironX** [comment]
For all my testing I guess I hadn't tried that. You are correct, _creating_ by the Desktop client and _editing_ it in the Server app in step 5 gives the same error. Which repo do you think I should refile this issue in? https://github.com/nextcloud/notes, https://github.com/nextcloud/desktop, or somewhere else?

**Comment by stefan-niedermann** [comment]
https://github.com/nextcloud/notes should be the right place to post the issue 🙂

**Comment by MillironX** [comment]
Transferred over to https://github.com/nextcloud/notes/issues/806
