### ISSUE TITLE
Design not looking right in latest update

### ISSUE THREAD

**Issue by hamoid** [stefan-niedermann/nextcloud-notes#1457]
![signal-2022-01-27-115918](https://user-images.githubusercontent.com/108264/151348376-2fe03d58-c47e-48ae-bff2-fa2f9c48231c.png)

![signal-2022-01-27-115913](https://user-images.githubusercontent.com/108264/151348381-ca929f4f-4964-4816-be34-84aa658efb0a.png)

**Is your feature request related to a problem? Please describe.**

UX shows too much empty space

**Describe the solution you'd like**

A way to list my 10 notes in a more compact way. Maybe the headline letters could exist only after a specific number of notes? I don't need headline letters, just a list of titles sorted alphabetically, with an excerpt, no "favorite" icons either. Currently a lot of screen space is unused.

**Comment by stefan-niedermann** [comment]
The design has not changed in the last update. For compact mode we already have https://github.com/stefan-niedermann/nextcloud-notes/issues/1151#issuecomment-825560786 - closing this issue therefore as duplicate.

**Comment by hamoid** [comment]
Thanks for your reply. How do I enable the compact mode? I don't see such an option in the settings.

**Comment by stefan-niedermann** [comment]
Since the linked issue is not yet closed but open, this feature has not been implemented yet and will come with a future version of the Notes Android app.
