### ISSUE TITLE
Handling of single newlines in preview mode

### ISSUE THREAD

**Issue by Yipten** [stefan-niedermann/nextcloud-notes#1478]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Single newlines in the text of Markdown files are shown as newlines in preview mode. As far as I know, Markdown paragraphs are separated by two newlines, and actual rendered single newlines must be created explicitly (either with trailing whitespace or `<br>`). A single newline in the file should not affect the rendered output. However, in edit mode, I would definitely still expect to see every newline (the Nextcloud Notes server app does this). 

**To Reproduce**

1. Create a Markdown file with multiple lines of text separated by single newlines. In my case, I created the file on my computer using Vim, which I have configured to automatically create newlines to enforce a maximum line length of 80. 
2. Sync the file with Nextcloud server. 
3. Open the file in Nextcloud Notes (Android app) in preview mode. 
4. Especially in portrait orientation with a lot of text, notice how the text is hard to read because of the line breaks not aligning with the width of the phone screen. 

**Example file contents**

```markdown
# Newline test

First line. 
Second line after single newline. 

Third line after double newline. 
```

**Actual behavior**

![Screenshot_20220302-182802-102](https://user-images.githubusercontent.com/25311591/156467391-96cedb2d-1f5b-4d28-bbec-36b9370495c5.png)

**Expected behavior**

![Screenshot_20220302-182829-593](https://user-images.githubusercontent.com/25311591/156467416-b5d41eaf-5e7d-4c38-b7c8-cbc4bd5c2043.png)

**Example of this being a problem**

File contents: 

```markdown
# Example of bad readability

I'm just going to type some sentences here and let Vim create new lines at 80
characters automatically. As you can see, it looks fine in monospace and
allowing each line to be fully shown on one line without wrapping. However, it
gets hard to read on a phone screen in portrait orientation because the
newlines don't match up with the width of the screen. 
```

Preview mode in app: 

![Screenshot_20220302-184204-889](https://user-images.githubusercontent.com/25311591/156468496-558e493a-4844-4925-8392-b20cf61ffe1f.png)

**Smartphone**
 - **Nextcloud Notes-Version (android app):** 3.4.18
 - **F-Droid or Play Store:** F-Droid
 - **Android-Version:** 11
 - **Device:** Motorola Moto G Stylus (2020)

**Server**
 - Nextcloud version: 22.2.2
 - Nextcloud Notes version (server app): 4.3.0

**Stacktrace**

*No error is thrown. This is a cosmetic/user interface bug.*

**Note**

If it is determined that this should be fixed, I'm willing to work on resolving the issue. I'll probably need a little guidance on where to begin, though.

**Comment by stefan-niedermann** [comment]
Hello and thank you for the very well described issue 👋 

We are aware that the current behavior contradicts with the `commonmark` specification - however this is [(the only) part of the app that derivates on purpose from the spec](https://github.com/stefan-niedermann/nextcloud-commons/blob/master/markdown/src/main/java/it/niedermann/android/markdown/markwon/MarkwonMarkdownViewer.java#L94).

In fact, [the Notes server app recently adjusted its behavior](https://github.com/nextcloud/notes/issues/801#issuecomment-1012059012). While there are pros and contras for both variants, the specified behavior is quite technically and not understandable for most of the users.

We therefore do not plan to change the current behavior.

Kind regards,
Stefan
