### ISSUE TITLE
Feature request: add reminder

### ISSUE THREAD

**Issue by TomW80** [stefan-niedermann/nextcloud-notes#1480]
Hello, 

It would be good if you could add a reminder for notes.

**Comment by stefan-niedermann** [comment]
This is out of scope for the Notes app. You can have a look at the Task app in combination with DavX5 or the Deck app in combination with the Deck Android app for more advanced organizational features.

Also: The (not by us developed) Notes server app [does not support this](https://github.com/stefan-niedermann/nextcloud-notes/issues/728#issuecomment-585311809).
