### ISSUE TITLE
no DNS refresh without network reconnect

### ISSUE THREAD

**Issue by ristein** [stefan-niedermann/nextcloud-notes#1491]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

dns IP address wont be refreshed while staying conneted to network, same as in Deck app

**To Reproduce**
1. Connect phone to WiFi/internet
2. reconect Internet connection in router of server and getting new IP address
3. try to refresh notes app
4. See error "java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to example.com/80.128.74.45 (port 443) from /10.1.10.1 (port 41251) after 5000ms" still pointing to old IP address
5. reconnect WiFi or internet and correct public IP will be fetched

**Expected behavior**

should fetch new IP address without network refresh when not able to connect

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.18
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: GM1917

**Server**
 - Nextcloud version: 23.0.3
 - Nextcloud Notes version (server app): 4.3.1

**Stacktrace**
lamp?

**Comment by stefan-niedermann** [comment]
Looks like the [same issue as over in the News Android app](https://github.com/nextcloud/news-android/issues/1077). The Notes Android app doesn't perform *any* network operation on its own, but "asks" the Nextcloud Android app to perform them. I'd therefore kindly ask you to open the issue in the [repository of the Nextcloud Android app](https://github.com/nextcloud/android/issues/).
