### ISSUE TITLE
Show a note on the lock screen

### ISSUE THREAD

**Issue by Ferruck** [stefan-niedermann/nextcloud-notes#1492]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

It's a feature request. I'd like to be able to keep the notes app visible on the lock screen, similar to what, for example, [Kore](https://github.com/xbmc/Kore/blob/a0b5784d148fcea559d56434e3f87e594c58b8a4/app/src/main/java/org/xbmc/kore/ui/sections/remote/RemoteActivity.java#L190) does. This would be quite handy when using the notes app for grocery shopping etc., where you look at a note over and over again in a short period of time.

**Describe the solution you'd like**

I'd like to be able to show one note on the lock screen. The following points could be discussed or kept configurable:

* Leaving the note (to select another one) should require unlocking. Thus, you'd be "captured" in the one note.
* The note could be read-only as long as the screen is locked. This would render checkboxes unusable for my use-case, though.
* Alternatively, entering the edit mode would require unlocking. This would allow the usage of checkboxes as they are editable from preview mode but it would also force the user to use the preview mode.

**Describe alternatives you've considered**

The only alternative is to unlock the screen whenever you want to look at the note.

**Additional context**

This is somewhat related to #1461

---

This is more or less a RFC, I don't expect anyone to jump in to implement the feature. If there's broader interest in the idea I could try to come up with a patch but I'm no Android dev by any means...

**Comment by stefan-niedermann** [comment]
Thank you for your suggestion!

According to the Google documentation of widgets, the `keyguard` property (which we already set for the `widgetCategory` property in our `AppWidgetProvider`)

> Declares whether your widget can be displayed on the home screen (home_screen), the lock screen (keyguard), or both <sub>[developer.android.com](https://developer.android.com/guide/topics/appwidgets/index.html#lockscreen)</sub>

But: 

> Only Android versions lower than 5.0 support lock-screen widgets. For Android 5.0 and higher, only home_screen is valid. <sub>[developer.android.com](https://developer.android.com/guide/topics/appwidgets/index.html#lockscreen)</sub>

Since the Notes Android app is only compatible with Android 6 and higher, we can not use this approach.

The resource of Kora, [you linked above](https://github.com/xbmc/Kore/blob/a0b5784d148fcea559d56434e3f87e594c58b8a4/app/src/main/java/org/xbmc/kore/ui/sections/remote/RemoteActivity.java#L190) seems to be a quite hacky way to achieve this goal by forcing the window floating above the lock screen. Honestly, this looks like a unreliable way I don't want to implement. It probably will stop working at some point in the future and looks inconsistent to the Android ecosystem.

**Comment by Ferruck** [comment]
It's of course totally fine if you don't want to add this feature. Just for completeness sake I'd still like to add here that with API level 27 (Android 8.1) a method `setShowWhenLocked(boolean)` [was added to the `Activity`](https://developer.android.com/reference/android/app/Activity#setShowWhenLocked(boolean)), which is still current and [replaces the now deprecated `FLAG_SHOW_WHEN_LOCKED`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SHOW_WHEN_LOCKED) that Kore uses. Doesn't seem to me like a hacky solution but, as I said, that's up to you.

**Comment by stefan-niedermann** [comment]
The fact, that this is actually not a widget but an`Activity` (= the open app) that is shown looks still hacky, but I'll have another look at your proposal since I wasn't aware of the new API yet.
