### ISSUE TITLE
Table with 2 columns

### ISSUE THREAD

**Issue by Bob-le-pirate** [stefan-niedermann/nextcloud-notes#1493]
Dear all,

Table with 2 columns doesn't show correctly in view mode. It seems that only table with 3 columns works fine.

Example :
| Docker | Version |
| --- | --- |
| nginxproxy/nginx-proxy |  1.0.0-alpine |
| nginxproxy/acme-companion | 2.2.0 | 

Thank you for your help.

**Comment by stefan-niedermann** [comment]
1. Thank youu ignoring and deleting the issue template.
2. Closing as it works as expected.
3. For more information see our [FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed)

![Screenshot_20220405-123401_Nextcloud_Notizen](https://user-images.githubusercontent.com/4741199/161735939-b366b33e-7d23-4076-845c-5c1aa5695a9f.png)

**Comment by Bob-le-pirate** [comment]
Sorry I didn't get any solution in the FAQ and the table was not printed as expected.
First message was edited.

**Comment by stefan-niedermann** [comment]
The link to the FAQ was posted to explain why I closed this issue (because of the poor description).

Can you please try putting a blank line between the `***` styled "headings" and the actual tables?

**Comment by Bob-le-pirate** [comment]
It works !
Thank you very much for your help.

**Comment by stefan-niedermann** [comment]
You're welcome, have fun with the app and sorry for the harsh reaction, but poor issue descriptions will not enable us to help - the important parts were missing as you noticed yourself :)
