### ISSUE TITLE
Stop creating .txt files. Start to create .md files instead.

### ISSUE THREAD

**Issue by bvn13** [stefan-niedermann/nextcloud-notes#1494]
The latest version in Google Play creates .txt file.
And edits it as a markdown source.
It is wrong. In NextCloud Web such files are being edited only as simple text. 
All files with markdown sources must be edited with markdown editor, I think.
Therefore it is necessary to give all files extensions '.md'.

**Comment by stefan-niedermann** [comment]
So why don't you just change your settings in the Nextcloud Notes web UI (at the bottom left where all app specific settings are in Nextcloud) or in the Android Notes account settings if you prefer `.md` as extension?

![Bildschirmfoto vom 2022-04-06 08-27-22](https://user-images.githubusercontent.com/4741199/161909610-1cdfdb96-0f7d-405d-8b6c-06fda7cf4365.png)
![photo_2022-04-06_08-27-43](https://user-images.githubusercontent.com/4741199/161909612-b8f47b6d-f6eb-425a-ad4d-48e360654079.jpg)

**Comment by bvn13** [comment]
@stefan-niedermann where that settings are placed? Could you give me the path to find them? I haven't found them in my copy.

**Comment by bvn13** [comment]
![Screenshot_20220406_144418_it niedermann owncloud notes](https://user-images.githubusercontent.com/682521/161967867-eb8b60cd-fd17-4747-8215-fabc3fecaf21.jpg)
This is a screenshot from my copy - the seetings.

**Comment by stefan-niedermann** [comment]
Those settings are account specific and not global. You can therefore find them in the account related settings when clicking on your avatar in the Notes Android app, press <kbd>Manage accounts</kbd> and the <kbd>⚙</kbd>.

**Comment by bvn13** [comment]
It's so nice! I've found it!
Thank you!
