### ISSUE TITLE
Tip for the Notes app

### ISSUE THREAD

**Issue by kandrix** [stefan-niedermann/nextcloud-notes#1522]
Good, it seems to me a good Notes application but it would be good to log in to the account without the Nexcloud application being installed

**Comment by stefan-niedermann** [comment]
Dear  #@kandrix,

while i understand your request, this is not an option for us.

We have discussed this long time and came to the conclusion that this is our way to go. Most people who are using notes have a Nextcloud account and will probably us the Nextcloud app anyway.

The effort of maintaining a complete network stack and support self-signed-certificates, second-factor-authentication and all possible special configurations is too high and caused most of connection and sync related issues in the past. Using SSO, we can ensure, that we have covered all those kind of special environments that the Nextcloud app also covers, without the need of testing edge cases or anything else.

Other benefits are an easier setup from a UX point of view and, maybe most notable, the immense security benefits. You won't have to trust an app developer, you don't need to enter your password and of course also bug can occur in third party apps which might leak sensitive data - all of this is prevented by using Nextcloud Single Sign On.

Kind regards,
Stefan
