### ISSUE TITLE
Improve user experience on slower devices

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#154]
I've tested the app on my old Samsung Galaxy Gio (from 2011) and found some bottlenecks: Especially,   loading the list of notes from the database and the synchronization are very slow.

## Loading the list of notes from the database
- [x] Introduce database index to speed up sorting
- [ ] Maybe it could be helpful to save the excerpt in a separate column (with index) and then do not load the full note (i.e. load it only without the actual text), when only the list of notes is required.

## Synchronization
- [x] Synchronization takes very much time, because always all notes are transferred and compared. This could be improved, but requires changes on the server site (e.g. check if the `ETag` of the notes file has changed).

**Comment by stefan-niedermann** [comment]
@korelstar the synchronisation part has already been done, right? Maybe we than should drop this paragraph while the other proposals still make sense.

**Comment by korelstar** [comment]
Yep, you're right. I've updated the text and introduced check-marks to track the progress.

**Comment by stefan-niedermann** [comment]
Follow-Up in #528.
