### ISSUE TITLE
Favorite Star in Menu not clickable

### ISSUE THREAD

**Issue by ksapp-dell** [stefan-niedermann/nextcloud-notes#1541]
*Describe the bug**
It is not possible to make  a nite ,Favorite' (adding the star icon).

**To Reproduce**
1. Open an existing note
2. Tap on the three dots to open menu
3. Tab on Favorit
4. Nothing happens

**Expected behavior**
Yellow star should be added if a note is selected as favourite.

**Screenshots**
![Screenshot_20220703-124340_Nextcloud Notes](https://user-images.githubusercontent.com/62463497/177036014-fe6e6ea5-f49e-4327-ba33-efa8acc17a1b.jpg)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.5.00
 - F-Droid or Play Store: F Drous
 - Android-Version: 8
 - Device: Samsung S7

**Server**
 - Nextcloud version: 3.20.3
 - Nextcloud Notes version (server app): 20

**Comment by stefan-niedermann** [comment]
Hmm, seems like it actually performs the (un)star action but does not immediately update the UI within the note...
