### ISSUE TITLE
ViewMode for CreateNoteActivity

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#156]
Depends on #155.
Wanted behavior:

The CreateNoteActivity should be able to display the Note without markdown just like the EditNoteActivity, too.

Solution 1: Use the same fragments (could cause duplicate code)
Solution 2: Merge CreateNoteActivity with EditNoteActivity

**Comment by korelstar** [comment]
Regarding merging of CreateNoteActivity with EditNoteActivity (which is a good approach), see also #57.
