### ISSUE TITLE
Allow changing server directory destination via Mobile app

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-notes#1567]
Please, add a capability to change server directory destination (especially for sync on server) via Mobile app as it possible on server app.

**Comment by stefan-niedermann** [comment]
It is already possible. Click on your avatar in the top right and then "Manage accounts". There is a three dot menu next to your account where you can edit account related settings.

![grafik](https://user-images.githubusercontent.com/4741199/184605776-0a230319-2818-4094-be48-b38cc3ee8b67.png)

**Comment by neerro** [comment]
Oh, yep... But a bit non-intuitive action. Nevertheless, I have no any chance to change it :(

**Comment by neerro** [comment]
Actually I've found the way to change it. Just written name directory destination in my note, after that using copy-past option change directory. Very strange as I can't change it by typing or in pop up meny, I have no this ways.

**Comment by stefan-niedermann** [comment]
Please see https://github.com/stefan-niedermann/nextcloud-notes/issues/916#issuecomment-1001071467 for your issue

> When opening the folder settings from the Android app, no keyboard is shown

It is a known issue for some devices which I couldn't fence yet - "works on my machine" as well as emulators, so I have no clue yet why the keyboard doesn't show up as in your case. You already found the copy & paste workaround.
