### ISSUE TITLE
Nicht proportionale Schrift

### ISSUE THREAD

**Issue by cptechnik** [stefan-niedermann/nextcloud-notes#1573]
Die Schaltfläche "Nicht proportionale Schrift" macht das gegenteil, sie schaltet auf proportionale Schrift um.
Oder ein Übersetzungsfehler?

The switch in the settings for the proportional font does the inverted function.
Or a translation-fault?

Version 3.6.0

**Comment by stefan-niedermann** [comment]
@Valdnet looks like a translation error? `Monospace font` should be `Proportionale Schriftart`, no?

**Comment by Valdnet** [comment]
This is a translation error.

@rakekniven can you confirm and correct it?

@cptechnik Danke, dass Sie diesen Fehler gemeldet haben 😉.

**Comment by cptechnik** [comment]
Monospace is proportional , yes...

I have sign on to translate, so if I get the confirmation that I am allowed to, I will search for it...

**Comment by cptechnik** [comment]
Anscheinend hättest Du dabei schreiben sollen welches Universum, in welchem Universum du dich befindest...
![Screenshot_20220829-224119](https://user-images.githubusercontent.com/5541222/187296008-b7eb3b5a-7d8f-4d82-9e85-1859af3a7d13.png)
![Screenshot_20220829-224302](https://user-images.githubusercontent.com/5541222/187296013-6ef73fde-df4a-4960-991e-e9320a7b553c.png)
![Screenshot_20220829-224422](https://user-images.githubusercontent.com/5541222/187296017-f3dcaa0d-b207-4e22-b02d-91d3fbf711ee.png)

... Hmmm...
Also
- ich kann/darf mich nicht zu "German" hinzufügen, der Admin ist benachrichtigt, ...
- ja auch da heiße ich cptechnik, seit 2014... Habe ich mich bei xfce angemeldet...
- und dein Link führt ins 404... (Vermutlich weil Zugang zu deutsch/german gesperrt...
🤷‍♂️
Einzig... Ich habe es noch nicht vom Desktop/PC getestet... 
🙊🙈

**Comment by cptechnik** [comment]
> Habe in diesem Projekt sehr viele Rechte, kann Dich aber nicht finden. Wenn ich https://www.transifex.com/user/profile/cptechnik/ aufrufe, so bekomme ich den Fehler "Profile not found".

Nicht öffentlich, dafür muss man angemeldet sein... zumindest sagt das die Einstellung...


...ja, jetzt ja... 

-changed-

**Comment by cptechnik** [comment]
Zu

**Comment by stefan-niedermann** [comment]
Dankeschön :)

**Comment by cptechnik** [comment]
nich doführ...!

**Comment by cloud2018** [comment]
Ist es wirklich geschickt, in Transifex den englischen String "Monospace font" mit "Proportionale Schriftart" zu übersetzen? Wenn das so ist, müssten vermutlich auch die Übersetzungen bei allen anderen Sprachen geändert werden.

Liegt es nicht eher am englischen String im Quellcode, der geändert werden sollte? Evtl.: 
https://github.com/stefan-niedermann/nextcloud-notes/blob/9322f475d4ed6ddedb847a53745fe9963487b9a3/app/src/main/res/values/strings.xml#L45

**Comment by cloud2018** [comment]
I think it is not an translation error (in Transifex), it is a error in the code. 

"Monospace font" is in German "Nichtproportionale Schriftart".
If you mean a font where each character takes the width it needs visually, the English string should be Proportional Font.  If the coder changes the source, then the translations in all languages could be corrected. Now in German it is "Proportionale Schriftart" e.x. in french still Texte monospace" in English "Monospace font"
