### ISSUE TITLE
Activity memory leak caused by anonymous threads

### ISSUE THREAD

**Issue by cuixiaoyiyi** [stefan-niedermann/nextcloud-notes#1574]
# Possible Memory Leak
An [anonymous inner class](https://stackoverflow.com/questions/17778077/would-anonymous-handler-or-runnable-create-a-memory-leak) will hold a reference to the this pointer of the outer class and will not be released until the thread ends.
It will hold the Activity and prevent its timely release. Please check the links below.

# Occurrences
https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/manageaccounts/ManageAccountsActivity.java#L141

# Possible Solution
If it is necessary, it can be changed to [static class + weak reference](https://stackoverflow.com/questions/22162642/will-handler-inside-a-method-leak-memory/27825703#27825703) to eliminate the reference to the activity, which may cause memory leaks.
Further discussion is welcome.

**Comment by stefan-niedermann** [comment]
Fixed by using an `Executor`.
