### ISSUE TITLE
claims that up-to-date Nextcloud F-Droid does not support SSO

### ISSUE THREAD

**Issue by yeupou** [stefan-niedermann/nextcloud-notes#1578]
Since a while, Nextcloud Notes, up-to-date from F-Droid (3.6.0)), fails to synchronize with the Nextcloud current stable server (24.0.5) and both stable and beta F-Froid Nextcloud app.

Following FAQ workaround, I cleared storage for both F-Droid apps (with the annoying nuisance of being for to reconfigure numerous specific instant-upload parameters).

Then restarting Nextcloud Notes fails with the claim that up-to-date Nextcloud F-Droid does not support SSO, 

**To Reproduce**
1. Make sure to have the latest Nextcloud Notes and Nextcloud from F-Droid
2. Make sure they have no battery restriction
3. Clear cache of both Nextcloud Notes and Nextcloud
4. Connect Nextcloud app to proper Nextcloud server account - no problem 
5. Start Nextcloud Notes
6. Select, in Nextcloud Notes, the configured Nextcloud account

**Expected behavior**
Successful connection.

**Screenshots**
Failure, with a pop-up message claiming that Nextcloud Files installed version does not support SSO

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app):  3.6.0
 - F-Droid or Play Store:  F-Droid
 - Android-Version: 13 
 - Device:  Pixel 4a

**Server**
 - Nextcloud version: 24.0.5
 - Nextcloud Notes version (server app): 4.5.1

**Comment by stefan-niedermann** [comment]
It's a bug in the Nextcloud SSO: https://github.com/nextcloud/Android-SingleSignOn/issues/470

You can use the released version of the Nextcloud app instead of the Dev app as workaround.

**Comment by yeupou** [comment]
Ok thanks, I'll try that.
