### ISSUE TITLE
Login without Google services

### ISSUE THREAD

**Issue by eapo** [stefan-niedermann/nextcloud-notes#1579]
**Describe the bug**
Can't find any other login method just using the _Nextcloud Synchronisation client v20220909_ installed from _f-droid_ which returns the following error:

> Your Nextcloud Files app currently does not support the single sign on feature. Please update it: https://play.google.com/store /apps/details?id=com.nextcloud.client

**To Reproduce**
1. Launch app
2. Select account from the list
3. Press OK

**Expected behavior**
Able to login without using Google services

**Screenshots**
![Screenshot_20220918-202654_Nextcloud_Notes](https://user-images.githubusercontent.com/4000929/190921169-5e59550c-3d44-4377-9801-d4cc2669b110.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.6.0
 - F-Droid or Play Store: f-droid
 - Android-Version: Linux localhost 4.9.248-lineageos-g7aa15468fcba #0 SMP PREEMPT Tue Mar 29 06:52:37 UTC 2022 aarch64 Android
 - Device: Google Pixel 3 XL

**Comment by stefan-niedermann** [comment]
It's a bug in the Nextcloud SSO: https://github.com/nextcloud/Android-SingleSignOn/issues/470

You can use the released version of the Nextcloud app instead of the Dev app as workaround.
