### ISSUE TITLE
Maximum size of note

### ISSUE THREAD

**Issue by dalb8** [stefan-niedermann/nextcloud-notes#160]
I have 0.9.0 from f-droid.org. When I pasted a largeish text in a new note the end was truncated. The way I found out was that I was unable to add text to note.

**Comment by stefan-niedermann** [comment]
Hey @dalb8, how many characters does your text have? Have you tried it via the web interface? I did not explicit limit the size of a note, so maybe the API is truncating it?

cc @Henni

**Comment by dalb8** [comment]
I can't say exactly, a few thousand. I've noticed that another text editor (Turbo) has the same problem so it could just be an issue with the ROM which is stock LG G4 running Android 6.0. Feel free to close.

**Comment by stefan-niedermann** [comment]
Feel free to reopen when the issue appears on other system in combination with Nextcloud Notes again ;)
