### ISSUE TITLE
Can't recover not syncronised notes on android

### ISSUE THREAD

**Issue by afora2** [stefan-niedermann/nextcloud-notes#1601]
**Describe the bug**
On android client, I have a user who collected and documented notes for over a year in Nextcloud Notes app. That app was over a year ago connected to a working instance of Nextcloud server, but that server has been offline since. The user wants to recover the notes to either plain text file, or a collection of plain text files. 

Although Nextcloud Talk is installed (v.3.6.0) and correctly running on an android client, no trace of where this data is actually stored on the android can be found.  

There is no interface or functionality to recover notes which do not have a connection with the server any longer.

**To Reproduce**
1. Go to android file system and search for *note*, *.txt*, *notes* - nothing returned
2. Start Nextcloud Notes, go to Settings for location of the notes - no options found. 

**Expected behavior**
A tool/functionality to extract data saved on the client to be able to transfer notes to a new server. Or just save it as a plain text file.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): (v.3.6.0) 
 - Android v10

**Server**
 - Nextcloud version: n/a

**Comment by stefan-niedermann** [comment]
The Notes Android app store the notes in the local SQLite database rather than actual files for performance reasons.

The Notes Android app, though offline capable, is *not* a backup tool and *not* designed to be used intensively without a running instance for a long time.

Either backup the notes one by one, use the multiselect option to select all notes that have changed and share them into another app (they will ne concatenated to one single large text though) or extract the contents from the database.

**Comment by IIerpos** [comment]
One question: where would I find the database? I can easily enough recover from there, but I'm just looking with a USB cable in "Internal Shared Storage/Android/Data" I can't find anything remotely resembling "it.niedermann.owncloud.notes" Any advice on how to find or extract the sqlite file from my phone? I realize this is kind of out of the scope, but when the server went into maintenance mode, the app began to crash and no longer register's the notes' existence...

**Comment by mitch-n** [comment]
Please any direction with this would save me. Where would the sqlite file be stored. I cant find it anywhere. I am on an adb shell (not root) and have searched every keyword I can think of. I am not finding anything.

**Comment by stefan-niedermann** [comment]
It's called `OWNCLOUD_NOTES` (without extension) for historical reasonsm

**Comment by mhastu** [comment]
for reference, I describe how I restored the not synchronized notes in [#2214](https://github.com/nextcloud/notes-android/issues/2214#issuecomment-2535797330)
