### ISSUE TITLE
Single sign on error

### ISSUE THREAD

**Issue by timunrau** [stefan-niedermann/nextcloud-notes#1607]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

When I try to sign in to my account I get the error in the screenshot.

**To Reproduce**
1. Open the notes app.
2. Try to add an account that's already added to the NextCloud app.
3. You'll get the error shown in the screenshot.

**Expected behavior**

It should login. 

**Screenshots**

![Screenshot_20221116-180835](https://user-images.githubusercontent.com/48539072/202322634-07231cf5-f656-4f67-b233-a2bff473569b.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.7.0
 - F-Droid or Play Store: F-droid
 - Android-Version: 13 (Graphene OS)
 - Device: Google Pixel 7

**Server**
 - Nextcloud version: 24.0.6
 - Nextcloud Notes version (server app): 4.5.1

**Stacktrace**

**Comment by stefan-niedermann** [comment]
This is a [known issue](https://github.com/nextcloud/Android-SingleSignOn/issues/456) of the Single Sign On library provided by the Nextcloud GmbH which currently prevents one from using the Dev version of the Nextcloud (files) Android App.

3rd party applications should work with the stable released version of the Nextcloud Android App.

**Comment by timunrau** [comment]
My apologies, I was unaware that I was using the Dec version of next cloud app. I installed the correct version and it works now.

Thanks for the reply, and thanks for making this awesome app. I use it daily!

**Comment by Exagone313** [comment]
I have latest Nextcloud stable and the issue is still happening. How can I deal with this?
