### ISSUE TITLE
High battery usage from this app

### ISSUE THREAD

**Issue by blastrock** [stefan-niedermann/nextcloud-notes#1608]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
I have installed the app and did not use it yet, but it consumes a lot of battery.

I use BetterBatteryStats and I can see that over the last 9h43min, this app took a wakelock for 1h56min, even though I didn't use it. The wakelock name is `*job*/it.niedremann.owncloud.notes/androidx.work.impl.background.systemjob.SystemJobService`

**To Reproduce**
1. Install the app
2. Open a note (not sure it's relevant)
3. Do something else for the day, don't open the app anymore

**Expected behavior**
The app shouldn't use battery when not in use.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.7.0
 - F-Droid or Play Store: F-droid
 - Android-Version: 13
 - Device: Pixel 4a 5g

**Server**
 - Nextcloud version: 25.0.1
 - Nextcloud Notes version (server app): 4.6.0

**Comment by stefan-niedermann** [comment]
Not really unexpected - The background symchronization is triggered each 15 minutes and wakes up the phone to do some network reqiests.

There is no push mechanism (and propably never will be thanks to Google), so the app has to poll for being up to date.

Please disable the background synchronization for a while to verify my assumption (however, I have *enabled* it and it doesn't suck too much battery in my case...)

**Comment by blastrock** [comment]
Hi, thanks for the answer.

After I had this bug, I set the app battery usage setting to "restricted" in android to solve the issue. Now I even if I set it back to "optimized" I can't reproduce the issue.

In the meantime however, I had the same issue with the NextCloud app. Could it be that a bug in the NextCloud app would wake up the Notes app too frequently?

> and propably never will be thanks to Google

I am curious about this, why can't NextCloud use FCM or whatever? You can just link me to an issue or something :)

**Comment by stefan-niedermann** [comment]
Nextcloud does not call or wake up 3rd party apps, the communication is always triggered from 3rd party to Nextcloud.

FCM is a proprietary, closed source push service by a 3rd party company - no chance I will build this stuff into Notes or Deck. (Also the server counterparts of those apps would need to implement support).

Regarding the Nextcloud app: It uses FCM afaik if available, but you can ask this in their repository :)

**Comment by blastrock** [comment]
Ok, thanks for the explanation!

As for this bug, I'll see if it happens again and try to gather more info.
