### ISSUE TITLE
ownCloud notes compatibility?

### ISSUE THREAD

**Issue by thejohnha** [stefan-niedermann/nextcloud-notes#1613]
**Describe the bug**
Connection to ownCloud notes doesn't work like nextcloud

**To Reproduce**
1. Configure ownCloud Notes, etc.
2. Connect to ownCloud using this android app.
3. Notes not completely accessible

**Expected behavior**
Access to ownCloud notes similar to Nextcloud Notes

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.7.1
 - F-Droid or Play Store: Play
 - Android-Version: 13 Nov 5, 2022
 - Device: Pixel 6 Pro

**Server**
 - ownCloud version: 10.11.0

The ownCloud notes FAQ links to this app as the android client. I've been using this app successfully with nextcloud, but I'd like to switch to ownCloud (for reasons of stability). I'm curious to know if this app can somehow work with ownCloud... I configured OAuth and was able to make it connect to ownCloud but it doesn't seem to work properly. Probably a long shot but thought I'd ask. Perhaps this app was at one point compatible with ownCloud?

**Comment by stefan-niedermann** [comment]
We have dropped support for ownCloud years ago for various reasons:

1. The ownCloud Notes server app is abandoned. There are a few commits, but they all aimed for CI/CD changes as far as I can see. In fact it is not maintained anymore from my point of view.
2. The ownCloud Notes server app is lacking many features like favorites or support for categories. Maintaining those differences and explain them to users is a no-go for me
3. ownCloud does not support Single Sign On and all the features that it brought to Nextcloud (like easier user experience, enhanced security, and way less develolment efforts for edgy server configurations, 2FA, self signed certificates and so on)

The Nextcloud Notes Android App does not and probably will never again support ownCloud (Notes) in the future.

You can for sure try to checkout a version 1.x.x of this app and it might work - more or less, but keep in mind that those versions are outdated and not maintained. 1.x.x might contain security issues and lacking features.

I recommend you to use any other note taking app in combination with the `WevDAV` protocol if ownCloud still supports this.

And last not least my very personal 2 cent: Focusing on the core product is a great thing, losing the community and wider ecosystem with all the 3rd party apps might have been the price for the decisions that were made.

**Comment by thejohnha** [comment]
@stefan-niedermann Thanks for the detailed explanation - much appreciated 🙏

If anyone finds anything better than android Joplin over webdav to ownCloud, please drop a comment :-)
