### ISSUE TITLE
Can't connect to an account

### ISSUE THREAD

**Issue by kaffeeringe** [stefan-niedermann/nextcloud-notes#1614]
I just installed both the Nextcloud-app as well as your Notes app from FDroid. 

Nextcloud runs normally. When I start Notes and select that account I get an error that says my version of Nextcloud didn't support this feature: 
![Screenshot_2022-11-24-17-56-04-64_63b898a59b1e6029a726d4b280b2687a](https://user-images.githubusercontent.com/367592/203836923-729b983a-7935-491e-bab6-c4725ebec9c7.jpg)

**Comment by stefan-niedermann** [comment]
Please see my response here: https://github.com/stefan-niedermann/nextcloud-notes/issues/1607#issuecomment-1318235204

**Comment by kaffeeringe** [comment]
Thank you! Sorry for the duplicate report!
