### ISSUE TITLE
Sync, add, edit, delete Tasks

### ISSUE THREAD

**Issue by promnight** [stefan-niedermann/nextcloud-notes#1616]
Hi,
I really like the notes app.
I just miss the possibility to sync, create, edit or delete my tasks in this app.
Maybe at some point, they can add another section or create another app to enable this feature.

**Comment by stefan-niedermann** [comment]
This is clearly out of scope for this app.

For your use cases exist various better apps like Deck or Tasks (in combination with DAVx5 for a native Android calendar integration).
