### ISSUE TITLE
Client not syncing since upgrade of server app to v2.2.0

### ISSUE THREAD

**Issue by YohannLYD** [stefan-niedermann/nextcloud-notes#163]
I noticed that the client isn't able to login/synchronize my notes since I upgraded the note app on my nextcloud server.
I get a "URL/Server has errors" message but I am 100% sure my credentials are correct.

Is anyone currently experiencing it too ?

Nextcloud Server : 11.0.0
Notes : 2.2.0 (recently upgraded)
Nextcloud-notes : 0.9.0

**Comment by stefan-niedermann** [comment]
I haven't noticed any problem yet (same setup). Can you clear android app cache and data and try it again please?

**Comment by YohannLYD** [comment]
I found the solution. Actually there were some permission issues with the Notes folder in which all the notes are stored as text files.
It can be fixed by removing the folder (after a backup of the notes) so the server/app recreates a proper one. Then the files can be restored in the folder.

Everything is fine !
