### ISSUE TITLE
Syntax interpretation

### ISSUE THREAD

**Issue by fredtostaky** [stefan-niedermann/nextcloud-notes#1632]
Hello,

I'm using the nextcloud Notes with the e/os/ operating system on smartphone.
I'm up to date with the OS version.

Description : 
All the syntax seem not to be interpreted, example of step of writing a note :

```
# main title
### sub title
```

Seems work fine, main title is bigger than sub, but the ‘#’ stay visible… Not good.
And when you wrote :

`1. test task one`

and put a linebreak you have to enter the number ‘2’ in (it's not appear automatically) :

`2. test task two`

and nowif you put a linebreak again, there is interpretation and the numbering start … at 2, again :

```
1. test task one
2. test task two
2. test task three
3. test task four
```
etc.

And, the more you attempt to rewrote thing correctly, the more text get indentation or numbering, but sometimes very randomly. I have difficulties to reproduce the exact same comportment two times.

**Comment by stefan-niedermann** [comment]
> Seems work fine, main title is bigger than sub, but the ‘#’ stay visible… Not good.

Depends on the expectations. Notes Android is supposed to *not* hide the markdown punctuation. Use the preview (👁️ -icon) for a rendered view. There are currently no plans to provide a wysiwyg editor with destructive markdown, for example chaning all bullet points from `*` to `-` or other random stuff.

> I have difficulties to reproduce the exact same comportment two times.

I also am not able to reproduce your issue. Creating a new note and entering

```
1. foo
```

pressing <kbd>Enter</kbd> results in

```
1. foo
2. 
```

as expected here. Please provide exact steps to reproduce this issue.

Also provide the exact version of the app you are using. You can find it in the `About` section of the sidebar and it should be `3.7.1`.

**Comment by stefan-niedermann** [comment]
Well, I guess you already figured it out: The fork of /e/ is stone age. Version [`1.0.1`](https://gitlab.e.foundation/e/os/notes/-/blob/master/app/build.gradle).

Try the current upstrram version from F-Droid or ask /e/ to rebase their fork on a current version 🤷

**Comment by fredtostaky** [comment]
Oh, I found the button to close the issue, just next the "comment" button x-D
