### ISSUE TITLE
Type of database column MODIFIED

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#166]
Currently, the `modified` column in the database is of type `TEXT` (using the format `yyyy-MM-dd HH:mm:ss`). Is there a reason for that? In my view, it should be of type `INTEGER` (using the unix epoch), since this should require less space, sorting should be faster etc. But maybe, I've overseen something.

**Comment by stefan-niedermann** [comment]
No reason, we can switch to unix timestamps, but if you want to implement it, think about the update method of the app, so older clients are migrating it correctly. We will have to test it well.

**Comment by stefan-niedermann** [comment]
@korelstar is this issue part of your speed-up-project? I lately saw #167 is outdated. Can i support you to get this merged into `master`?

**Comment by korelstar** [comment]
No, this was not part of my speed-up-project. Currently, I'm not working on this issue. It has very low priority for me since I'm not expecting that the change of the type will have large effects. However, in long-term, I still think the change to `INTEGER` is a good idea. So please feel free to do something, here.

I hope, I'll find some time in the near future to update #167. But this depends on a rework of nextcloud/notes#51 and there are other things in the pipeline ... but I will definitely do that. :-)

**Comment by schaarsc** [comment]
anyone working on this issue?

**Comment by stefan-niedermann** [comment]
nope

**Comment by stefan-niedermann** [comment]
Fixed by #416
