### ISSUE TITLE
Server connection is brokern

### ISSUE THREAD

**Issue by avalx** [stefan-niedermann/nextcloud-notes#168]
I've just upgraded my phone (Oneplus 3) from Oxygen OS 3.2.8. (Android 6.x) to the latest Oxygen  OS 4.0.2 (android 7.0) and the app stopped working. I get an error message: "Synchronization failed: server connection is broken." I tried and removed the app and installed it again but get the same error. It was working without problems under OOS 3.2.8.

The Nexcloud app is working without a problem as is the DAVdroid. I've checked on the server and there is nothing in the log to indicate any problem. Is there anything else I should check?

EDIT: Some more info
I've played with the protocol dump on the server and found out there is an error message in the communication (TLSv1.2): Fatal - Certificate Unknown. I could not figure out the cause for this.

**Comment by stefan-niedermann** [comment]
Are you using a self signed cert? If so: Have you imported your self signed cert into android keystore?

**Comment by avalx** [comment]
Yes to both questions. I can see the cert in the Trusted credentials store under USER certificates. I imported it with CAdroid app.

And as mentioned the Nextcloud app is working OK - it did ask me to trust the cert the first time  ran it.

**Comment by avalx** [comment]
Just to add info that the MyOwnNotes application is working well - even with my Nextcloud server.

**Comment by cptechnik** [comment]
Pse let it be easier to use self-signed certificates!
The main app nextcloud has not such problems with self-signed certificates!
And to import certificates to android I have to use the lockscreen, but I won't to use the lockscreen!
And the last news about SSL and certificates especially the Chinese one and their unacceptance from Firefox should be a rethinking of a too strikt using of certificates...

**Comment by joefidler** [comment]
Getting error "Invalid Login: server connection is broken" with a Lets Encrypt certificate on the Nextcloud (11.0.2) site. The Nextcloud  file client app is able to connect fine after telling it to trust the site's certificate. I have tried with and without a certificate imported into Android (7.1.1) but it makes no difference either way. Very frustrating - want to try the Android Notes app but I can't even get into it. Notes app version is 0.9.0 from FDroid.

**Comment by bigbear42** [comment]
Downloaded the app from Google today but did not get it to connect. I run Owncloud 9.1.4 with a "Lets Encrypt certificate". Smartphone runs Android 5.1. The ownNotes app connects without a problem.

**Comment by stefan-niedermann** [comment]
Dear @bigbear42,

this app is a client for "ownCloud Notes" and **not** for "ownNotes". Therefor you will have to install the correct app on your server to get it work.

Regards

**Comment by bigbear42** [comment]
Ahhh, I see. Will give it a try than. Thank you.


Am 18.03.2017 um 10:00 schrieb Niedermann IT-Dienstleistungen:

**Comment by avalx** [comment]
With the new version 0.10.0 this problem is not present anymore.

**Comment by stefan-niedermann** [comment]
Great news, thank you for retesting!

**Comment by joefidler** [comment]
Just confirming what has already been tested. I can now sync notes  using version 0.10 with Nextcloud (11.0.2) from Android (7.1.1). One aside, my Android version (LinageOS) did not include trust for the Let's Encrypt authority so I had to add their certificate.
Thanks all for your work on this app - I can now see it and it looks good.

**Comment by stefan-niedermann** [comment]
> Thanks all for your work on this app - I can now see it and it looks good.

Thank you very much. :)
Any help is very welcome. especially at the self-signed-certificate-front 😉
