### ISSUE TITLE
Nested numbered list levels and combined list types do not work

### ISSUE THREAD

**Issue by joephein** [stefan-niedermann/nextcloud-notes#173]
### Expected behavior
Android app shows combined list types identical as in the Nextcloud web UI.
At the same time there seems to be no support for nested numbered list levels but this might be a feature request for the Nextcloud app and not for this android app.

### Actual behavior
Combined list types (numbered and bullet-ed list types) are numbered according to first list type.
So if the list items start with a * all subsequent rows automatically use this list item.

### Steps to reproduce the behavior
1. Create a note with the attached markup
[test_markup.txt](https://github.com/stefan-niedermann/nextcloud-notes/files/727178/test_markup.txt)

2. Compare the results in the web UI with the Android app.

Android app:
<img src="https://cloud.githubusercontent.com/assets/12627719/22255253/1d982094-e257-11e6-911b-d666013643b5.jpeg" alt="Android UI" width="270" height="480">

Nextcloud UI:
<img src="https://cloud.githubusercontent.com/assets/12627719/22255298/40d8912e-e257-11e6-9c51-04f01fcd634a.png" alt="Nextcloud UI" width="296" height="373">

### Possible solution (optional)
- Enter some header to reset the list type. There is no real solution.

### Server configuration
**Web server:** Apache 5.6.28
**Database:**  mysql
**PHP version:** 5.6.28
**ownCloud/Nextcloud version:** Nextcloud 11.0.0 (stable)
**Are you using encryption:** yes (https)

### Android app
**Version:** Android v0.9.0

### Client configuration
**Operating system:** Windows 8.1 with Firefox

**Comment by splitt3r** [comment]
Also ### dies work in web but not in the APP.

**Comment by stefan-niedermann** [comment]
Yeah, see, there are some issues with this:

1.) The markdown interpreter is not coded by us.
2.) The screenshot is from v0.8.0
3.) We switched in current master from `ByPass` to [`RxMarkdown`](https://github.com/yydcdut/RxMarkdown/issues)

So the behavior will change in the **next released version**. If *then* something does not work like expected, feel free to open issues on upstream.
