### ISSUE TITLE
Allow to share into exiting note

### ISSUE THREAD

**Issue by gsantner** [stefan-niedermann/nextcloud-notes#174]
Please allow to share into (=append) a existing  note.
I sometimes select multiple text parts to remember, or want to temporary save an url, which always creates a seperate Note. But it would be great if I had the option to just append to an other (or the last created) note.
This would save a lot of time, because I don't need to merge everything anymore.

**Comment by stefan-niedermann** [comment]
Would you expect that the note will stay open ready to edit after you shared or would you expect to close the notes app directly after selecting a note which the shared text will be appended to?

**Comment by gsantner** [comment]
To stay open - but the previous screens can be `finish()`ed, so a simple back button will go back to app used share into. 

It could be also an setting/option:
* Default: Stay open after share into
* Other Opt: Instant go back

**Comment by stefan-niedermann** [comment]
Okay, Pull Requests are welcome, but without introducing any new option. Your suggestion, to finish the previous screen is a pretty good default.

**Comment by aslmx** [comment]
I came here to open a Feature Request for exactly the same problem. Apparently i can't develop this and raise a PR. Anyone working on this? Would really appreciate this feature :)

**Comment by stefan-niedermann** [comment]
You can put a bounty on it, maybe someone has more time to implement this 🤷‍♂ 

I will see how much time i have, but there are more important topics for me and this issue has low priority for me, so no promises.

**Comment by gsantner** [comment]
By the way, this one of the reasons and things why I worked on my own project, which has this feature. If somebody interested, check it out :D


https://gsantner.net/project/markor.html

**Comment by gsantner** [comment]
I'm closing as anyway nobody cares here, and I don't use NextCloud-Notes.

**Comment by stefan-niedermann** [comment]
That's not true, it's still an issue that absolutely makes sense.

It's a pitty that you don't use the app anymore, but this is a feature i plan to implement, so i will reopen the issue.

**Comment by aslmx** [comment]
I comment here just to give you some motivation. I still would like to see this feature :)

**Comment by stefan-niedermann** [comment]
Fixed in master, will be published with the next version :rocket:
