### ISSUE TITLE
Some issues on translations/Transifex

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#175]
- [x] In some languages (e.g. `es`), quotes in hyperlinks are escapes with backslashes which breaks the build: e.g., https://github.com/stefan-niedermann/nextcloud-notes/blob/3647ec3c3524ce409bc51e61113c53b215e38d5b/app/src/main/res/values-es/strings.xml#L77 -- However, I don't know where this comes from. Maybe we have to use `&lt;` instead of `<` for HTML tags inside of a string, but that's only a hypothesis.
- [x] Constant parts of strings (e.g. URLs) should be moved into separate (untranslatable) string. This will simplify changes in these parts (i.e. in `about_source`, `about_issues`, `about_app_icon_disclaimer`, `about_icons_disclaimer`, maybe also the license name in `about_app_license`).
- [x] Some of these URLs point to an outdated location, so a change is definitely required (`about_source`, `about_issues`).
- [x] I propose to merge the two sections about icon into one (`about_app_icon_disclaimer`, `about_icons_disclaimer`). Strings can be concatenated.
- [x] The list of translators (`about_translators`) is obsolete. I propose to change the string to `Nextcloud community on Transifex`.
- [x] Plurals are currently in a separate file (`plurals.xml`). However, there is no need for this and it causes that there are two separate resources in Transifex, which bloats the project. I propose to integrate plurals into `strings.xml`.
- ~~There is an XML schema in order to provide more information about untranslatable parts of a string (especially placeholders) which can be helpful for translators (see [docs](https://developer.android.com/distribute/tools/localization-checklist.html)), e.g. `<xliff:g id="app_version" example="v2.1.0">%1$s</xliff:g>`. We could use it, but I don't know how it works with Transifex!~~ *doesn't work with Transifex export*
- [x] (by @stefan-niedermann ) `Contribute`-tab should get a new section "Translate"

Fixed in PR #180.

**Comment by stefan-niedermann** [comment]
8. `Contribute`-tab should get a new section "Translate"

**Comment by korelstar** [comment]
Unfortunately, Transifex prevents us from using the `xliff:g` tags: Transifex adds backslashes also to the quote signs from the attribute value of the tag. This is wrong, because here, the `<` must not be escaped (it belongs to an XML tag of the resource file and not to the content of the string). Too bad, since `xliff:g` is a nice approach.
