### ISSUE TITLE
Use .md as filename extension for new notes

### ISSUE THREAD

**Issue by mejo-** [stefan-niedermann/nextcloud-notes#176]
Please change the filename extension for new notes from `.txt` to `.md`. This is the correct filename extension for markdown files. It also helps text editors to choose the right syntax highlighting.

**Comment by stefan-niedermann** [comment]
There is a correspondenting issue in the server part (https://github.com/nextcloud/notes/issues). This app only uses the API and is therefore not able to set *any* extension itself at all.
