### ISSUE TITLE
API Compatibility Issues

### ISSUE THREAD

**Issue by lilicoding** [stefan-niedermann/nextcloud-notes#177]
Dear developers,

We have recently developed a state-of-the-art static analysis tool for uncovering API compatibility issues in Android apps. Applying this tool to open source apps on F-droid, we have exposed a few instances of compatibility issues and submitting them to development teams for a fix. 

For your app, we have found that this project has accessed the following APIs which are available only on an API level higher than the declared minSdkVersion and which are accessed without proper protection. In other words, if those APIs get called at runtime, it will trigger a NoSuchMethodError and thus result in a crash of the running application.

<android.widget.RemoteViews: void setRemoteAdapter(int,android.content.Intent)>:[14,25]

Note that, because of the nature of the static analysis, we cannot confirm whether the flagged APIs would actually be called at runtime (e.g., unreachable code). However, we still believe that those APIs, which may cause compatibility issues, should not be accessed or at least be accessed with proper protections. 

In addition to the aforementioned APIs (i.e., backward-compatibility), which could cause app crashes if accessed, we have also identified that this project has also accessed some APIs that have been removed from the latest public SDK, making the app possibly suffer from forward-compatibility issues.

NONE

We would be very much appreciated if you can acknowledge to us that those reported APIs are indeed problematic for the project’s long-term stability. please let us know if you need any more information relating to this issue report.

**Comment by korelstar** [comment]
> `<android.widget.RemoteViews: void setRemoteAdapter(int,android.content.Intent)>:[14,25]`

That's from the `AllNotesWidget`. Indeed, this is currently unreachable code. But I agree, that we should do something, here.

@stefan-niedermann What are your plans belonging the widgets? I have no demand for this, therefore I will not contribute in this part :stuck_out_tongue_winking_eye: (there are other things which are more important).

@lilicoding Does "NONE" means, that we have not any forward-compatibility issues?

**Comment by stefan-niedermann** [comment]
hehe, widgets are planned (one for all notes and one for a single note) but with low priority as i do not need those, too. I think when i finally have time to code there, i will throw away the code and start from scratch.

**Comment by korelstar** [comment]
Okay, then let's throw away the code, now. It makes only more work for us when we are refactoring something etc.

**Comment by stefan-niedermann** [comment]
Aggree
