### ISSUE TITLE
Cannot login to nextcloud

### ISSUE THREAD

**Issue by marlemion** [stefan-niedermann/nextcloud-notes#179]
I have nextcloud 11.0.0.1 running (on arch) using nextcloud notes:

https://github.com/nextcloud/notes

Downloaded the app from f-droid and tried to logon to my (https) server. Certificates are managed via letsencrypt and are working fine using the browser or other apps.

The app does not connect throwing 'Login fehlgeschlagen: URL/Server fehlerhaft'.

Reproducible: always, OS: Cyanogenmod 13.0 (Android 6.0.1) Galaxy S4.

**Comment by stefan-niedermann** [comment]
Okay, that's strange. Can you set up a test account for me and mail me the information to my private email address?

**Comment by xraMsamohT** [comment]
It is not a problem with the Let´s Encrypt certificate. It is a problem with the Nextcloud Notes app and the user, imho.

@marlemion Do you use 2FA with the TOTP app? How many notes do you have? One single folder oder with sub-folders?

**Comment by codejp3** [comment]
Verifying same issue.

Rooted Galaxy S5, variation of CyanogenModROM called BlissPop.

I'm using a self-signed cert which I believe to be issue. The cert is generated for the private LAN and used by several LAN users and the public facing domainname.tld IP address. It works just fine with DavDroid, NextCloudSMS, the NextCloud default App, through browsers, and so on. This app is the first one I've had connection issues with and I think it's related to the cert. 

Cert details:
Issued TO:
Common Name (CN) hostname.domain.lan
Organization (O) <Not Part Of Certificate>
Organizational Unit <Not Part Of Certificate>
Serial Number XX:XX:XX:XX:XX:XX:XX:XX:XX

Issued BY:
Common Name:
Common Name (CN) hostname.domain.lan
Organization (O) <Not Part Of Certificate>
Organizational Unit <Not Part Of Certificate>

Certificate Signature Algorithm: PKCS #1 SHA-256 With RSA Encryption
Subject Public Key Algorithm: PKCS #1 RSA Encryption
Cert Basic Constraints: Not Critical, Is not a Certificate Authority

**************Here's where I think the issue might be*************
Certificate Subject Alt Name:
Not Critical
DNS Name: hostname.domain.lan
DNS Name: domain.lan
DNS Name: hostname
DNS Name: localhost
********************Does NOT include public domainname.tld, which is used for public access******************

Like I said, it works fine for everything else, but I'm going to get my certs sorted out tomorrow and generate a proper self-signed cert specifically for the public domain. I'll report back whether it is indeed lazy/inacurate certs causing your app to break, or if there's something more on your end to look into.

**Comment by codejp3** [comment]
Just checking back in as promised.

Proper Certs took care of it. I also had to import the new cert to Android (CAdroid).

Beautiful app! Thank you for your time and effort!

**Comment by stefan-niedermann** [comment]
@marlemion have you been able to solve this issue, too? Have you set up a test account like i described?

**Comment by marlemion** [comment]
Hey. Sorry, I was completely absorbed by other (more important) things the last days. So I checked right now and it is working. Don't know what changed. Do you still want a test login?

**Comment by stefan-niedermann** [comment]
No, if everything is working, it's fine for me :) probably only a caching issue or so...

**Comment by eriteric** [comment]
I'm using a letsencrypt cert and have a similar issue.
Using 0.11.0 from f-droid on android 7.1.2
After about a minute, the toast says: `Invalid Login, Server has errors`

Android nextcloud, owncloud, and owncloud notes apps are able to connect.
OSX owncloud is able to connect.
iOS nextcloud is able to connect.

When i enter the server address it shows a checkmark.
The username and password I'm using is correct.
Is there a path I should be adding on to the server URL for connecting to notes? (right now i am using e.g. https://nextcloud.mydomain.com )

**Comment by kolaente** [comment]
I have the exact same issue as @marlemion described, i am on version 0.11.0 (Downloaded from F-Droid) on LineageOS 14.1-2017-09-11 Nightly (Android 7.1.2), Oneplus One.

Should i set up a testaccount for you @stefan-niedermann ?

**Comment by stefan-niedermann** [comment]
Yep, please mail the credentials to info[a]niedermann.it

**Comment by kolaente** [comment]
Email is sent.
