### ISSUE TITLE
Provide Preview Images for Widgets

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#18]

**Comment by stefan-niedermann** [comment]
Preview Image for Single Note Widget in c90e95e31476d9e513770c40303cfff461355a1f.

**Comment by dan0xii** [comment]
I believe this was closed by #250 and #273.

**Comment by stefan-niedermann** [comment]
I see, thanks for the hint :)

**Comment by dan0xii** [comment]
I was trying to see if there were any older issues I could work on and spotted it. :)
