### ISSUE TITLE
Zoom / make font size adjustable

### ISSUE THREAD

**Issue by dejj** [stefan-niedermann/nextcloud-notes#189]
I have a document with manual line-breaks, to make lines match with the source document.
I edit the document on my tablet, and read it on my phone, with different resolutions.
2-3 words of every line get wrapped over to the next line. This makes reading uncomfortable.

Can you add a method to adjust the font size in the app?

**Comment by stefan-niedermann** [comment]
Dear @dejj,

i understand your issue. Briefly: I thought about it and i will not add an option to adjust font-size for now.
**Simplicity is a major design goal** of the app and therefore i want to implement only settings which are really needed by most of the users.
The app currently uses the system font-size, is it possible to decrease system font-size for you?

I am sorry i don't have better news for you.
Regards and thank you for feedback

Stefan
