### ISSUE TITLE
Render markdown tables

### ISSUE THREAD

**Issue by borghal** [stefan-niedermann/nextcloud-notes#190]
It would be great if the app could render a simple markdown table like this 
| name            | address                  | phone      |
|-----------------|--------------------------|------------|
| John Adams      | 1600 Pennsylvania Avenue | 0123456789 |
|-----------------|--------------------------|------------|
| Sherlock Holmes | 221B Baker Street        | 0987654321 |
|-----------------|--------------------------|------------|

RxMarkdown is capable of doing this, isn't it?

**Comment by borghal** [comment]
Ah, sorry, just found out that RxMarkdown doesn't do tables. So there's nothing you can do, I guess.
My bad.

**Comment by stefan-niedermann** [comment]
You are right, but it seems like RxMarkdown has it already on its roadmap. So maybe we will see this feature in a future release - otherwise you can of course [open an issue at upstream](https://github.com/yydcdut/RxMarkdown/issues). :)

**Comment by stefan-niedermann** [comment]
`v2.19.0` will support viewing tables.
