### ISSUE TITLE
HTTPS problem with not trusted certif AND certif trusted for other domain

### ISSUE THREAD

**Issue by voxdemonix** [stefan-niedermann/nextcloud-notes#191]
Hello community.

Their is a problem with this application in [LAN](https://en.wikipedia.org/wiki/LAN) (IPv4).
I can connect easy in http (it's work) but not in httpS. The problem come from the certificate : not work with self signed and not work with certificate trusted but for other domain name.
In [WAN](https://en.wikipedia.org/wiki/Wide_Area_Network) it's work in https (certificate trusted only).
Please can you add the same system than Nextcloud App for accept the certificate?

I don't want modify my /etc/hosts and don't want to be forced to use trusted certificate. ^^

Thank you well and thanks for your work.

GNU Powaaa.

**Comment by korelstar** [comment]
This is already on the agenda, see #73.

**Comment by stefan-niedermann** [comment]
@voxdemonix can you retest with v0.12.0 please? (not on google play yet but on fdroid)

**Comment by stefan-niedermann** [comment]
`v0.12.1` is currently rolling out on Play Store. It should reach all users in the next view days if no bug occurs. Please retest and feel free to reopen or comment this issue if your problem persists.

Regards
