### ISSUE TITLE
edit any txt file not only notes

### ISSUE THREAD

**Issue by sdadoun** [stefan-niedermann/nextcloud-notes#192]
Hello,
   Thanks a lot for this very convenient app.
Would it be possible/complex to edit any text file ?
It will require to add a file browser to move in sub-folders to select the file one wants to edit.
Thanks
Simon

**Comment by stefan-niedermann** [comment]
Dear @sdadoun,

sorry, but this is not a goal of this app. main goal is to support the api of the notes app and provide a simple UI for this.
there are many file maanagers which allow to edit text files like oi filemanager, cm filemanager, ghost commander and hundrets others.

Sorry
