### ISSUE TITLE
App crashing on editing note with CRLF line ending

### ISSUE THREAD

**Issue by ThingsGetWorse** [stefan-niedermann/nextcloud-notes#215]
**Android version:** 7.1.2  
**Device**: Nexus 9  
**System language**: English (UK?)
**App version:** 0.11.0
**App source:** Google Play Store

**Steps to reproduce:**
  1. open the app
  2. click on attached note
  3. try to enter an additional character

Editing was/is fine in
**Android version:** 6.0.1  
**Device**: S5 Neo  
**System language**: German
**App version:** 0.9.0

[__Markdown Reference.zip](https://github.com/stefan-niedermann/nextcloud-notes/files/1010650/__Markdown.Reference.zip)

**Comment by ThingsGetWorse** [comment]
Reason is Windows vs. Unix line endings (CRLF vs. LF)
The note was created as an **.md** file on a Windows system and not through the apps. Switching line endings to _LF_ resolved this issue.

Not sure how to proceed though.

**Comment by stefan-niedermann** [comment]
sounds reasonable. i think this should be solved in the server app, shouldn't it?

I guess you created the file on windows and uploaded it manually to the Notes-folder in your Nextcloud instance? The server app recognizes it and provides it via the API to the clients. When detecting new files, they should be converted automatically.

I am sure, there was recently a similar issue about the charset (utf-8 and others)

cc: @Henni @korelstar

**Comment by Henni** [comment]
In my opinion we shouldn't modify files without any user interaction. Line endings should be handled by the editor.

**Comment by ThingsGetWorse** [comment]
@Henni - on the other hand the file name is already altered wo/ interaction by the user.
Meaning the actual file name is set/changed to the first line of the file which is assumed to be the title of the note.

**Comment by korelstar** [comment]
Recently, this bug has shown on my device, too. I investigated it and found out that not every note with windows-style line-breaks lead to a crash. However, it is reproducible for some sorts of lists. I've reported it to RxMarkDown (see yydcdut/RxMarkdown#41).

However, I propose to implement a workaround until the bug is fixed. The workaround should convert `\r\n` to `\n` if the user wants to edit a note. The change would only be saved if the user makes any changes to the note. Please see PR #292 for this solution.

**Comment by stefan-niedermann** [comment]
So i think #292 should have solved this issue, shouldn't it? We can close it as the fix will be shipped in the next version.

**Comment by korelstar** [comment]
Yes, but it's already auto-closed ;-)

**Comment by stefan-niedermann** [comment]
nope, i just closed it :D
