### ISSUE TITLE
[Feature] Please setup View-Mode as default or add a option to change it

### ISSUE THREAD

**Issue by ghost** [stefan-niedermann/nextcloud-notes#222]
Please setup the View-Mode as default, like the previous version (0.9.0) it have. It is very annoying when you want to view a note. Because at first the keyboard comes up and you prescribes a note.

**Comment by cstackpole** [comment]
Using the 0.11.0 app from F-Droid.

Throwing in on this. For the last few hours I've been working on a group project where other people are updating a note in Nextcloud and I'm just trying to "read-only" from my tablet the updated information as things change. I don't get the update [1] unless I back out of the note and go back in. But to do that puts it on the "edit" feature and if I'm not *PERFECTLY precise* in touching the eyeball icon, it causes an "edit change" [2] which then causes a conflict to be found on the server which then causes issues with syncing from the others. We've adapted, but sheesh is it annoying.
[1] Swiping down doesn't work for refresh it seems when in view or edit mode. This means backing out to the main screen. If there's a refresh from the view page, I don't know about it.
[2] Doing a diff of the file shows that there wasn't actually any change. But it seems that whatever (timestamp ?) the app does causes the server to think that there was a change.

On a side note, I really do like this app. I use it all the time and this is really the first time I've had a moment of frustration. Thank you to everyone involved! :-)

**Comment by korelstar** [comment]
@schaarsc implemented a setting for the view-mode in #242!
This will be part of the next release :-)

@cstackpole Adding a synchronize action to the view page is an interesting idea. This is not possible, yet. Please create a new issue for this feature request!
