### ISSUE TITLE
Impossible to connect with ownCloud release 9.1.5

### ISSUE THREAD

**Issue by Viald** [stefan-niedermann/nextcloud-notes#224]
I just bought the app and try to connect to my ownCloud server 9.1.5. 
I have this error message: Incorrect connection, does the note app is enable on your server? 
And that's the case! 
Thank you for your help.

**Comment by stefan-niedermann** [comment]
Hi, please make sure you

1. have installed a valid certificate and
2. have installed the "[Notes](https://github.com/owncloud/notes/)"-App on the server-side.

**Comment by Viald** [comment]
The certificate is valid and note app is installed. I can send you credentials in private for testing.

**Comment by Viald** [comment]
Can I expect support? Or should I ask for a refund? Thank you

**Comment by stefan-niedermann** [comment]
Okay, please send me credentials to my email adress, i will try to reproduce the problem. i am not sure if a refund can be granted at google play store after this long time period (though you can try it if you want of course ;-) )

regards

**Comment by Viald** [comment]
I sent them to your email address today.

**Comment by stefan-niedermann** [comment]
Dear Viald,

thanks, i checked the instance and you are using the wrong server side notes app.
Please install "Notes" - not "NextNotes", not "ownNotes" or anything else. The correspondenting github repo is https://github.com/nextcloud/notes

Please feel free to reopen if you experience any further issue :)

Regards

**Comment by Viald** [comment]
Thank you for your support. 
We'll correct this mistake. 

Regards

**Comment by stefan-niedermann** [comment]
No problem, i am glad that i was able to help.

If you have purchased the app via Play Store please feel free to leave a rating if you like the app ;-)

Regards

**Comment by Viald** [comment]
It works like a charm. Thank you.
