### ISSUE TITLE
Solution for reserved characters in filenames

### ISSUE THREAD

**Issue by DonRichie** [stefan-niedermann/nextcloud-notes#228]
I had the issue that my notes were not synced to my windows desktop.
After some investigation I found out that the character ":" which occured in a "https://" URL was not compatible with the NTFS filesystem.

Also the character "/" was ignored to satisfy the needs of a unix filesystem.

I personally would like a solution like this:
- Ignoring characters which are not allowed in nextcloud should be default.
- In the configuration menu it is possible to exclude specific characters by ticking checkboxes for windows and maybe also what the mac filesystem need.
- After someone uses one of the special characters the first time, the user is asked to choose if he wants to ignore those characters or not. Also he should ge a hint to the configuration menu.

Also:
The problem doesn't occur in the text itself since it is UTF-8 encoded in owncloud. But the filename seems to be auto generated from the text. Maybe it would be a good idea to make the filename editable in the app.

**Comment by korelstar** [comment]
I think escaping more characters (like `:`) is a good idea. However, since generating the filename is part of the server app, please open an issue there: https://github.com/nextcloud/notes

**Comment by korelstar** [comment]
Please see nextcloud/notes#148 for a fix.

**Comment by korelstar** [comment]
This was fixed in the server app v2.3.2.
