### ISSUE TITLE
.md - Make default file ending choosable

### ISSUE THREAD

**Issue by DonRichie** [stefan-niedermann/nextcloud-notes#229]
Currently .txt is the default ending for created notes.

I would like to be able to switch it to .md since all my other notes use this ending as default.

A simple textfield in the configuration menu would be a good idea.

**Comment by stefan-niedermann** [comment]
Hi,

it is impossible to define the file type via the API, but there is a correspondenting issue in the server side repository (this is only the android client): https://github.com/nextcloud/notes/issues/24

Regards
