### ISSUE TITLE
Markdown: sublists broken?

### ISSUE THREAD

**Issue by minimeee** [stefan-niedermann/nextcloud-notes#232]
Hi!

 It seems that sublists are not being correctly displayed in the app. I'm not a markdown expert, but I couldn't get it to work, no matter what I did. I've attached screenshots of a simple example.

This is the list as it looks in nextcloud (OK):
![nc_notes](https://user-images.githubusercontent.com/5322305/27864770-331519fa-6190-11e7-972d-21cbf60d6155.png)

This is how it looks in the edit mode of the app (mostly correct, but not nicely formatted):

![android_notes_edit](https://user-images.githubusercontent.com/5322305/27864955-f56f5e34-6190-11e7-995f-7c9f9a9fc6fb.png)

And finally, this is how it looks in view mode (completely broken):

![android_notes_view](https://user-images.githubusercontent.com/5322305/27864783-4127b9b2-6190-11e7-9cb9-92c3ffc75888.png)

Am I doing something wrong (it looks as intended in the nextcloud web GUI) or is this a bug?

**Comment by stefan-niedermann** [comment]
i guess it's a bug in the used markdown library.
You should open an issue in the upstream project: https://github.com/yydcdut/RxMarkdown
Thanks for reporting :)

**Comment by minimeee** [comment]
OK, thanks. I've created an issue here: 
[https://github.com/yydcdut/RxMarkdown/issues/34](https://github.com/yydcdut/RxMarkdown/issues/34)

**Comment by Hanzei** [comment]
Since this is PxMarkdown problem, can we close this one?

**Comment by minimeee** [comment]
I understand why you closed it, but the problem remains and it seems that it won't be fixed in upstream soon... Is it possible to disable Markdown support in the app? In its current state, it's more annoying than helpful :-(

**Comment by stefan-niedermann** [comment]
Sorry, there is an idea to enable source-code-edit, but i have not decided yet if it will be implemented.
