### ISSUE TITLE
Add note title

### ISSUE THREAD

**Issue by mase76** [stefan-niedermann/nextcloud-notes#233]
Hi!
The notes should have a title field to define the filename.
The current behaviour is, that the first word is the title.
This could mess up with other applications on other machines
accessing the notes.

**Comment by stefan-niedermann** [comment]
This is by design. You could ask in the serverside repository, but i don't think they will add this feature because it is wanted behaviour. Check https://github.com/nextcloud/notes/issues

**Comment by mase76** [comment]
Sorry! I did not notice, that the serverside app causes this behaviour. I use it not such long.
I filed an issue there.

**Comment by stefan-niedermann** [comment]
no problem. the server app provides no api for changing or setting the title, therefore the android app has no option. personally i like the current pehaviour

**Comment by mase76** [comment]
I workaround this by writing the title (and so the filename) in the first line.
I started using the notes app a few weeks ago. Before that I used the
normal filesync with textfiles with a normal texteditor.
