### ISSUE TITLE
Unable to connect on non-standard port

### ISSUE THREAD

**Issue by doucettom** [stefan-niedermann/nextcloud-notes#243]
I am using a non-standard port for my HTTPS setup and I am unable to get the check at the end of the server line.

I use a self-signed cert but I imported it in my Android phone so I don't think it's the issue.

HTTP on the LAN is working just fine (standard port used...)
(I/O error when trying to connect)

**Comment by korelstar** [comment]
This issue looks similar, the app uses the same library for https: https://forums.bitfire.at/topic/1540/non-standard-port-ignored-with-untrusted-cert
Maybe, you have problems with algorithms, too?

**Comment by stefan-niedermann** [comment]
@doucettom did you check the linked conversation? Do you have any updates for us?

**Comment by schaarsc** [comment]
I think we should revisit this after #418

**Comment by stefan-niedermann** [comment]
@doucettom some versions ago we updated the `cert4droid`-library. Could you please recheck with the latest version of the app?

If the problem is still persistent, please reopen this issue and provide some log entries - without logs we can hardly fix the issue.
