### ISSUE TITLE
on the fly "formatting" of list is broken

### ISSUE THREAD

**Issue by znegva** [stefan-niedermann/nextcloud-notes#245]
**Android version:** 6.0.1 Marshmallow
**Android Keyboard version:** Gboard 6.4.16.162469584-release-armeabi-v7a (Version 20170724, de_DE)

**Device**:  Motorola Moto G (3. Generation)

**System language**: German, ...

**App version:**  v0.11.0

**App source:** F-Droid

**"naming conventions"**
For clarification all spaces will be represented as `_` !

Note Editing has two modes:
 1) _edit mode_ where I can modify the content with the Software keyboard provided by Android. Markdown markups applied here do format the text on-the-fly (e.g. when starting a line with `##_` the fontsize is increased and font is bolt)
 2) _view_mode_ can be entered by clicking the eye on top-right, here we can see a _rendered_ preview of the note (I will also outline spaces in _view mode_, maybe these are in fact margins or whatever)

**Problem description**
on-the-fly formating of lists in _edit mode_ is kind of broken, some examples

 1) in _edit mode_ entering `*_item1` on a new line does not trigger any reformatting
but in _view mode_ this is shown as `_•_item1`

 2) in _edit mode_ entering `_*_item2` on a new line does not trigger any reformatting
but in _view mode_ this is shown as `__•_item2`

 3) in _edit mode_ entering `*_item1` and THEN inserting a space in front of the `*` triggers a reformatting to `_•_*_item1`
but in _view mode_ this is shown the same way as before: as `__•_item2`

4) in _edit mode_ entering `_*_item4` and THEN putting the cursor in front of the `*` and click BACKSPACE triggers a reformatting to `_•_*_item4`
in _view mode_ this is shown as `_•_item4`

 5) when the on-the-fly rendering of a list-item has worked (there is a • in front of it), it is possible to add a new item by hitting RETURN at the end of any item, but this only works if the Android keyboard did not autocorrect the last entered word

It seems the on-the-fly formatting of lists in the editor is totally broken, the _view mode_ seems to do the right thing.
It is not possible to "initialise" a list without setting the cursor in front of the `*` and insert a space.

**Comment by stefan-niedermann** [comment]
Okay, thank you very much for your great description. The Markdown-rendering is completely delegated to the [RxMarkdown](https://github.com/yydcdut/RxMarkdown/issues)-Library. Therefore we would have to bring our issues and contributions upstream if we want it to use in this app.

I would like to ask you to bring your issue upstream. I know, there is currently not much active development, but it is really hard to find an active developed library that fits our needs (we used `ByPass`-Library for a while, but this did'nt work well at the long term).

If you have any further questions please feel free to comment or reopen this issue.

Regards
