### ISSUE TITLE
Edit/Preview Activity enhancements

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#246]
Thanks a lot to @schaarsc for #242 !

I have some further ideas for enhancement:

- [x] The ActionBar buttons and menu entries should be consistent for edit mode and for preview mode. Currently, there is a "Category" button in edit mode, but none in preview mode. **(high priority)**
- [ ] I suggest a new view mode "source code", which contains a native `EditText` without Markdown functionality. This could be useful, if there are problems with `RxMDEditText` or if someone wants to edit text only. **(low priority)**

Edit: Here are some more issues:
- [x] `NoteEditFragment.getNote()` saves implicitely the notes and triggers synchronization. This is kind of bad hack: E.g., when opening a note in edit mode, `saveData()` is called twice (without a need at all), when triggering the favorite action in edit mode, `saveData()` is also called twice (triggering once at the end is sufficient). This should be optimized. **(high priority)**
- [x] The label of the *edit* button is wrong. A good solution would be to add both (edit and preview) buttons to the XML file and then toggle visibility instead of modifying them. **(high priority)**
- [x] I suggest to change the order of the buttons/menu and put the preview/edit button at first position. In my point of view, this is the most important button which should be shown even on devices which are so small that only one button can be shown. **(medium priority)**
- [x] It's good that the mode strings in `EditNoteActivity` (e.g. `edit`, `preview`, ...) were moved to constants. However, there are still two sources of these strings: `arrays.xml` and `EditNoteActivity`. This should be consolidated into one source. E.g., add constant strings to `arrays.xml` (e.g. `<string name="note_mode_preview">preview</string>`) and reference those from `string-array` (e.g. `<item>@string/note_mode_preview</item>`) and from `EditNoteActivity` (`getString(R.string.note_mode_preview)`). Another option would be to use class constants and then fill the preference activity manually from these constants. **(low priority)**
- [x] We should do this also for all preference keys, such as `PREF_NOTE_MODE` (but also for the other preferences). But that can be done later. **(low priority)**

**Comment by stefan-niedermann** [comment]
I agree with the first, but how would the source code help to fix bugs in Rx?

**Comment by korelstar** [comment]
This is not the purpose. But "live markdown highlighting" will always have a special look&feel that can make things more complicated than editing plain text. It's just my experience from using Notes for a longer time.

But it would be interesting, to get other people's feedback on this.

**Comment by stefan-niedermann** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
Well, a big inspiration for Notes is iA Writer: https://ia.net/writer/

They handle Markdown really well and are quite popular. So if we have any issues regarding interaction, best check out their app. :)

Also, can you post screenshots of work-in-progress and also in general? That makes it easier to understand what is being referred to. :)

**Comment by korelstar** [comment]
@jancborchardt 
A screenshot isn't sufficient for this discussion. It's more about the look and **feel**. Please install the app and compare it to your loved iA Writer. As far as I can see (since it's not free), iA Writer is more like editing source-code (with some syntax highlighting). The current Notes (both server and Android) app approach is more WYSIWYG.
The iA Writer approach *looks* good to me, but I can't say, how it *feels*! However, I think, a source code / plain text mode would go in the right direction.

**Comment by jancborchardt** [comment]
@korelstar sorry, I just don't have that much time to always test every app. :/ Basically the Notes web interface is already a great adaptation of how iA Writer does it, having markdown formatting inline - a middle ground between plaintext and WYSIWYG.

**Comment by jancborchardt** [comment]
Also, the seamlessness of switching between plain text and markdown is very important in Notes. It's not a setting or a mode - you just do it.

**Comment by schaarsc** [comment]
what do you think about using the L&F from edit/preview for MD/TXT
- Menu Item to switch while viewing/editing
- Preference for always TXT / always MD

**Comment by stefan-niedermann** [comment]
> Menu Item to switch while viewing/editing
> Preference for always TXT / always MD

Both implemented in the meantime.

I still do not think, that a source code view is a good idea, it would more distract then be helpful. :-1:
