### ISSUE TITLE
Refresh from server when in view mode

### ISSUE THREAD

**Issue by cstackpole** [stefan-niedermann/nextcloud-notes#248]
Greetings,
Creating request based on #222 feedback.

When working on a group project, my team was editing files on the server and I was on my tablet getting the changes. Backing out of the file to refresh then going back into the file to view changes was a bit cumbersome. It is likely I will be working on a similar project in a similar fashion in the future.

It would be great if there was a way when in view mode, I could easily refresh that file from the server. It doesn't bother me if it is a button or a swipe down or something else. 

Thank you! Love this project and I'm getting tons of use out of it. :-)

**Comment by stefan-niedermann** [comment]
Great idea. I will go for pull2refresh since it is common android pattern and we already use it in the app.
