### ISSUE TITLE
Prepare for next F-Droid version (screenshots, localized descriptions, ...)

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#249]
The next F-Droid version will allow for new meta-data, i.e. localized descriptions, graphics, and screenshots, that can be provided directly from the app's source repository. It's part of a longly overdue design overhaul. This will be very cool! We need to provide this data ;-)

More Information:
- https://f-droid.org/2017/04/04/new-ux.html
- https://eighthave.gitlab.io/fdroid-website/docs/All_About_Descriptions_Graphics_and_Screenshots/
- https://github.com/nextcloud/android/issues/1081

**Comment by stefan-niedermann** [comment]
yep i planned to do this before the release, but its good to track this in an issue ;-)

**Comment by stefan-niedermann** [comment]
@korelstar i am struggeling with myself for the screenshots - whats your opinion?

1. Simple Screenshots
2. Screenshots with phone-frame
3. kind of banner like firefox focus does it (really like this but could break with new fdroid/gplay layouts

**Comment by korelstar** [comment]
Hmmm. I would use the screenshots (with phone) from Google Play, for now. The F-Droid app releases which display these screenshots are still alpha, so we don't know the exact layout of how they are displayed. But I think all options are fine.

**Comment by stefan-niedermann** [comment]
Started with previous F-Droid texts and images. This should be enough for the next release and can be extended with each version.
Languages: english & german.

Anyone: Feel free, to contribute screenshots and texts in your language.

Maybe we can find a way to integrate Transifex for this folder structure... @MorrisJobke ?

**Comment by stefan-niedermann** [comment]
Hm. Seems to not work...

**Comment by stefan-niedermann** [comment]
Help requested from fdroid-team: https://gitlab.com/fdroid/fdroiddata/issues/948

**Comment by MorrisJobke** [comment]
> Maybe we can find a way to integrate Transifex for this folder structure... @MorrisJobke ?

What do you mean by that? How can I help you?

**Comment by stefan-niedermann** [comment]
@MorrisJobke we have added some text files that contain title, descriptions etc for the app (used by F-Droid), e.g. here: https://github.com/stefan-niedermann/nextcloud-notes/blob/7510de60d52a6d8c7f80da52ceaf08d27cb40eec/fastlane/metadata/de-DE/full_description.txt

I have seen the official Nextcloud android client does the same, at least in the beta branch.

The question was, if those files can be translated via Transifex, too.

**Comment by MorrisJobke** [comment]
> The question was, if those files can be translated via Transifex, too.

I guess it's not easy to do so :(

@tobiaskaminsky what do you do with those files?

**Comment by tobiasKaminsky** [comment]
In Beta/Dev branch this was done manually by me for testing.
Indeed I tried to connect fdroid with transifex, but it is not that easy.
There is one plugin (https://github.com/JackyQu/fastlane-plugin-transifex), where I asked if this could solve the problem, but never got an answer.
Hans (from Fdroid) also asked at fastlane about an integration: https://github.com/fastlane/fastlane/issues/9520

If I have some time left, I will try to write a small script which copies the strings to the correct folder structure/files.

**Comment by stefan-niedermann** [comment]
Thank you for feedback :)

**Comment by stefan-niedermann** [comment]
Well. closing this for now. I subscribed to the linked issue and maybe at some point in the future, we can translate the stuff via transifex :-)

**Comment by tobiasKaminsky** [comment]
I have written this script and it is called within nexcloud transifex bot.

https://github.com/nextcloud/android/blob/master/scripts/metadata/generate_metadata.py

You would have to adjust https://github.com/nextcloud/android/blob/master/scripts/metadata/generate_metadata.py#L13-L16

Please ping me, if you need any help.

**Comment by stefan-niedermann** [comment]
That sounds great. How can i trigger the script? Or will the bot automatically scan for `scripts/metadata/generate_metadata.py` and execute it?

**Comment by tobiasKaminsky** [comment]
This will handled automatically:
https://github.com/nextcloud/docker-ci/blob/master/translations/handlePlainTranslations.sh#L40-L43

**Comment by stefan-niedermann** [comment]
I have one concern left: If all the meta data is stored in the `strings.xml`-files - doesn't that mean, that the description in x languages will be delivered to the android app and bloat it with (in the app) not needed strings? Or removes the build optimization those strings if no references from the app can be found?

@korelstar what do you think?

**Comment by tobiasKaminsky** [comment]
As far as I see, src/generic/fastlane/* is not included in build apk.
I unpacked it with apktool (https://ibotpeaches.github.io/Apktool)

**Comment by tobiasKaminsky** [comment]
Correct, they are included.
Maybe there is a way to remove them. 
Even if we have 100 languages, I doubt that this is too much overhead, especially as all resources are compressed.

**Comment by korelstar** [comment]
@stefan-niedermann 
I would go with this approach, since I think its advantages predominate.

(Thanks, @tobiasKaminsky !)
