### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by pejakm** [stefan-niedermann/nextcloud-notes#256]
Dark theme would be useful. For example, the news app (https://github.com/nextcloud/news-android) has this.

**Comment by dan0xii** [comment]
How's this for a rough start. I'm not sure about the difference in colours between the title bar and the category labels, might try a grey for the categories.

![Imgur](https://i.imgur.com/PbaJrLk.png)

![Imgur](https://i.imgur.com/pOxazkL.png)

![Imgur](https://i.imgur.com/VCsrSc0.png)

![Imgur](https://i.imgur.com/aLPIdNr.png)

**Comment by pejakm** [comment]
That's fantastic! Thank you!

**Comment by mcR00T** [comment]
i would love to see a real black theme for my OnePlus 3 OLED screen

**Comment by jpggithub** [comment]
+1

**Comment by MisterY** [comment]
@dan0xii, thanks, that looks fantastic for a start! What's the chance of seeing it any time soon on our devices?

**Comment by dan0xii** [comment]
There's a pull request (#304) for it that needs testing. If you build the app from that [branch](https://github.com/dan0xii/nextcloud-notes/tree/dark_theme) and provide some feedback it might speed up the process of having it incorporated into the master tree.

**Comment by timkrief** [comment]
As @mcR00T said, an oled theme (true black) would be great :smile:

**Comment by dtcg** [comment]
+1

Prototype looks great!
