### ISSUE TITLE
Notes sync failing

### ISSUE THREAD

**Issue by nagelbh** [stefan-niedermann/nextcloud-notes#257]
Android version: 
Device: LG G6
Language: English
App version: 0.11.0
App source: Play Store

Error is:
Synchronization failed: is the Notes app activated on the server?  (I created all of these notes previously using this same app, on this server.)

Then there are additional popup messages about a java doctype issue "string cannot be converted to JSONobject".

Then it gives a java doctype error.Device: LG G6

**Comment by stefan-niedermann** [comment]
Please make sure you installed "Notes" and not "NextNotes" on the server.
Did you update the server app, the server itself or the android app? it is unlikely that it just stops working if it worked before.

**Comment by nagelbh** [comment]
I am not the admin for the system hosting the nextcloud instance, what specifically do I need to request that they install on the server side?

**Comment by korelstar** [comment]
This one: https://apps.nextcloud.com/apps/notes

**Comment by stefan-niedermann** [comment]
@nagelbh did you have time to check if you have installed the correct app mentioned by @korelstar?

**Comment by stefan-niedermann** [comment]
@nagelbh please feel free to reopen this issue if the problem appears with the correct app installed or if you have any further questions :)

*just cleaning up a little bit here*

**Comment by nagelbh** [comment]
Thank you for following up, if I can get the sysadmin to install I'll let 
you know the results.

It still seems odd to me that it functioned just fine for a while at first.

Thanks,
Bruce
