### ISSUE TITLE
[Feature request] Calculate in line

### ISSUE THREAD

**Issue by wawont** [stefan-niedermann/nextcloud-notes#258]
Calculator - Allows computing the answer to equations in the note, with the answer inserted directly after the equation. Like this:
QownNotes: https://github.com/pbek/QOwnNotes/issues/152
TextCalc:
https://play.google.com/store/apps/details?id=com.technoriver.textcalc2&hl=ru

**Comment by stefan-niedermann** [comment]
To be honest, i think this feature is a bit out of scope for now. This is an edge case, but i would be happy to hear some opinions :)

**Comment by stefan-niedermann** [comment]
Sorry. Won't add this feature because it adds much complexity for too little win.
