### ISSUE TITLE
[Feature] Sort notes alphabetically

### ISSUE THREAD

**Issue by DamsFR** [stefan-niedermann/nextcloud-notes#262]
Notes are ordered by date. It would be nice if we could also sort them alphabetically

**Comment by stefan-niedermann** [comment]
#92 can you please explain what benefit you are expecting? In which way is "sorted by recent" bad for you?

**Comment by DamsFR** [comment]
_My answer is in #92, because I didn't know where I was supposed to answer._

**Comment by stefan-niedermann** [comment]
Closing in favor of enhanced Subfolders/Categories handling
