### ISSUE TITLE
Lazy UI and crashing after typing a long text

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#267]
When (fast) typing a long text into a note, the app becomes lazy, hangs and then finally crashes. Maybe there is a problem with the Timers for autosave or something. This problem wasn't there in the last release.

Is somebody able to reproduce this? Maybe, this happens only on a real device.

*(I moved this from https://github.com/stefan-niedermann/nextcloud-notes/issues/246#issue-254441077 to a new issue, since I think it's release critical.)*

**Comment by dan0xii** [comment]
I've tried this on my phone running 7.1.2 and can't reproduce it. Am I correct in thinking you're doing nothing more complex than opening a note and typing a lot of text?

**Comment by korelstar** [comment]
Yes.

Hmm. Do you have a high-end phone? Maybe it depends on CPU power (mine is Wileyfox Swift, it's rather low-end but not totally slow).

Can somebody else reproduce this?

**Comment by korelstar** [comment]
Please note: It wasn't there in the latest release (v0.11.0). I found this in current master on Git, only.

**Comment by dan0xii** [comment]
I have a oneplus2 which is fairly high-end but not much greater spec than yours by the looks of it.

I'll try and test it on an old m8 mini 2 I have at home.

**Comment by stefan-niedermann** [comment]
I have a Nexus 5x on which i can not reproduce the problem, too. I have set up a low-end VM in which i am not able to reprodice the bug either.... hmm... Let's wait for @dan0xii m8 mini test

**Comment by dan0xii** [comment]
I'm still struggling to reproduce this issue. The m8 mini decided it would go into a reboot loop shortly after I turned it on but I found OneX running 4.3.1 (CM 10.2.1) and I don't see any problems entering a lot of text quickly as you describe above. The phone is on the same LAN as the nextcloud instance so there is very little latency there--I can't test from a mobile data connection because I don't have a SIM for this phone.

**Comment by korelstar** [comment]
Thanks for your efforts. I have tried to make a video using `adb`, but when the app hangs, the video recording fails.

However, I began to rewrite the whole `Timer` thing and replaced it by a `Handler`. This seems to be a good approach and I think it fixes the problem. I will finish and commit this in the next days.

**Comment by korelstar** [comment]
I fixed this in #269.

**Comment by stefan-niedermann** [comment]
Great to hear. Do you know what the exact problem was and why we were not able to reproduce it? Or did it just disappear for you?

**Comment by korelstar** [comment]
I'm not sure what the exact cause was. I think it was that
