### ISSUE TITLE
Widget look

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#27]
Just as a comparison, here’s how our widget (bottom) looks vs the [Jot widget](https://play.google.com/store/apps/details?id=com.simplidget.jot&hl=en) (top):
![img_20151023_171450](https://cloud.githubusercontent.com/assets/925062/10684469/10b89d84-79aa-11e5-9b53-be43297e642f.jpg)
- Seems that the background for ours is a tad blue? Should probably be just black/grey and 50% (or 70%) opacity.
- Font-size could be decreased a bit to make more of the note readable. It’s quite important that the last visible line gets visually cut in half so it’s clear that the note continues.
- The font-weight should be a bit thinner too. But maybe that’s just because of the size.

**Comment by stefan-niedermann** [comment]
- Can you please provide a exact color in rgba style?
- Should we change to OpenSans?

**Comment by jancborchardt** [comment]
* Let’s go with straight up rgba(255,255,255,.5) – black with 50% opacity. We might need to increase the opacity a little if we find there are visibility problems with some backgrounds.
* Good question on the font, probably regarding the whole app. Can you change to OpenSans Light + Semibold and check how it looks like in the app?

**Comment by stefan-niedermann** [comment]
> Good question on the font, probably regarding the whole app. Can you change to OpenSans Light + Semibold and check how it looks like in the app?

Is this also the default for the ownCloud (Files) app?

**Comment by jancborchardt** [comment]
No, not yet. But might be something worth doing if our experiment with it here looks nice. Of course no priority. What do you think?

**Comment by stefan-niedermann** [comment]
well first some technical problem: i did'nt find a way to change font-family global in style yet, only programatically - which i dont't want.
second: i personally dislike the thin font because it's hard to read - there is an issue in core, too.

let me think about it. i will keep you updated.

**Comment by jancborchardt** [comment]
Already looks much more awesome! :) Just one real issue left for now:

* [ ] Currently the widget with a height of 1 shows 4 1/2 rows. That makes the text quite tiny and difficult to read. Instead it should show 3 1/2 rows of text.

**Comment by stefan-niedermann** [comment]
could you please clairify? current configuration:
Single Note Widget:
```
XX
```
All Notes Widget (does not work yet)
```
XXXX
XXXX
```

**Comment by jancborchardt** [comment]
Yup, bigger font size than now. :) So that the resulting widget of a height of 1 will display 3 1/2 rows of text.

**Comment by korelstar** [comment]
This issue was about the old widget, which was replaced by a completely new implementation. Therefore, I think this remarks are obsolete. Hence, I'm closing this one.
