### ISSUE TITLE
Unable to delete notes

### ISSUE THREAD

**Issue by exili0n** [stefan-niedermann/nextcloud-notes#271]
Hi, using nextcloud 12.0.2 with notes 2.3.1
I have 17 new notes that i can not delete. Tried to delete from app, from browser, from fileserver, from database (mariadb) but thea are still reappearing.
Any idea where can be tge problem?
Thx.

**Comment by stefan-niedermann** [comment]
is there any error message when you try to delete them via browser? appear they deleted and come again or does it even fail to delete them?

for the server side app have a look at the repo https://github.com/nextcloud/notes/issues (this repo is only about the android client.)

regards

**Comment by korelstar** [comment]
Please have also a look at the server's log file `nextcloud.log` (look for the time when you tried to delete).

**Comment by stefan-niedermann** [comment]
@exili0n did you have time to check the log files or can you provide any further error messages or hinter that enables us to solve your problem?

**Comment by korelstar** [comment]
Does the problem still exists with the latest versions of the Android app and the server app?

**Comment by exili0n** [comment]
Hi, sorry, haven't seen the last message. With the last update everything works fine, i was able to delete "undeletable" notes.
Thanks a lot!
