### ISSUE TITLE
F-Droid-Build broken

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#274]
https://f-droid.org/wiki/page/it.niedermann.owncloud.notes/lastbuild_17

**Comment by korelstar** [comment]
There was a new build today, which succeeded. Did you changed anything, @stefan-niedermann ?

**Comment by stefan-niedermann** [comment]
Nope,i'm ona conference right now. maybe some member of fdroid changed the meta data. will check in the fdroiddata repo for commits.

**Comment by stefan-niedermann** [comment]
Haven't found anything chained to the notes app... https://gitlab.com/fdroid/fdroiddata/commits/master

will wait until it is avilable in the store and close the issue ôO hmmmm....
