### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by eemantsal** [stefan-niedermann/nextcloud-notes#276]
Hi.

I have read [this issue](https://github.com/stefan-niedermann/nextcloud-notes/issues/189), but I want to insist and ask the developer to reconsider the matter, not because line breaks that make the notes look more or less pleasant, but for a very simple reason: seems that mature people have difficulties to read, but especially to edit their notes. I've verified with two persons I have "evangelized" to abandon Google and come to the "free world".
They don't have any visual defficiency beyond what's normal in the sixties and seventies: presbyopia, something that practically all of us shall suffer when we turn 40 - 45 y. o. and beyond. While their mobiles'  UI font size seems sufficient to read most of the apps, it turns out that NC Notes app's summary view uses a much smaller font. But the major problem comes when editing the notes: the font size makes difficult to handle the cursor, make selections, to copy/paste, etc, even with their glasses.
I must add thay while I have no problems to see the text clearly, I'd thank if I could set the interface font size bigger because the size of my fingers. Not that they are enormous, I think are normal for a near to 1,90 m man, but sometimes it's hard to place the cursor where I want; it hapens also when typing an email or chatting, but in those kind of applications I don't use text format nor edit what I type so often, so I don't care much. But it's different in an editor like this notes editor.

So, the fixed font size is more than an aesthetic problem, it's really an usability one. I hope you may reconsider your position. I invite you to let use the app to your aunt, or your father, and ask them about their experience, I think it might be rather similar to my two "subjects".

Regards

**Comment by korelstar** [comment]
Did you changed the device's font size? This can be done in the Android 
settings in the section "Display" -> "Font size" or in "Accessibility" 
-> "Font size". This has also effects to the Notes app's font size.

I think, it's more productive to change the font size of the whole 
device instead of changing the font size in every single app. Isn't this 
sufficient?

**Comment by eemantsal** [comment]
I know, I know text size can be changed for all the Android UI, but the bigger the size you set, the less information fits on your screen. In my personal case I have no problem in reading the text in my phone's UI nor in the notes app's one, but I can't handle editions as well as my girlfriend, for example, who has smaller and thinner fingers. I don't need bigger fonts in a system-wide manner, not even for just reading my notes in the notes app, but would benefit from an option to increase it in the edition mode.
For me this isn't a huge problem, or maybe I've just got accustomed since I have always been rather imprecise when editing or selecting text on my mobile phones, so I' haven't known anything better. But the problem for many older people does involve vision. Sure they could increase the system UI font size, but they don't really need it since usually one doesn't need to see crystally clear the menues, for instance and prefers an aquilibrium between clear legibility and screen space optimization.
Let me link a comment I saw yesterday that I think ilustrates very well what many users feel like when using apps which involve some long time reading (not certainly an user interface):
https://github.com/nextcloud/news-android/issues/467#issuecomment-161784507

I don't know if just adding a simple option to independently increase font size is too complicated; Telegram has it, Whatsapp has it, a lot of apps have it... Seems like a rather simple feature, but I know nothing about programming so maybe it involves more work that I think, I don't know. But if it doesn't, taking it into account could improve many users' experience, I believe.

**Comment by stefan-niedermann** [comment]
Well it does not make a problem programming wise, this would not take much effort. It is more about keeping the app as simple as possible. Yes, the mentioned messengers have this option, and this is wrong IMHO.
Either i can read everything then its fine or the font is too small, then i have to adjust it everywhere. "the menus have not to be crystal clear"... well. this is the case of your gf and works for well-known apps she uses everyday. but i think the majority of the userbase will adjust it globally or not at all.

**Comment by dan0xii** [comment]
I have been in a scenario similar to the one @eemantsal describes where I had a phone with a 4.5in screen and I found reading large bodies of text hard on the eyes. I particularly remember increasing the font size slightly in the twitter app. My eye sight is fine but I just felt more comfortable with larger text and I can understand not wanting to bump up the system font size as that does make parts of the interface a bit too big.

I understand the intention to keep the app as simple as possible and prefer it that way but I can't see that an option in the settings for font size wouldn't at least be worth trying.

**Comment by stefan-niedermann** [comment]
Just to make it clear. The official `android-app` does not implement a own font-size-setting nor does the `news-app` for android it, nor does the `phone-sync-app` implement one.

**It is currently no target to implement this setting here**. Though we can talk about increasing the default overall font-size.

**Comment by stefan-niedermann** [comment]
v1.0.0 has a setting for the font-size.
