### ISSUE TITLE
Very limited Markdown support

### ISSUE THREAD

**Issue by eemantsal** [stefan-niedermann/nextcloud-notes#277]
I haven't been testing seriously, but I have noticed that a basic MD feature like headers, both made with `#`, `===` or `---` , don't work in the app.
I'll try to test more MD syntax breaks and report when I have time.

**Comment by korelstar** [comment]
A heading using `# Heading` should work. Please provide a screenshot and 
more details if not. The alternative markup using `====` or `----` isn't 
implemented. Please have a look at https://github.com/yydcdut/RxMarkdown 
for the list of features.

**Comment by eemantsal** [comment]
@korelstar 

True, `#` work fine when adding a space at its right. I wasn't doing it, and just typing like `#Header`, `##Smaller header`, etc, which weren't being correctly rendered. I guess I must have a good read to that RxMarkdown implementation you have linked since I'm used to edit MD files on Linux and my desktop editor seems to follow a different implementation.

Thanks, and excuse the confusion. I think this issue can be closed. I'll open a new one in case I'd see any real inconsistence, once I've read well about the implementation that NC notes app uses, of course, heheh.

Regards.

**Comment by stefan-niedermann** [comment]
No problem :) You van also open issues at upstream (RxMarkdown) - if there will some new "standards" be implemented, we will adopt it automatically in new versions.

Regards
