### ISSUE TITLE
Save updated note failes

### ISSUE THREAD

**Issue by kpleines** [stefan-niedermann/nextcloud-notes#280]
Some times when I try to update a existing note, this note will not be saved.
I use Firefox 56 (64Bit) on a Windows 10. 

I tried somthing:
* Updated it more than once --> not saved
* Updated it in different places: header, footer --> not saved
* Give note a Star --> not saved.

What can I do to give you better errorlogs?

**Comment by korelstar** [comment]
Sounds that you are talking about the web app. This repository and issue list is about the Android app for notes.

If you are really talking about the web app, then please close this issue and create a new issue in the respective repository https://github.com/nextcloud/notes and provide log excerpts from the server (`data/nextcloud.log`) and the client (web console of your browser). Without meaningful log entries, nobody can help.

**Comment by kpleines** [comment]
Thanks for the Info.

**Comment by stefan-niedermann** [comment]
@kpleines Please open issues regarding the server here: https://github.com/nextcloud/notes/issues

And please provide detailed log files from browser console or the nextcloud-log, as @korelstar mentioned.

Regards
