### ISSUE TITLE
No connection with some android devices

### ISSUE THREAD

**Issue by hubertmeier** [stefan-niedermann/nextcloud-notes#282]
I use a nextcloud-server in a virtual machine, connected with a dyndns-Adress and a port translated by the router like this: https://xyz.dyndns.org:9443

Every connection to my nextcloud with the nextcloud-clients works fine, the notes APP worked yesterday the first time on my Galaxy Tab S, on my Note 3 there is no connection possible. I think it's a problem with the certificate, the Tab S showed a message after several tries in the status bar where i could confirm the certificate, the Galaxy Note 3 shows nothing, only the error message. The note 3 uses Android 5.0 (latest possible update). Thank you

**Comment by stefan-niedermann** [comment]
I assume you are using v0.12.0 from F-Droid, right?

**Comment by hubertmeier** [comment]
yes

**Comment by hubertmeier** [comment]
aktuell von F-Droid ist 0.11.0 , habe ich gerade noch mal überprüft

**Comment by stefan-niedermann** [comment]
Could you please recheck the F-Droid-Version? The current version is v0.12.0:

![screenshot_20171019-151634](https://user-images.githubusercontent.com/4741199/31772650-af132634-b4e0-11e7-8274-ce0f4330831e.png)

**Comment by hubertmeier** [comment]
Yes, half an hour ago F-Droid showed an update and it works ! 

Thank you very much

**Comment by stefan-niedermann** [comment]
You're welcome :)
