### ISSUE TITLE
Open in read-mode by default

### ISSUE THREAD

**Issue by armaccloud** [stefan-niedermann/nextcloud-notes#283]
When a new entry is opened, the keyboard is shown and the cursor blinks at the first line; all is fine.

When an existing entry is opened it shows the same behaviour, which doesn't seem logical from a users perspective. The notes have just as much purpose for being read as they have for being edited. Also, the chance that one has to start typing at the beginning of the first line within an existing note  is very small.

It might be more efficient to hide the keyboard by default for existing entries and open the text in read-mode, until the cursor is placed in between the text somewhere by hand.

Consider the following scenario's

**I want to read an existing entry**
_Current behaviour_
I open the entry I want to read from the overview and it opens with the keyboard in sight, blocking half the screen. I have to tick the android back-button to get rid of the keyboard so I can start reading.

_Proposed behaviour (read-only)_
I open the entry I want to read from the overview and it opens the full text. I can immediately start reading and scroll through the text where needed.

**I want to edit an existing entry**
_Current behaviour_
I open the entry I want to edit from the overview and it opens with the keyboard in sight and I want to start editing where I stopped last time.

I have to either scroll through the text with the keyboard in sight (less overview) of I first hide the keyboard so I have more overview of my text (more actions).

_Proposed behaviour (read-only)_
I open the entry I want to edit from the overview, it opens in read-only mode. I want to edit where I stopped last time.
I scroll down to the place where I want to start typing and tap the screen in order to point the cursor there and open the keyboard (edit-mode)

Hopefully this description is clear enough, let me know if you have any questions.
Kind regards

**Comment by korelstar** [comment]
I'm fine with to not open the keyboard for existing notes. But I wouldn't introduce a read-only mode, because it makes editing more complicated, I don't see the advantage beyond not opening the keyboard, and you can use the settings to start always in preview mode (from v0.12.0).

**Comment by armaccloud** [comment]
Ah, I wasn't aware about the view mode in the settings.

I agree with you the benefit of hiding the keyboard by default.

Tapping somewhere within the text in view mode that would open edit mode with the cursor blinking on the tapped location. That would also be a user friendly addition. I don't know about the complexity of that change though.

Cheers

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by stefan-niedermann** [comment]
Well. my personal opinion is "keyboard extended, cursor on last position, ready to write". the only reason it is like it is: @jancborchardt thought it was a good idea.

And i definitely aggree, that it is good that the keyboard is extended, because in writemode that's what i want: write.

If there should be any change, than the cursor should be at the end of the note.

**Comment by jancborchardt** [comment]
> I'm fine with to not open the keyboard for existing notes. But I wouldn't introduce a read-only mode, because it makes editing more complicated

Absolutely agree @korelstar. The keyboard should not show immediately for existing notes.

@stefan-niedermann sorry, might have been a misunderstanding?

**Comment by stefan-niedermann** [comment]
i clearly remember an old issue here at github, your statement was, the keyboard should be open and the cursor at the first position :D

So here are three peole who think that the keyboard should be hidden in edit mode and the cursor should not be placed at all, am i right? the user should every time manually set the cursor (which causes the keyboard to appear)?

**Comment by korelstar** [comment]
I would simply set android:windowSoftInputMode="stateHidden" - that's all. Displaying the cursor can be nevertheless helpful to indicate that we are in edit mode. Furthermore, on devices with a hardware keyboard, you can start typing directly.

But of course, we should test how this feels in practice before integrating in a release.

Here is an old discussion on this topic: https://github.com/stefan-niedermann/nextcloud-notes/issues/3#issuecomment-150464144

**Comment by jancborchardt** [comment]
@stefan-niedermann we could set the cursor and scroll to the point where one last edited the note, if possible?

(@stefan-niedermann I kind of also remember that now … sorry, there's always lots of different stuff going on in the Nextcloud universe so sometimes I make mistakes, or design decisions simply change. Hence I'm glad when the devs are design-minded in the first place like you folks also. :)

**Comment by korelstar** [comment]
Please test my PullRequest #286. The edit-note activity is just started with a closed keyboard. I like it, and I think it is sufficient.

Of course, it would be nice to remember the last position of editing, but I think that is much more complex to realize (if it is even possible?).

**Comment by stefan-niedermann** [comment]
technically it is possible but adds much complexity. maybe in the future. otherwise okay, lets go for hidden keyboard :+1:

**Comment by armaccloud** [comment]
Hi @korelstar,

I would like to test the pullrequest, but how can I do that? Is there an APK I can download?
I've checked the contributor guidelines but can't find anything about that.
Thanks for the quick implementation,
Arno

**Comment by korelstar** [comment]
You would have to install AndroidStudio in order to build this. But due to the feedback on the pull request, we've merged it an this will be part of the next release.

**Comment by dtcg** [comment]
How about: 

1) Always open in view mode (no keyboard)
2) Long-press to select text (useful to copy/paste content without accidentally editing/deleting it)
3) Double-tap to switch to edit mode, in the same spot we've just taped (my notes are long, scrolling is a pain) and reveal keyboard

**Comment by korelstar** [comment]
My above mentioned PR is merged and part of the current release (v0.13.1). Hence, I think this issue can be closed. A further enhancement would be to synchronize the scrolling position when changing between view mode and edit mode. But that should be discussed in a new issue.
