### ISSUE TITLE
checkboxes can't be (un)checked in view mode

### ISSUE THREAD

**Issue by jpggithub** [stefan-niedermann/nextcloud-notes#287]
With the syntax 
'- [ ] item 1'
'- [x] item 2'
I have two checkboxes in view mode but I can't check or uncheck them.
Is the normal behavior?

**Comment by stefan-niedermann** [comment]
Unfortunately yes.

You can open an issue at the upstream project for the Markdown-Library we are using: https://github.com/yydcdut/RxMarkdown/issues

See also #157

**Comment by jpggithub** [comment]
Ok, I submitted a request on https://github.com/yydcdut/RxMarkdown/issues/40

**Comment by stefan-niedermann** [comment]
Closing this issue until there is an upstream solution.
