### ISSUE TITLE
Request: promote app as shared shopping list

### ISSUE THREAD

**Issue by beatstick** [stefan-niedermann/nextcloud-notes#291]
I use this app as shared shopping list with my wife.  I installed the app on both our phones and we use the same nextcloud account to login. I think it's a great feature, that does not seem to be documented anywhere. It should be listed as a feature on the f-droid store in my opinion. I have been looking for a shared shopping list (with my own server as backend) for some time since the app I have been using so far (shoppinglist from frdroid) is no longer maintained and does not support multiple lists. I just happened to stumble upon this app by accident on f-droid and thought it might work as a shared list because of the nextcloud back-end. And it works! 
If it is not an intended feature, my question would be if the use by multiple users could lead to corrupt files or errors if the list is edited and maybe saved at the same time?

**Comment by spaetz** [comment]
beatstick, yes, the notes app does not protect or handle simultanous changes at all. There are issues filed against the upstream app to improve that.
Actually, I want to use this as a shared shopping list as well, but between different users of the same server and the upstream app and the android app cannot deal with this at the moment....

**Comment by korelstar** [comment]
@beatstick Yes, you can share notes if you use the same account or the share functionality of Nextcloud. But currently, this is not suitable for notes that are changed often by multiple users. Please see nextcloud/notes#56 for a detailed discussion of this.

@spaetz Sharing is also possible between different users of the same server. In general, this works (except for the concurrency problem)! Why this doesn't work for you have to be investigated in the respective issue (#290) and not here.

**Comment by beatstick** [comment]
I see. I will stick with a shared user account for now, as it does work for me and I don't want to introduce another possibility for error (cmp. #290). (By the way: What's the proper term for introducing new variables into a system that might cause the system to not work any more?) The same goes for #56. It would definitely be nice to have but I see a lot of potential to break things. A big plus of the notes app is that it's fast and lean. Introducing several algorithms might bloat the app and slow things down to much, but the idea is intriguing.

**Comment by spaetz** [comment]
Can we then close this issue, please?
