### ISSUE TITLE
Crash when the note used in SingleNoteWidget is deleted

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#293]
Steps to reproduce:

1. Create a note
2. Add a SingleNoteWidget to the launcher and chose the above created note
3. Start the app
4. Delete the above created note
5. Synchronize with the server

Result:
The app crashes with a `NullPointerException`, Android starts the app again, the app crashes again, ...

Solution:
The widget should check if the note is still there, and then
a) Show a hint instead of the content, or
b) Remove the widget (if this is possible)

/cc @dan0xii

**Comment by dan0xii** [comment]
Hmm, that's a bit of an obvious one. I'm away currently but will try and patch it this weekend.
