### ISSUE TITLE
Check-Boxes in every line-start of paragraph

### ISSUE THREAD

**Issue by treborxy** [stefan-niedermann/nextcloud-notes#294]
Android version:** 7.1.2 LineageOs

**Device**: Sony Xperia Z

**System language**: German

**App version:** 0.1.21

**App source:** F-Droid

**Steps to reproduce:**
  1. open the app
  2. click on a note
  3. use the edit button
  4. insert long text with checkbox, e.g.

- snip start
# Test ToDo
- [ ] lore ipsum infernalis lore ipsum infernalis lore ipsum infernalis
- snip end

5. in view-mode you get a checkbox at every line's start within the paragraph when viewing on small devices with force line-breaks

**Comment by stefan-niedermann** [comment]
I can reproduce this issue. Please open an issue in the upstream markdown library: https://github.com/yydcdut/RxMarkdown/issues

**Comment by stefan-niedermann** [comment]
https://github.com/yydcdut/RxMarkdown/issues/42
