### ISSUE TITLE
Seperate file name and first line

### ISSUE THREAD

**Issue by Luensche** [stefan-niedermann/nextcloud-notes#300]
I actually don't like to have an encrypted file name, so I often rename the notes. If I change the notes afterwords online, all is fine. But if I change the notes within the app, the file name is overwritten by the text of the first line.

It would be nice, if both will be separated (maybe an opt-out within the settings), so that I can rename the files and they will keep their name after editing with the app.

**Comment by SeWieland** [comment]
My URLs for [Pico CMS](https://github.com/nextcloud/cms_pico) content get modified as well when editing notes. My notes are all named 
- `---.txt`
- `--- (2).txt`
- `--- (3).txt`
(#306)

**Comment by stefan-niedermann** [comment]
I see, but this is also an issue that has to be discussed at the server-side app.
I suggested this myself some time ago here: https://github.com/owncloud/notes/issues/198

Please continue discussion there, if the server-side app decides to change the behavior, the android app will follow :)

regards
