### ISSUE TITLE
Add search string to a header for a new created note

### ISSUE THREAD

**Issue by sprnza** [stefan-niedermann/nextcloud-notes#302]
Hi there!
My feature request is pretty simple. When a user type a string into search field and finds nothing, it would be great to get the string added to a header of the new note if the add button being tapped with the search field filled.

**Comment by stefan-niedermann** [comment]
Current implementation hides the floating action button when something is typed into the search.

@mario suggested to hide the fab when the user is search, personally i think it's a quite nice feature, but i do not know how often it would be used.

@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
I think @sprnza means something more like what we discussed for categories: When you search **recipes** and there's no results, show an entry in the list saying "New note **recipes**". (which on tap would create the note and switch to it)

I agree that would be nice, and the FAB would not be needed.

**Comment by mario** [comment]
@stefan-niedermann this was what I was about to suggest you tomorrow :P  It's nice.

**Comment by clairevelicaria** [comment]
Hi can I know are you talking with who pls .....all the conversation issue now only instead to my phone I out to google I enter to emuei now I see the 54 conversation in my account about isue us that me pls help me bcoz I'm not expert in touch screen phone this is my first time to use it and to enter the trading industry

**Comment by stefan-niedermann** [comment]
Dear @clairevelicaria ,

i am sorry but i have no idea what you are talking about. Please let your question translate from someone who know english, so we can understand your problem and help you :)

If you have a question about Nextcloud Notes, please open a new issue and do not write it to this issue if it is not related to it.

Regards

**Comment by stefan-niedermann** [comment]
Closed in bb2110ac3b7aeff517b73efb31dbe0793ccc7cde
