### ISSUE TITLE
Notes app doesn't work with TLS 1.2

### ISSUE THREAD

**Issue by davidchisnall** [stefan-niedermann/nextcloud-notes#305]
This was previously reported on the Notes NextCloud app bug  nextcloud/notes/issues/131

This appears to still be an issue (notes app 0.12.1 installed via F-Droud, LineageOS 14.1 [Android 7.1]).  Enabling the http2 option in nginx implicitly disables pre-1.2 TLS (which is a good idea anyway, as these versions have known vulnerabilities) and prevents the notes app from synchronising.  Disabling http2 allows the notes app to work again.  

The NextCloud app, all web browsers that I've tried, DAVDroid, and iOS and macOS calendar and contact sync all all work correctly with http2 enabled (and several of them work noticeably faster), so it's a shame that I have to disable it for the notes app to work.

**Comment by treuss** [comment]
Hi @davidchisnall,

I'm succefully using the Notes app on pretty much the same setup as you do: nginx and http2 - thus TLS1.2 enabled, although I have to point out that I'm running OwnCloud. 
However I'm sure that if Notes is able to communicate using http2 and TLS1.2 with OwnCloud, it should also be able to do this with another application.

Did you check the logs? Did you wipe the app settings?

Best regards

**Comment by rodrigoesborges** [comment]
I have exactly the same issue on an older device of mine (wingray, with Android 4.4.4) . Going to ssllabs.com and testing my browser, it shows TLS 1.2 as enabled for the device.

All other apps (Nextcloud/DAVDroid/ Web Browsers) work but Notes refuses to connect to the server when http2 is enabled.

My others devices with Android  (v 5.1 / v. 8.0) correctly connect to the server, though.

I couldn't see anything wrong on the server logs. Tried wiping settings and installing other versions (0.13 , 0.12 , 0.12.1)

**Comment by schaarsc** [comment]
I think we should revisit this after #418

**Comment by stefan-niedermann** [comment]
See #570

Please wait until #418 has been resolved.
