### ISSUE TITLE
Choose between .txt and .md file extension

### ISSUE THREAD

**Issue by SeWieland** [stefan-niedermann/nextcloud-notes#306]
I'd really like to be able to choose the file extension `.md` for my notes.
I use the app to quickly add or modify content serverd with [Pico CMS](https://github.com/nextcloud/cms_pico).
When adding notes, I always have to manually rename the files. Furthermore, the automatic naming is inconvenient (#300).

**Comment by stefan-niedermann** [comment]
Dear @SeWieland,
thanks for the feature request, but this has to be solved in the server side app.
Please have a look and continue discussion at https://github.com/nextcloud/notes/issues/24
Regards

**Comment by mimmiepower** [comment]
> 
> 
> Dear @SeWieland,
> thanks for the feature request, but this has to be solved in the server side app.
> Please have a look and continue discussion at [nextcloud/notes#24](https://github.com/nextcloud/notes/issues/24)
> Regards

This was implemented on the server app on July 24, 2018 but Nextcloud Notes still does not support md files.

**Comment by stefan-niedermann** [comment]
I have no idea what you are talking about. The question was where one can change the **extension** of the **files** from `.txt` to `.md`. The answer is, that changing the file extension is only possible in the Web UI:

![grafik](https://user-images.githubusercontent.com/4741199/87356675-c02f1780-c562-11ea-8b9c-34c99780d581.png)

This settings will usually be used exactly **one** time, so it does not make sense to implement this setting in the Android app.
Please specify your issue more.
