### ISSUE TITLE
adding date.

### ISSUE THREAD

**Issue by frederiiiic** [stefan-niedermann/nextcloud-notes#308]
Hi there all,

I really like this application, particularly for simplicity compare to other notes app, but right now i'm writing date on every notes at the begining, i like them ordering by name with the date at the beginning.

I'd like to known if it's interresting for someone else than me, to get something like one more bouton on the top right that add a date on the text field, or even better an option on parameters to auto-add date at the new notes names.

I've never try to do any android app for now, so i'm not sure to be able to pull an even simple requests like this for now. Maybe sometimes.

Thanks.

**Comment by abmurksi** [comment]
Would be great to have creation date & last edit date visible somewhere

**Comment by stefan-niedermann** [comment]
I can not get the use case for it, to be honest. Why is it interessting, **when** a note has been created?

Isn't the content much more relevant (which one can search)?

**Comment by stefan-niedermann** [comment]
@frederiiiic @abmurksi can you please explain the use-case futher?

**Comment by abmurksi** [comment]
After using the app for some time now, I do not really need the info. I agree, it does not make the content more relevant. It would be interesting to know sometimes when the Note has been created, but that would be it for me. Thanks for following up.

**Comment by stefan-niedermann** [comment]
Thank you for your statement :) I will close this issue for now. If more people are interested in this and have valid arguments, i am happy to reopen and discuss this issue.

Regards

**Comment by frederiiiic** [comment]
Hi there,

I'm still interested by this feature.

I'm using the app on the phone and on the computer, and for some folders, i'm review a regular contents, so i'm dating every notes in there. This way my notes on the computer are sorted by name so time related, and i can easily go back to where i want. That's a part of my using.

Anyway for the other Notes i made, recent sorting and research are the best tools.

**Comment by webracer999** [comment]
I would also be happy, if there's a button to insert the current date, time or both.

I often make notes, where the date or time is relevant.
E. g. I make a note, when I clock in or clock out from work; or when I use the ATM, to note down when and which sum of money I pulled.

**Comment by dgleba** [comment]
I am keenly interested in have access to the created and updated timestamps. 

Created_at is an audit trail item. I use it to trace when something was initiated. Then I can look for other relevant documents using the date range. For example if I create a note when the power fails at our company, I can use that info in later weeks in my work as a facilities engineer. Knowing the time to the second when I created the note is useful and immutable. The range from created to updated can also narrow down the time frame when searching for some info.
