### ISSUE TITLE
Please allow chosing the file name extension

### ISSUE THREAD

**Issue by treuss** [stefan-niedermann/nextcloud-notes#311]
Hi,

it would be amazing if you gave the opportunity to chose an own default file name extension (like .md for Markdown) in the settings. 
That way I wouldn't need to rename my notes for editors like QOwnNotes or vim to work properly. 

Best regards and thanks for the great app!

**Comment by stefan-niedermann** [comment]
Dear @SeWieland,
thanks for the feature request, but this has to be solved in the server side app.
Please have a look and continue discussion at nextcloud/notes#24
Regards

(dup of #306)

**Comment by pbek** [comment]
> That way I wouldn't need to rename my notes for editors like QOwnNotes or vim to work properly.

you can also tell QOwnNotes which file extension to use ;)
