### ISSUE TITLE
Markdown numbering difference in view and edit mode

### ISSUE THREAD

**Issue by hubertkn** [stefan-niedermann/nextcloud-notes#312]
Hi,
the images below show the difference in appearance of numbering in edit/view mode written with markdown.
Of course the the right way is shown in edit mode, hence the view mode unproperly show the numbering.

Notes version v0.12.1

![edit mode](https://user-images.githubusercontent.com/28611780/34421480-d0b5d974-ec0f-11e7-9a46-a1abdd6a38cb.jpg)
![view mode](https://user-images.githubusercontent.com/28611780/34421482-d0e7559e-ec0f-11e7-8d8c-2390699bfdd5.jpg)

best regards,
Hubert

**Comment by korelstar** [comment]
As far as I know, markdown ignores the actual number in an ordered list, see https://daringfireball.net/projects/markdown/syntax : 
> "It’s important to note that the actual numbers you use to mark the list have no effect on the HTML output Markdown produces."

However, on GitHub, the number is used for the list.

I think this topic should be discussed in the [RxMarkdown](https://github.com/yydcdut/RxMarkdown) repository.

**Comment by stefan-niedermann** [comment]
Dear @ hubertkn,

i also think, this is a topic of the markdown library. Unfortunately we are not capable of tracking issues caused by upstream apps, sorry.

Please report upstream, as @korelstar mentioned.

Regards
