### ISSUE TITLE
Markdown doesn't work in widget mode ...

### ISSUE THREAD

**Issue by hubertmeier** [stefan-niedermann/nextcloud-notes#313]
the widgets don't show the correct formatting, they show the markdown tags. Is this feature planned ?

Thank you

**Comment by dan0xii** [comment]
As far as I can see this is a limitation of the type of widget that Android will allow you to place on the home screen and so not a feature that can be implemented.

**Comment by stefan-niedermann** [comment]
@dan0xii Would it be possible to convert a TextView (in this case the subclass from RxMarkdown) to a bitmap and from bitmap to an ImageView?

**Comment by dan0xii** [comment]
Seems reasonable. I'll take a look.
