### ISSUE TITLE
Apostrophes in links don't get parsed correctly

### ISSUE THREAD

**Issue by repsorp** [stefan-niedermann/nextcloud-notes#314]
URL's with apostrophe character (') are broken in preview mode.

For example:
http://en.wikipedia.org/wiki/Conway's_Game_of_Life

Enclosing URLs in angle brackets (RFC 2396) doesn't work here

Android 7.1.2
nextcloud-notes v0.12.1

**Comment by stefan-niedermann** [comment]
https://github.com/stefan-niedermann/nextcloud-notes/blob/7ecfac6cdad64d63f0d548c8fb3cfd6435b8595b/app/src/main/java/it/niedermann/owncloud/notes/android/fragment/NotePreviewFragment.java#L65

@korelstar i think we can fix it by adding the `'` character to the list here, but there might be more characters which are allowed in URL....

**Comment by korelstar** [comment]
Yes, sound reasonable. In general, it's not easy to create a regular expression for detecting URLs without any side-effects. Hence, there will always be a better one, but most cases should be caught with the current one (respectively the new one with the apostroph) ;-)

**Comment by korelstar** [comment]
However, it would be advantageous to move that regular expression into a Util class and write a test case for it.

**Comment by stefan-niedermann** [comment]
What do you think about this expression: `^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\(\)\*\+,;=.]+$`

It is for Javascript, but we could easily translate it. It also contains 
Source: https://www.regextester.com/94502

The specifically mentioned URL will be detected.

**Comment by stefan-niedermann** [comment]
We are not doing the linking-part in the Notes app anymore, it happens in the Markdown-rendering lib: https://github.com/yydcdut/RxMarkdown/commit/c30609a68e60aec8ced28618f646e309a8cb5212#diff-62b97722e3e68b869ca54e67daad437eR45

Therefore i opened a new issue upstream: https://github.com/yydcdut/RxMarkdown/issues/62
