### ISSUE TITLE
Can't log in with Nextcloud-Account

### ISSUE THREAD

**Issue by ChESch** [stefan-niedermann/nextcloud-notes#315]
Hello there!
When i try to log in, i get a message which says "Invalid login: server connection is broken".
I don't know why, i use a BQ Aquaris X Pro Smartphone with Android 7.1.1 and Nextcloud 12.0.3.

Hope you can help me!

**Comment by dan0xii** [comment]
Hello @ChESch,

What happens when you login to your nextcloud instance via your phone's browser?

**Comment by ChESch** [comment]
Hello @dan0xii,
everything works like expected, I even use CalDAV and CardDAV with DavDroid for syncing my Calendar and Contacts, and I have installed the official nextcloud app, which also works fine!

**Comment by stefan-niedermann** [comment]
which version of the android app and the server-side notes app are you using exactly?

**Comment by ChESch** [comment]
App Version: 0.12.1
Nextcloud Notes Version: 2.3.2

**Comment by SavageCore** [comment]
Same issue I think, cannot do any syncing at all. DAV and offical app work no problem.

App: **0.12.1**
Server: **2.3.2**

Addtionally I get javaFileNotFound on `https://example.com/apps/notes/api/v0.2/notes` and `https://example.com/apps/notes/api/v0.2/notes?pruneBefore=1517822885` 

Visiting /notes I get `{"message":"CORS requires basic auth"}` in the browser.

**Comment by lovenemesis** [comment]
I met the similar issue, but only on one Sony Xperia device with official Android 8.0.

App: 0.13.1
Server: 2.3.2

The NextCloud instance is running on a non-standard port with self-signed certificate. Unlike the NextCloud client and DavDroid on the same Android 8.0 device, Notes App doesn't prompt a certificate confirmation pop-up for me to acknowledge the certificate.

Strangely, on other Sony Xperia devices with Android 7.0 devices, the Notes App works the way like other NextCloud clients, giving a prompt for self-signed ceritificate and asking for acknowledge. And syncing well with the same NextCloud instance.

My wild guess is that Google might change how self-signed ceritificate is recognized in system and Notes App has yet to adjust for it.

**Comment by cliffordsnow** [comment]
I just installed the app today. I'm getting the same problem signing in to my ownCloud notes. I do use LetsEncrypt certificates. The ownCloud storage works as expected. I've had it running for sometime. 

Is there a port that needs to be open beside 80 and 443?

**Comment by stefan-niedermann** [comment]
No, no special port is needed. Have you enabled the serverside "ownCloud Notes"-App? (not maintained currently!)

**Comment by cliffordsnow** [comment]
@stefan-niedermann ownCloud Notes app was the problem. I confused with with the QownNotesAPI which was enabled.

**Comment by stefan-niedermann** [comment]
Could everyone who still has issues please do a retest with the latest version? We have improvde the support for self signed certs greatly in the meantime and i am curious if those issues still persist.

**Comment by ChESch** [comment]
I just tested with android 8.1.0 and nextcloud 13 (latest version to date) and it worked flawlessly!
Thank you very much!

**Comment by stefan-niedermann** [comment]
Okay, then i will close this issue for now. If someone is still experiencing issues, just leave a message to reopen it / create a new issue.
