### ISSUE TITLE
Numered lists do not continue

### ISSUE THREAD

**Issue by avalx** [stefan-niedermann/nextcloud-notes#316]
Hi!

I'm using numbered lists in QOwnNotes application but on my phone the lists are not displayed correctly -  continuously.
Here is an example how it looks on Windows and on the phone. Also included is the note itself.

Do I need to format such notes in some specific way to display them correctly?

[Note 2018-01-11T11.11.27.txt](https://github.com/stefan-niedermann/nextcloud-notes/files/1622150/Note.2018-01-11T11.11.27.txt)

![qownnotes](https://user-images.githubusercontent.com/22810741/34821083-d1767338-f6c2-11e7-82e0-ef880dec8ed0.jpg)

![screenshot_20180111-112208](https://user-images.githubusercontent.com/22810741/34821089-d7750272-f6c2-11e7-99f0-2acc310926b4.jpg)

**Comment by stefan-niedermann** [comment]
Hi, i can confirm this issue, though it has to be solved upstream in the `RxMarkdown`-lib by @yydcdut - Please reopen an issue here: https://github.com/yydcdut/RxMarkdown/issues

**Comment by avalx** [comment]
OK, I did post in the mentioned section.
Thanks
