### ISSUE TITLE
remove annoying toasts who says that server connection fails

### ISSUE THREAD

**Issue by naplaya** [stefan-niedermann/nextcloud-notes#318]
these toasts should be removed because there are annoying and a normal user (not I am) don't understand the showing stack trace

**Comment by stefan-niedermann** [comment]
It is a help to debug. When users report a problem it is more helpful request the shown error message than "sorry that it does not work, but i have no idea what possibly might wrong".

**Comment by naplaya** [comment]
ok, the an Option in setting might be helpful, because my server is in my hause and I only connect from out side my network. within my wifi I don't have connect caused by an other address/ip with wifi

**Comment by stefan-niedermann** [comment]
We should IMHO definitely keep the toast.

Maybe we can use more high-level text like "Network not available" and rework the way to get to a stack trace (like a details-button on the toast which leads to a fragment / dialog that shows the stacktrace and allows creating directly an issue in github or copying the stacktrace).

What do you think?

**Comment by naplaya** [comment]
Yes this sound great. I thought also about a setting to disable. An other thing is if some one use next cloud at home network and on public network. You can’t set an alternativ ip/domain if the first one fails. If you can, it would be a good solution too. Because the most times an error occurs is I guess when I am at home and the app tries to reach public domain. Because at home I can’t resolve same domains to an other ip.

**Comment by stefan-niedermann** [comment]
> You can’t set an alternativ ip/domain if the first one fails. If you can, it would be a good solution too. Because the most times an error occurs is I guess when I am at home and the app tries to reach public domain. Because at home I can’t resolve same domains to an other ip.

To be honest, this seems to be a edge case. I do not think that many people are experiencing this kind of problems. Does the file app or the desktop clients have the capability to set different IP addresses?

**Comment by naplaya** [comment]
I guess they can’t.  But The mobile App can handle multiple accounts, so I have an account to each domain/ip in this case one for home and one for outside. On a Desktop computer I use web app only and I resolve ip over linux host file.

**Comment by stefan-niedermann** [comment]
So i think handling this correctly would be to resolve https://github.com/stefan-niedermann/nextcloud-notes/issues/171 (Multiple NC Servers) :-) ?

**Comment by korelstar** [comment]
I think it's a good thing to move from Toast to Snackbar with a "details" button. But we should not do a special handling (e.g. setting) for the special situation of @naplaya.

@naplaya You should fix your network, i.e. install a local DNS server which serves the correct IP address.

**Comment by stefan-niedermann** [comment]
Multiple accounts are available starting with v2.0.0 (available on F-Droid and Play Store beta track).

Displaying a message when a network is not available seems still to be correct for me.

Everything else is indeed something that should be setup correctly / fixed on the clients networks like korelstar said (e.g. by a local dns server)
