### ISSUE TITLE
Note list widget not loading

### ISSUE THREAD

**Issue by kukukk** [stefan-niedermann/nextcloud-notes#321]
Hi,

On Sony Xperia XZ1 Compact running Android 8.0.0 I can't put on the screen the Note list widget. The strange thing is that it works on Nexus 6P running Android 8.1.0.

I think the problem is in NoteListWidgetConfiguration.java: You initialise retIntent, use putExtra and setAction then you re-initialise retIntent. Here is the diff to fix it:
` -            Intent retIntent = new Intent();`
`+            Intent retIntent = new Intent(this, NoteListWidget.class);`
`             retIntent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID, mAppWidgetId);`
`             retIntent.setAction(AppWidgetManager.ACTION_APPWIDGET_UPDATE);`
`-            retIntent = new Intent(this, NoteListWidget.class);`

**Comment by korelstar** [comment]
Oh, yes, that's weird. I'll make a PR to fix that.

**Comment by korelstar** [comment]
Can't reproduce the bug (emulator with Android 8.0 and device with Android 6.0.1). However, since the code is definitely errornous, #322 should fix this.
