### ISSUE TITLE
Opening multiple notes from the note list widget

### ISSUE THREAD

**Issue by dan0xii** [stefan-niedermann/nextcloud-notes#328]
The note list widget confuses EditNoteActivity when the user attempts to open multiple notes without closing them first. For example, open a note via the note list widget and then press home. Open another note and the original note will be displayed -- I've tried to get around this by "notifying" createFragment() in EditNoteActivity that a different note is being requested. Is the call to fragment.onPrepareClose() the cleanest way of saving the existing data? 

The code is [here](https://github.com/dan0xii/nextcloud-notes/commit/ef4bae31f0133718988ec51b722281b4613aeb1b). Will someone take a look before I make a PR.

**Comment by korelstar** [comment]
Ouh, that's not good. I thought, I tested this, but I can reproduce this bug.

I will have a look on this.

**Comment by korelstar** [comment]
Your bug fix wasn't sufficient for me: when the second note is chosen, the EditNoteActivity opens with an empty text field. However, the trick was to move the code from `NoteEditFragment.onActivityCreated()` to `NoteEditFragment.onStart()` (and detach the old fragment in `onNewIntent`). See #338 for my fix.
