### ISSUE TITLE
Blue bar below textarea looks strange

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#331]
The blue bar below the textarea just makes it look like a giant input field. And to normal people not familiar with Material Design, it just looks off.

Since for new notes the cursor and keyboard shows automatically could we remove that blue bar below?

**Comment by fazlerabbi37** [comment]
I have been facing the issue for sometime and I think I would great if we could use the full screen (except for the keyboard's place off coures) to write while we are in editing mood.

**Comment by stefan-niedermann** [comment]
Technically i think we need some kind of clicklistener at the scrollview. imagine taking a new note, you only have a single line and the edittext is not filling the whole screen. one clicks anywhere in the "white area" and wonders why the cursor gets not positioned.

onClick on the scrollview we would place the cursor at the latest position of the edittext. onClick on the edittext should have the same behaviour like now.

**Comment by stefan-niedermann** [comment]
Closing in favor of #538
