### ISSUE TITLE
Position of favorite star

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#333]
It would look much better if the favorite star is the "icon" of the note on the left. Then the note text would also left-align with the title in the header.

Additionally, then the swipe action could expose the star on the left instead of a second delete action.

**Comment by jancborchardt** [comment]
Same for the widget @dan0xii :)

**Comment by korelstar** [comment]
No, we had a discussion on this: putting the star on the left side of the widget has disadvantages.

And also in the app's list of notes, I wouldn't put the star to the left. That's not a usual position of the star on Android and the favorite functionality is not that important (not a first-level action)!

**Comment by dan0xii** [comment]
https://github.com/stefan-niedermann/nextcloud-notes/pull/273

That's the discussion that we had regarding the widget. This is what it looked like on the left:
![widget](https://imgur.com/FYpmJMJ)

**Comment by jancborchardt** [comment]
@korelstar ok. What do you think about the swipe action exposing the star on the left instead of a second delete action?

**Comment by korelstar** [comment]
In general, I would be fine with that. But I think, that the current favorite action (clicking on the star) is more intuitive. And do we need a second favorite action?

**Comment by jancborchardt** [comment]
Sure, clicking on the star would stay. It's more that a swipe to one direction for delete is enough for a destructive action like that.

And for people who use gestures, swipe to right for favorite (action appearing on left) is convenient instead of it doing nothing. :)

**Comment by dan0xii** [comment]
I would prefer the swipe gesture would "archive" the note if that feature was available.

**Comment by korelstar** [comment]
Swipe to delete is @stefan-niedermann 's baby. He should decide. I'm fine with reducing the risk to delete.

**Comment by stefan-niedermann** [comment]
Well, as i stated in #310 i think it's okay, if swipe from left to right marks a note as favorite (in this case the star should indeed be placed on the left side).

swipe from right to left should still delete the note. If archiving will be implemented on some point, the swipe right-to-left should archive the note and a "hard" deletion should only be available at the three-dots-menu because it is very destructive. - but that's something for the future.

**Comment by stefan-niedermann** [comment]
Put the favorite star on the left side to get conform with the web interface. Swipe actions will be handled in separate issues.
