### ISSUE TITLE
slash don't appear in link in presentation view

### ISSUE THREAD

**Issue by voxdemonix** [stefan-niedermann/nextcloud-notes#336]
The [slash (/)](https://en.wikipedia.org/wiki/Slash_(punctuation)) of link don't appear in the view with the presentation of all notes.
In the edition view the slash are correctly displayed.

**Comment by korelstar** [comment]
What exactly do you mean? Can you please provide an example and/or screenshot?

**Comment by voxdemonix** [comment]
![screenshot_20180326-131916](https://user-images.githubusercontent.com/8572474/37904067-b6f60d58-30fa-11e8-907c-5e4574a9c9dd.png)

**Comment by voxdemonix** [comment]
![screenshot_20180326-131916](https://user-images.githubusercontent.com/8572474/37904098-de0bc414-30fa-11e8-8aba-7d48cd3494a5.png)

**Comment by stefan-niedermann** [comment]
This can not be resolved on the client.

When the client sends a new note to the server, the server parses a title from the content to reuse it as filename. To avoid attacks, the title / filename gets sanitised:

https://github.com/nextcloud/notes/blob/8018c30b976dbc0faa6493dda16e062d01a11bcf/service/notesservice.php#L220

Please open an issue in the server repo: https://github.com/nextcloud/notes/issues
