### ISSUE TITLE
Bootloop after installing version 0.13.1 on CyanogenMod 11

### ISSUE THREAD

**Issue by ariacorrente** [stefan-niedermann/nextcloud-notes#337]
**Android version:** CyanogenMod 11.0.0M8 from 2014/08/04 (but I'm not sure, it' an unofficial build)

**Device**: Sony Xperia P

**System language**: English (US)

**App version:** 0.13.1

**App source:** F-Droid

**Steps to reproduce:**
  1. install app
  2. the phone will reboot immediately after completing the installation
  3. when the boot is complete the phone works fine for some seconds
  4. the phone reboots
  5. go back to point 3

**Logcat:** [error on first reboot](https://gist.github.com/ariacorrente/636493f15de3daa7bd73bc3ab142d387)

The only solution I found to stop the bootloop is to uninstall the application with adb.

I think this may be related to [Several apps causes a phone reboot or boot loop
](https://gitlab.com/fdroid/fdroiddata/issues/979) because I had the same problem with other apps. I don't understand the problem but it may be caused by the update to Gradle v3 in  [this commit](https://github.com/stefan-niedermann/nextcloud-notes/commit/009ca40cd081d9e89a82a41dd7c1f1c4b46f7b22#diff-c197962302397baf3a4cc36463dce5ea) . The previous version 0.12.1 available on f-droid is fine.

**Comment by korelstar** [comment]
It looks that this bug can be fixed by using the build tools for Android 27. I'm using CyanogenMod, too, but the bug doesn't happen to me.

However, #326 updates the build-tools and therefore it should fix the bug. Could you test this, please? (you need to compile the app by your own).

**Comment by stefan-niedermann** [comment]
LineageOS 14.1 here, the bug does not happen to me either.

**Comment by ariacorrente** [comment]
I do not have experience in android development but I'll try. I started downloading the development tools but this is the third day of download and it keeps downloading stuff (because of the very low bandwidth of my ISP). I probably need some more days, when I will have more information I will inform you, thanks.

**Comment by korelstar** [comment]
Thanks for testing!

We should merge and release the fix soon ...
