### ISSUE TITLE
Switch to OkHttp?

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#340]
Some people have connection problems: see, e.g., #305 and #315. They say, that other apps like DavDroid work with the same server. DavDroid uses the OkHttp library (http://square.github.io/okhttp/) for http connections: https://gitlab.com/bitfireAT/davdroid/blob/master-ose/app/src/main/java/at/bitfire/davdroid/HttpClient.kt

Does anyone has some experiences with OkHttp? Should we use that library, too?

**Comment by stefan-niedermann** [comment]
I am open for switching the lib, but i have no experience with OkHttp (Never heard about it to be honest). What are the benefits? Where does it differ from the default HttpClient?

**Comment by korelstar** [comment]
Honestly, I can't tell. The idea is based on the bug reports which say that they have connection problems in Nextcloud Notes, but not in DavDroid and Nextcloud. DavDroid uses OkHttp and the website from OkHttp says, that "OkHttp perseveres when the network is troublesome: it will silently recover from common connection problems". That sounds interesting and could fix the reported bugs. But that's just some hope and therefore I'm asking for experiences :smiley:

**Comment by stefan-niedermann** [comment]
The jar-File is round about 0,4 kB big. This is an acceptable size, so let's try it. We have nothing to loose, the handling is similar as far as i see and since the mentioned other apps are using it too, it worth a try i think :)

**Comment by korelstar** [comment]
This is obsolete if we use the Nextcloud SingleSignOn library (see #418). Hence, we should wait for a decision over there before implementing anything here.

**Comment by stefan-niedermann** [comment]
See #418, therefore obsolete.
