### ISSUE TITLE
»Syncing« icon looks like a warning

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#344]
The current syncing icon looks a bit like there’s an error, because it uses the icon for »sync problem«:
![screenshot from 2018-03-09 16-24-22](https://user-images.githubusercontent.com/925062/37214828-8336b55e-23b6-11e8-8f29-4f8626018963.png)
There is no problem though :) so we should simply use the icon for »sync«: https://material.io/icons/#ic_sync

cc @stefan-niedermann @korelstar

**Comment by korelstar** [comment]
Currently, the icon doesn't indicate that the note is syncing, but it indicates that the note wasn't synced yet (please try offline mode to check). Therefore, I think the icon is appropriate.

**Comment by jancborchardt** [comment]
Something not being synced yet is _not_ an error. :)

In the desktop client for example, a changed file is shown with the blue sync icon while it is not synced. Not an error icon.

**Comment by korelstar** [comment]
Okay, we could try it ...

**Comment by stefan-niedermann** [comment]
Okay, we are using the icon in blue without the exclamation mark for now.

I tested the  icon from the nextcloud android app, too, but it was too attention begging and collapsed with the category. (https://raw.githubusercontent.com/nextcloud/android/master/src/main/res/drawable-xxhdpi/ic_synchronizing.png)

![grafik](https://user-images.githubusercontent.com/4741199/38558078-5d3703c2-3ccf-11e8-83e1-bd36b039a309.png)
