### ISSUE TITLE
Favorites in main notes list

### ISSUE THREAD

**Issue by korelstar** [stefan-niedermann/nextcloud-notes#346]
@dan0xii suggested to sort the notes list by favorite attribute (again). Since this issue is hidden in the discussion of another PR (#275), I'm making it more visible with this separate issue.

## Variants to decide
There are two possibilities of sorting the notes in the app's main activity:

1. First by favorite (favorites first), then by date (recent notes first)
2. Only by date, separate menu item for favorites

## Situation
We had the first variant in the Android app until the navigation drawer was introduced. Now, we have a separate menu item for favorites.

The web app uses the first variant, too. But this may change when introducing categories to the web app - currently, it lacks of separate/filtered notes lists.

The Nextcloud files app doesn't sort by favorite, there we have a separate menu item like in this app now.

## Evaluation
The idea of the favorite feature is to be able to fast find often used notes. This is more effective, if the main list view is sorted by favorites. However, recently modified notes move down in that view and it obsoletes a separate favorites list.

Did I missed something?

## Remarks
This discussion is only about the notes list activity. The notes list widget should be discussed separately (I think that favorites should be first in the widget).

What do you think, @jancborchardt and @stefan-niedermann ?

**Comment by jancborchardt** [comment]
Yes – lots of people rarely use the sidebar (including me and @camilasan ;) and the main view should already be quite good. So sorting favorites up top is the proper way (inside favorites of course also most recently modified up top), and then all the other notes, my most recently modified first.

**Comment by jancborchardt** [comment]
@korelstar @stefan-niedermann if you are fine with it then yes – we could remove the favorites section. :) That's the intention of sorting favorites up top, to make the default view more relevant and not need specific other views. :)

**Comment by korelstar** [comment]
The difference could be: favorites in main view are sorted by last modified date (like non-favorite notes in the main view) and in the favorites view, they are sorted by name.

What about this?

**Comment by jancborchardt** [comment]
That would be quite confusing though. Also, sorting by name for notes makes little sense – the starting letter has no correlation to the note's relevance for you. (That's why sorting by last modified is best.)
