### ISSUE TITLE
Adaptive Icon

### ISSUE THREAD

**Issue by splitt3r** [stefan-niedermann/nextcloud-notes#355]
The app icon should be adaptive just like the Nc and Nc Talk apps. See https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html for further details :relaxed:

**Comment by stefan-niedermann** [comment]
I have tried to adapt the solution of the nextcloud android app.
Problems i experienced and that are reproducable at the branch i just pushed:
- Breaks on an API 15 device
- the logo has to be small and centered in ic_launcher_foreground.xml to look good on round icon sets. this leads to padding everywhere we are using it (e. g. in the sidebar). An option would be to use different images or anyone knows a hack how to give padding only at the adaptive icon.

![grafik](https://user-images.githubusercontent.com/4741199/38543407-c866e958-3ca4-11e8-8cde-070dfef3f372.png)

![grafik](https://user-images.githubusercontent.com/4741199/38543456-db6dee66-3ca4-11e8-9590-d67a310f518b.png)

All in all it's a bit a mess, the logo is just not designed to fit all shapes. So i talked to @jancborchardt and he suggested to redesign the logo completely from scratch.

From the technical view: I would suggest to eleminate all (logo/launcher) icons we currently have in the app and recreate it using the "image asset" creator (delivered by android studio) so we know it works well on all API levels and has fallbacks and so on.

**Comment by splitt3r** [comment]
Thanks :) looks like a good start.

**Comment by stefan-niedermann** [comment]
@splitt3r you can build the app and give it a try :) every feedback is appreciated :)

**Comment by splitt3r** [comment]
I will give it a try 👍
