### ISSUE TITLE
Automatic save

### ISSUE THREAD

**Issue by benpro** [stefan-niedermann/nextcloud-notes#357]
Hi,

Please add an automatic save (locally), we are on a mobile device, anything can go wrong.
I lost my notes because I not saved the content and my battery died.

Adding an automatic save like every 5 minutes could be nice...
Adding an automatic synchronize afterward would be nice too.

**Comment by korelstar** [comment]
There is already automatic save when you edit a note. However, when you create a note, automatic save was introduced in v0.14.0.

Did you used an older version and just created the note?

**Comment by benpro** [comment]
> However, when you create a note, automatic save was introduced in v0.14.0.

I was in v0.13.1. I'm glad to hear that v0.14.0 has enabled automatic saves! I'm now running v0.14.2 and cannot reproduce the issue. Good!
