### ISSUE TITLE
Context based formatting

### ISSUE THREAD

**Issue by maenujem** [stefan-niedermann/nextcloud-notes#363]
I'm using nextcloud-notes on android together with nextcloud notes on the server and qownnotes on the desktop to manage the notes using markdown. Sync working fine for me. A feature I'm missing is some better support for _editing markdown in the android app eg. some buttons for easily inserting markdown characters_, similar as it is in Markor (which I couldn't get to sync with nextcloud android client so far).

**Comment by stefan-niedermann** [comment]
I think this is out of scope for this app. IMHO this fits better to e. g. NextNotes (i don't know if they have an companion android client) because the focus of this app is writing and not formatting.

cc @jancborchardt

**Comment by maenujem** [comment]
I'm happy with the Nextcloud serverside Notes service.

I'd only like to have easier support on Android side to edit/write markdown: have the Markdown commands/characters always directly accessible on the onscreen-keyboard (as in Markor) without need to switch keyboard between signs and characters all the time.
Everything else works better than in the other mentioned app.

**Comment by stefan-niedermann** [comment]
This might help with the implementation: https://stackoverflow.com/questions/12995439/custom-cut-copy-action-bar-for-edittext-that-shows-text-selection-handles/13004720#13004720

**Comment by stefan-niedermann** [comment]
Next version will contain basic support:

- select some text
- pop-up includes "italic" and "bold"
- pressing adds `*` and `**` automatically

![grafik](https://user-images.githubusercontent.com/4741199/52372261-fc9a4200-2a57-11e9-9991-6a822639095f.png)

Possible enhancements are:

- Remove signs, when already bold/italic
- Enable links

**Comment by stefan-niedermann** [comment]
Okay, this is already in master. I will soon release a new version containing those improvements. We should keep tracking further features regarding Context based formatting in new issues - otherwise we will have a never ending issue here :)

**Comment by jancborchardt** [comment]
@stefan-niedermann so cool! Great work there. :)
