### ISSUE TITLE
Implement new login flow for Notes app

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#373]
The new login flow from the files app shall be adopted, like @mario suggested.
@tobiasKaminsky i've added you as contributor, so you should be able to merge into this project. If i can help you with anything, just ask :)

**Comment by tobiasKaminsky** [comment]
Sorry for the delay. I want to start this now. 
Is it okay for you that it is similar to NC files app? So that the user first only see a "server address" input field, which then redirects to the new weblogin.
As fallback, I would show the old login, just like on NC files app.

**Comment by tobiasKaminsky** [comment]
PR is in https://github.com/stefan-niedermann/nextcloud-notes/pull/396

**Comment by stefan-niedermann** [comment]
yeah, that's absolutely fine :-) Thanks for the PR, just tell when it is ready to review.

**Comment by tobiasKaminsky** [comment]
As noted in PR, there are some open questions.
Can you answer them or adapt the PR for your need?
If you need help, then just ping me. :-)

**Comment by stefan-niedermann** [comment]
Fixed in v. 1.0.0

Staged rollout on Play Store begins and it should be on F-Droid in a few days.
