### ISSUE TITLE
Hardcoded list for special category images

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#375]
The server part might come soon with some predefined categories (like "Personal" and "Work").

We could define a list for some of them (like "Music", "Personal", "Movies" and so on) and display them as category icon.

cc @camilasan

**Comment by stefan-niedermann** [comment]
We now have a hard coded list for

- Music
- Movies / Movie
- Work

Any suggestions for more are welcome, i have no idea what categories people are using :man_shrugging: 

![grafik](https://user-images.githubusercontent.com/4741199/66234126-25f59580-e6ed-11e9-86f3-356e860b90e9.png)

**Comment by korelstar** [comment]
Hmmm. Maybe Shopping, Photography, Financial, Private?

But please be aware of subcategories! Currently, the icon switches to a folder with a plus sign, if the category has subcategories. This change may break this behavior.

**Comment by jancborchardt** [comment]
Yeah, that’s kinda cool to show people the categories.

The first 2 should definitely be:

- Personal (we have that as default calendar too)
- Work

And then we can have some categories as already mentioned. Let’s not go above 7 total though (Personal, Work and max 5 more) as then it’s a bit excessive. :)

Maybe
- Finances
- Movies
- Music
- Shopping
- Vacation

**Comment by stefan-niedermann** [comment]
Yes, sounds good, but which icons to use? Ideally just use material icons...

**Comment by jancborchardt** [comment]
Updated my post above with suggestions for the icons. :)

**Comment by stefan-niedermann** [comment]
@jancborchardt: @korelstar is right.

![grafik](https://user-images.githubusercontent.com/4741199/66638737-d0057e00-ec15-11e9-91cc-b2ea19055e20.png)

We are currently displaying a folder with a `+`-sign, when there are subcategories which can be expanded. Of course the entries still expand on icon click when there are subcategories.

How could we resolve this style-wise with many different icons? Just assume, the user "knows" there are subcategories?

**Comment by jancborchardt** [comment]
Ah sorry, missed @korelstar’s point above.

Is there a common Android pattern for how to do these subcategories in the navigation? Changing the icon and requiring click on it to expand the subcategories seems a bit difficult to discover.

**Comment by stefan-niedermann** [comment]
I think, usually subcategories are always expanded and only [separated via a subheader](https://i.stack.imgur.com/gJqy7.png)...

# Current behavior:

- **Clicking on the title**
  - Parent category gets selcted
  - Drawer gets closed
  - Notes list shows all items from the parent categories and separated from them all items from the subcategories
- **Clicking on the icon**
  - Parent category gets selected
  - Drawer stays open
  - Categories in drawer get expanded
  - Notes list shows all items from the parent categories and separated from them all items from the subcategories

# Possible future behavior:

- **Clicking on the title**
  - Expands the categories
  - Drawer stays open
  - Parent category gets selected
  - Notes list shows all items from the parent categories and separated from them all items from the subcategories
- **Clicking on the icon**
  - Behaves exactly the same like clicking on the title

## Benefits

- Subcategories are **always** easy to discover as you can not longer miss this feature when you select the parent category

## Drawbacks

- Drawer has to be closed manually when selecting a category that has subcategories. Might be annoying.

Another variant would be to use the possible future behavior but close the drawer. The user would see the expanded subcategories in the time while the drawer closes (animated) and if the user opens the drawer again. Drawback of this solution would be that a user has to open the drawer twice if he wants to directly open a subcategory. Might be annoying, too :man_shrugging: :man_shrugging: :man_shrugging:

**Comment by korelstar** [comment]
I think we should not slow down the default use-case. I.e., showing notes of a primary-level category should not require more steps than now.

Btw., the plus icon is a fast-track in order to jump to subcategories. It's not the only way to do this and it does apply to advanced users only.

**Comment by jancborchardt** [comment]
Agree with @korelstar here, showing the notes of the primary level category should take precedence. A simple behavior could be:
- Tap on the text / most part of the entry → Go to the notes of that category
- Tap on the icon, which has a sort of triangle indicator overlaid in case there are subcategories → Expand the subcategories.

What do you think?

**Comment by korelstar** [comment]
Sounds good. We would have to change the current plus sign with a triangle then.

**Comment by stefan-niedermann** [comment]
I aggree, but then we have as remaining issue, that the triangle might look good in a folder, but it is hard to discover in a "special category icon" as overlay. How should we solve this?

**Comment by jancborchardt** [comment]
I’d say it’s possible, if we just overlay it correctly. The triangle just needs to have a proper distance to the existing icon, that is a border which is cut off from the icon being overlaid.

Just like e.g. icon-menu-sidebar or the notifications icon:
![](https://docs.nextcloud.com/server/17/developer_manual/_images/menu-sidebar.png) ![notifications](https://user-images.githubusercontent.com/925062/67604771-cbe07100-f77c-11e9-9569-be4b642d0e04.png)

**Comment by NA0341** [comment]
You can put the triangle directly in between the category icon and name.
Letting it rotate 90° clockwise when the category is expanded - just like a graphical file-tree view.

**Goods:**
-» Very clean looking solution.
-» Folder purpose (custom icon) & subfolder indicator clearly separated.
-» Visually easier to recognize than a on-icon-indicator solution (especially with small text size).
-» Less room for (visual) errors.
-» May be easier to implement.

**Odds:**
-» May look convoluted with many subfolders.
-» Triangle placing & text size may look out of place with some text sizes & font types.

![Screenshot_20220321-025227_Nextcloud Notes](https://user-images.githubusercontent.com/26059513/159197582-35f63bce-b8cb-4099-bda0-81f08c0075c9.jpg)
