### ISSUE TITLE
Move sync icon to the left side

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#376]
The sync icon should be on the left side of the items, at the bottom/right of the favorite star (compare to files app)

**Comment by jancborchardt** [comment]
Good point! That will make everything be more focused as all important things are more to the left.

**Comment by stefan-niedermann** [comment]
![device-2018-08-25-162911](https://user-images.githubusercontent.com/4741199/44619303-6d6fe800-a884-11e8-84f5-7689149e1d24.png)
