### ISSUE TITLE
New section style

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#377]
- [x] align section titles with notes titles horizontally
- [x] remove background-color
- [x] add margin-top (or padding-top)
- [x] adjust text size so it matches excerpt text size

The result should look similar to the sections in the webinterface (compare e. g. to the activity feed)

![grafik](https://user-images.githubusercontent.com/4741199/38736083-385497f0-3f2b-11e8-9b64-3530e44149fc.png)

Reason: They are currently catching too much attention.

**Comment by stefan-niedermann** [comment]
cc @jancborchardt mmmh i think i might get used to it

![device-2018-04-13-153837](https://user-images.githubusercontent.com/4741199/38737932-18dd25b2-3f31-11e8-927c-e91637f2623f.png)

**Comment by stefan-niedermann** [comment]
sure, should excerpt and category get a lighter font as well?

**Comment by jancborchardt** [comment]
@stefan-niedermann category can be lighter, but excerpt is good. :) The general rule is that meta-info (date & category) should be lighter than content (title & excerpt)

**Comment by korelstar** [comment]
Please be aware, that these section titles are also used for sub-categories (when you have chosen a category from the navigation drawer) and not only for unimportant time information.

**Comment by jancborchardt** [comment]
@korelstar what do you mean by sub-categories? In any case, categories are also secondary info (just like time), as said above.

**Comment by korelstar** [comment]
@jancborchardt 
The Notes (server) app maps directories to categories (and reverse). Hence, if you create a sub-directory `Recipes/Cakes/` on the server (nobody can hinder you), you'll get a sub-category `Cakes` in the main-category `Recipes` (i.e., the category `Recipes/Cakes`). Currently, sub-categories are not propagated in the Android app, but you can use them if you have already hierarchically sorted notes on your server. E.g., if you select the category `Recipes` in the NavigationDrawer of the app, you'll get the following list:

- Recipe 1
- Recipe 2
- *section:* Recipes / Cakes
- Cake 1
- Cake 2
- *section:* Recipes / Lunch
- Lunch 1
- Lunch 2
