### ISSUE TITLE
Enhance Settings

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#379]
Currently the most "nerdy" stuff in the settings gets the most attention / space: The self signed certificate stuff.

- [x] Rename "Account Settings" to "Account" since you know you already are in the settings
- [x] Display "guy"-icon at the left of "Account"
- [x] Display "eye"-icon at the left of "Display mode for Notes"
- [x] Merge the two certificate-related entries into on dialog. Call the Entry "Manage certificates" and put an appropriate icon at the left of it. (cc @schaarsc )

**Comment by schaarsc** [comment]
@stefan-niedermann could you please explain this requirement
1. "merge cert entries into dialog"? something like this https://developer.android.com/guide/topics/ui/settings#Subscreens?
2. any preference for the icon? I'd suggest Material Design / https

**Comment by stefan-niedermann** [comment]
1. Yes, exactly, a subscreen :)
2. I thought about this icon ("lock"): ![grafik](https://user-images.githubusercontent.com/4741199/41485959-d7f6c556-70e2-11e8-83e7-25e45293a5ec.png) Do you have any better idea?
