### ISSUE TITLE
Logo Proposal for Nextcloud-notes

### ISSUE THREAD

**Issue by area55git** [stefan-niedermann/nextcloud-notes#381]
Hello, I wish to cooperate with Nextcloud-notes, for this reason I have decided to design a logo for it. If you like this proposal, I can send you the files.

You can suggest the changes you think are necessary.

[![PROPUESTA_LOGO_NEXTCLOUD-_NOTES.jpg](https://s18.postimg.cc/d752bxje1/PROPUESTA_LOGO_NEXTCLOUD-_NOTES.jpg)](https://postimg.cc/image/b2kpauhr9/)

**Comment by stefan-niedermann** [comment]
Dear @area55git,

awesome you want to start contributing :rocket: 

I have reviewed your logo proposal and to be honest, i do not like it very much for different reasons:

- The nextcloud brand (color and backgrounds) are note respected
- The logo does not represent the focus on simplicity of the app
- The color scheme is notwhere else used

See, this is how the other apps of the ecosystem look:

![Nextcloud Apps](https://user-images.githubusercontent.com/4741199/38733821-ba772ebc-3f23-11e8-8635-15e5f1780846.png)

Basically, they all have the same background with an white, monochromatic foreground, which should be as simple as possible.

Also, our user experience expert @jancborchardt mentioned, he already had something else in mind to improve the logo in combination with round backgrounds, so i think it's better to stay with it currently.

Again, thank you very much for contribution, it's great to hear, you like the app :-) If you want, you can try to solve other issues, e. g. #376 is a great starter issue to get used to the code.

I hope this did not sound rude or keep you from contributing to this project.

Sincerely yours

**Comment by jancborchardt** [comment]
@area55git hey, awesome that you want to contribute design to open source projects – designers are certainly more needed in the open source space! :)

I agree with @stefan-niedermann here that we need to be consistent with the Nextcloud brand. While we want to adjust the current icon, it will mostly just be changing the white inner shape to something like a pencil or similarly simple. If you have suggestions, you are welcome! :)

And if you want to help more open source projects with design, I can recommend checking out [Open Source Design](https://opensourcedesign.net)! :)

**Comment by area55git** [comment]
Hi @jancborchardt I have no problem in sending you a proposal in 2 days

**Comment by area55git** [comment]
Hi @jancborchardt In response to your request, this is my Icon and Logo proposal for Nextcloud Notes.

[![PROPUESTA_LOGO_NEXTCLOUD-_NOTES.jpg](https://s31.postimg.cc/ey6h9e64b/PROPUESTA_LOGO_NEXTCLOUD-_NOTES.jpg)](https://postimg.cc/image/635myvhbr/)

What proposal do you like?
I will send you an pull request and send you the original files.

**Comment by jancborchardt** [comment]
@area55git ideally use the current logo as base, because we need the background pattern. The only change necessary is to replace the current white icon part with a simpler pencil. The pencil part of your proposal looks good for that. :)

**Comment by stefan-niedermann** [comment]
Yeah, it already looks much better than the first proposal.

I will add the background pattern myself (because i have to adjust it for different resoltions, etc.)

We only need the inner white part of the logo. I think a "n"-letter as in your second and third column suggested is not needed.

**Comment by jancborchardt** [comment]
@stefan-niedermann just remembered the edit icon: https://github.com/nextcloud/server/blob/master/core/img/actions/edit.svg
That would be consistent with the rest of Nextcloud, could we use that in white?

**Comment by stefan-niedermann** [comment]
can you post it as png, i currently can not view an svg file cause i'm on mobile

**Comment by area55git** [comment]
## [ICON DOWNLOAD](https://drive.google.com/open?id=1598dVoV6hMt2ju5CFCxVXhiGG34lckTS)

Hi, in the link are the files in png and svg

**Comment by jancborchardt** [comment]
@stefan-niedermann I actually meant the rename icon:
https://github.com/nextcloud/server/blob/master/core/img/actions/rename.svg
![](https://i.imgur.com/k28Hcwm.jpg)
