### ISSUE TITLE
Could not connect app to my instance

### ISSUE THREAD

**Issue by oyse** [stefan-niedermann/nextcloud-notes#382]
I installed the app from the Google Play store on a Samsung S8 with Android 8.0.0  and it failed to connect to my NextCloud 13 instance. No error message. The apps just says "Connecting..." (not sure about exact text as it was translated) but nothing happened.

I tried connecting specifying with and without https:// as part of the server address.

**Comment by stefan-niedermann** [comment]
There is a bug in the current version that causes the initial login to take up to several minutes (!). It is fixed in the source code and will be released on Play Store within the next view days.

Please try it again some tomes and give it up to 5 minutes for initial sync.

Regards

**Comment by stefan-niedermann** [comment]
@oyse please add a comment when you have tried it again whether your login was successful or not, so we can close this issue or go deeper into the bug analysis :)

Also: latest version is currently staged rolling out - please comment, when you receive the update and tell us if this might solve your problem

**Comment by oyse** [comment]
I tried again and after about 10 minutes it claims that the logon information is incorrect.

I have tried with and without adding https in front of the server address.

I assume that I just need to point it to the server name and not some API endpoint or similar.

I currently have version 0.13.1 installed.

**Comment by stefan-niedermann** [comment]
> I assume that I just need to point it to the server name and not some API endpoint or similar.

That's right, in v0.13.1 you have to enter example.com (or example.com/nextcloud).

Better URL handling is also part of the next release (you will be able to enter the server OR the rest endpoint)

**Comment by stefan-niedermann** [comment]
@oyse have you been able to connect to your instance in the meantime?

**Comment by oyse** [comment]
Yes. It is working after the app updated to the latest version.

2018-04-18 12:46 GMT+02:00 Niedermann IT-Dienstleistungen <
notifications@github.com>:

**Comment by stefan-niedermann** [comment]
Great to hear :)
