### ISSUE TITLE
always open single note from widget in edition mode

### ISSUE THREAD

**Issue by Keho** [stefan-niedermann/nextcloud-notes#385]
Hi,

I use the preview opening mode. It's great when opening notes from the application, or from the widget listing notes.
Nevertheless I think that widgets displaying a single note should bypass this setting since we can already read the note thanks to the widget and the only reason one would want to tap on it is to edit the note.
Obviously this would make no difference to people who set the parameter to « open in edition mode ».

**Comment by stefan-niedermann** [comment]
It might not be the only reason. E.g. Markdown rendering is much better in reading mode then in edit mode. For example one might want to see actual checkboxes instead of `- [ ]`.

**Comment by Keho** [comment]
Indeed markdown looks better in reading mode, the note I have as a widget uses checkboxes.
But I thought that the inconvenience of not being able to render markdown in the widget is less important than having to tap one more time to edit the note, since the widget listing notes may be better for someone who uses a lot of markdown in a note, can't stand non-rendered markdown and thus finds himself often tapping the widget to view the note with rendered markdown. One drawback of the list widget might be the loss of time finding the said note(s), especially if the order changes often, but I guess using stars would solve this issue (usually we are talking about a few notes only).
Well I admit there is no ideal solution, but I think my use case is more common ; you've got the final say.

**Comment by stefan-niedermann** [comment]
My opinion is that we should not overwrite the users choice.

What do you think @korelstar @dan0xii ?

**Comment by korelstar** [comment]
I agree to @stefan-niedermann
