### ISSUE TITLE
Using indent for blocks is unsupported

### ISSUE THREAD

**Issue by tribut** [stefan-niedermann/nextcloud-notes#390]
The app works great, but it does not seem to support the "indent block with four spaces for code" syntax. I've changed my notes to use triple-backticks which works but especially on mobile typing a few spaces would be easier.

**Comment by stefan-niedermann** [comment]
Dear @tribut,

thank you for reporting.
Unfortunately this can only be solved in the used upstream Markdown library.

Therefore i'd like to ask you to open an issue in the upstream repository: https://github.com/yydcdut/RxMarkdown/issues

Regards
