### ISSUE TITLE
Cannot connect if server uses elliptic curves.

### ISSUE THREAD

**Issue by GAS85** [stefan-niedermann/nextcloud-notes#391]
Old name: Could not connect to server if strong ciphers being used. 
-----

Hallo,
Since i enable http2 and strong ciphers on my Apache2 I could not connect anymore to my server with this app. Error message is:

        javax.net.ssl.SSLHandshakeException:Handshake Failed

Setup is as here: https://gist.github.com/GAS85/42a5469b32659a0aecc60fa2d4990308

Update: SSL config

       SSLCipherSUite "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384" 

![20180425_173052](https://user-images.githubusercontent.com/6813635/39256190-8b702922-48ae-11e8-94e1-ba7d890fd805.png)

**Comment by mario** [comment]
Because I can do a PR for this if it's a Google Play version.

**Comment by GAS85** [comment]
This is FDroid.

**Comment by stefan-niedermann** [comment]
@mario F-Droid and Play Store version are identical

**Comment by mario** [comment]
@stefan-niedermann I know. But this can only be fixed if users have Google Play Services ;)

**Comment by stefan-niedermann** [comment]
I'm curious: how? What is the cause of this error?

**Comment by mario** [comment]
Ciphers and supported protocols are tied to Android version and/or the vendor. Google provides a way to install newer ciphers and protocols support if you're running Google Play Services.

**Comment by stefan-niedermann** [comment]
Okay, two further questions:

1. How would a patch affect users that do not have installed Play Services?
2. Is there any kind of fix for Non-Play Services-Users possible (as far as you know)? Maybe on rooted devices?

**Comment by GAS85** [comment]
Thats strange... I have Google play services and on this device with Android 7.0. For example nextcloud client does not meet this issue.

**Comment by mario** [comment]
1) It would not. But it separates the app in two flavours - gplay and fdroid so F-Droid build recipe has to be changed.
2) No idea, sorry. 

@GAS85 That's strange. Nextcloud client has the same fix but only if you install the app from Play Store. Before I did that we had a bunch of similar reports.

Then maybe this is something else? Hm...

**Comment by stefan-niedermann** [comment]
Maybe @GAS85 installed the Nextcloud app from Play Store and the Notes app from F-Droid because it's free at F-Droid?

> it separates the app in two flavours

Well, i wanted to avoid that, because it means more affords at every release, maintaining, merging, ...

**Comment by mario** [comment]
@stefan-niedermann no it does not? Have you heard of gradle flavours? :P

**Comment by GAS85** [comment]
Basically yes, I have a F-Droid and install Notes from there, but then I find out that some programs could not be lunched without Google Play Services, so I have to install Services afterwards, because e.g. Signal could not e lunched without it.

**Comment by mario** [comment]
@stefan-niedermann no because it does NOT update supported ciphers for Android itself.

**Comment by GAS85** [comment]
> @stefan-niedermann no because it does NOT update supported ciphers for Android itself.

I'm a bit confused about this, I have at least 2 points:
1. If this is an Android issue then other Apps should also use SSL API and will have same trouble, but nor FireFox, or Nextcloud Client have't any issues with hand shake.
2. If this is an Android 7.0 issue - then why SSLLabs shows successful handshake from Android 4.2.2 with TLS 1.2 and Android 7.0 even supports HTTP2 ([bigger screenshot](https://screenshots.firefox.com/cyoQBhzcFtOqQxwL/www.ssllabs.com)):
![screenshot-2018-4-26 ssl server test gas85 ddns net powered by qualys ssl labs](https://user-images.githubusercontent.com/6813635/39318904-ab41027c-497f-11e8-8368-ef45f7647d9c.png)

So, for me it still strange how you describes connection between GApps/Android/F-Droid and Ciphers being used issue.

**Comment by schaarsc** [comment]
I cannot reproduce this issue.
Server: Apache 2.4 / Ciphers see above
Client: Android 7.1.1, Notes-App 0.17 (weblogin branch)
Apache Access Log: TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 

Supported Ciphers
https://developer.android.com/reference/javax/net/ssl/SSLEngine

maybe Apache log level debug can give more insight on what is going wrong...

**Comment by schaarsc** [comment]
can you repeat the test with http (not http2)?

**Comment by GAS85** [comment]
I did not manage to disable http2 in w proper way before going to bed, so I just enable all ciphers by comment my cipher line in ssl.conf. Basically then connection goes to http 1.1 with TLSv1.2 and cipher: DHE-RSA-AES256-GCM-SHA384 (256/256 bits). It looks like it does not support elliptic curve.

```
sudo tail -f /var/log/apache2/error.log | grep -v "192.168.0"
[Mon Jul 16 22:04:33.812019 2018] [proxy:debug] [pid 1062:tid 2706338864] proxy_util.c(2162): AH00942: FCGI: has acquired connection for (*)
[Mon Jul 16 22:04:33.812091 2018] [proxy:debug] [pid 1062:tid 2706338864] proxy_util.c(2215): [client 111.111.111.111:7538] AH00944: connecting fcgi://localhost/var/www/nextcloud/index.php to localhost:8000
[Mon Jul 16 22:04:33.812158 2018] [proxy:debug] [pid 1062:tid 2706338864] proxy_util.c(2252): [client 111.111.111.111:7538] AH02545: fcgi: has determined UDS as /run/php/php7.0-fpm.sock
[Mon Jul 16 22:04:33.813296 2018] [proxy:debug] [pid 1062:tid 2706338864] proxy_util.c(2424): [client 111.111.111.111:7538] AH00947: connected /var/www/nextcloud/index.php to httpd-UDS:0
[Mon Jul 16 22:04:33.813638 2018] [proxy:debug] [pid 1062:tid 2706338864] proxy_util.c(2795): AH02823: FCGI: connection established with Unix domain socket /run/php/php7.0-fpm.sock (*)
[Mon Jul 16 22:04:33.815051 2018] [authz_core:debug] [pid 1062:tid 2706338864] mod_authz_core.c(809): [client 111.111.111.111:7538] AH01626: authorization result of Require all granted: granted
[Mon Jul 16 22:04:33.815223 2018] [authz_core:debug] [pid 1062:tid 2706338864] mod_authz_core.c(809): [client 111.111.111.111:7538] AH01626: authorization result of <RequireAny>: granted
[Mon Jul 16 22:04:35.807503 2018] [proxy:debug] [pid 1062:tid 2706338864] proxy_util.c(2177): AH00943: FCGI: has released connection for (*)
[Mon Jul 16 22:04:40.813692 2018] [ssl:debug] [pid 1062:tid 2681148464] ssl_engine_io.c(1103): [client 111.111.111.111:7538] AH02001: Connection closed to child 7 with standard shutdown (server blablabla.net:443)
[Mon Jul 16 22:04:51.466843 2018] [ssl:info] [pid 1063:tid 2597180464] [client 111.111.111.111:8261] AH01964: Connection to child 81 established (server blablabla.net:443)
[Mon Jul 16 22:04:51.469439 2018] [ssl:debug] [pid 1063:tid 2597180464] ssl_engine_kernel.c(2141): [client 111.111.111.111:8261] AH02043: SSL virtual host for servername blablabla.net found
[Mon Jul 16 22:04:51.469934 2018] [ssl:debug] [pid 1063:tid 2597180464] ssl_engine_kernel.c(2141): [client 111.111.111.111:8261] AH02043: SSL virtual host for servername blablabla.net found
[Mon Jul 16 22:04:51.470079 2018] [core:debug] [pid 1063:tid 2597180464] protocol.c(2257): [client 111.111.111.111:8261] AH03155: select protocol from h2,h2c,http/1.1, choices=http/1.1 for server blablabla.net
[Mon Jul 16 22:04:51.470218 2018] [core:debug] [pid 1063:tid 2597180464] protocol.c(2302): [client 111.111.111.111:8261] AH03156: select protocol, proposals=http/1.1 preferences=h2,h2c,http/1.1 configured=h2,h2c,http/1.1
[Mon Jul 16 22:04:51.470310 2018] [core:debug] [pid 1063:tid 2597180464] protocol.c(2320): [client 111.111.111.111:8261] AH03157: selected protocol=http/1.1
[Mon Jul 16 22:04:53.249310 2018] [ssl:debug] [pid 1063:tid 2597180464] ssl_engine_kernel.c(2069): [client 111.111.111.111:8261] AH02041: Protocol: TLSv1.2, Cipher: DHE-RSA-AES256-GCM-SHA384 (256/256 bits)
[Mon Jul 16 22:04:53.327805 2018] [ssl:debug] [pid 1063:tid 2597180464] ssl_engine_kernel.c(377): [client 111.111.111.111:8261] AH02034: Initial (No.1) HTTPS request received for child 81 (server blablabla.net:443)
[Mon Jul 16 22:04:53.329739 2018] [authz_core:debug] [pid 1063:tid 2597180464] mod_authz_core.c(809): [client 111.111.111.111:8261] AH01626: authorization result of Require all granted: granted
[Mon Jul 16 22:04:53.331708 2018] [authz_core:debug] [pid 1063:tid 2597180464] mod_authz_core.c(809): [client 111.111.111.111:8261] AH01626: authorization result of <RequireAny>: granted
[Mon Jul 16 22:04:53.333509 2018] [proxy:debug] [pid 1063:tid 2597180464] mod_proxy.c(1239): [client 111.111.111.111:8261] AH01143: Running scheme unix handler (attempt 0)
[Mon Jul 16 22:04:53.333713 2018] [proxy_fcgi:debug] [pid 1063:tid 2597180464] mod_proxy_fcgi.c(1021): [client 111.111.111.111:8261] AH01076: url: fcgi://localhost/var/www/nextcloud/index.php proxyname: (null) proxyport: 0
[Mon Jul 16 22:04:53.333814 2018] [proxy_fcgi:debug] [pid 1063:tid 2597180464] mod_proxy_fcgi.c(1028): [client 111.111.111.111:8261] AH01078: serving URL fcgi://localhost/var/www/nextcloud/index.php
[Mon Jul 16 22:04:53.333909 2018] [proxy:debug] [pid 1063:tid 2597180464] proxy_util.c(2162): AH00942: FCGI: has acquired connection for (*)
[Mon Jul 16 22:04:53.334008 2018] [proxy:debug] [pid 1063:tid 2597180464] proxy_util.c(2215): [client 111.111.111.111:8261] AH00944: connecting fcgi://localhost/var/www/nextcloud/index.php to localhost:8000
[Mon Jul 16 22:04:53.334098 2018] [proxy:debug] [pid 1063:tid 2597180464] proxy_util.c(2252): [client 111.111.111.111:8261] AH02545: fcgi: has determined UDS as /run/php/php7.0-fpm.sock
[Mon Jul 16 22:04:53.334997 2018] [proxy:debug] [pid 1063:tid 2597180464] proxy_util.c(2424): [client 111.111.111.111:8261] AH00947: connected /var/www/nextcloud/index.php to httpd-UDS:0
[Mon Jul 16 22:04:53.335452 2018] [proxy:debug] [pid 1063:tid 2597180464] proxy_util.c(2795): AH02823: FCGI: connection established with Unix domain socket /run/php/php7.0-fpm.sock (*)
[Mon Jul 16 22:04:53.336460 2018] [authz_core:debug] [pid 1063:tid 2597180464] mod_authz_core.c(809): [client 111.111.111.111:8261] AH01626: authorization result of Require all granted: granted
[Mon Jul 16 22:04:53.336709 2018] [authz_core:debug] [pid 1063:tid 2597180464] mod_authz_core.c(809): [client 111.111.111.111:8261] AH01626: authorization result of <RequireAny>: granted
[Mon Jul 16 22:04:55.367653 2018] [proxy:debug] [pid 1063:tid 2597180464] proxy_util.c(2177): AH00943: FCGI: has released connection for (*)
[Mon Jul 16 22:05:00.374426 2018] [ssl:debug] [pid 1063:tid 2588783664] ssl_engine_io.c(1103): [client 111.111.111.111:8261] AH02001: Connection closed to child 82 with standard shutdown (server blablabla.net:443)
[Mon Jul 16 22:05:01.963379 2018] [proxy:debug] [pid 1063:tid 2555196464] proxy_util.c(2162): AH00942: FCGI: has acquired connection for (*)
[Mon Jul 16 22:05:01.965170 2018] [proxy:debug] [pid 1063:tid 2538402864] proxy_util.c(2162): AH00942: FCGI: has acquired connection for (*)
[Mon Jul 16 22:05:01.966906 2018] [proxy:debug] [pid 1063:tid 2555196464] proxy_util.c(2795): AH02823: FCGI: connection established with Unix domain socket /run/php/php7.0-fpm.sock (*)
[Mon Jul 16 22:05:01.967420 2018] [proxy:debug] [pid 1063:tid 2538402864] proxy_util.c(2795): AH02823: FCGI: connection established with Unix domain socket /run/php/php7.0-fpm.sock (*)
```

**Comment by schaarsc** [comment]
two suggestions
1. rename to "Cannot connect if server uses elliptic curves"
2. revisit after #418

**Comment by GAS85** [comment]
Can do after vacation! If owner could do this - please, feel free.

P.S. as workaround I enable 1 "simple" Diffie Hellman setup.

3 сентября 2018 г. 16:39:57 GMT+02:00, schaarsc <notifications@github.com> пишет:

**Comment by GAS85** [comment]
Successfully tested with latest version 0.24.3. Works good, thanks!
Apache Config:

    SSLCipherSUite "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384"

![image](https://user-images.githubusercontent.com/6813635/59767547-d9538f00-92a2-11e9-892e-81522a445351.png)

**Comment by stefan-niedermann** [comment]
Wow, that was a long vacation :laughing: Glad to hear you had time to retest and everything works fine :)

**Comment by GAS85** [comment]
Actually was not so long, but only now I have had time to reconfigure the server and test it.
