### ISSUE TITLE
Nextcloud-notes on Owncloud: API not working since latest Owncloud update

### ISSUE THREAD

**Issue by stefan-schilling** [stefan-niedermann/nextcloud-notes#394]
Hello,

first: the versions in place:
- Owncloud: 10.0.8-1+1.1 (on Raspberry Pi), latest working version: 10.0.7-1.1
- Nextcloud Notes App: 2.0.2 (no version change known)
- Android Nextcloud Notes App: 0.16.1 (update possible, but that happens in the background)

I'm using Owncloud on my Raspberry (owncloud-files_10.0.8-1+1.1_all.deb), which got updated to this version from 10.0.7-1.1 on Apr. 29 2018.
Since then, the Android Nextcloud Notes App (version 0.16.1) cannot communicate with the server anymore:
- it cannot add notes
- it cannot sync the currently available notes from the server to the app.

Using the Nextcloud Notes app on the owncloud installation itself is working fine, as does the Owncloud sync client to Windows.

Upon creating a new note, I'm getting the following Exception in my owncloud.log:

```
{"reqId":"lgB1yD3uAjqEZHvaLyVz","level":3,"time":"2018-05-03T22:12:30+02:00","remoteAddr":"1.2.3.4","user":"stefan","app":"index","method":"POST","url":
"/owncloud/index.php/apps/notes/api/v0.2/notes",
"message":"Exception: {"Exception":"OCP\\\\Files\\\\NotPermittedException","Message":"Could not move /files/Notes/New note.txt to /files/Notes/New note.txt","Code":0,"Trace":"#0 
/var/www/owncloud/apps/notes/service/notesservice.php(148): OC\\\\Files\\\\Node\\\\Node->move('//files/Notes/N...')\\n#1 
/var/www/owncloud/apps/notes/controller/notesapicontroller.php(116): OCA\\\\Notes\\\\Service\\\\NotesService->update(246, '', NULL)\\n#2 
/var/www/owncloud/apps/notes/controller/errors.php(31): OCA\\\\Notes\\\\Controller\\\\NotesApiController->OCA\\\\Notes\\\\Controller\\\\{closure}()\\n#3 
/var/www/owncloud/apps/notes/controller/notesapicontroller.php(117): OCA\\\\Notes\\\\Controller\\\\NotesApiController->respond(Object(Closure))\\n#4 
[internal function]: OCA\\\\Notes\\\\Controller\\\\NotesApiController->create('')\\n#5 
/var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 
/var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Notes\\\\Controller\\\\NotesApiController), 'create')\\n#7 
/var/www/owncloud/lib/private/AppFramework/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Notes\\\\Controller\\\\NotesApiController), 'create')\\n#8 
/var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('NotesApiControl...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 
[internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 
/var/www/owncloud/lib/private/Route/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 
/var/www/owncloud/lib/base.php(912): OC\\\\Route\\\\Router->match('/apps/notes/api...')\\n#12 
/var/www/owncloud/index.php(55): OC::handleRequest()\\n#13 {main}","File":"
/var/www/owncloud/lib/private/Files/Node/Node.php","Line":416}"}
```

Running a sync, the server records:
`"GET /owncloud/index.php/apps/notes/api/v0.2/notes HTTP/1.1" 200 5124 "-" "nextcloud-notes/0.16.1 (Android)"`
But record is shown in owncloud.log. But no notes appear in Android app. 

I have updated the Nextcloud Notes app to the current version (it has been and stayed version 2.0.2), but that didnt change it.

Any ideas? Please do not hesitate to ask for any further information required.

Thanks in advance,
Stefan

**Comment by stefan-schilling** [comment]
Hey again,

Nextcloud Notes 2.3.2 is not compatible to Owncloud anymore (see https://github.com/nextcloud/notes/issues/194 and https://central.owncloud.org/t/notes-app-unable-to-write-to-owncloud-data-oc-db-connection-method-error/11215).

So I reverted to Nextcloud Notes 2.0.2.

Using the Android App, I can see in the access.log, that it  tries to retrieve the data calling  /owncloud/index.php/apps/notes/api/v0.2/notes. 
This works perfectly well using a browser, but not the Android App - it just doesnt show me the notes.

I haven't tried to add a new note though, it should be able to retrieve the content anyway (and it used to many times since October 2017).

Any ideas?

Thanks in advance.
Stefan

**Comment by stefan-niedermann** [comment]
Thank you for the detailed bug report and the further investigations. I will have a look, but ownCloud-Support is not my highest priority ro be honest. (Just to have asked: Switching to Nextcloud is no option for you?)

The https://github.com/owncloud/notes 

cc @korelstar @Henni @camilasan

**Comment by stefan-schilling** [comment]
Good morning,

I forgot: this is the returned content when calling /owncloud/index.php/apps/notes/api/v0.2/notes using the browser (these are the not so private entries...) with status 200 returned:

[{"modified":1507364018,"title":"MTB - Gabelrepararurbetriebe","content":"MTB - Gabelrepararurbetriebe\nBikeSchmiede, St. Anna Platz (Rock Shox),\u00a0\nSportShop M\u00fcnchen, Kreilerstr. (?)","favorite":false,"id":223},{"modified":1525385188,"title":"Notes-App","content":"Notes-App\nhttps:\/\/github.com\/owncloud\/notes\nhttps:\/\/github.com\/stefan-niedermann\/nextcloud-notes\/issues\/394\n","favorite":false,"id":231},{"modified":1507364050,"title":"Reifengr\u00f6\u00dfen","content":"Reifengr\u00f6\u00dfen\nReifen \nJanosch: 37-622 (28x1,40, 700x35c): 2200 \nGiant: 57-584 (27.5x2.25, 650B): 2250\nCube: 57-559 26x2,25: 2120","favorite":false,"id":224}]

Hope this helps
Stefan

**Comment by stefan-schilling** [comment]
Hello again,

@stefan-niedermann Thanks for your response. Actually, I was looking into migrating to Nextcloud. But there seems to be no Nextcloud .deb package I can install on my Raspberry. All I found were instructions for manually installing Nextcloud. But then I would be off the apt update cycle, something I want to avoid if possible.

Thanks and best wishes from Munich,
Stefan

**Comment by TKLCZ** [comment]
The same issue like the stefan-shilling's on my OwnCloud after update to the 10.0.8 (10.0.8.5).
Debian Stretch, PHP7. OC update via the build-in updater, Notes app installed from Github.
I can see all my notes (and add/delete too) via web interface but all notes lost from Android app. When I try add a new note in app, I get almost the same error like stefan-shilling. Migrating to the NextCloud  is not the solution for me. I have many of users and very much of valuable data and I'm afraid of complications.

**Comment by stefan-niedermann** [comment]
@minteral are you using `Nextcloud Notes` or `ownCloud Notes` on your ownCloud Server?

**Comment by minteral** [comment]
I used ownCloud Notes. I'm now on Nextcloud Notes 2.3.2. Both don't work for me with your app. Thank you for your quick response.

**Comment by stefan-niedermann** [comment]
Well, okay, The ownClouds Notes App is unmaintained, therefore it has not changed. Neither has the Android app, so i assume ownCloud itself changed something that causes incompatibility with ownCloud Notes (at least the API part)..

**Comment by minteral** [comment]
It think so too. The issue occurred after the last owncloud update from 10.0.7 to 10.0.8. About a month ago.

**Comment by stefan-schilling** [comment]
Hey,

I added the app's output using a browser a couple days ago. Does that look good?
I mean, If the Android app uses the address given and receives the content as given, it should be able to display it ,not?

Stefan

**Comment by stefan-niedermann** [comment]
Can you guys please check if the file permissions of your data folder are set correctly?

I will set up an ownCloud instance next week to ivestigate it further. There did not seem to be breaking changes according to the ownCloud changelog, but ownCloud never cared that much on breaking things for 3rd party apps.

---

**I can not promise that i can fix the issue** and even if, there will never be a new version of the ownCloud Notes app because it is unmaintained.
Therefore: If i find the cause and can fix it you will have to apply the patch yourself.

---

Please note that the Nextcloud Notes Android client does require a Nextcloud instance to run correctly and does no longer support ownCloud as a platform officially (mentioned in [README.md](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/README.md#link-requirements) and Play Store).

**Comment by TKLCZ** [comment]
Hello, my permissions seems to be ok:
OwnCloud's data folder: www-data:www-data 770
OwnCloud user's Notes folder: www-data:www-data 777
Path to Notes folder is:
$OCDATAFOLDER/$USERNAME/files/Notes

**Comment by stefan-schilling** [comment]
Hey,

I just test-installed nextcloud (on another machine).
After the installation, I added two notes:
1. using the web interface
2. using the mobile app 
both ways work.

I also tried to access the notes' content using Postman / Firefox:
1. Nextcloud installation, URL http://xxx.xxx.xxx.xxx/nextcloud/index.php/apps/notes/api/v0.2/notes:
- using Postman, I can access the nextcloud content using Basic Auth
- using Firefox, this does not work, since the Cookie (which is set after the user's login) is not accepted; the Notes app seems to accept Basic Auth only

2. Owncloud installation, URL http://xxx.xxx.xxx.xxx/nextcloud/index.php/apps/notes/api/v0.2/notes:
- using Postman, I cannot access the nextcloud content using Basic Auth and I do not have a Cookie available
- using Firefox, I can access the content using the Cookie (which is set after the user's login)

Is this the difference? Owncloud does not accept Basic Auth, which is expected by the Notes App?

**Comment by stefan-schilling** [comment]
Hello,

sorry, but I have to go back a bit: I just installed owncloud-10.0.7 and owncloud-10.0.8 on my local machine. For both I can retrieve notes using URL http://xxx.xxx.xxx.xxx/owncloud/index.php/apps/notes/api/v0.2/notes with Postman and BasicAuth.

The mobile app is working using owncloud-10.0.7 only, owncloud-10.0.8 is not working for the mobile app (again).
I also checked the header and body returned by owncloud-10.0.7 vs. 10.0.8. They are identical.

I also tried it again with the same settings towards my actual installation, here I can retrieve the notes using Postman as well with BasicAuth.

Still, the mobile app wont retrieve the notes from the remote site. From the logs there, I can see, it is still using the correct URL with a GET command (as I do with Postman).

I have to admit, that doesn't make any sense to me - at least the call and its handling (as far as I can reproduce) is identical between 10.0.7 + 10.0.8.

Please note again: I'm using the notes app 2.0.2 on the server side (for all versions), since there is a problem with function supports4ByteText used by notes app 2.3.2 and owncloud, which doesnt provide it.

Thanks for your help.
Stefan

**Comment by stefan-schilling** [comment]
Hey,

I just had Wireshark trace the connection, and I think, I found it:
Upon the first request using Owncloud-10.0.8, the client sends the basic auth info and gets a cookie in return from the owncloud server.
Using this cookie, the request is successful during the second request.
I was able to validate this using Postman, which would not send the cookie upon the first call, but send it on the 2nd one.

This behavious seems to have changed from Owncloud-10.0.7 -> 10.0.8. Owncloud-10.0.7 returned a cookie upon the first requst too, but continued sending the requested content as well. This is now different, it seems to be a 2-step process.

@stefan-niedermann do you have any chance to adjust the mobile app to handle this behaviour?

Here are the logs:

**Owncloud-10.0.7, using the mobile app (reference):**
`GET /owncloud/index.php/apps/notes/api/v0.2/notes HTTP/1.1
Authorization: Basic c3RlZmFuOnRlc3Q=
Connection: Close
User-Agent: nextcloud-notes/0.16.1 (Android)
Host: 192.168.178.30
Accept-Encoding: gzip

HTTP/1.1 200 OK
Date: Fri, 29 Jun 2018 15:15:22 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: ocygaynly7kz=eg1d0cactbhk4guj2d4r2nq7m1; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=49I8SrXdjm68lYwA7LXZXn8NHsOd6YI4pg4Ae6hynxLUy2rOx0d%2B0ykMZZwm4lezHDs1WQznrWd5Qa8q56TRYQ25H4oMJcYgUn79H8Q3YnGm2hKnSHg9PZOBnJkbSpVZ; path=/owncloud; HttpOnly
Content-Security-Policy: default-src 'none';manifest-src 'self';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
Set-Cookie: ocygaynly7kz=jq9dvm00e5ismpj01486f7ru23; path=/owncloud; HttpOnly
Set-Cookie: cookie_test=test; expires=Fri, 29-Jun-2018 16:15:22 GMT; Max-Age=3600
Content-Length: 233
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Connection: close
Content-Type: application/json; charset=utf-8

[{"modified":1530271519,"title":"2. Notiz","content":"2. Notiz\n","favorite":false,"id":49},{"modified":1530271510,"title":"Testnotiz - Owncloud - 2018-06-29","content":"Testnotiz - Owncloud - 2018-06-29\n","favorite":false,"id":30}]`

**Owncloud-10.0.8, using Postman; trace 1st call:**
`GET /owncloud/index.php/apps/notes/api/v0.2/notes HTTP/1.1
Host: 192.168.178.30
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Cache-Control: no-cache
Authorization: Basic c3RlZmFuOnRlc3Q=
Postman-Token: 8b2964db-8d58-7b0a-1c07-bd250025ea57
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7

HTTP/1.1 200 OK
Date: Fri, 29 Jun 2018 15:20:31 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: octta7j2xedi=8ujoasu43c56br3jtrtf59uvs6; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=bitIe26MV%2Fu04czSEb67w1U6z7ezqCuOCQVK7p%2FiGmdIBFexqdLTMklwdXgD3E3ixOzVyliqfT2s6Oo2SVqKpFtWA3wHD47ICUHp%2BOjfd9FOkSGXhskhq3%2BqCLnPz2gF; path=/owncloud; HttpOnly
Content-Security-Policy: default-src 'none';manifest-src 'self';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
Set-Cookie: octta7j2xedi=s1693pv72tjln7li6uib3bse54; path=/owncloud; HttpOnly
Set-Cookie: cookie_test=test; expires=Fri, 29-Jun-2018 16:20:31 GMT; Max-Age=3600
Content-Length: 2
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8

[]`

**Owncloud-10.0.8, using Postman; trace 2nd call:**
`GET /owncloud/index.php/apps/notes/api/v0.2/notes HTTP/1.1
Host: 192.168.178.30
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Cache-Control: no-cache
Authorization: Basic c3RlZmFuOnRlc3Q=
Postman-Token: 8905af60-8470-67e6-f2b7-efbdfee17455
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: cookie_test=test; oc_sessionPassphrase=bitIe26MV%2Fu04czSEb67w1U6z7ezqCuOCQVK7p%2FiGmdIBFexqdLTMklwdXgD3E3ixOzVyliqfT2s6Oo2SVqKpFtWA3wHD47ICUHp%2BOjfd9FOkSGXhskhq3%2BqCLnPz2gF; octta7j2xedi=s1693pv72tjln7li6uib3bse54

HTTP/1.1 200 OK
Date: Fri, 29 Jun 2018 15:20:40 GMT
Server: Apache/2.4.18 (Ubuntu)
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'none';manifest-src 'self';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
Content-Length: 229
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8

[{"modified":1530272022,"title":"Test - owncloud-10.0.8","content":"Test - owncloud-10.0.8\n","favorite":false,"id":30},{"modified":1530272134,"title":"another test note","content":"another test note\n","favorite":false,"id":42}]`

**Owncloud-10.0.8, using the mobile app; trace 1st call:**
`GET /owncloud/index.php/apps/notes/api/v0.2/notes HTTP/1.1
Authorization: Basic c3RlZmFuOnRlc3Q=
Connection: Close
User-Agent: nextcloud-notes/0.16.1 (Android)
Host: 192.168.178.30
Accept-Encoding: gzip

HTTP/1.1 200 OK
Date: Fri, 29 Jun 2018 15:41:06 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: octta7j2xedi=n8n5mi8iv9qpjbt5s0g2fujbe3; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=NZmxKtAh7qqfdSSon%2B%2FIJYINrkLvyMLj%2FZm1vqh%2FXhVN6rE88NxpOV38QI%2BhOMs35I%2F4gP5ioQ%2BGtsUAoS3s5sck%2Bv8HscdcKK06nnkIGg5VPouqGKesi7sqGzI3sc%2Bb; path=/owncloud; HttpOnly
Content-Security-Policy: default-src 'none';manifest-src 'self';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
Set-Cookie: octta7j2xedi=ojam0cm5jspdtvakb69ta75j52; path=/owncloud; HttpOnly
Set-Cookie: cookie_test=test; expires=Fri, 29-Jun-2018 16:41:06 GMT; Max-Age=3600
Content-Length: 2
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Connection: close
Content-Type: application/json; charset=utf-8

[]`

**Owncloud-10.0.8, using the mobile app; trace 2nd call:**
`GET /owncloud/index.php/apps/notes/api/v0.2/notes HTTP/1.1
Authorization: Basic c3RlZmFuOnRlc3Q=
Connection: Close
User-Agent: nextcloud-notes/0.16.1 (Android)
Host: 192.168.178.30
Accept-Encoding: gzip

HTTP/1.1 200 OK
Date: Fri, 29 Jun 2018 15:41:08 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: octta7j2xedi=ndv6do0e0us8q92o39jki4d100; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=MVifsUtY98b8vXTpRUWzEL7iln%2FKf4TA9AgUD1MtQKz5x5lIB33iyRv6gKl9Q%2FqIOce7O79Q7Obr%2FoO5W2f0%2Bi1L1INYZInMULnONWiyflXm%2FyYlY8MHNFZ4Kxmw9TGq; path=/owncloud; HttpOnly
Content-Security-Policy: default-src 'none';manifest-src 'self';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
Set-Cookie: octta7j2xedi=rgf310n0de9oclfo1v918bc9f1; path=/owncloud; HttpOnly
Set-Cookie: cookie_test=test; expires=Fri, 29-Jun-2018 16:41:08 GMT; Max-Age=3600
Content-Length: 2
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Connection: close
Content-Type: application/json; charset=utf-8

[]`

Thanks a lot for you help.
Stefan

**Comment by stefan-schilling** [comment]
Hello again,

although it would be nice, if the Notes mobile app would support OAuth2, there seems to be a bug in OC 10.0.8. I've opened a bug report there and have been informed, that there is yet another report. OC 10.0.8 seems to handle app passwords incorrectly.

Here's my one: https://central.owncloud.org/t/owncloud-10-0-8-basic-authentication-not-working-for-mobile-apps-nextcloud-notes/14344

Stefan

**Comment by stefan-schilling** [comment]
Hello,

the problem got finally solved :)
owncloud-notes has been updated to 2.0.4. Installing it (and running an owncloud update), allows this mobile app to connect to the server again.
See https://central.owncloud.org/t/owncloud-10-0-8-basic-authentication-not-working-for-mobile-apps-nextcloud-notes/14344/7 or https://github.com/owncloud/notes/releases/tag/v2.0.4.

Thanks for your help.
Stefan

**Comment by stefan-niedermann** [comment]
Great to hear and thank you for all the efforts :)
