### ISSUE TITLE
App-Setup + fail2ban: blocking access when entering the host's URL

### ISSUE THREAD

**Issue by stefan-schilling** [stefan-niedermann/nextcloud-notes#395]
Hello,

I'm using Notes on Owncloud (but that's irrelevant here), secured by a 404-check by fail2ban.
When I set up the nextcloud-notes app, the app checks the URL given by the user. 
Since no credentials have been entered at this point, the app tries to connect without it. 
The server on the other side recognizes this request and records it as an request with status 404, which is picked up by fail2ban:

1.2.3.4 - - [03/May/2018:21:53:22 +0200] "GET /status.php HTTP/1.1" 404 4427 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.1; Moto G (5S) Plus Build/NPSS26.116-26-11)"
1.2.3.4 - - [03/May/2018:21:53:22 +0200] "GET /status.php HTTP/1.1" 404 4428 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.1; Moto G (5S) Plus Build/NPSS26.116-26-11)"
1.2.3.4 - - [03/May/2018:21:53:23 +0200] "GET /o/status.php HTTP/1.1" 404 4429 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.1; Moto G (5S) Plus Build/NPSS26.116-26-11)"
1.2.3.4 - - [03/May/2018:21:53:24 +0200] "GET /ow/status.php HTTP/1.1" 404 4429 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.1; Moto G (5S) Plus Build/NPSS26.116-26-11)"
1.2.3.4 - - [03/May/2018:21:53:24 +0200] "GET /own/status.php HTTP/1.1" 404 4430 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.1; Moto G (5S) Plus Build/NPSS26.116-26-11)"
1.2.3.4 - - [03/May/2018:21:53:24 +0200] "GET /ownc/status.php HTTP/1.1" 404 4432 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.1; Moto G (5S) Plus Build/NPSS26.116-26-11)"

As a result, the connect cannot be established properly after the user entered his credentials, since his ip has been blocked by fail2ban for one hour already.

Is there any way to run this check upon the user has entered his credentials?

Thanks.

Stefan

**Comment by korelstar** [comment]
Yes, this should be optimized. We could wait a second before starting the check. If the user types something during this wait, the timer should restart.

This would eliminate most of the failing checks.

However, I think there was a plan to rewrite the login completely.

**Comment by stefan-niedermann** [comment]
This should be covered by https://github.com/stefan-niedermann/nextcloud-notes/pull/446 shouldn't it?

**Comment by stefan-schilling** [comment]
Hey Stefan,
#446 sounds good. The question remains: how long do you wait for another user's input before checking the URL? Or do you start the check upon a specific button click?
Otherwise, the problem should be reduced but not solved.

Stefan

**Comment by stefan-niedermann** [comment]
With #446 there is non check for the URL **until** the user sets the focus to elsewhere. Workflow would be:

1. User types in the complete URL
2. User is done with the URL, clicks to username to proceed
3. Request to the URL is done to check if the URL is valid
4. User starts typing username

I think it is safe to assume that the user has entered the complete URL when he clicks to another input field.

**Comment by stefan-schilling** [comment]
Yes, sounds good. Please tell me, when changes made to #446 become available and I will try them.
But it looks like this will solve this matter here.
Enjoy the weekend.
Stefan

**Comment by stefan-niedermann** [comment]
They are already in master, i will release a version on F-Droid in the next few days. Play Store has to wait a bit longer due to staged roll-out and some other circumstances.

**Comment by stefan-niedermann** [comment]
Should be fixed in the meantime.

Please be aware that this android client does officially not support ownCloud.
