### ISSUE TITLE
Crash on open after change of files on server

### ISSUE THREAD

**Issue by hammerheadlemon** [stefan-niedermann/nextcloud-notes#399]
Hi - Just started trying out this app with a new Nextcloud server. It worked well initially but then I moved all my notes from the Notes directory on the server temporarily (and took with it the .sql file I think). Reinstated the notes, but now app crashes upon opening. Cleared cache, cleared data, reinstalled several times, rebooted - same result. Not sure how to debug it other than that!

**Comment by stefan-niedermann** [comment]
Does the webinterface itself work? (Just trying to understand the issue, this repository is only for the android app, just to be sure we all understand the same).

**Comment by hammerheadlemon** [comment]
Yes, no problem. Set up server myself, no issues there. Nextcloud 13 on a Ubuntu instance. Have just disabled the Notes app and am going to reboot the server - can't do that at the moment as I'm at work.

**Comment by stefan-niedermann** [comment]
Okay, any hints in the server log that might be related to the Notes app?

And do you have the option to install a log reader like CatLog or MatLog on your Android device? Maybe we could get some hints from there what might have gone wrong...

**Comment by hammerheadlemon** [comment]
Actually - problem is back. It's something to do with QOwnNotes on the desktop. As soon as I tested adding a new file from QOwnNotes, a `notes.sqlite` and a `trash` directory appears in my `Notes` directory on the server, and the Notes Android app crashes on launch again. However, removing `notes.sqlite` and `trash` on the server does not resolve it.

**Comment by hammerheadlemon** [comment]
Fixed by ensuring all directories, local and remote, were named Notes. I'd been creating symbolic links to directories - not sure if that was helping.

**Comment by stefan-niedermann** [comment]
Okay, thanks for feedback :)
