### ISSUE TITLE
Dark Theme: Bullets are not visible

### ISSUE THREAD

**Issue by bigtreiber** [stefan-niedermann/nextcloud-notes#404]
When turning on the dark theme in nextcloud-notes the text turns "white" on dark background, but bullets (made with markdown) e. g. for lists stay black which makes them unreadable

- for example
- the bullets in this list
- will be black on dark background
- with the black theme

**Comment by natrius** [comment]
Confirm. Numbered list does work.

**Comment by dan0xii** [comment]
I have a fix for this that I should be able to push for testing in the next few days.
