### ISSUE TITLE
widget not working anymore

### ISSUE THREAD

**Issue by Perrin-the-wolf** [stefan-niedermann/nextcloud-notes#405]
Since Version 17.0 the widget is not working anymore. When adding the widget you can choose which category you want (or all)  and everything works as expected . 
After some time (half a day or so) the widget is empty and there is no way to open the Notes app or add a new note with the widget.  The app itself works.

Greetings

**Comment by stefan-niedermann** [comment]
cc @dan0xii

**Comment by tecufanujacu** [comment]
Same problem here.

**Comment by stefan-niedermann** [comment]
@dan0xii i had the same issue. After flashing a lineage update and rebooting the content was shown again (if this helps you in any way).

Providing 30,-€ bounty for a fix.

**Comment by dan0xii** [comment]
I'm having trouble replicating it. Are you all using Android 7.x? Any common actions that causes it to happen?

Logcat at the time would be handy if possible.

**Comment by Perrin-the-wolf** [comment]
I have Android 8.0 (OxygenOS 5.0.1 on oneplus 3) and I'm root (as far as it matters)

**Comment by tecufanujacu** [comment]
I have Android 6, the widget becomes empty without any specific action. I can try to get a logcat.

**Comment by stefan-niedermann** [comment]
@dan0xii did you have any success?

**Comment by dan0xii** [comment]
I've replicated it and should be able to look at it properly this weekend.

**Comment by Perrin-the-wolf** [comment]
I made a strange observation: I changed my launcher from 'nova launcher' to the original 'oneplus launcher'
Since 3 days the widget is working. Maybe this helps or it's a coincidence.

**Comment by stefan-niedermann** [comment]
Hey @dan0xii,

did you already have some time? :-)

This bug is a show stopper to roll out further releases imho.

If you are too busy, maybe you can leave here some hint what your solution would be?

Thanks :)

**Comment by dan0xii** [comment]
Hello @stefan-niedermann,

The fix I am testing is in #423. I haven't been able to replicate the fault since I made the change but I'm not 100% sure it's fixed.

**Comment by stefan-niedermann** [comment]
Great! Maybe @Perrin-the-wolf and @tecufanujacu can test if this fixes the issue?

**Comment by Perrin-the-wolf** [comment]
I would test it but I don't know how to use the Patch. I only use the version from f-droid. Can you share a link for the apk-file?

**Comment by tecufanujacu** [comment]
In these days I'm not at home and I can't compile the new apk, I'm sorry.

**Comment by dan0xii** [comment]
@Perrin-the-wolf, @tecufanujacu, would you both email me and I'll provide you with an apk download URL.

dan0xii [at] pm [dot] me.

**Comment by Perrin-the-wolf** [comment]
I have used the patched widget for 1,5 days until now and it works without problems. Since I don't know what triggers the error I can't test that situation.

**Comment by stefan-niedermann** [comment]
Thank you for testing :) Let's wait for another 2 days and then merge it into master :)

**Comment by tecufanujacu** [comment]
Yes, I can confirm that with the new version the widget works without problems.

**Comment by stefan-niedermann** [comment]
Great. I will release a new version today which should be on F-Droid in 2-3 days. Play Store will take some more time until the new version will be rolled out to everyone.

Thank you for testing and thanks @dan0xii - i will send you the promised bounty :)

**Comment by Perrin-the-wolf** [comment]
So, after 3 weeks it's still working as expected :-)
I would like to support the project, do you have an paypal account?

**Comment by stefan-niedermann** [comment]
Sure: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=K7HVLE6J7SXXA

I will send the money to @dan0xii who fixed this bug :)

**Comment by tecufanujacu** [comment]
With last update the problem has returned.

**Comment by Perrin-the-wolf** [comment]
sorry for the delay, I send the money today and you can pass it on to dan0xii

**Comment by stefan-niedermann** [comment]
no problem :) thank you, i will send it to @dan0xii in a few days.
