### ISSUE TITLE
Question regarding .txt as the default filename extension

### ISSUE THREAD

**Issue by nfode** [stefan-niedermann/nextcloud-notes#407]
Hello I'd like to use the app for the notes but I dislike the standard `.txt` extensions since I use `.md` everywhere. Is there are reason for the current situation? I searched for an issue regarding my question but found no answer.

Is there anything against implementing a setting option which enables the possibility to change the default extension?

I am looking forward to getting some feedback!

**Comment by stefan-niedermann** [comment]
Yeah, it's in the server repo ;-)

https://github.com/nextcloud/notes/issues/24
