### ISSUE TITLE
Save note when hiding application

### ISSUE THREAD

**Issue by pruje** [stefan-niedermann/nextcloud-notes#408]
When I edit a note and push the Home button quickly after a modification, the note is not saved and my changes are lost.
It would be great if the application could save the note when the app looses focus.

For example, the [ColorNote](https://play.google.com/store/apps/details?id=com.socialnmobile.dictapps.notepad.color.note) app does that (with a small "Saved" notification) and it's really convenient.

Thanks and keep up the great work!

**Comment by korelstar** [comment]
You're right. I thought we had this already, but I reproduced this problem. A fix should be easy. I hope that I find time to provide it, soon.

**Comment by stefan-niedermann** [comment]
> I thought we had this already

I also think we save on `onPause()` - isn't that called, when pressing the home button?

**Comment by korelstar** [comment]
No, strangely not. Did a fix in #409. :smile:

**Comment by pruje** [comment]
Thank you guys! 👍
