### ISSUE TITLE
Possible to stop renaming files?

### ISSUE THREAD

**Issue by ntnsndr** [stefan-niedermann/nextcloud-notes#415]
I've long kept my notes in .md files in my NextCloud /Notes directory, and I've started trying to use this app to manage them. It seems to work fairly nicely, but it keeps renaming the files to whatever the text of the first line is. I'd rather not use the first line in all those files as the title of the file (and I can't even see a way of doing that as some kind of hidden comment). Is there a way to get the app to stop changing the filenames? Before it changes them, it works as I would like (for instance, displaying a file called Readme.md as "Readme").

Thanks for your work on this.

**Comment by stefan-niedermann** [comment]
Hi,

there have been lots of issues about this topic. Please contine the discussion at the server repo in this issue: https://github.com/nextcloud/notes/issues/190

Regards
