### ISSUE TITLE
[Feature request] Realtime markdown formatting: "Mark text like"

### ISSUE THREAD

**Issue by biva** [stefan-niedermann/nextcloud-notes#425]
"Mark Text is a realtime preview editor text styles and formatting update automatically as you type". This is an open source project:
- https://marktext.github.io/website/
- https://github.com/marktext/marktext

I'd love to see this available in Nextcloud Notes: would it be possible on the Android app?

Question also asked for the We UI here: https://github.com/nextcloud/notes/issues/214

**Comment by stefan-niedermann** [comment]
This is a markdown rendering library written in javascript, isn't it?

The android native client will only use native or java code to render markdown for performance and other reasons.

Maybe the Webinterface will switch, but this os out of my scope.

**Comment by stefan-niedermann** [comment]
Please read my last comment. This repository is for the android client and does not use any web technology for several reasons.

**Comment by biva** [comment]
Sorry, I was not skilled enough to understand the nuance.
