### ISSUE TITLE
Linked lists have huge spacing between bullet points

### ISSUE THREAD

**Issue by wallyreport** [stefan-niedermann/nextcloud-notes#429]
Linked lists seem to be double spaced.

**Comment by stefan-niedermann** [comment]
Can you please post a screenshot? I did not recognize the space as too large.

**Comment by stefan-niedermann** [comment]
@wallyreport can you please report a screenshot? I don't get what you mean. Are you talking about edit mode or view mode?

**Comment by stefan-niedermann** [comment]
Please reopen if this still bappens with v0.20.0 or higher and please add screenshots.
