### ISSUE TITLE
Make connection process easier by using Nextcloud-Account-Importer

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#43]
Currently on first run, you need to manually put in your credentials to the app. However it’s very likely that you already have the Nextcloud app installed and hence the account can be reused there. This will dramatically ease the first run experience.

@David-Development of the Nextcloud News app for Android built an awesome library for that: https://github.com/David-Development/ownCloud-Account-Importer

**Comment by stefan-niedermann** [comment]
Closing in favor of #418.
