### ISSUE TITLE
Crash when selecting

### ISSUE THREAD

**Issue by SqueeZen** [stefan-niedermann/nextcloud-notes#431]
Hello,

For several version of this great app, when I make a long press to select text, the two cursors appear at the beginning of the note. When I want to extend the selection, the application systematically crashes (Unfortunately, "Notes" Has Stopped ...)

I'm using a Xperia Z3C (D5803) with the latest official ROM available (Android 6.0.1).

Thank you in advance and have a good summer!

**Comment by stefan-niedermann** [comment]
Hmm, i am not able to reproduce this issue. Is anyone else able to reproduce this problem? @korelstar @dan0xii ?

@SqueeZen can you reproduce this issue with another device or a virtual machine? Maybe you can provide some Logcat information to investigate this further?

**Comment by SqueeZen** [comment]
Yes, I can reproduce it with another device, but it is the same model (Z3 Compact) ... :\
How can I try with a virtual machine ? I don't know how to do logcat, can you tell me?

**Comment by korelstar** [comment]
I can't reproduce this. Does this happen with every note or a specific only?

**Comment by SqueeZen** [comment]
This issue is now solved since last update ! Congratulations !

**Comment by stefan-niedermann** [comment]
Great to hear :)

Please feel free to reopen of it still occurs.

**Comment by SqueeZen** [comment]
Hello,
The issue occurring again since the last release.
