### ISSUE TITLE
Checkboxes: wrapped lines have checkbox for every line

### ISSUE THREAD

**Issue by brenthuisman** [stefan-niedermann/nextcloud-notes#435]
GFM-style checkboxes have a bug when the text of the bullet in question has to be line-wrapped: the app will show checkboxes for every line on screen, instead of per bullet (as defined in the file).

**Comment by stefan-niedermann** [comment]
#294

**Comment by stefan-niedermann** [comment]
https://github.com/yydcdut/RxMarkdown/issues/42
