### ISSUE TITLE
Alternate Headers no longer displayed

### ISSUE THREAD

**Issue by mrmotallebi** [stefan-niedermann/nextcloud-notes#438]
On v 0.18.0 from F-Droid.

Headers in the alternate format such as 
```
Header1
========
```
and
```
Header2
----
```
would display correctly on v.0.17.0 but are no longer rendered in this version. Can you please investigate the cause?

**Comment by stefan-niedermann** [comment]
Confirmed.

**Comment by stefan-niedermann** [comment]
Has to be fixed upstream. I opened an issue: https://github.com/yydcdut/RxMarkdown/issues/56
