### ISSUE TITLE
Allow Rendering of any markdown file

### ISSUE THREAD

**Issue by returntrip** [stefan-niedermann/nextcloud-notes#439]
I apologise if this request has been already submitted but I could not find a duplicate.

Would it be possible to allow Notes to open markdown file stored locally on the phone and files stored in other Nextcloud directories? Or at least could you add Notes to the android "Open with" picker?  

Thanks for the great app!!!

**Comment by stefan-niedermann** [comment]
Maybe we can add a handler to open Markdown files, but instead of providing the full edit stack, simply use the view mode and show a button "Import to Nextcloud Notes" or something like this?

**Comment by stefan-niedermann** [comment]
Another option would be to directly open the file in the Create Note-mode, just like one is sharing text into the Notes app. This would allow immediately creation but it might be confusing for the user that he is actually working with the copy in Nextcloud Notes instead of the file.

@jancborchardt Opinions?

**Comment by jancborchardt** [comment]
Not sure how this is normally done on Android, especially as we are connected to a sync service and people might indeed not expect a random Markdown file to be synced to their notes.

But it would be nice if the Notes app could simply open all kinds of plaintext files (not only Markdown) and make it possible to read or even edit them. If that is only possible by syncing them, I would say that’s fine? If they are opened and edited they probably are reasonably important, and they can also be removed afterwards.

**Comment by stefan-niedermann** [comment]
This issue has been fixed in version `2.7.0`.
