### ISSUE TITLE
Note list widget star placement

### ISSUE THREAD

**Issue by dan0xii** [stefan-niedermann/nextcloud-notes#443]
I'm doing some work on the note list widget and noticed that in master the star is still positioned on the left and slightly out of alignment, meaning if a note isn't starred there is some dead space to the left of each entry.

I know we talked about positioning left or right in #273 but can't remember what was decided. Did I forget to move it?

From that thread: 
> tl;dr put the ★ on the right side

**Comment by stefan-niedermann** [comment]
Yeah, @jancborchardt and i had some discussion at the hackweek 2018 in Stuttgart. We decided to ultimately move it to the left side to be equal to the files app, where it also is on the left side. Also dead space is ok for now.

<sub>I am at the Nextcloud Conf starting tomorrow in Berlin and i will discuss this topic again. I personally can imagine a final solution ala: "Always show a gray star and if it is marked as favorite, show a yellow star" - this way we don't have dead space and it does not look off. But as i said: I will discuss this again.</sub>

**Comment by jancborchardt** [comment]
Yeah, either is fine: whitespace, or grey stars. But the stars should be on the left to be the same as in the app view and in files too. :)
