### ISSUE TITLE
Issue when rendering "---" markdown as a line while editing

### ISSUE THREAD

**Issue by NicolasWeb** [stefan-niedermann/nextcloud-notes#469]
Since v 0.21.0, when writing
`[Enter]
---`

The grey line isn't drawn. You need to close and reopen the note to see it.
It was working well in the previous version 0.20.0

**Comment by stefan-niedermann** [comment]
Hi,

i have opened an issue upstream: https://github.com/yydcdut/RxMarkdown/issues/59#issuecomment-418408262

This has to be fixed there, therefore closing this issue.

If you could provide a screenshot or a video this might help to solve this issue faster.

Regards

**Comment by NicolasWeb** [comment]
> If you could provide a screenshot or a video this might help to solve this issue faster.

Done in [59#issuecomment-418545329](https://github.com/yydcdut/RxMarkdown/issues/59#issuecomment-418545329)
