### ISSUE TITLE
Ask before delete a note

### ISSUE THREAD

**Issue by kzar79** [stefan-niedermann/nextcloud-notes#470]
It can happen to mistakenly delete a note (a casual touch that is interpreted as a swipe - actually it happens quite a lot to me...).

The solution is simple: before executing the deletion (line 423 of NotesListViewActivity.java), the app should ask for confirmation. 

If an additional tap is considered too troublesome for some users, this behavior could be enabled/disabled adding also a preference.

https://github.com/stefan-niedermann/nextcloud-notes/blob/7766f6504323b3e12149b0710d752c231726d83f/app/src/main/java/it/niedermann/owncloud/notes/android/activity/NotesListViewActivity.java#L423

**Comment by schaarsc** [comment]
relates to #238

**Comment by stefan-niedermann** [comment]
Yes, we should not ask for confirmation. There are simple ways to undo an accidential deletion: A toast to undo, a link to the trashbin from where one can easily restore a deleted note.
