### ISSUE TITLE
widget not working anymore

### ISSUE THREAD

**Issue by tecufanujacu** [stefan-niedermann/nextcloud-notes#476]
Since Version 21.0 the widget is not working anymore as already happened in the issue #405.
The last working version is the 20.0.

**Comment by stefan-niedermann** [comment]
Can you please retest with 0.22.0? should be already available at f-droid and on play store.

**Comment by stefan-niedermann** [comment]
Please wait for 0.22.2 which will contain the fix.

**Comment by tecufanujacu** [comment]
Installed the version 0.22.2, the problem persists.
