### ISSUE TITLE
List widget freezes

### ISSUE THREAD

**Issue by Phaet** [stefan-niedermann/nextcloud-notes#485]
The list widget freezes regularly after a short time (on Galaxy S9). Has to be removed and placed anew each time.

**Comment by dan0xii** [comment]
What version of the app are you using and on what version of Android?

**Comment by Phaet** [comment]
It's v022.2 on Android 8.0.0. Sorry, forgot to mention.

**Comment by dan0xii** [comment]
If you have the ability to build the source code I'd ask that you test out the b5ca773e21c579aac0cb50310b4cd05c68bf0368 branch (master). It contains improvements to the widget code.
