### ISSUE TITLE
Add the ability to change the category of notes displayed in the widget

### ISSUE THREAD

**Issue by darhma** [stefan-niedermann/nextcloud-notes#490]
Currently when you add the widget with the list of notes you are asked the category to show and you can not change it, you could make it so that pressing on the title of the widget instead of opening the application you can select and change the category on the fly and allow you to open the application by pressing on the icon on the left of the title?

**Comment by dan0xii** [comment]
What would be the use of this feature, to save time?

**Comment by dan0xii** [comment]
I feel as though the effort involved for the user to just re-create the widget with a different category is not worth implementing this feature.

**Comment by stefan-niedermann** [comment]
Agree.
