### ISSUE TITLE
Can't find where notes are saved in phone storage

### ISSUE THREAD

**Issue by polkillas** [stefan-niedermann/nextcloud-notes#494]
I have a little problem with this Notes app, which otherwise works fine. I'd like to find where notes are stored in the phone, as I had a problem with my Nextcloud server and now I have a set of unsynced notes in the phone, and I'd like not to lose the changes I made to these notes. So, where are notes saved? Are they files in a folder or it is a database?

**Android version:** LineageOS 14.1 (Android 7.1.2)

**Device**: Xiaomi Mi4c

**System language**: Spanish

**App version:** 0.22.3

**App source:** F-Droid

**Steps to reproduce:**
  1. Search the app folder.
  2. Notes can't be found in any folder.

**Comment by stefan-niedermann** [comment]
Hi, they are not saved as files but in a sqlite database for performance reasons.

You can check if you have synced them with the files app or, sadly, only use "share" on each single note to export the content to another app.
