### ISSUE TITLE
changing password does not actviate "connect" button

### ISSUE THREAD

**Issue by denics** [stefan-niedermann/nextcloud-notes#495]
Hi @all,
I really like note, it makes me feel secure :)

lately I changed my password on my nextcloud server and I had to change it (obviously) on the application. I have discovered that when I go to change my password, I have to modify the server name to activate the connect button.

thanks

**Comment by stefan-niedermann** [comment]
This should be obsolete with the now released version 1.0.0 which uses the new weblogin flow.

Please feel free to reopen this issue if it is still a problem :)
