### ISSUE TITLE
Widget do not update

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#496]
When changing a note, the widget do not update the displayed content. @dan0xii

Known devices:

Android 7.1.1, Nova Launcher Prime 5.5.4 and Nextcloud Notes 0.22.3 on a NextBit Robin

Android 9, Nova Launcher Prime 5.5.4 and Nextcloud Notes 0.22.3 on a Google Pixel

**Comment by hemker** [comment]
Same here:
Device Android 7.1.2 LineageOS, Nextcloud Notes 0.22.3 on Sony Z3 Compact.
Interesting thing is that the widget is updated after I performed a hot reboot.

**Comment by KopfKrieg** [comment]
Same here with LineageOS 15.1 (Android 8.1.0), default Trebuchet launcher, and Nextcloud Notes v0.22.3.

**Comment by hemker** [comment]
@KopfKrieg activate developer settings, then the third entry is extended reboot

**Comment by 05nelsonm** [comment]
Having the same issue on Android (6.0.1).

**Comment by Kim-San** [comment]
I have the same issue on Galaxy S7, Android 8.0.0, Nextcloud Notes 0.2.2.3.

**Comment by iamtpage** [comment]
Same issue on both my phones with the latest version of notes

**Comment by kukukk** [comment]
Same issue on XZ1 Compact with Android 8.0.0 using the latest version from F-droid.
Newly created/deleted notes are also not appearing/disappearing in Note list widget.

**Comment by kukukk** [comment]
Hi,
I tested the 496ud branch and the it seems to fix the widget update problem for both widgets: Note list and Single note.

**Comment by stefan-niedermann** [comment]
Also tested and works :) Thank you very much @dan0xii as always :)
