### ISSUE TITLE
[Bug] Android Widget, click + for new note, hit back, create empty note - breaks desktop sync

### ISSUE THREAD

**Issue by BloodyIron** [stefan-niedermann/nextcloud-notes#499]
I use notes very regularly both on my desktop, laptop and my phone.

I have the note list widget on my android phone, and just now I hit the "+" button by mistake, then hit back to cancel, and it created a "new note" that was empty. Then my desktop sync client could not complete sync since it was empty.

Pretty sure this is a bug.

**Comment by stefan-niedermann** [comment]
Not reproducable. Also i am pretty sure it's a bug of your Desktop app if it has problems with an empty file.

You can check the note in the Web interface (files app). If it is a simple empty file, its no bug from my point of few.

But as i stated; Hitting back button does not create an empty note in version 1.0.0.

**Comment by BloodyIron** [comment]
If I observe it again I'll try to pay close attention to how it happened, but I haven't seen this in a good while. :)
