### ISSUE TITLE
Syncronization settings

### ISSUE THREAD

**Issue by chorus12** [stefan-niedermann/nextcloud-notes#507]
Good day to all.
Please make a settings for automatic and manual sync for the notes. The issue with that is that at the moment it is not clear at all how often periodic sync runs - and whenever the data connection is off you got an annoying notification with bunch of java code that sync is failing. Besides that this drains the battery. Please make a settings that control sync recurrence and provide pure manual sync mode.

Regards!

**Comment by korelstar** [comment]
Sounds reasonable, but I think we should fix #161 before doing that.

**Comment by stefan-niedermann** [comment]
Synchronization is nothing a user should have to handle.

Sync happens on displaying the list view (where one obviously wants to see the latest notes) and whenever a change has been done.

Instead let's change the behavior of the "sync not possible"-toast. Maybe we show it too often - Being offline is not an error state.
