### ISSUE TITLE
Search by tag

### ISSUE THREAD

**Issue by jjisnow** [stefan-niedermann/nextcloud-notes#510]
It would be nice to be able to list notes by their tags similar to the current folders and similar to the qownnotes native apps

**Comment by stefan-niedermann** [comment]
Each category is displayed in the left sidebar. Clicking on one of them show only notes from within this category. Isn't that exactly what you are requesting?

**Comment by frederiiiic** [comment]
Maybe @jjisnow is thinking about a tag, like key-words or hashtag system to mark notes with.

I agree with him, i've already thought about that.

**Comment by stefan-niedermann** [comment]
Ah, i understand. If the server app supports tags/labels, the android app will also implement support.

There was even a discussion a while ago, but since the Notes app is designed to be usable without a database and only with files (e.g. the default sync client), it has not been implemented.

**Comment by stefan-niedermann** [comment]
Closing this for now. I will notice, if the server app implements this and add support if it is possible :)
