### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by bisherbas** [stefan-niedermann/nextcloud-notes#511]
V0.22.4

OnePlus 5T

OxygenOS 9.0.1

Error: Synchronization failed no network connection

Connected to home wifi. Works fine.
Double checked Nextcloud credentials.
Double checked Davx5 settings. Looks good.
Calendar and tasks are synced properly.

Any suggestions?

**Comment by stefan-niedermann** [comment]
- Did the initial login work?
- Does sync work in general via mobile data connection?
- Do you use a self signed certificate?

**Comment by bisherbas** [comment]
@stefan-niedermann 

Yes.
Yes.
No.

I was just able to fix (perhaps temporarily) the problem by clearing the app from the recent apps clearing the app cache.

**Comment by stefan-niedermann** [comment]
so the sync did work via mobile data but **not** via wi-fi (before you cleared the app cache)?

i guess your home wi-fi is a standard wi-fi without any TOS-check-page or some special stuff?

**Comment by bisherbas** [comment]
Sorry for the confusion. I meant to say that when it was working before the first error message I encountered, the app was functional both on LTE and WiFi. After the error, the app did not work in either network.

Clearing the app cache appears to have solved the problem everywhere.

**Comment by stefan-niedermann** [comment]
Okay, thank you for the reporting, but i do not really know how to start because this issue seems not to be reproducable.

I'd suggest to simply reopen the issue if it occurs again - ideally with some steps to reproduce...

Regards

**Comment by fazlerabbi37** [comment]
So it would seem I am facing the same problem. :unamused: 

Step to reproduce:
1. open app and do some edit offline
2. connect to Wi-Fi
3. pull down to sync

Expected result: 
should perform sync successfully

Actual result:
gives an "Error: Synchronization failed no network connection" message

App version: V0.25.0
Phone: Xiaomi redmi note 6 pro
OS: MIUI Global 10.3.5

---

@stefan-niedermann maybe consider re-opening the issue?

**Comment by stefan-niedermann** [comment]
Can you provide some Logcat? otherwise i do not know how i should fix this issue, since i can't reproduce it on 2 physical devices and 3 virtual devices with various configurations...

**Comment by fazlerabbi37** [comment]
@stefan-niedermann here is the logcat [link](https://hastebin.com/unamohepiw.pl). Hope it helps!
