### ISSUE TITLE
'Share via ...' > 'New Note' Android function gives the error message "Notes has stopped" and nothing is shared

### ISSUE THREAD

**Issue by bartatgithub** [stefan-niedermann/nextcloud-notes#513]
Hi 
Thanks for the Notes app, that has worked smooth until now: 
I lost all notes after install version 0.22.4 and changing server. 
But no import possibility from backup? 

So, tried to import my backups in text (.txt) format thru the 'Share via ...' > 'New Note' (with the Note icon) Android function but that gives the error message "Notes has stopped" and nothing is shared. 
Other than that Notes version 0.22.4 works and sync's correct to the server. 

**Android version:** 7.1.2
**Device**: HTC 10
**System language**: English
**App version:** v0.22.4

**App source:** F-Droid

**Steps to reproduce:**
  1. open Filemanager
  2. select a note text file (.txt) from a backup
  3. Share via ...
  4. 'New Note' (with the Note icon)
  5. error message "Notes has stopped" 
  6. select 'Open app again'
  7. Note app opens but nothing shared

**Comment by stefan-niedermann** [comment]
Are the notes still accessible via the web interface? If not: did you have a look into the trashbin?

**Comment by bartatgithub** [comment]
No notes in the web interface or trash. 
Trying now to put a backup back. 
Will it work when i put simple back the notes in the Notes folder? 
Or will the v number at the end of the file name be a problem?

**Comment by stefan-niedermann** [comment]
should work - @korelstar does the notes app recognize new files in the folder?

**Comment by bartatgithub** [comment]
Ok, notes are back! 
I have put a backup with all .txt files back and taken out all .v numbers extensions. 
But strange in 3 of the notes the text is missing, this notes are complete empty but show the title.

**Comment by bartatgithub** [comment]
Yes, the notes app recognises new files in the folder, but not in the sub folders. 
The sub folders i have put manually back. All notes are back except the 3 empty ones. 

The above problem that text (.txt) files thru the 'Share via ...' > 'New Note' (with the Note icon) Android function are giving still the error message "Notes has stopped" and nothing is shared, is still there.

**Comment by stefan-niedermann** [comment]
Did you originallycreate your notes with the webinterface or android app? Or did you use a third party tool and import them into the Nextcloud app?

**Comment by korelstar** [comment]
Putting text files in subdirectories should work, too. If you do this directly on the file system, you have to run `occ files:scan` after that.

Regarding your problem with the share functionality in the Android app: please connect your phone to a computer and check the logs from adb / logcat for exceptions when trying to share.

**Comment by stefan-niedermann** [comment]
Not reproducable without any logs... please reopen when you can provide some logs like korelstar suggested, so we can solve the problem :)
