### ISSUE TITLE
Network error when server is local

### ISSUE THREAD

**Issue by adamsson6** [stefan-niedermann/nextcloud-notes#514]
Hello, I discovered a strange behavior. I'm using a nextcloud server on a local network, and a server IN the phone itself (127.0.0.1), and when the phone have no internet connexion, the nextcloud note app (only this app) says that there is no network even if the server is pingable. The other nextcloud apps works correctly but the note app still trying to get an internet network to connect.

Is it possible to correct this please ? Thank you for your work !

**Comment by stefan-niedermann** [comment]
wow, what a strange edge case. currently we only sync if internet connection is available to avoid errors and save battery capacity.

I don't think that pinging an address each and every time when we want to sync (or login) to check if it is available is a good solution.

But i can imagine to add a white list for `localhost` and `127.0.0.1`. So basically the logic would be "IF InternetConnectionAvailable OR localhost THEN sync".

@adamsson6 Pull Requests are welcome :)

**Comment by adamsson6** [comment]
Yes I know it's very strange but it works !
If you could add something to allow me to use my 127.0.0.1 server it would be great, thanks. I'm gonna do a pull request.

**Comment by adamsson6** [comment]
Is it possible for example to add a whitelist depending on the IP address of the given server name when we configure the account ?
It would allow LAN connexion and 127.0.0.1 connexion.

**Comment by stefan-niedermann** [comment]
No, i think a configuration surface for the users will be a overkill. There are reserved IP ranges for local area networks (e.g. 192.168.*.*). Also localhost and 127.0.0.1 are valid.

This list should be hard coded or automatically detected, but as i said: there is **no** gui change necessairy.

A pull request is welcome, you can also set a bounty to this issue, so maybe other volunteers might solve this for you. It is not very high on my own priority list.

**Comment by stefan-niedermann** [comment]
happy to hear that :)
