### ISSUE TITLE
support nested tags / subfolders

### ISSUE THREAD

**Issue by schiessle** [stefan-niedermann/nextcloud-notes#518]
It would be great if the app would support nested tags / subfolders. On the desktop I use QOwnNotes and there I can create random hierachies. For example I can create something like Notes/projectA/foo/bar.md

The note bar.md already shows up in the Android app and the tag is set to "projectA/foo". I can also create this nested hierachies on Android by setting a new tag "a/b". So it is already supported to some extend. The main issue for me, the sidebar only shows the top level folders as tags and not the sub folders. It would be great if I could see and select the the subfolder (nested tags) in the sidebar as well.

**Comment by stefan-niedermann** [comment]
Would you expect them to bee at the same indention like

```
Test
Test/Foo
Test/Bar
Fuzz
```

or with some left padding like

```
Test
    Foo
    Bar
Fuzz
```

The first one is ugly as hell, but the second does not scale very good if the nested hierarchies are getting deeper....

**Comment by schiessle** [comment]
good question, I'm also not sure what would be the best solution. Initially I thought a flat list like this would be OK:

```
Test
Test/Foo
Test/Bar
Fuzz
`````

But I agree that it looks ugly and probably also doesn't really scale.

Maybe something like that you start with:

````
Test [..]
Fuzz
````

Clicking on [..] will expand to:

````
Test [..]
 Foo
 Bar
Fuzz
````

and so on... (of course [..] should be a nice icon which indicates that you can expand/collapse it) ?

**Comment by schiessle** [comment]
The folder icons don't have a plus here and they also don't expand if I click on them they just show all notes with the tag (and sub tags), although in the notes list there is some kind of headline for each subfolder, is this what you are referring to? I use v0.22.4 from fdroid

**Comment by korelstar** [comment]
No, I refer to the navigation. Here are some screenshots (the design of the notes list is outdated, but the navigation is up-to-date):
https://github.com/stefan-niedermann/nextcloud-notes/pull/275#issuecomment-339957534

The plus should show up if there is more than one subcategory.

**Comment by korelstar** [comment]
I've limited this to two levels of categories in order to reduce complexity. But I'm fine with unlimited expandability. I think we should do some design case studies in order to find the best layout for this. Maybe some designers could help...

**Comment by schiessle** [comment]
@korelstar this would be great... @jancborchardt maybe you have some idea how this could look like?

**Comment by jancborchardt** [comment]
Personally I think the design of Notes should stay simple. :) QOwnNotes is not a good benchmark as they are unfortunately doing their own, quite complicated thing.

So I’m not the best person to ask here. But if there is any kind of hierarchy, it should use the same method we use in the navigation of Files, News etc. – ideally working towards a Vue component: https://github.com/nextcloud/nextcloud-vue cc @skjnldsv @juliushaertl

**Comment by juliushaertl** [comment]
The main issue is that nested hierarchy always will break at some level of indentation, because our space in the sidebar is limited. So we either need to limit the depth of nesting or flatten the hierarchy out for example by moving subfolders to the same Hirarchy

```
  Level 1/
  	Level2/
  	Level2/Test/
  	Level2/Other/
```

**Comment by stefan-niedermann** [comment]
>  ideally working towards a Vue component

This issue is about the android client :) but sure, i think the navigation in the android app and the navigation in the web sidebar could use the same pattern.

**Comment by stefan-niedermann** [comment]
I am closing this because

1. the original issue has been solved (technically the android notes app supports unlimited depth of nested tag hierarchies)
2. the current solution works fine for most people. I think it's a primary goal to support first-level tags in this app optimally; deep-level-hierarchies should work at least technically, but they are no hot spot. So if anyone has an actual *issue*, one can provide a concrete proposal about **what** to change **how** and **which problem** will be solved with the change.
