### ISSUE TITLE
Synchronize on WiFi only 

### ISSUE THREAD

**Issue by blkqi** [stefan-niedermann/nextcloud-notes#519]
An option to only synchronize when a device is on WiFi and optionally filter for only specific SSIDs (or similar) is required for users who connect to their Nextcloud instance using a local network address.

The consequence of not having this is unecessary synchronization attempts and the resulting error message toasts.

**Comment by stefan-niedermann** [comment]
Will be included within the next release.

**Comment by blkqi** [comment]
Thanks @stefan-niedermann !
