### ISSUE TITLE
App should register as notes app

### ISSUE THREAD

**Issue by quthla** [stefan-niedermann/nextcloud-notes#520]
I tried adding a note with Google Assistant but it won't show this app.

It shows other apps like SimpleNote and https://github.com/dmfs/opentasks so maybe there's something missing in the manifest for this to work.

**Comment by stefan-niedermann** [comment]
Yes, definitely! Personally i do not use any Google Services, so didn't notice it yet.

**Comment by stefan-niedermann** [comment]
@quthla i implemented the requested `intent-filter` in this branch: https://github.com/stefan-niedermann/nextcloud-notes/pull/521

can you please test and confirm whether this works for you?

**Comment by quthla** [comment]
Sure can you provide me with a build? Would be easier than me having to spin up Android Studio and build it myself

**Comment by stefan-niedermann** [comment]
Sure: https://nextcloud.niedermann.it/index.php/s/sns2QQq3qXcD9f2

Please note, that this is a debug build which should be used for testing purposes only.

**Comment by quthla** [comment]
I'm not sure why but somehow I now get the message no notes app installed. Might be related to a Google update. Can't really test now

**Comment by stefan-niedermann** [comment]
Do you get the message only using Nextcloud Notes or also with Simple Notes? There might be something wrong with my implementation, too.

**Comment by quthla** [comment]
No it won't let me choose any notes app anymore

**Comment by quthla** [comment]
For some reason it works now after plenty more failures.

It'll open the save note activity but not receive the text from Assistant.

**Comment by stefan-niedermann** [comment]
As i previously mentioned, i do not use any Google service (not even have it installed on my phone) - therefore i need you some more tests to do:

https://nextcloud.niedermann.it/index.php/s/sns2QQq3qXcD9f2

Now the text should be received

**Comment by quthla** [comment]
Can confirm it's working now

**Comment by stefan-niedermann** [comment]
Glad to hear that :)
