### ISSUE TITLE
Overflow-menu contains "search" when searchview is open 🔎

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#522]
This is a follow-up to #400, detected by @korelstar :

On my phone, I have some weird behavior regarding the menu items: By default, the search menu item is shown in the ActionBar. If I start a search and type some chars, the search menu item is not shown anymore (which is intended). However, if I use the three-dot-menu then, the search is still active and the search menu item is shown in the pull down menu. After closing and reopening the three-dot-menu again, the search menu item isn't shown anymore. This behavior is reproducible (Android 6.0.1).

**Comment by dan0xii** [comment]
I think this is gone now that the app has had a redesign. I can't reproduce it on 6.0.

**Comment by stefan-niedermann** [comment]
No, it's still present. It's about the in-note-search

**Comment by dan0xii** [comment]
OK, I see. It only happens when you're in View mode not Edit. I'll see if I can figure out what's going on.
