### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by fazlerabbi37** [stefan-niedermann/nextcloud-notes#531]
Hi, I use this app from F-Droid and whenever a new version is released, my natural tendency is to check the changelog so that I can see the updates. Unfortunately, for Notes I can't do that and the only way to know the updates is to go through the commites which is not really a effective way. It would be great if you could find some time to provide a changelog.

Thanks for this awesome app anyway!

**Comment by stefan-niedermann** [comment]
Changelog is written for each new version as a comment on the tag: https://github.com/stefan-niedermann/nextcloud-notes/releases

For future releases there will also be changelogs in the fastlane folder :)

**Comment by fazlerabbi37** [comment]
Did not notice the logs attached with the releases. Don't you think it would be more beneficial to add a separate changelog file specially when F-Droid has a changelog link-holder on Links section?

**Comment by stefan-niedermann** [comment]
Oh! It used to be there, but was removed by F-Droid-Team. I will talk to them if they can readd it.

**Comment by fazlerabbi37** [comment]
@stefan-niedermann thank you!

**Comment by fazlerabbi37** [comment]
@stefan-niedermann I still can't see the changelog. They are not in the release comment and definitely not in a separate file. The changelog link in F-Droid goes to release on GitHub but as there is no comment with those release there is no way to see it.

**Comment by stefan-niedermann** [comment]
Yes there is, you have to press the 3-dots-menu:

![IMG_20200120_081857_497](https://user-images.githubusercontent.com/4741199/72706127-8c4bda00-3b5d-11ea-95c1-6c17dffb519f.jpg)

**Comment by stefan-niedermann** [comment]
You can also find the changelogs here (fastlane , where f-droid gets its information from): https://github.com/stefan-niedermann/nextcloud-notes/tree/master/fastlane/metadata/android/en-US/changelogs

But the files have to be named for the version code, not the version. Finding news on the Release-section is easier therfore.

**Comment by fazlerabbi37** [comment]
Oh, I see that now! Must have forgotten it. I asked it again because it seems FastHub-Libre say's `No Body` when  I click on the release tag. :unamused:

**Comment by stefan-niedermann** [comment]
Github distinguishes between Releases and the usual git Tags, i only use tags :)

**Comment by Go-rom** [comment]
Hello @stefan-niedermann 

Changelogs seem not to be published anymore since 4.x branch.
Have they been moved elsewhere please ?

Thank you !

ps : didn't want to open a ticket for that kind of question

**Comment by TheCrowned** [comment]
Same problem here, no way to see changes

![Screenshot_Fennec_20230715-132129](https://github.com/nextcloud/notes-android/assets/7880569/59519779-c755-4172-8084-6aed5a8f3527)

**Comment by scollovati** [comment]
What about putting a short and amended version under the `/fastlane` folder? This may be useful for understanding the key changes, not always easily readable from a long changelog like this one: https://github.com/nextcloud/notes-android/releases/tag/4.3.0
