### ISSUE TITLE
Missing translation, replaced by filler text

### ISSUE THREAD

**Issue by pludi** [stefan-niedermann/nextcloud-notes#536]
Notes Version:  0.24.0, installed from F-Droid
Android Version: 8.1.0

In the de_AT locale all translatable strings are replaced by "Benötigt kein Übersetzung. Für Android wird nur die formelle Übersetzung verwendet (de_DE)"

See https://github.com/nextcloud/news-android/issues/692 for similar behaviour.

**Comment by stefan-niedermann** [comment]
Thanks, will have a look :)

Did this happen in earlier versions?

**Comment by stefan-niedermann** [comment]
Since https://github.com/stefan-niedermann/nextcloud-notes/commit/4115da63bbea9e80f60c611aefc52982cfa53c58#diff-cdca861e65ab0caf0dac48368b3fa2a6

**Comment by stefan-niedermann** [comment]
cc @MorrisJobke

**Comment by korelstar** [comment]
We have to copy these changes:

https://github.com/nextcloud/docker-ci/commit/9c6da911e6e5edcd4edfb1924493cbfe82e8c58b

to

https://github.com/nextcloud/docker-ci/blob/e7d721a5f91840e1f213f629c4e56d22f2a7ac64/translations/handleExternalBranchedAndroidTranslations.sh

I can do a PR for that, later.

**Comment by MorrisJobke** [comment]
@stefan-niedermann This is made on purpose by the German translation team on transifex because it was decided so for Android. I guess they adopted for all android apps. Let me add the script that was linked by @korelstar to your repo as well.

**Comment by MorrisJobke** [comment]
Fixed via https://github.com/nextcloud/docker-ci/commit/3976fcca3ed5a178082ee6afa82e428557d36732 - once docker hub has built the image I will retrigger the sync run.

**Comment by MorrisJobke** [comment]
And there it is: https://github.com/stefan-niedermann/nextcloud-notes/pull/534/files

Now it should work like before and also de_AT will have proper translation.

**Comment by stefan-niedermann** [comment]
woohoo, great! thank you! :)

@pludi i will create a bugfix release tomorrow - should be on F-Droid at the end of the week.

**Comment by stefan-niedermann** [comment]
Bugfix release tagged - 0.24.2 is on it's way. For F-Droid i guess 2-3 days, Play Store will take some more time.

Thank you for reporting :)
