### ISSUE TITLE
Text area should cover whole screen

### ISSUE THREAD

**Issue by quthla** [stefan-niedermann/nextcloud-notes#538]
On devices with large screen it's not easy to tap in the small text area when creating a new note. 

I think there's no disadvantage in making it always cover whole screen (like in other note apps)

**Comment by stefan-niedermann** [comment]
Basically a duplicate of #331 but yes. See there for implementation problems. Pull Requests are welcome :)

**Comment by quthla** [comment]
Couldn't you just make the edittext match_parent?

**Comment by stefan-niedermann** [comment]
there was a issue with the scroling behavior as far i remember (i once tried to solve this some time ago)
