### ISSUE TITLE
Date divider in list view

### ISSUE THREAD

**Issue by quthla** [stefan-niedermann/nextcloud-notes#539]
When I started using the app I didn't even realize what it was meant for. I'm not sure if it's got any use for somebody.

Maybe the date could be shown for each note with a mix of relative times for recent notes and absolute times like when note older than a week or so. 

https://cloud.addictivetips.com/wp-content/uploads/2017/07/pin-notes-ios-11.jpg

**Comment by stefan-niedermann** [comment]
I think the exact time is not that relevant. Though we could split the "earlier"-divider into specific year/month combinations like

- today
- yesterday
- this week
- this month
- december 2018
- november 2018
- may 2016
- ...

cc @jancborchardt

**Comment by quthla** [comment]
The thing is this wastes a lot of space for dividers when instead the date could be easily shown in the note's row itself without losing any space plus the benefit of knowing when exactly the note was edited last

But that's just my opinion

**Comment by stefan-niedermann** [comment]
The content is more interesting than the meta attributes, therefore it won't be displayed in a row.

The divider solution give some whitespace to distinguish different periods of time to roughly get an overview without cluttering each item with the (mostly irrelevant) exact time.

**Comment by jancborchardt** [comment]
Yup, agree with @stefan-niedermann. The dividers are nice for a sense of time and the exact date is not so relevant.

There should be more dividers though like "Last week" and "Last month", and then as Stefan said instead of "Earlier" have the "Month 2019" combinations.
