### ISSUE TITLE
When first date header is not »today«, show it

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#54]
The »today« date header does not need to be shown of course. But if the first note is older, say »yesterday«, that date header should be shown. :)

**Comment by stefan-niedermann** [comment]
So "today"-separator is not needed at all if i understand you right?
Could you please test with current [app-debug.apk](http://owncloud.niedermann.it/index.php/s/BOM5V1VZwscFk1k)-version? is this behaviour correct in your opinion?

**Comment by jancborchardt** [comment]
Yes, the »today« separator is never needed. However, if the most recent note was edited »Yesterday« or »This week«, that separator should show up top in the list. Even in the app-debug version as of just now it doesn’t.

**Comment by stefan-niedermann** [comment]
## With note from today

| ★ | ☆ |
| --- | --- |
| ![with-favorites](https://user-images.githubusercontent.com/4741199/84134589-1a5f2900-aa49-11ea-85f1-b29e0f06fdc3.png) | ![no-favorites](https://user-images.githubusercontent.com/4741199/84134577-13d0b180-aa49-11ea-9c00-9fde076befd1.png) |

## Without note from today

| ★ | ☆ |
| --- | --- |
| ![3](https://user-images.githubusercontent.com/4741199/84134894-893c8200-aa49-11ea-806b-ee8be5605bd4.png) | ![4](https://user-images.githubusercontent.com/4741199/84134901-8b064580-aa49-11ea-9bae-408ed86855cd.png) |

---

# Remaining question

**If we have favorites and a note from today, i currently have some spacing. Should we keep this spacing or should i remove it? Screenshots for easier decision:**

| 1 | 2 |
| --- | --- |
| ![with-favorites](https://user-images.githubusercontent.com/4741199/84135131-de789380-aa49-11ea-9887-15beff71803c.png) | ![99](https://user-images.githubusercontent.com/4741199/84135279-12ec4f80-aa4a-11ea-9899-971e4fb487ac.png) |

**Comment by korelstar** [comment]
Honestly, it's very confusing to me, that the "today" header is only shown in some cases (especially in the first screenshot). I vote for always showing (non-empty) headers. But at least, the header should be shown if there are favorites.

**Comment by stefan-niedermann** [comment]
> Honestly, it's very confusing to me

I agree, but at least we have screenshots now to discuss :smile:

I sometimes worry that i am not able to objectively judge those kind of changes because I'm so used to the current appearance... (German: tafelblind), so more feedback is appreciated.

**Comment by jancborchardt** [comment]
> If we have favorites and a note from today, i currently have some spacing. Should we keep this spacing or should i remove it?

Definitely remove it, the spacing is only for the different date divider sections. Looks much better when the favorites are nicely integrated with the "Today" notes, which are just as relevant. :)
Then the design is basically perfect! :D 

> Honestly, it's very confusing to me, that the "today" header is only shown in some cases (especially in the first screenshot).

What do you mean by that? The "Today" header is never shown. :)

**Comment by korelstar** [comment]
That shows that this design approach is very confusing. It would be much clearer if the today header would be shown always (if there is a note changed today).

The most important point is: the sections are always divided by time slots - but not if there are favorites *and* notes changed today. In this special case (and only in this special case!), we have a mixed section of notes changed at any time but are favorites, and notes changed today.

You see, this not a straight approach, the design is hard to understand.

**Comment by jancborchardt** [comment]
@stefan-niedermann what do you think? My main worry is taking away more vertical space. And we used to have the "Today" header and it was always basically useless.

**Comment by stefan-niedermann** [comment]
Well the use of it was, like @korelstar said, to separate

- the unordered favorite notes which might be from today or from 4 years ago from
- the notes one has edited today

While both are more important than all other notes, they are not the same and currently a separation is only achieved by the favorite icon.

Therefore indeed i would agree to keep the current state instead of merging this PR.

We could also ping the designers talk, maybe someone else wants to put his/her opinion here?

**Comment by stefan-niedermann** [comment]
PS.: Updated [the screenshots](https://github.com/stefan-niedermann/nextcloud-notes/issues/54#issuecomment-641190247) and removed the ones with spacing.

**Comment by jancborchardt** [comment]
Ok so then we could have a "Today" header only if there are favorited notes? That way the favorited and Today notes are separated, but we don’t have a useless "Today" header if people don’t use favorites.
(Or is this already what you meant? :)

**Comment by stefan-niedermann** [comment]
You described the current behavior, because there arent any favorites, there is no "Today"-header

**Comment by stefan-niedermann** [comment]
Closing this because it would be confusing and the proposed behavior

> Ok so then we could have a "Today" header only if there are favorited notes? That way the favorited and Today notes are separated, but we don’t have a useless "Today" header if people don’t use favorites.

is already in the currently released version.

**Comment by jancborchardt** [comment]
Right, I guess the confusion came from the issue being from 2016, likely before the current version did it like that, and we simply missed to close it along the way. :)

**Comment by stefan-niedermann** [comment]
probably 😄
