### ISSUE TITLE
Would you like a privacy policy statement.

### ISSUE THREAD

**Issue by HarryHeights** [stefan-niedermann/nextcloud-notes#540]
Hi, I'm Harry.
I'm a content creator and copywriter. I've rendered my services to open source projects by creating documents for them. This I do at no cost at all.
I feel your project would be needing a privacy policy. Especially if you deal with data collection, but if you don't it's still necessary anyway. For people that are skeptical about their privacy.

I'd love to hear your thoughts.

**Comment by stefan-niedermann** [comment]
Well, there is no data collected. absolutely nothing. It's pretty easy and even the Play Store versions are only built from tagged Github commits (they have to be, it's GPL after all). Therefore the Play Store builds do not collect any data, too. There are no trackers, heck, not even Matomo.

To be honest: Noone ever asked this question, after all the, already know Nextcloud and their strong privacy promise. Therefore i appreciate your contribution, but i do not think it is necessairy.

Regards :)

**Comment by HarryHeights** [comment]
Oh okay, no qualms

**Comment by stefan-niedermann** [comment]
The [statement](https://github.com/stefan-niedermann/nextcloud-notes/issues/540#issuecomment-464300644) is still correct, but in the meanwhile we added a `PRIVACY.md` which contains explanations for the used permissions and so on: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/PRIVACY.md
