### ISSUE TITLE
Large notes

### ISSUE THREAD

**Issue by Deathorn** [stefan-niedermann/nextcloud-notes#543]
Hello. I cannot sync large (>30kb approx.) notes. I can open it inside Nextcloud's web interface and QOwnNotes, for example. When I try to synchronize it with android app, I can see only infinite spinning circle. If I delete corresponding note and restart the app, sync goes fine. Also this is true when syncing many notes with big total size from fresh install, I have to do it in "chunks" on new device - removing some, then syncing, then adding some, then syncing etc.

**Comment by stefan-niedermann** [comment]
Might have been caused by a timeout. Could you please retry with version 2.x.x as soon as it appears on you app store? just reopen, in case the problem still occurs :)
