### ISSUE TITLE
Widget for a single note not loading

### ISSUE THREAD

**Issue by Dstr8ction** [stefan-niedermann/nextcloud-notes#545]
The widget which should display one single note isn't loading for me.
It works if I have one of those widgets on my homescreen and then restart the phone, but this method doesn't help if I have 2 of the widgets on the screen.
![Screenshot_2019-03-14-22-01-41-073_com mi android globallauncher](https://user-images.githubusercontent.com/3104676/54391996-c54a3100-46a6-11e9-97ee-7427de186913.png)

Android version: 8.1.0 Oreo

Device: Xiaomi Redmi Note 5 Pro

System language: German

App version: v0.24.3

App source: F-Droid

Steps to reproduce:
  1. add a new widget that should display a single note

**Comment by stefan-niedermann** [comment]
@dan0xii maybe you can have a look at this if you have some time? :)

**Comment by Dstr8ction** [comment]
Are there any more information I can provide to help with this issue?

**Comment by stefan-niedermann** [comment]
@Dstr8ction can you please verify that this issue still persists in the current version?

If yes, please try to grab a logcat and post it here.

Thank you

**Comment by stefan-niedermann** [comment]
Closing because of missing feedback.

@Dstr8ction please feel free to verify whether this issue appears in the current version and reopen it if it persists.
