### ISSUE TITLE
markdown renders while editing

### ISSUE THREAD

**Issue by bitconnector** [stefan-niedermann/nextcloud-notes#546]
When i edit a already existing note with markdown in it, the app renders the already existing markdown markers while showing it's symbol on top of it. It would be better to see the plain text in it's normal form instead for editing and copying

**Comment by stefan-niedermann** [comment]
No sorry, this is the intented behavior :)

It actually makes a lot of sense to render the markdown directly because this makes it easierer to scan the content and get the structure of the note.

**Comment by bitconnector** [comment]
OK thanks :relaxed:
