### ISSUE TITLE
How to import/export notes after new install of NC

### ISSUE THREAD

**Issue by cptechnik** [stefan-niedermann/nextcloud-notes#547]
How to import new notes?

Yes, the notes are stored at /data/USER/files/Notes , 
but, only copy and paste at the new server dont work, only new notes are shown, old are ignored.

Just insert the new adress in the Note-App also dont work, i think it must be resetted/delete Data/reinstall...

...so, please help (to export and import my notes into the new NC-Server)!

**Comment by korelstar** [comment]
Your Nextcloud server is out of sync with your filesystem. Typically, you should upload files only through the web interface or using the file sync client.

If you put files directly in the file system, you have to run the command `php occ files:scan USERNAME` in the root directory of your Nextcloud installation in order sync Nextcloud again.

**Comment by cptechnik** [comment]
> the command php occ files:scan USERNAME
must one of these commands we have to memorize... :-/
THANKS
