### ISSUE TITLE
In-note-search doesn't jump to occurrence of searchstring

### ISSUE THREAD

**Issue by KopfKrieg** [stefan-niedermann/nextcloud-notes#550]
I've got a few rather large notes (about 500-1000 lines of text) and sometimes *know* what I'm searching for, but can't find it in the file. If I open a note and then search in it, there's no indicator of how many matches I get on my search term or where/at what line I can find them (and unfortunately also no way to jump to the line where the match is found).

Would it be possible to implement that?

**Comment by stefan-niedermann** [comment]
Yes, i imagine a bottom bar like in a browser search which could look like

Result **4** of **14** `v` `^`

Where one can directly jump to the `next` or `precious` result.

Pull Requests are highly appreciated :)

**Comment by alexanderdd** [comment]
I came here for this.

See https://github.com/stefan-niedermann/nextcloud-notes/pull/400 and https://github.com/stefan-niedermann/nextcloud-notes/issues/106

Looks like this feature was planned. Looks like https://github.com/mario could do it. Looks like he would love some money/pancakes :-)

**Comment by alexanderdd** [comment]
To be honest, the current functionality is not a search, it is "**highlighting**", 

The current functionality should not be called a search, and the looking glass icon should not be used for it. 

(I wrote this because in the past days, I was frustrated multiple times because I could not find what I am looking for with the "search" function)

**Comment by stefan-niedermann** [comment]
Well, as you already saw, this is planned. We all have very limited resources to work on this project and do it all in our spare time. You can contribute to this project and start a PR if you want :rocket:, but just saying again, that this feature has not been fully implemented yet, will not speed up the development. :wink:

**Comment by stefan-niedermann** [comment]
Fixed with version `2.6.0` :)

**Comment by alexanderdd** [comment]
wohooooo I am so happy!! this works like a charm, using it right now! 
Thank you @stefan-niedermann !!
