### ISSUE TITLE
App shortcuts for fav / recent notes

### ISSUE THREAD

**Issue by quthla** [stefan-niedermann/nextcloud-notes#554]
It would be nice to have app shortcuts for fav and / or recent notes

**Comment by stefan-niedermann** [comment]
What exactly do you mean with "shortcuts"?

Do you mean this:

![Shortcuts](https://images.techhive.com/images/article/2016/11/android-71-app-shortcuts-100693489-large.jpg)

**Comment by quthla** [comment]
https://developer.android.com/guide/topics/ui/shortcuts

https://github.com/stefan-niedermann/nextcloud-notes/pull/201

**Comment by stefan-niedermann** [comment]
Got it, should be possible, yes :)

**Comment by quthla** [comment]
Looked over the code quickly and I think you could just add an Application subclass and register push / pull callbacks there in order to update the dynamic shortcuts.

**Comment by stefan-niedermann** [comment]
A Pull Request would be welcome :) If you want to take it on you, just let me know. otherwise, i will implement it myself.

**Comment by quthla** [comment]
I'm not really familiar with the code unfortunately and usually only do Kotlin.

**Comment by quthla** [comment]
Just saw your commit but what I meant was dynamic shortcuts which link directly to the note.

https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts#dynamic

I think what you implemented is just static shortcuts which link to the list view if I'm correct

**Comment by stefan-niedermann** [comment]
That's right, i misunderstood you.

**Comment by quthla** [comment]
The advantage is that with dynamic shortcuts one can also just drop the shortcut on the home screen for a shopping list or so

**Comment by stefan-niedermann** [comment]
Here we go

![device-2019-07-19-130833](https://user-images.githubusercontent.com/4741199/61531164-5bf87700-aa26-11e9-98bd-c21bed0347fb.png)

Current implementation only uses recent notes instead of mixed fav / recent due to limitations of count

**Comment by quthla** [comment]
Looking good! Will you also consider pinned shortcuts?

**Comment by stefan-niedermann** [comment]
Yes, i will open a new issue for that.

**Comment by quthla** [comment]
![Screenshot_20190723-123706__01](https://user-images.githubusercontent.com/30180109/61705713-a475a480-ad46-11e9-8f3f-1a4bf7cef09b.jpg)

Is the icon meant to be like this? And I unfaved Test but it's still yellow.

Apart from that working good

**Comment by stefan-niedermann** [comment]
Well, no. It should be a star actually. (it is on my physical device and on emulator).Which android version? Stock/LineageOS/...?

**Comment by stefan-niedermann** [comment]
PS:Color should change after next sync. can you try to force sync via swipe-down gesture and have a look?

**Comment by quthla** [comment]
I think it might be due to Lawnchair adaptive icon generation.

And no color did not change. Neither from gray to the yellow nor the other way around

**Comment by stefan-niedermann** [comment]
Well, i have tested it on Pixel Launcher and trebuchet - to be honest i have no idea how to handle Lawnchair (maybe it might even a bug on their side?)

**Comment by quthla** [comment]
Seems it is. In OnePlus launcher it will change the color instantly.

**Comment by stefan-niedermann** [comment]
Does the OnePlus launcher display aa star or is the shortcut also filled with color completely?

**Comment by quthla** [comment]
I also see the star in Lawnchair when I turn off adaptive icon generation

**Comment by stefan-niedermann** [comment]
Hi @quthla 

I noticed, that recently lawnchair 2.0 has been released. I am wondering if they fixed the problem in the meantime?

**Comment by quthla** [comment]
Right now it doesn't work at all. Seems there's an issue in lawnchair. It's not possible to pin anything currently

But apart from from that it should work better now due to recent changes in adaptive icon generation

**Comment by quthla** [comment]
Not sure if it's possible but in case you can set an adaptive icon as the shortcut's icon, the launcher wouldn't try to generate an adaptive icon itself
