### ISSUE TITLE
Quick Actions for Editor

### ISSUE THREAD

**Issue by jake-walker** [stefan-niedermann/nextcloud-notes#555]
I just got the app today and it's so useful! I'm finding, however, that it's a bit irritating to go into symbols every time to make bold, italics, lists, etc... so I think would be nice to have some 'quick actions' such as:
* **Bold** which adds 2 asterisks before and 2 asterisks after the cursor (or around selected text).
* **Italics** which adds 1 asterisk before and 1 asterisk after the cursor (or around selected text).
* **List** which adds ` - ` at the start of the current line.
* **Todo** which adds ` - [ ] ` at the start of the current line.
* **Heading** which adds `# ` at the start of the current line.

and so on...

These quick actions would probably be buttons just above the keyboard in a small bar.

**Comment by stefan-niedermann** [comment]
When you select a text section there are already the mentioned quick action in the pop-up-menu just next to "copy", "cut", " paste", "select all".

**Comment by jake-walker** [comment]
I understand there is already actions built into Android when you select text. I'm thinking more along the lines of something like this:
![](https://i.vgy.me/iAlj4f.png)
Where there would be bold, italics, etc... which are at the bottom of the screen all the time in the editor.

**Comment by stefan-niedermann** [comment]
The actions are there. Please have a look at #363 for why we qill not display them permanently but only on selecting text :)

![](https://user-images.githubusercontent.com/4741199/52447038-f4153a80-2b2f-11e9-8bc8-9fb1cdb143cf.png)

**Comment by jake-walker** [comment]
Ah ok!
