### ISSUE TITLE
login using QR code

### ISSUE THREAD

**Issue by dusscloud** [stefan-niedermann/nextcloud-notes#556]
From version 16, Nextcloud server can display a QR code when generating dedicated app credentials, giving something like this :
![bildschirmfoto von 2019-03-04 11-19-37](https://user-images.githubusercontent.com/1374172/53726967-6e0abc00-3e6f-11e9-810b-633d94a75d87.png)

Using such QR code has been implemented in the Nextcloud Android app (since [1.4.0](https://nextcloud.com/blog/nextcloud-android-client-1.4.0-has-been-released/)).
Can it be added to the Nextcloud-notes app ?

**Comment by stefan-niedermann** [comment]
Nice idea, but will close this in favor of #418 (Single Sign on).
