### ISSUE TITLE
Move the cursor to the beginning of the document after entering the character

### ISSUE THREAD

**Issue by meugr** [stefan-niedermann/nextcloud-notes#558]
If I create a code block in .md, and then I enter text into it, then after each character entered, the cursor goes off and the beginning of the document. If the code block is not closed, then everything works correctly.

* Create block
```

```
* I bring the text inside the block
* BUG

**Comment by stefan-niedermann** [comment]
Can not reproduce. Please post Android version and App version. Do you use fro. F-Droid or Play Store?

**Comment by meugr** [comment]
@stefan-niedermann 8.1 AOSP, F-Droid.

I apologize for the inaccuracy - there should not be a blank line between opening and closing a block of code. try to enter it:
 ``` python
 ```
After adding a blank line, everything works correctly.

**Comment by Valdnet** [comment]
The problem also occurs on Android 6.
In my opinion, the gray background obscures the cursor 😉 

App:
Android 6
Nextcloud Notes v0.24.3 F-Droid

**Comment by stefan-niedermann** [comment]
Okay, i think i might have found a workaround for this bug in `RxMarkdown`.

Can you confirm, that the cursor jump only happens when the cursor is positioned directly after the thre "```" characters (doesn't matter whether the start- or end-tag of the code-block)?

It would be great if you could check out and try this testing-apk from the `558-cursor-jumps-code-block`: [app-release.apk.zip](https://github.com/stefan-niedermann/nextcloud-notes/files/4143315/app-release.apk.zip)

**Comment by stefan-niedermann** [comment]
Will be fixed in the next released version.
