### ISSUE TITLE
Free application on the Google Play

### ISSUE THREAD

**Issue by albertooka** [stefan-niedermann/nextcloud-notes#561]
I would like the Google Play application to be free.

**Comment by stefan-niedermann** [comment]
The Play Store version is completely free and open source software. It is identical with the source code here on GitHub.

The price is symbolic and meant to be as a donation.

If the price is too high for you, you can build the app yourself directly from the sources or alternatively get the identical app for free on F-Droid app store, an app store that truly respects the privacy and freedom of its users (Link is in the README.md of this project).

Regards
