### ISSUE TITLE
Import notes from xiaomi / miui

### ISSUE THREAD

**Issue by influenist** [stefan-niedermann/nextcloud-notes#563]
Hi,

Is there any possibility to import notes from Xiaomi / MIUI?

**Comment by stefan-niedermann** [comment]
Well - is there any kind of export mechanism? json, csv, txt files or anything else? If not, theres unfortunately not much we can do on this side of the end...

**Comment by influenist** [comment]
Hi Stefan, 

Per note I can export / share. Might be an option to add it from this menu towards Nextlcoud notes app.

**Comment by influenist** [comment]
Hi Stefan, just confirmed sharing from inside the Miui notes app to Nextcloud-notes works. Only images are note being added. Guess this is related to the matter that your app doesn't support in-text images?

**Comment by stefan-niedermann** [comment]
yes, that's right :) glad to hear you found the "share to new note" menu :)
