### ISSUE TITLE
New feature: Support Latex Math commands

### ISSUE THREAD

**Issue by tiptruck** [stefan-niedermann/nextcloud-notes#566]
Use Latex commands such as $\frac{1}{2}$ like the Nextcloud Markdown editor

**Comment by stefan-niedermann** [comment]
Please post this issue in the upstream project: https://github.com/yydcdut/RxMarkdown

**Comment by bodograumann** [comment]
You are already using the Markwon renderer now. It has a plugin for latex support.
Could you please enable it, @stefan-niedermann ?

Cf. https://noties.io/Markwon/docs/v4/ext-latex/#blocks
