### ISSUE TITLE
Enable pinning notes as shortcut

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#567]
The options menu of specific notes could be expanded with some kind of "Add to homescreen"-button to pin a shortcut to that specific note on the launcher.

https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts#pinned

---

Followup to #554

**Comment by quthla** [comment]
Right now it doesn't work at all. Seems there's an issue in lawnchair. It's not possible to pin anything currently
