### ISSUE TITLE
Support of TLS1.3

### ISSUE THREAD

**Issue by antanof** [stefan-niedermann/nextcloud-notes#570]
There is error when the nextcloud server use TLS 1.3 in web server

**Comment by S74HK9hV** [comment]
I am getting "Invalid login: server connection is broken" message starting a few days ago. I couldn't figure why, and then i remembered that i switch to TLS 1.3 only. 

javax.net.ssh.SSLHandshakeException; Handshake failed.

Let me know if there's any other log info i can add to help with fixing. thanks

**Comment by antanof** [comment]
Yes, I think TLS1.3's ciphers are the cause.

**Comment by antanof** [comment]
https://github.com/square/okhttp/issues/4190

**Comment by stefan-niedermann** [comment]
Okay, i had quite a long time to think about this problem. It is hardly a bug in the app at all but a lack of support for modern TLS in android itself.

## Cause

As @S74HK9hV stated, the default HttpClient relies on whatever Android has to offer. Therefore, old Android versions will not be able to connect via TLS 1.3 by default.

## Workarounds

1. It is possible to use Google Play Services to install TLS 1.3 support
2. Using OkHttp might be a solution
3. When Single-Sign-On (#418) is implemented, the Notes app is able to use completely the network stack of the files app (which includes TLS 1.3 support on old android versions) 

This app also supports users of F-Droid and will therefore not rely on proprietary services like Play Services. Sure, we could use different flavors for Play Store and F-Droid, but i am not ready to maintain two different flavors and having some side effects on some users and on others not.

Using OkHttp sounds good and might also solve some other problems. I accept Pull Requests in this direction. But eventually the only solid future proof solution will be waiting on Singe-Sign-On.

As i stated in #418, i am currently experimenting with SSO in the Deck android app and will use my experiences then to upgrade the Notes app. Please be patient until i have gathered enough experience and the SSO lib itself is stable enough to bring the feature to the Notes app. If you can not wait, i suggest to maybe install a current custom rom.

Thank you.
