### ISSUE TITLE
Using the drop-down button "New note" crashes application

### ISSUE THREAD

**Issue by digital-mystik** [stefan-niedermann/nextcloud-notes#571]
The application opens fine, but when using the drop-down button the application crashes. If the application is closed to begin with, a "Notes keeps stopping" prompt appears. If it is open and the button is used, the following error occurs:

https://gist.github.com/digital-mystik/4e527517444d57ad956fbd893e272d1a

This is on Android Pie with One UI 1.0 (Samsung S8+) with the latest 0.25.0 F-Droid release.

**Comment by stefan-niedermann** [comment]
Oh sorry, i knew there was some ticket. The problem should be solved with the latest version :)

**Comment by digital-mystik** [comment]
Hello,

Just updated on F-Droid and closed the issue.. thanks!

On September 19, 2019 4:57:31 PM UTC, Niedermann IT-Dienstleistungen <notifications@github.com> wrote:
>Oh sorry, i knew there was some ticket. The problem should be solved
>with the latest version :)
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/stefan-niedermann/nextcloud-notes/issues/571#issuecomment-533219765

-- 
Sent from a mobile device; please excuse my brevity and any typos.
