### ISSUE TITLE
embedded git client for data sync

### ISSUE THREAD

**Issue by DarwinJS** [stefan-niedermann/nextcloud-notes#572]
Would be great if you added an embedded git client like https://github.com/GitJournal/GitJournal, so I can replace Gnotes.

I use typora for authoring on desktops and I'm looking for a companion for Android.

Just like GitJournal it would be great if syncing commits were automatic.

GitJournal does not allow naming the notes - strictly more journal oriented.

**Comment by stefan-niedermann** [comment]
I understand your feature request, but goal of this app is to provide an client for Nextcloud Notes. Therefore there will not be any support for other sync mechanisms, sorry.
