### ISSUE TITLE
Feature request: choosing note extension

### ISSUE THREAD

**Issue by samarulmeu** [stefan-niedermann/nextcloud-notes#573]
Will it be possible to have an option in choosing the extension: `.txt` or `.md`? So that switching between other apps that support only .md files not be a pain...

**Comment by stefan-niedermann** [comment]
Well, it is possible to globally set this in the webinterface - have a look at the bottom left sidebar, there's a "settings" section:

![grafik](https://user-images.githubusercontent.com/4741199/62186849-d64ec280-b367-11e9-9065-fcab86dcc4bc.png)

**Comment by samarulmeu** [comment]
Thank you very much. I just discovered the app. I'll be using it a lot!
