### ISSUE TITLE
Combination of hashtag and URL wipes note 

### ISSUE THREAD

**Issue by mazimmer** [stefan-niedermann/nextcloud-notes#576]
Adding a hashtag and URL with certain properties will wipe the note empty on sync. Only the title remains.

If the hashtag or the elements of the URL are below a certain length, the effect doesn't occur. (I haven't established the exact lengths, just given elements that reproduce the behavior on my device) 

Example note:

`Abcdef` 
`http://abcdefghik.org/abcdef/abcde.html`
` #abcdefghijklmnh`

#### Steps to reproduce:
* create new note/use exisiting note
* paste example note into new note
* back out of note

#### Expected behaviour
Note gets saved, with "Abcdef" as title, body with URL and hashtag

#### Actual behaviour
Note body is cleared.

**Comment by stefan-niedermann** [comment]
Can you please give exact steps to reproduce (1. 2. 3. 4. ...) and the expected and the real behaviour? I have troubles to understand the issue. Thanks

**Comment by stefan-niedermann** [comment]
Closing due missing feedback.

Feel free to reopen with a video which demonstrates the issue or exact steps to reproduce the issue.
