### ISSUE TITLE
No new version on F-Droid

### ISSUE THREAD

**Issue by Valdnet** [stefan-niedermann/nextcloud-notes#578]
No new version 0.26.0 on F-Droid for over 3 weeks.

**Comment by fazlerabbi37** [comment]
it would see the [Build Metadata](https://gitlab.com/fdroid/fdroiddata/tree/master/metadata/it.niedermann.owncloud.notes.yml) is not available :confused: source: [F-Droid Notes Page](https://f-droid.org/en/packages/it.niedermann.owncloud.notes/)

cc @stefan-niedermann @korelstar

**Comment by korelstar** [comment]
Build metadata is here: https://gitlab.com/fdroid/fdroiddata/tree/master/metadata/it.niedermann.owncloud.notes.txt

Looks like the Fdroid bot doesn't catch the new version, although tag and build gradle look fine. I think we should open an issue on fdroiddata repository.

**Comment by Valdnet** [comment]
> I think we should open an issue on fdroiddata repository.

Open issue: [1753](https://gitlab.com/fdroid/fdroiddata/issues/1753)

**Comment by Valdnet** [comment]
@stefan-niedermann New versions of the app have already been released and you can still not download them from F-Droid. Do you know anything about it?

Or maybe share ready apk in "Releases" 😉.

**Comment by stefan-niedermann** [comment]
I can imagine that the latest Pull Request by korelstar fixed the issue. I rerelease 0.27.1 and i am watching F-Droid to check whether the build is successful or not :) Thank you for the hint

**Comment by Valdnet** [comment]
@stefan-niedermann There is still no new version in [F-Droid](https://f-droid.org/packages/it.niedermann.owncloud.notes/).

**Comment by stefan-niedermann** [comment]
I know... There haven't been any updates for any apps recently. I thunk they might have a general problem. Also they said on GitLab, the problems with notes are resolved now.

**Comment by stefan-niedermann** [comment]
https://f-droid.org/wiki/page/it.niedermann.owncloud.notes/lastbuild_47

**Comment by korelstar** [comment]
Release 0.27.1 is now on [F-Droid](https://f-droid.org/de/packages/it.niedermann.owncloud.notes/)! 🎉
