### ISSUE TITLE
Reference to cert4android invalid

### ISSUE THREAD

**Issue by stephanritscher** [stefan-niedermann/nextcloud-notes#581]
$ git pull --recurse
Fetching submodule cert4android
Already up to date.
error: Server does not allow request for unadvertised object 47abc356823d7c13c329161fcbf30f8d872f2426
Fetched in submodule path 'cert4android', but it did not contain 47abc356823d7c13c329161fcbf30f8d872f2426. Direct fetching of that commit failed.

**Comment by stefan-niedermann** [comment]
Strange. I will have a look into this, thank you

**Comment by korelstar** [comment]
Can't reproduce. Did you execute `git submodule init`?

Please try also to execute `git submodule update --init --recursive`

**Comment by korelstar** [comment]
Okay, now I can reproduce the problem. That commit indeed doesn't exists in cert4android. Strange.

Let's update the submodule.
