### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by igor-cali** [stefan-niedermann/nextcloud-notes#587]
**Android version:** 8.0.0 Oreo

**Device**: Honor 8

**System language**: Italian

**App version:** v0.25.0

**App source:** F-Droid

**Steps to reproduce:**
  1. open the app
  2. Wait for automatic sync or drag down top down to start manual sync

Sync does not complete (permanent rotating progress bar).
Sometimes following toast message pops up:
![IMG_20190912_203236](https://user-images.githubusercontent.com/12466054/64810883-8127e280-d59c-11e9-8bf3-52d3c1a41ea8.jpg)

 The issue started some days ago and sync never worked since.

Thanks!

**Comment by stefan-niedermann** [comment]
Current state: Sync works flawlessly with the test instance of the provider, we guess that it might be a setup- or performance-issue at the provider itself.
