### ISSUE TITLE
path of notes in android

### ISSUE THREAD

**Issue by odoooooo** [stefan-niedermann/nextcloud-notes#590]
Hi,
where does the app store the notes as a file on my android device?

Background: my Nextcloud server is offline and I want to backup my notes that I added recently (while server offline, so they are only on my android device).

This can be also connected with a feature request: feature that let's you export all notes to a txt file for example.

**Comment by stefan-niedermann** [comment]
they are stored in a SQLite database, you can only open each note and press ",share" in the options menu, sorry.
