### ISSUE TITLE
Notes Widget : the text is unreadable

### ISSUE THREAD

**Issue by marmotte32** [stefan-niedermann/nextcloud-notes#594]
Hello,
Using lawnchair launcher, after the notes widget added on my Android desktop, the text of each notes are unreadable because its background color dark grey and the text is black.

Thanks for your help!

Steps to reproduce
Open Notes apps Add some notes Install Lawnchair launcher and start it Add the notes widget on your desktop

What is the current behavior?
Notes are not visible because the text color is black and background is dark grey color.

What is the expected correct behavior?
Notes are visible in the widget.

Possible fixes
Change the widget code in order to have text color in white...?

Screenshot
![Screenshot_NotesWidget](https://user-images.githubusercontent.com/4152464/66050958-c3f32f80-e536-11e9-9d8e-86be337be10b.png)

**Comment by dan0xii** [comment]
I'm using Lawnchair with the notes widget and don't see this problem. What version of the Notes app are you using?

**Comment by marmotte32** [comment]
Hello,
I'm using version 0.22.3 under /e/OS (based on LineageOS 14.1 so it's an Android 7.1.2 base).
The source code is here:
https://gitlab.e.foundation/e/apps/Notes

I have open an issue here:
https://gitlab.e.foundation/e/apps/Notes/issues/6

Thanks for your help!

**Comment by dan0xii** [comment]
Interesting. So I think that fork doesn't include a fix from this repo (https://github.com/stefan-niedermann/nextcloud-notes/commit/431fb7e79e012987844932ad092ac052cc6377f3) for this issue. Your options are to install f-droid and install from there or build from the source in this repo if you have the facility.

**Comment by marmotte32** [comment]
Yes it works great with this v0.27.1.47
Thanks a lot for you help, I will discuss with the eOS community to include this patch
You can close this issue.

**Comment by stefan-niedermann** [comment]
Thank you :)
