### ISSUE TITLE
error message, syncing 

### ISSUE THREAD

**Issue by Trebor87** [stefan-niedermann/nextcloud-notes#595]
![Screenshot_20191002-225342](https://user-images.githubusercontent.com/55857416/66081287-fff2b880-e567-11e9-93a5-7e8979434f35.png)
hi

am getting this message, all the time 

have un installed and reinstalled to no avail 

running android 10 latest version 

Thanks

**Comment by Trebor87** [comment]
sussed it, its to do with the Two Factor Authentication being abled, was I diable it, all is OK

**Comment by stefan-niedermann** [comment]
Hello,

do you use Play Store or F-Droid version?

Have you created an app password? The Notes android client does unfortunately not yet support 2FA natively, so you will have to create an app password in thr webinterface and use this to authenticate.

Any other special configuration? e.g. Self signed certificate?

**Comment by Trebor87** [comment]
hi

thanks for the answer

I use the F froid version

No special config.

"so you will have to create an...."  will look at the Web interface to see 
how to do that, thanks


I know you don't have password / fingerprint protection, but any idea on a 
date if you do it?




Trevor BROOKES

**Comment by stefan-niedermann** [comment]
No estimation about the date for password protection, sorry. It's a spare time project, so i can not estimate. Simply reopen the issue if the problem still occurs after using an app password :)
