### ISSUE TITLE
Duplicated notes when using voice to text (Google Voice Typing) 

### ISSUE THREAD

**Issue by aproposnix** [stefan-niedermann/nextcloud-notes#602]
**Android version:**  8.1.0

**Device**: 
Xiaomi Redmi 6

**System language**: 
English (US)

**App version:** e. g. v0.8.1
v1.0.0 
**App source:** Google Play Store, F-Droid or self-built?
F-Droid 

When using voice to text (aka Voice Typing) within the Notes application, it often happens that I get duplicated notes. It appears that it's trying to sync too often. is there any option to only manually sync, or sync only on exit? 

It's not known exactly how to reproduce it. Sometimes it does and sometimes it doesn't. It happens frequently enough though to be very annoying.   It's usually when I am doing a lot of notes. As I said, it seems to be syncing too often (whenever I close a note). 

Update: I don't know if it's related, but I often get this error - even though I do have a network connection.  in such cases, I need to kill the app and the open it again. 

http://pix.toile-libre.org/upload/original/1570605428.png

**Comment by stefan-niedermann** [comment]
Can you please check if this issue persists with v2.5.0?

**Comment by aproposnix** [comment]
Is the new version available on F-Droid? I'm not seeing it. I'm currently on 2.4.8 and it appears to be working proper;y right now -- no duplicated notes yet (I'll monitor it and report back if the situation changes). 

The error mentioned has not shown up for some time now. Thanks for the great work!

**Comment by stefan-niedermann** [comment]
You're welcome, thank you too :)
