### ISSUE TITLE
option 'last modified' sort on categorized note list needed

### ISSUE THREAD

**Issue by aproposnix** [stefan-niedermann/nextcloud-notes#603]
As a user I am frequently creating notes and categorising them and within each category I could have many notes (20, for example). However I'm only interested in the most recently used notes. In the current setup some of these notes are in the bottom some of these notes in the middle of the list so it's very hard to distinguish them, especially if they have similar naming conventions. so it would be nice if I could sort by last modified so that I always know which ones I'm actually working on. This is the sort view seen in the 'all' category. 

EDIT: to be clear, I'm talking about the Android app. If this is the wrong issue board, please let me know.

**Comment by stefan-niedermann** [comment]
Have you considered to use the "all notes" and search there for the category-name? Of course there might be some false positives if a note from another category has the category-name in its content - i think it depends on your organization. But this might be an easier solution?

**Comment by aproposnix** [comment]
@stefan-niedermann Yeah, this is what I'm doing now but it's not ideal at all. All I'm asking is that the categories have the ability to sort by last modified like the "all notes"

**Comment by Isaac-Graham** [comment]
@aproposnix Do you mean sort categories or the notes in each category with the lastest modification?

**Comment by aproposnix** [comment]
The notes in each category. 

If I go to "all notes", I see the notes that were modified recently. But if I go to a category, everything is sorted alphabetically I think.

**Comment by stefan-niedermann** [comment]
Will be fixed in `v2.16.0`, credits to @WingsUpete @Hui-Ouyang16 @IF-ACT
