### ISSUE TITLE
Attachments, camera access and ?drawing tool

### ISSUE THREAD

**Issue by bijang** [stefan-niedermann/nextcloud-notes#605]
I realise you're busy with other more important things like SSO etc, for the future though, could be get insertion of attachements (files pdf picture media etc), camera access to attach picture taken, and idealy a freehand drawing tool even if rudiementary blank ink line drawing....

**Comment by stefan-niedermann** [comment]
This will be implemented as soon as the server app provides an API for it:

https://github.com/nextcloud/notes/issues/74
