### ISSUE TITLE
Wrong account name color in dark mode

### ISSUE THREAD

**Issue by juliushaertl** [stefan-niedermann/nextcloud-notes#606]
![Screenshot_20191019-163739~2](https://user-images.githubusercontent.com/3404133/67147732-af819780-f297-11e9-9539-9a3fc222e032.png)

It should stay white I'd say :wink:

**Comment by stefan-niedermann** [comment]
Of course. Already fixed on the SSO-branch, but i guess this might be worth a patch release from master...
