### ISSUE TITLE
feature request :: open at end of file / save position

### ISSUE THREAD

**Issue by xxKeith20xx** [stefan-niedermann/nextcloud-notes#616]
I use the notes app ask a staging area for a journal system. I move the text to an archive every so often but until I do, my note files get extremely long. When I open the app, I select my note and scroll all the way to the bottom of the file. It would be useful if there was a way to open the file at the end of the file with the keyboard pop-up. I'm trying to have the quickest system to write append to an existing note. Saving the position in the file would be nice too but maybe that's harder to do since that doesn't sync with Nextcloud.

**Comment by stefan-niedermann** [comment]
Hi,

yes, there is already an issue about this topic: #227 

This issue ihas currently only a low priority, but 
Pull Requests are welcome, of course. Alternatively you can upvote the issue or put a bounty on it.
