### ISSUE TITLE
Note list widget now missing "+" button

### ISSUE THREAD

**Issue by edo0** [stefan-niedermann/nextcloud-notes#630]
**Android version:** LineageOS 16 - Android 9.0 

**Device**: Pocophone F1

**System language**: English (UK)

**App version:** v2.0.1

**App source:** F-Droid 

**Steps to reproduce:**
  After having updated the app from v1.0.1 to v2.0.1 today, I have realized that the "note list" widget has lost its "+" button on the top right corner - which at the same time, will still prompt you to a new note if pressed. 
(Please refer to the image below)
![IMG_20191221_010523](https://user-images.githubusercontent.com/16632292/71299853-3e8e5700-2390-11ea-9128-374946db16f7.jpg)

Removing and placing again the widget would not restore the button either

**Comment by stefan-niedermann** [comment]
cc @dan0xii

**Comment by stefan-niedermann** [comment]
I tracked it down to the usage of `app:srcCompat=""`. Using `android:src=""` will result in a visible `+`-icon.

I disabled `vectorDrawables.useSupportLibrary = true` in the `app.gradle`-file, this likely caused the error.
