### ISSUE TITLE
Swipe delete "Undo" creates new note

### ISSUE THREAD

**Issue by kzar79** [stefan-niedermann/nextcloud-notes#661]
If one clicks on the "undo" command that appears after a note is (mistakenly) deleted with a swipe (a thing that happens way too often!!!), the app does not restore the note, but creates a new empty note instead.

Proposed fix: just remove completely the swipe delete function!!!

**Comment by stefan-niedermann** [comment]
First aid: The note is still in the trashbin and can be restored from there.

**Comment by paskalito** [comment]
i can confirm this bug. same thing just happened to me.

also see https://github.com/stefan-niedermann/nextcloud-notes/issues/663

**Comment by stefan-niedermann** [comment]
Yes, and i already found out the cause: Since we moved the `excerpt` into a separate column in the database, we do not longer read it at the place where we restore a deleted note. I am currently working on a fix.

**Comment by stefan-niedermann** [comment]
Will be fixed in `v2.4.1`. Thank you for reporting!
