### ISSUE TITLE
Glide does not use SSO network stack

### ISSUE THREAD

**Issue by avalx** [stefan-niedermann/nextcloud-notes#666]
I have configured two accounts in the Notes app:
1. my account on Disroot.org
2. an account on my local Nextcloud server (located on my internal network)

I've noticed that for the second account (on my local server) there is no profile picture shown although it is configured in the Nextcloud account settings. It only shows the generic profile icon. I've tried with different pictures but none was displayed as profile picture.

My config is:
Server Fedora 31 (latest updates)
Nextcloud 17.0.2
Nextcloud client 2.4.0

**Comment by stefan-niedermann** [comment]
Currently the first contact image is cached. Unfortunately there is not yet a solution for updating the image except deleting app storage (or remove and reinstall the app).

Could you try this?

We know about the problem and are working on some concept to properly update the avatar when it has been changed.

**Comment by avalx** [comment]
Yes, I also tried to delete storage and reinstall the app but still the profile picture for that particular account is not shown.

I also deleted the first (Disroot) account from Notes and only configured one account (the one from my local server) but even in this case the picture is not shown (deleting app data as well).

**Comment by stefan-niedermann** [comment]
Okay, so this seems to be a problem with your local setup or with local instances in general.

Can you maybe grab a logcat (there are apps which are reading them) so we can see something more? Interesting would be everything with a warning or an error, i think you will find something starting with `Glide` (this is the library we are using to fetch images).

What does happen in the official nextcloud (files) app? Are you able to see your profile image there?

**Comment by avalx** [comment]
> Okay, so this seems to be a problem with your local setup or with local instances in general.
> 
> Can you maybe grab a logcat (there are apps which are reading them) so we can see something more? Interesting would be everything with a warning or an error, i think you will find something starting with `Glide` (this is the library we are using to fetch images).
> 

OK, I will try to do this - never done it before so I will have to do a little research before. 

> What does happen in the official nextcloud (files) app? Are you able to see your profile image there?

Yes, in the NC app I can see both profile pictures without problem (even if I change the picture it shows in the app when I change the account and sync).

**Comment by avalx** [comment]
And here is a logcat.

As far as I can see there are some problems regarding certificates of the server. As my server is accessible from local lan only I'm using my local CA for issuing the certificates. I did import my CA certificate into my phone (it's in the USER part of Trusted credentials).  Looks like this is not enough?!

Just to add some additional info. I have similar problem with the Bookmarks app: if I try to use https connection it fails, so I have to use http for it to work. And if I remember correctly I also used http on the older Notes app but this is not possible anymore. On the other hand the official Nextcloud app does not have this kind of problems - it works OK.

[logcat.zip](https://github.com/stefan-niedermann/nextcloud-notes/files/4030132/logcat.zip)

**Comment by stefan-niedermann** [comment]
Makes sense, the profile picture gets loaded directly by glide, not via SSO.

Maybe it's possible to write a [glide interceptor](https://square.github.io/okhttp/interceptors/) to use SSO.

**Comment by stefan-niedermann** [comment]
Maybe @david-development or @tobiasKaminsky know how `Glide` can be told to use the SSO stack out of the box?

**Comment by tobiasKaminsky** [comment]
The avatar can be fetched without authentication, or? So we do not use SSO?

But if you want, you can use something like this: https://github.com/nextcloud/android/pull/2871/files#diff-cf498629b982b5c51f844fcf83de8937

**Comment by stefan-niedermann** [comment]
We do not only use SSO for authentication purposes, but also to use the identical network stack (including self signed certificates) to support every special edge case that is already covered by the Nextcloud files app.

**Comment by stefan-niedermann** [comment]
The link looks interesting, i'll have a look 👀

**Comment by tobiasKaminsky** [comment]
> We do not only use SSO for authentication purposes,

True, I confused myself. But that then means that Glide has its own http client…But maybe you can convince it to use SSO :-)

**Comment by stefan-niedermann** [comment]
We solved this in the Deck App: https://github.com/stefan-niedermann/nextcloud-deck/blob/attachments/app/src/main/java/it/niedermann/nextcloud/deck/util/glide/SingleSignOnLibraryGlideModule.java

Just needs some copy pasta. Maybe this module could be an option for the SingleSignOn lib? Don't know...

**Comment by stefan-niedermann** [comment]
@avalx could you try whether your avatar shows up correctly with this .apk (or build from brach `666-glide-sso`)?

[glide-sso.zip](https://github.com/stefan-niedermann/nextcloud-notes/files/4180835/glide-sso.zip)

**Comment by avalx** [comment]
Sorry to report that I still don't see the avatar on my internal server. I'll try to get the logcat now.

**Comment by stefan-niedermann** [comment]
Did you see my comment that i updated the .zip-file? The first .zip-file contained a bug.

Thanks for testing, looking forward to the logcat :)

**Comment by avalx** [comment]
So this is strange:

First the avatar on my Disroot.org account was the one from my local NC server and there is still no avatar for my local NC server?! And after some time the avatar for Disroot is the right one again (but still without one on my local server).

Here is a log if it helps somehow.

[logcat.zip](https://github.com/stefan-niedermann/nextcloud-notes/files/4181931/logcat.zip)

**Comment by avalx** [comment]
> Did you see my comment that i updated the .zip-file? The first .zip-file contained a bug.
> 
> Thanks for testing, looking forward to the logcat :)

Yes I saw your comment and downloaded after that. So the timestamp of the apk is: Feb 10, 2020 2:38:23 PM - is this OK?

**Comment by stefan-niedermann** [comment]
Can you try deleting cache and storage from files app *and* notes app? And then readd all accounts. There are several 302- redirects from your server which should not happen (at least at this point because files app *should* handle them)

**Comment by avalx** [comment]
Just to be sure: by files app you mean the Nextcloud Android App?

**Comment by stefan-niedermann** [comment]
Yes

**Comment by avalx** [comment]
OK, now this could be the problem: on my phone I have the files app installed from F-Droid repo, but I think it is not the last one. I have 3.9.2 installed and I don't know why the F-Droid repo is not updated with the latest one. I guess you need this test with the latest version?

Let me see if I can test this on my other device (an old Samsung tab).

**Comment by stefan-niedermann** [comment]
The files app version doesn't matter (each version >=3.9.0 should work).

The notes app should be the zipped version from this issue
(F-Droid has currently some troubles with their build infrastrcuture, therefore some apps will arrive delaied)

**Comment by avalx** [comment]
OK, so here it goes:

1. remove all accounts from the notes and files apps and force stop/delete storage
2. create both accounts in the files app -> both avatars shown correctly
3. add the account from my local NC server to notes app -> no avatar shown
4. add my Disroot account to notes -> the avatar shown is from my local NC server!! (but still no avatar for my local NC server?)
5. force stop/clear cache for the notes app and start it again -> the right avatar for the Disroot account is shown and no avatar for my local NC server

Everything is in the log - I hope ;)


[logcat_02-10-2020_19-11-36.zip](https://github.com/stefan-niedermann/nextcloud-notes/files/4182412/logcat_02-10-2020_19-11-36.zip)

**Comment by stefan-niedermann** [comment]
So, i guess here we have the bad boy:

```
[02-10 19:08:07.173 18626:18642 E/InputStreamBinder]
Error during Nextcloud request
java.lang.IllegalStateException: CE_5
	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:433)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:134)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:117)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:134)
	at android.os.Binder.execTransact(Binder.java:752)
Caused by: java.lang.IllegalStateException: 302
	... 5 more
Caused by: java.lang.IllegalStateException: 
	... 5 more
```

and

```
Load failed for https://www.sever.lan/nextcloud/index.php/avatar/aval/64 with size [192x192]
class com.bumptech.glide.load.engine.GlideException: Failed to load resource
There was 1 cause:
com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException(HTTP request failed with HTTP status-code: 302)
 call GlideException#logRootCauses(String) for more detail
  Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
There was 1 cause:
com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException(HTTP request failed with HTTP status-code: 302)
 call GlideException#logRootCauses(String) for more detail
    Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
There was 1 cause:
com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException(HTTP request failed with HTTP status-code: 302)
 call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 302
```

Again this `HTTP 302`... @tobiasKaminsky i had a few users (10?) which had problems with the `302`-redirect in the last week. Often this could be solved easily by reinstalling both apps and configure the accounts from scratch.

But you mentioned this should not even appear, so maybe we could add some more detailled logging in the files app in cases where a `302` is returned to find out how this constellation is even possible.

The question is: Should we put work into fixing this issue or should we dig deeper to find the actual root cause?

**Comment by tobiasKaminsky** [comment]
Is there a reliable way to reproduce this?
Then i can give it a try.

**Comment by stefan-niedermann** [comment]
Unfortunately i am not aware of a way to reproduce it... especially in this case it seems to be a local server only...

**Comment by stefan-niedermann** [comment]
Sorry, but i have to agree with @tobiasKaminsky in this case. Close this issue because

- it's a very special case
- which we cannot reproduce
- it's related to local environment and
- it's a minor problem if only the avatar is replaced by the fallback image (that's why we have it after all :wink: )

**Comment by avalx** [comment]
OK, I understand. Thanks for trying anyway.

**Comment by stefan-niedermann** [comment]
@avalx are you using the OID Connect app on your problematic Nextcloud instance?

**Comment by avalx** [comment]
> @avalx are you using the OID Connect app on your problematic Nextcloud instance?

No, I am not.
