### ISSUE TITLE
Shortcut: not up to date

### ISSUE THREAD

**Issue by jwsp1** [stefan-niedermann/nextcloud-notes#672]
**Describe the bug**
A note which is being opened via shortcut on homescreen is not being updated 

**To Reproduce**
1. Create a shortcut of a note (pin to homescreen) 
2. Make changes to this note somewhere else than the app
3. Open the note via shortcut
4. Not up to date

**Expected behavior**
The app should automatically check for an updated version on the server right after clicking on the shortcut 

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro
 - Android-Version: 9

**Comment by stefan-niedermann** [comment]
Basically a duloicate of #442.

This will likely be a less problem as soon as #656 has been implemented.

**Comment by jwsp1** [comment]
Correct. Didn't see this one even though I've searched a while. Thanks for replying.

**Comment by stefan-niedermann** [comment]
No problem :)
