### ISSUE TITLE
Sync stopped working

### ISSUE THREAD

**Issue by maste9** [stefan-niedermann/nextcloud-notes#674]
Strangely the Sync stopped working since a few days (Can't tell exactly). While the app is obviously trying to the sync-symbol remains at every edited entry and indeed there's now change on the server.

I uninstalled the app (F-droid) on the phone, tried downgrade to 2.3.0, switched back to 2.4.0 ...
It is able to download the files from the server but after altering the files with the app sync doesn't work in neither direction. It doesn't depend on network (WIFI or LTE), and I don't receive any error message by the app.

Android9 (LineageOS) on OnePlusA3003, Nextcloud16.0.7 with Notes3.1.1

**Comment by korelstar** [comment]
Maybe this is related to https://github.com/nextcloud/notes/issues/430 ?

Do you have that app "RansomwareDetection" enabled on your server?

**Comment by stefan-niedermann** [comment]
Please also tell us, which PHP-version you are using on your server.

I just released v2.4.6 which comes with a new exception dialog. I hope that this will give us some better insights about what actually is happening.

If you want, you can directly install this zipped `.apk`-file for testing purposes.

[notes-2.4.6-(signed).apk.zip](https://github.com/stefan-niedermann/nextcloud-notes/files/4047941/notes-2.4.6-.signed.apk.zip)

**Comment by stefan-niedermann** [comment]
Also: Please check whether this might be related to https://github.com/stefan-niedermann/nextcloud-notes/issues/653

**Comment by ilippert** [comment]
I experience the, seemingly, same issue.
PHP 7.3

**Comment by ilippert** [comment]
I do not see a resemblance with #653

**Comment by ilippert** [comment]
notes-2.4.6-(signed).apk.zip same problem

**Comment by ilippert** [comment]
disabling ransomware protection allows syncing again

**Comment by stefan-niedermann** [comment]
@ilippert if ransomware recovery is the origin of your problem and disabling it solves the peoblem for you, i would advice you, to upvote (or comment) the issue at their repository: https://github.com/undo-ransomware/ransomware_detection/issues/26

**Comment by stefan-niedermann** [comment]
Also, @ilippert if you already use 2.4.6, wasn't there a snackbar which offered you a detailled stack trace? This might be helpful for ransomware detection, too.

**Comment by maste9** [comment]
I can confirm that I use the ransomware_detection and will upvote this topic at their repo.

Thank you for your help!

**Comment by stefan-niedermann** [comment]
Glad to help, let's hope they can detect and fix the issue :)
