### ISSUE TITLE
Markdown rendering broken (for numbered lists)

### ISSUE THREAD

**Issue by minimeee** [stefan-niedermann/nextcloud-notes#676]
**Describe the bug**
Numbered lists are correctly displayed in the browser, but not in the preview mode of the app (see screenshots below). Note that this bug is already pretty old (I noticed it almost a year ago).

**To Reproduce**
1. Create new note
2. Fill with following text:

```
10. November
11. November
12. November

13. November
* A
* B
* C

26. Dezember
* A
* B
* C

05. Januar
* A
* B
* C
```
3. Switch to preview mode
4. Find all the wrong numbers (hint: 6)

**Screenshots**
![Edit](https://user-images.githubusercontent.com/5322305/72207801-7c1c6680-349c-11ea-8b85-c7f10b4b9f1e.jpg)
![View](https://user-images.githubusercontent.com/5322305/72207802-7c1c6680-349c-11ea-8ae5-97f70fc48e46.jpg)

**Notes App**
 - Version 1.0.1 (latest from Play Store)

**Smartphone (please complete the following information):**
 - Device: Huawei P20
 - Android-Version: 9

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Yes, i see. I have been busy with implementing Multiple accounts & Single-Sign-On (and i still am).

You can report the bug upstream at https://github.com/yydcdut/rxmarkdown but the current lib is not maintained anymore, so i guess, it will not get fixed.

But as you might have seen: [This issue](https://github.com/stefan-niedermann/nextcloud-notes/issues/549) is pinned in GitHub. Replacing the Markdown Editor completely will be the nix big topic, as soon as SSO has been stabilized.

**Comment by minimeee** [comment]
I understand and guess I'll wait some more then... Anyway, as I'm not a big fan of Markdown, it would be nice if it would be possible to disable it completely in a future version (would also be a workaround for bugs like this). So, "preview mode" would just render the text read-only. No more, no less...

**Comment by stefan-niedermann** [comment]
Thank your understanding. I hope i will soon have time, but this will have to wait until all problems with the Single-Sign-On are done.
