### ISSUE TITLE
dark mode colors with markdown

### ISSUE THREAD

**Issue by xxKeith20xx** [stefan-niedermann/nextcloud-notes#677]
**Describe the bug**
In dark mode, markdown code bracketing shows gray background with white text, making it illegible.

**To Reproduce**
1. Write some text
2. Add ``` to the top of the paragraph
3. Add ``` to the bottom of the paragraph
4. See gray background with white foreground text

**Expected behavior**
Maybe just make the background black instead of gray?

**Screenshots**
![PSX_20200111_210556](https://user-images.githubusercontent.com/28391818/72213587-ffe34c80-34b6-11ea-9c66-c87a1e617168.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - Android-Version: 10

**Comment by stefan-niedermann** [comment]
Will be fixed beginning with v2.4.8:

![grafik](https://user-images.githubusercontent.com/4741199/72549763-989c1280-3891-11ea-84bc-3c44f5df4532.png)

![grafik](https://user-images.githubusercontent.com/4741199/72549784-a3ef3e00-3891-11ea-8b05-b63d7c538a91.png)
