### ISSUE TITLE
Lots of empty notes are created if the server is full 

### ISSUE THREAD

**Issue by tommag** [stefan-niedermann/nextcloud-notes#679]
**Describe the bug**
I recently tried to create a new note while my Nextcloud server was full. Every time the app tried to sync, dozens of empty notes were added. The problem disappeared once I cleared some space from my Nextcloud server. 

I don't know if it is relevant but I don't have my own server, I have an account with limited storage from a 3rd party provider. 

**To Reproduce**
1. Log in to an account with no space left
2. Create a new note and sync it. 

**Server**
 - Nextcloud-Version: 17.0.0.9
 - Nextcloud Notes-Version (server app): unknown 
 - PHP-Version: unknown

**Smartphone (please complete the following information):**
- Device: Sony Xperia x compact 
 - Android-Version: 8.0.0

**Comment by stefan-niedermann** [comment]
@tommag how does the webinterface handle this? are you able tk create new empty notes there, too?

@korelstar do you know how this is handeled by the server? There should be returned an appropriate status code so that we can handle this more gracefully.

**Comment by korelstar** [comment]
I don't know how this is handled by NC server. I would have to test this. Sounds like we have to add additional check in the server app.

**Comment by stefan-niedermann** [comment]
@korelstar do you need a seperate issue in your repository so it doesn't get lost or are you fine with dealing with the issue here?

**Comment by tommag** [comment]
Hello,
As i said I don't have my own Nextcloud server so I'm sorry I can't try from the web interface (now that I've cleaned up my account I would have to fill it up with dummy data I guess). 

Thanks for looking at this issue !

**Comment by stefan-niedermann** [comment]
Web interface does return `HTTP Status 500` with roughly the following content (as an html document):

```
Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: xx.xx.xx.xx
    Request ID: XxxxxR@NxxxxxG@xxDs
```

I would expect the notes server app to return `HTTP Status code 507 Insufficient Storage` in this case, which can appropriate be handled by the Android client.

**Comment by stefan-niedermann** [comment]
I opened a issue at the server repo: https://github.com/nextcloud/notes/issues/438

As soon as this has been implemented at the server, we can give a hint in the android client what's going wrong :)
