### ISSUE TITLE
Cannot connect to Nextcloud secured with SSL

### ISSUE THREAD

**Issue by targor** [stefan-niedermann/nextcloud-notes#682]
**Describe the bug**
When selecting my nextcloud account (The Nextcloud app (3.9.2) is installed and working), then the Notes app tries to connect to my server, which uses https and has a redirection from http to https. The Notes app alerts me with this message:

> com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 302

No sync possible, i just get this message.

**To Reproduce**
1. Start Notes app

**Expected behavior**
Syncing with my Notes app on my nextcloud server

**Server**
 - Nextcloud-Version: 16.0.4 RC1
 - Nextcloud Notes-Version (server app): 2.4.4
 - PHP-Version: dunno...

**Comment by stefan-niedermann** [comment]
Interesting. Why does your server return 302 in the first place? Do you have any kind of special setup (e.g. only available on local LAN)?

> Nextcloud Notes-Version (server app): 2.4.4

Are you sure that this is the version of the server app? It looks more like the version of the android app...

**Comment by targor** [comment]
Oh sorry, no, the 2.4.4 is the android app.. the server version is 3.1.1

I am running a nextcloud in docker coupled with traefik. it it available via internet and the nextclkoud app itself works without problems connecting to it.

The 302 happens because traefik automatically redirects all http requests to https.

**Comment by targor** [comment]
I think it would be better if traefik generates 301, this seems to be a known problem (https://github.com/containous/traefik/issues/671)

**Comment by stefan-niedermann** [comment]
@tobiasKaminsky should in your opinion the SSO API automatically redo the request when a 301 or 302 is returned or do i need to handle this in the 3rd party clients? also cc @david-development

**Comment by targor** [comment]
I dont really know how this works internally in android or within SSO, but i thought, that the Notes android app uses my nextcloud account data from the nextcloud app right? Does it not provide the information that the server uses https? because when configuring the nextcloud app on android i used the url as "https://" so the notes app should have this information too and instead of trying to reach the server on http, it should usé the original saved https url then there wouldnt be a problem anymore. But as i said, i dont know how this works internally and maybe i am totally wrong with this tought.

**Comment by tobiasKaminsky** [comment]
@stefan-niedermann Files app tries always https and only if this does not succeeds or if there is a redirection (which we follow), we fallback to http. This is on initial setup.
After that we store the correct url, e.g. if you redirect from nc.cloud.com to cloud.com/nextcloud we store the later and use this for any subsequent call.

**Comment by targor** [comment]
What is the "Files" app?

**Comment by tobiasKaminsky** [comment]
Nextcloud Files: https://play.google.com/store/apps/details?id=com.nextcloud.client&hl=de

**Comment by targor** [comment]
Ah you mean the nextcloud main app ... as i said.. i configured my account in the nextcloud app with leading https. so i wonder why http is used.. also.. the nextcloud app (files) itself works without problems. maybe the problems lies in a subroutine of the (files) app within the api that is used by your notes app?

**Comment by tobiasKaminsky** [comment]
This is indeed quite strange, as with newest Notes app, the Notes app itself does not do any network traffic at all, but only ask the Files app to query it, so if it is working on Files it should work also on Notes…

**Comment by targor** [comment]
maybe in your request method using the nextcloud property .setFollowRedirects(true); would help. currentyl this options maybe not activated:

private ResponseData requestServer(String target, String method, Map<String, String> parameter, JSONObject requestBody, String lastETag) throws Exception {
        NextcloudRequest.Builder requestBuilder = new NextcloudRequest.Builder()
                .setMethod(method)
                .setUrl(API_PATH + target);
        if (parameter != null) {
            requestBuilder.setParameter(parameter);
        }

**Comment by targor** [comment]
I have now tried to exclude problems with my server and reinstalled the docker containers set up everything new and the problem seem to be gone now. This is really odd. I think it may was an error in my server architecture/docker that changed over time maybe? ... So it seems not a problem in your soruce or nextclouds.. i think it had something to do with traefik

**Comment by stefan-niedermann** [comment]
Okay, so i close this as not reproducable / local environment problem.

Please feel free to reopen if the issue occurs again.

**Comment by stefan-niedermann** [comment]
@targor are you using the OID Connect app for your Nextcloud?
