### ISSUE TITLE
Sort notes alphabetically

### ISSUE THREAD

**Issue by szmt** [stefan-niedermann/nextcloud-notes#683]
Title basically says it all: in some cases it is faster to find notes if you can sort them by name and not the default when they were last edited

**Comment by stefan-niedermann** [comment]
Can you please explain what benefit you are expecting? In which way is "sorted by recent" bad for you?

This has been discusses some tim ago (https://github.com/stefan-niedermann/nextcloud-notes/issues/92#issuecomment-187565250) and i still can not see a benefit.

**Comment by stefan-niedermann** [comment]
Closing in favor of our discussion in #92 (to avoid duplicate issues)
