### ISSUE TITLE
Disable preview in note list

### ISSUE THREAD

**Issue by szmt** [stefan-niedermann/nextcloud-notes#684]
If using names to organize notes the preview in the note list is obsolete. It would decrease the clutter in the note list if you could disable the preview in the settings.

**Comment by stefan-niedermann** [comment]
Sorry, i do not understand your request. You mean the second line (we call it "excerpt") below the title?

**Comment by szmt** [comment]
Exactly, the excerpt is exactly what I mean. It is simply information that not everybody needs, so it would be quite helpful to disable the second line since it cleans up the gui and therefore improves the clarity of the UI.

**Comment by stefan-niedermann** [comment]
Many notes start with a plain headline like

```
# ToDos
```

The excerpt is helpful to get an idea of the content. This is a very common pattern on Android (Compare to GMail, Messages, Whatsapp, Telegram, ...) and i think, we should not remove the excerpt. (though Title and category should be centered if no excerpt is given #374).

You can use the Note List widget (which does currently not contain the excerpt).

**Comment by szmt** [comment]
As mentioned in the initial post it shouldn't be removed for everyone, but be decided by the user via a setting. (which isn't an unusual pattern either).
So basically it could display an empty string instead of the excerpt if the user decides to. This way there wouldn't be any changes in the UI necessary.

**Comment by szmt** [comment]
> You can use the Note List widget (which does currently not contain the excerpt).

I am using a single page launcher (Kiss), so the list widget won't be an efficient work-around.

**Comment by stefan-niedermann** [comment]
> which isn't an unusual pattern either

Yes, it is. None of the above mentioned apps have an option to remove the second line.

We can not make a setting for each aspect that one (of thousands) user requested, i'm sorry. I only add settings, if there are many users who desire the exact same issue, or if it is a really common pattern. And only then if i believe that the benefit will be higher than the drawbacks for the majority of the users.

Maybe you read the comment i linked in the other image 😉 

![Settings](https://camo.githubusercontent.com/b0e4f87130b2c966da0fe34ce0b2ceb4a6a2fe52/68747470733a2f2f626c6f672e636f64696e67686f72726f722e636f6d2f636f6e74656e742f696d616765732f75706c6f6164732f323030362f31312f366130313230613835646364616539373062303132383737366665633634393730632d70692e706e67)

**Comment by ngthr** [comment]
Hello, 
New to the app, new to Android.
Thanks for your work !

I understand this request.
It refers to a feature allowing to condense notes. In "Simplenote" the option is called "Condensed notes".
I would really appréciate this request to be considered :  most users know the content on a note from its title.

Possible one day ?

**Comment by stefan-niedermann** [comment]
Since we can set the title separately from the content now, i will think again about this topic. Granted: We have a "compact mode" in the Deck app, too. Though i will have to watch the amount of settings which i am able to maintain (especially because we also introduced the grid view a few versions ago).

I will think about it again, but no promises.
