### ISSUE TITLE
LiberaPay button has different size than other buttons

### ISSUE THREAD

**Issue by aha999** [stefan-niedermann/nextcloud-notes#695]
**Describe the bug**
(See screenshot) on the github page the liberapay donation button doesn't have the same size as the other buttons.
![ruC8fwKb6Z](https://user-images.githubusercontent.com/50620416/72737488-f4bbab00-3b9f-11ea-93a5-0fac264e811f.png)

**Comment by stefan-niedermann** [comment]
Well, LiberaPay doesn't offer buttons in the same format like Google and F-Droid do... Maybe you should open the ticket upstream at LiberaPay?

**Comment by aha999** [comment]
Sorry but i don't know what a ticket upstream is... Like issue report?

**Comment by aha999** [comment]
Unless someone else made a github project for liberapay button to have the same design... like the paypal button you're using that is from someone's github project

**Comment by aha999** [comment]
wait that is you haha

**Comment by stefan-niedermann** [comment]
😂😂 yes, it was me. Didn't have time yet for yet another button ;-)

**Comment by stefan-niedermann** [comment]
Upstream means: Find liberapay repository or support and report the problem to them 😉

**Comment by aha999** [comment]
https://github.com/liberapay/liberapay.com/issues/1650

**Comment by stefan-niedermann** [comment]
Great, i subscribed to your issue and will update the button if they create one :)

**Comment by aha999** [comment]
@stefan-niedermann, it got closed XD
WELL...You have a Paypal button already made and all... you could just use that one and change the logo and text to Liberapay and later maybe others like patreon... since it doesn't look like they're interested.
https://github.com/liberapay/liberapay.com/issues/1650

**Comment by aha999** [comment]
There. I made it similarly with photoshop. my first repository :)
if you have any tips on things i should know, let me know!
You can try the icon from here:
https://github.com/aha999/DonateButtons

**Comment by stefan-niedermann** [comment]
I like it very much :) Just forked your repo and added your button to Nextcloud Notes and Nextcloud Deck. Thank you :)

> it got closed XD

No it didn't, it's still open.

![grafik](https://user-images.githubusercontent.com/4741199/72965251-21e4a500-3dbc-11ea-8802-b18d93fa332b.png)

But they don't sound like they would create a button which aligns to Play Store and F-Droid :man_shrugging:
