### ISSUE TITLE
Nextcloud Text Editor

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-notes#698]
Hi, 
is it possbile to use the Nextcloud Text webview for note editing?

In the latest Nextcloud Android App it's possible to edit markdown files directly:
https://github.com/nextcloud/android/pull/4890

**Comment by stefan-niedermann** [comment]
Would be great, but the performance of a WebView can not keep up with a native solution, unfortunately. We already did tests with several WebView solutions and non of them were satisfying from a performance point of view.

We can discuss alternative solutions in #549. If you know one you can suggest them or test one the "Ready to analyse"-solutions in the first comment.
