### ISSUE TITLE
Swipe to delete broken

### ISSUE THREAD

**Issue by quthla** [stefan-niedermann/nextcloud-notes#714]
**Describe the bug**

Swiping from right to left does not work. It always bounces back. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Server**
 - Nextcloud-Version: 
 - Nextcloud Notes-Version (server app): 
 - PHP-Version: 

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): F Droid 2.9
 - F-Droid or Play Store: 
 - Device: [e.g. Samsung Galaxy S10] OP6T
 - Android-Version: [e.g. 8] 10

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Yes it works, but we reduced the sensitivity because many people complaint that it was too sensitive previously. (https://github.com/stefan-niedermann/nextcloud-notes/issues/663 from @paskalito)

I guess it's impossible to fully satisfy both 🤷‍♂🙁

Please try to swipe quicker.

Mayve i will increase sensitivity again in a future version because i personally am also not satisfied and would expect a higher sensitivity.

**Comment by quthla** [comment]
I got it working once in like 20x. Not sure how it's on your device but on mine it's absolutely shit

Swiping from left to right works perfectly though

**Comment by paskalito** [comment]
heyo ^^ lif is so ironic..
howewer as i wrote this https://github.com/stefan-niedermann/nextcloud-notes/issues/663#issuecomment-580188308 i think there is something not actually/coherently working as intended i guess..

**Comment by quthla** [comment]
To be honest, I never deleted anything by accidentally swiping so far. And now, I can't delete anything, even if I wanted to.

**Comment by stefan-niedermann** [comment]
@paskalito the default implementation of the `ItemTouchHelper` has two ways of achieving a succesfull swipe.

1. **Swipe speed**: If you are swiping very quickly, but only a short distance, the swipe-event will be dispatched
2. **Swipe distance**: If you are swiping for a very large distance slowly, the swipe-event will also be dispatched.

Both values are configurable. One can overwrite the given `defaultValue`. In the first case this is some kind of factor which can easily be multiplied to decrease sensitivity. In the second case this is a percentage of the screen width.

@paskalito you have mentioned multiple times the behavior of "Conversations", which seems to completely disable the first way. I do not want to mimic this behavior. I know the first way from each other app from Telegram to GMail and it feels just natural to swipe a shorter distance if you swipe really fast.

@quthla I also noticed a difference when comparing Notes with GMail: the degree which you are swiping is in the GMail app pretty clear `45°` - below this value a Pull 2 Refresh is performed, above this value a horizontal swipe gesture is performed. This seems not to be the exact same behavior like in Notes. In Notes one has to really move the finger exactly horizontal to perform a swipe action (which is naturally easier from left to right than from right to left for right-handers - which might explain why you are able to mark as favorite but not to delete).

I want to adjust the behavior to GMail, but to be honest i have currently no idea what exactly they are doing different. Ideas and suggestions and PRs are welcome of course :)

Hope i could clarify the whole situation about the swipe-mechansim a little bit?

**Comment by quthla** [comment]
This issue is extremely weird. I found out that you can move your finger up and nothing will happen. Only when you move your finger even the slightest bit down, it will cancel the swipe instantly. 

I've tried some things but nothing would fix it.

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SwipeToDeleteCallback.kt

This is how it's implemented in Firefox Preview (Fenix). You can move your up and down as much as you wish and it'll still work. That leads me to believe the issue might be somewhere in the code, maybe not even in the ItemTouchHelper code itself.

**Comment by paskalito** [comment]
> This issue is extremely weird. I found out that you can move your finger up and nothing will happen. Only when you move your finger even the slightest bit down, it will cancel the swipe instantly.

**Comment by stefan-niedermann** [comment]
Possible solution for @quthla issue: https://stackoverflow.com/a/29946734

Will have to investigate this further.

**Comment by quthla** [comment]
Now that you mention it, it is really because of pull to refresh. I guess that'll solve it then.

**Comment by quthla** [comment]
Has your investigation yielded any results?

**Comment by stefan-niedermann** [comment]
We tried the solution at the Deck app where we have a similar scenario.

Like i said; this will solve your issue @quthla (unfortunately not the issue from @paskalito)

I will implement this in the near future.

**Comment by stefan-niedermann** [comment]
Disabling pull2refresh will be disabled while one is dragging an item.

This will be shipped with the next released version **after** `v2.11.3`.
