### ISSUE TITLE
Multiselect broken

### ISSUE THREAD

**Issue by quthla** [stefan-niedermann/nextcloud-notes#715]
**Describe the bug**

Multiselect does work but when selecting is canceled, notes can't be opened anymore. They'll just be selected. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Server**
 - Nextcloud-Version: 
 - Nextcloud Notes-Version (server app): 
 - PHP-Version: 

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): F Droid 2.9
 - F-Droid or Play Store: 
 - Device: [e.g. Samsung Galaxy S10] OP6T
 - Android-Version: [e.g. 8] 10

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Thanks for reporting. Will be fixed in the next version.
