### ISSUE TITLE
Change the font color for Markdown

### ISSUE THREAD

**Issue by Valdnet** [stefan-niedermann/nextcloud-notes#716]
**Is your feature request related to a problem? Please describe.**
When using a dark theme with "` `" the font is hardly visible.

![obraz](https://user-images.githubusercontent.com/47037905/73614424-4a13a580-45ff-11ea-8b82-706eb56f200a.png)

**Describe the solution you'd like**
Change the font color for "` `''.

**Describe alternatives you've considered**
Change the background color for "` `''.

**Additional context**
The cursor for "` `" is also not visible.

![obraz](https://user-images.githubusercontent.com/47037905/73614483-c73f1a80-45ff-11ea-81a5-4ba223174fba.png)

App:
Android 6
Notes Android 2.10.0

**Comment by stefan-niedermann** [comment]
Hi @Valdnet,

we are currently only able to change the background color (as you described as alternative).

The result looks like this:

![grafik](https://user-images.githubusercontent.com/4741199/73616314-23ab3580-4612-11ea-9311-c3b5fc936bf9.png)

Would this solve the issue for you?

**Comment by Valdnet** [comment]
Hi @stefan-niedermann,

A suggested change of background color will solve this problem.
Thank you.
