### ISSUE TITLE
the f-droid apk not found 

### ISSUE THREAD

**Issue by arm2arm** [stefan-niedermann/nextcloud-notes#722]
when i try to install the app from the f-droid repo it shows an error: 
![Screenshot_20200205-102210](https://user-images.githubusercontent.com/2283443/73828581-d2fa2f00-4801-11ea-9e3a-0f878dfb0f94.png)

**Comment by stefan-niedermann** [comment]
Your f-droid cache is outdated. There are already more recent versions available.

F-Droid only keeps the latest three versions directly available (this old version can still be found in the archives).

Please update your F-Droid cache with Pull 2 Refresh and if this doesn't help, delete the app data of F-Droid and start it again.

**Comment by arm2arm** [comment]
Thanks!
fixed by clearing the cache of the f-droid and restarting again!

**Comment by stefan-niedermann** [comment]
You're welcome :)
