### ISSUE TITLE
Multiple notes folders

### ISSUE THREAD

**Issue by aleixq** [stefan-niedermann/nextcloud-notes#724]
**Is your feature request related to a problem? Please describe.**
Sometimes both personal and organization notes are needed and thes must be separated. So different directories are needed. I think that a way to choose the root directory will be great. Also a way to add more than a single root notes directory. 

**Describe the solution you'd like**
As it is in qownnotes a way to define different directories. This functionality is explained in https://www.qownnotes.org/Knowledge-base/How-to-use-the-Set-notes-folder-feature-to-categorize-notes-using-real-filesystem-directories. For each root notes folder you have:
 - name
 - active folder
 - local path to notes directory
 - if subdirectories in this directory must be used
 - if git must be used. 
 - remote path to notes folder.

**Describe alternatives you've considered**
Using nexcloud files app

**Comment by stefan-niedermann** [comment]
Hi,

did you consider the following approaches?

For separating personal from business stuff, you could either use another Nextcloud account (this app supports adding multiple accounts) or use different categories (pressing the three-dots-menu) in an open note (nested categories are supported, e.g. `Personal/ToDo`).

**Comment by aleixq** [comment]
Hi Stefan , thank's for you proposal. But it doesn't fit my needs. Using distinct accounts is not practical as the organization notes are to be used not just for me but for other members in the organization. So it must be based in the fact that every member has a folder of his own and another one(s) that is(or are) shared(the organization folder).
 About the second option, using categories will be useful, again, if only user basis is considered, only classification is solved, but not suitable for a workflow of an organization and all of its members.

**Comment by stefan-niedermann** [comment]
Well, i think this is a hard edge case then.

You can open a issue at the server repo (we could only implement this if the server provides an API): https://github.com/nextcloud/notes/issues

But i personally would vote against this feature as it adds much complexity which would be only used by very few people.

Isn't it possible to specify the share target of your shared folder within the Notes-folder?

```
Notes/
  todo.txt
  Shared/
    meeting.txt
```

**Comment by aleixq** [comment]
> Well, i think this is a hard edge case then.
> 
> You can open a issue at the server repo (we could only implement this if the server provides an API): https://github.com/nextcloud/notes/issues
> 
Ok ! thank's Stefan, I'll ask for this feature request to the server repo.

> But i personally would vote against this feature as it adds much complexity which would be only used by very few people.
> 
> Isn't it possible to specify the share target of your shared folder within the Notes-folder?
> 
> ```
> Notes/
>   todo.txt
>   Shared/
>     meeting.txt
> ```
If I do it as you say then this shared folder will not appear to the other user's Notes app (neither web app nor android app)...

**Comment by aleixq** [comment]
I think this issue is related: https://github.com/nextcloud/notes/issues/285 (you have posted there too :) )

**Comment by stefan-niedermann** [comment]
https://github.com/nextcloud/notes/issues/285#issuecomment-448686822

> share a folder inside the notes folder to your group and let every user move that shared folder from their root directory to their notes folder

This didn't work for you? Of course every user has to move the shared folder to their correspondenting Notes folder.

**Comment by stefan-niedermann** [comment]
ping @aleixq

**Comment by aleixq** [comment]
Nice workaround, so this is the way... Thank's!
