### ISSUE TITLE
404 error for apk download

### ISSUE THREAD

**Issue by Harney** [stefan-niedermann/nextcloud-notes#727]
when I  (directly or via F Droid) try to download the latest notes apk, I receive a 404 error:

https://f-droid.org/repo/it.niedermann.owncloud.notes_75.apk

"404 Seite nicht gefunden

Wenn Sie finden, dass hier etwas fehlt, eröffnen Sie bitte ein Ticket."

**Comment by stefan-niedermann** [comment]
Please see https://github.com/stefan-niedermann/nextcloud-notes/issues/722#issuecomment-582318054
