### ISSUE TITLE
Reminder notification

### ISSUE THREAD

**Issue by xplosionmind** [stefan-niedermann/nextcloud-notes#728]
The app is awesome but it lacks a feature which I think is fundamental: **reminders**. There should be added an option to set a **reminder with notification** on the device, where after completing writing the note a button can be clicked to choose a day and time when to prompt the notification.

**Comment by stefan-niedermann** [comment]
Sorry, but this is nothing we are currently planning nor are we able to do it.

Personally i think this is out of scope for this project, but you can always add an issue [at the server repo](github.com/nextcloud/notes/issues). If they accept and implement it, this android client will follow.

**Comment by stefan-niedermann** [comment]
PS.: Please use the issue template next time :wink:

**Comment by xplosionmind** [comment]
I'm sorry. I'm relatively new to both NextCloud and GitHub. I'll be more careful next time. Thanks a lot for developing this project.

**Comment by stefan-niedermann** [comment]
No problem, you're welcome :)

Thanks for using our project.
