### ISSUE TITLE
After Upgrade: nextcloud connection lost and unreadable, quickly moving dialog

### ISSUE THREAD

**Issue by klemens-u** [stefan-niedermann/nextcloud-notes#729]
I upgraded from an older version (a few month old) to V2.10.1
1) The connection to my nextcloud instance is lost (upgrade should be seamless)
2) There is an unreadable dialog moving very fast from the middle to the bottom of the screen. I captured a video to read it. It reads "Add account (Konto hinzufügen)". See screenshot below.

I also tried older Version 2.9.0 from F-Droid, but same result.

![grafik](https://user-images.githubusercontent.com/1863743/74415285-5c81b080-4e43-11ea-8f37-4db87d1b31aa.png)

**Server**
Nextcloud 17.0.3, Notes 3.1.5, PHP 7.2.24

**Smartphone (please complete the following information):**
Nextcloud Notes V2.10.1, F-Droid, 1.7.1 Galaxy Tab S3, Android 9

**Comment by klemens-u** [comment]
The problem was solved by completely wiping the app (data and cache), then re-installing V2.10.1
Would still be nice if the cause could be found, because it may be a show stopper for novice users.

**Comment by stefan-niedermann** [comment]
Can you please add the missing information from the [bug issue template](https://github.com/stefan-niedermann/nextcloud-notes/issues/new?assignees=&labels=bug&template=bug_report.md&title=)?

For example: Which version of the [main Nextcloud app](https://play.google.com/store/apps/details?id=com.nextcloud.client&hl=de) are you using?

**Comment by klemens-u** [comment]
Of course Stefan: Nextcloud Android App 3.9.2

**Comment by klemens-u** [comment]
Btw: I gave all required information from the bug template. Please add "Main Nextcloud App" to the template :-)

**Comment by stefan-niedermann** [comment]
Indeed! I will have to update the template, thanks for the hint!

Just if you have time and want: Can you downgrade to the previously used version and try to upgrade again?

I can't reproduce it. Ideal would be a Logcat snippet so we know what's going on 🙂

**Comment by klemens-u** [comment]
I tried to down- and upgrade again. And this time it worked....

**Comment by stefan-niedermann** [comment]
Well then... local circumstates 🤷‍♂ 

Just let me know if any other issues occur. Thanks for reporting though 🙂
