### ISSUE TITLE
Can not copy any text from the app

### ISSUE THREAD

**Issue by chorus12** [stefan-niedermann/nextcloud-notes#734]
**Can not copy any selected text from the app**

**To Reproduce**
1. Go to any note
2. Select any text
3. See no menu to copy selected text

**Screenshots**

**Server**
 - Nextcloud-Version: n/a
 - Nextcloud Notes-Version (server app):  n/a
 - PHP-Version: n/a

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.5.0
 - F-Droid or Play Store: 18.8.16
 - Device: moto Z2 play
 - Android-Version: 8

**Stacktrace**
n/a

**Comment by stefan-niedermann** [comment]
Well that's strange. Does this happen on each note or only on specific notes?

Can you reproduce this issue on another device?

**Comment by stefan-niedermann** [comment]
F-Droid or Play Store: 18.8.16

Errr.... ??

**Comment by stefan-niedermann** [comment]
Did you install the app the first time or did you update the app?

Which version was the latest known version that worked?

**Comment by stefan-niedermann** [comment]
Closing because of missing feedback.

**Comment by chorus12** [comment]
Sorry for late feedback - It has always been like this - all versions don't let copy the text.

**Comment by stefan-niedermann** [comment]
Please answer thr questioms from https://github.com/stefan-niedermann/nextcloud-notes/issues/734#issuecomment-588413597 and the following questions:

Are you using the version from F-Droid or Play Store?

Are you able to copy text in preview or edit mode?

**Comment by chorus12** [comment]
I am using a version from Play Store 19.2.24. In both modes I can not copy a text.  App version 2.5.0

**Comment by stefan-niedermann** [comment]
Ah, no i get it, 19.2.24 is the version of the Play Store app itself 💡 Okay, the exct version of the Store app doesn't matter, just wanted to make sure you are using the Play Store ✔️ 

So what exactly happens? Does some kind of menu pop up:

![IMG_20200322_132149](https://user-images.githubusercontent.com/4741199/77249264-20125300-6c40-11ea-9c69-dddeedb77fe4.jpg)

Is only the menu ebtry "Copy" missing or doesn't the menu appear at all?

**Comment by chorus12** [comment]
You know what I have found - when I select a text - I don't see controls for copy and paste BUT... if I wait for 30-60 seconds - it appears. 
And I have a gut feeling that it is sync related - it runs a sync first and then get's back for UI processing and pops up the controls for copy and paste.

**Comment by chorus12** [comment]
updated to 2.11 and can see the copy/paste controls now

**Comment by stefan-niedermann** [comment]
Thank you for the feedback :) Just reopen if the issue occurs again.
