### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by guitar9** [stefan-niedermann/nextcloud-notes#738]
It would be nice if the app has a widget

**Comment by stefan-niedermann** [comment]
The app has 3 widgets...... what are you missing?

**Comment by guitar9** [comment]
I mean widget for homescreen. If I want to add Widget to Homescreen I dont find any widget with galaxy s7

**Comment by stefan-niedermann** [comment]
Like i said, there are 3 widgets available:

![Screenshot_20200222-234457_Trebuchet](https://user-images.githubusercontent.com/4741199/75100410-72bf0780-55cd-11ea-9e73-0d9fc14a1436.png)

**Comment by guitar9** [comment]
Thank you. I looked for nextcloud but the appname is Notizen

**Comment by maaaaadn** [comment]
I see no widget on my Android 8.1.0!
is it because Google notes and nextcloud notes both translate to "Notizen" in the German version?
![Screenshot_20200624-080055](https://user-images.githubusercontent.com/4591716/85506528-dc3d3a00-b5f0-11ea-9bae-150947a0f478.png)


I've installed the app via F-Droid, could this be an issue?

**Comment by stefan-niedermann** [comment]
> I see no widget on my Android 8.1.0!

No reason for getting mad here.

Please open a **separate issue** and fill the issue template (as far as possible).
Important to know: Device, Manufacturer, Launcher, OS.

**Comment by maaaaadn** [comment]
> No reason for getting mad here.
I'm really sorry if you got this wrong, wasn't meant in a bad way. I heavily appreciate your work here. 
Finally I also figured out the problem: I had the app installed on the SD card first, moving it to the internal storage fixed the missing widgets.
again, I'm sorry if I upset you.

**Comment by stefan-niedermann** [comment]
Glad to hear that you already figured it out.

According to [this entry on Stackoverflow](https://stackoverflow.com/a/18662798) 
> there is no way to make a Widget to work while the app is installed on the SD-Card.
