### ISSUE TITLE
Seperate field for title

### ISSUE THREAD

**Issue by PopeRigby** [stefan-niedermann/nextcloud-notes#743]
Having a seperate field for the title makes it easier to organize your notes, because the title is treated as a seperate entity, instead of a part of the note's body.

This would work internally by formatting the title as an H1 when viewing the raw .md file.

**Comment by stefan-niedermann** [comment]
Please read: https://github.com/nextcloud/notes/issues/190

If the server does implement this, the android app will follow, though i personally do not prefer a separate title.
