### ISSUE TITLE
Butterknife is going to get deprecated

### ISSUE THREAD

**Issue by beatbrot** [stefan-niedermann/nextcloud-notes#747]
[Butterknife ](https://github.com/JakeWharton/butterknife/)is not supported anymore and Jake Wharton suggests [switching to ViewBinding.](https://github.com/JakeWharton/butterknife/#butter-knife).

I am already preparing a PR that migrates us to viewbinding (which we can do since #745 was merged). Do you have any ideas? Should we not migrate? Should we not replace it with viewbinding?

**Comment by stefan-niedermann** [comment]
I read it too, this morning. We will have some troubles with the `@BindString()`-resource bindings, but this should be doable.

Yes, i think we should go this way.

**Comment by stefan-niedermann** [comment]
Can you please contact me via E-Mail? (info@niedermann.it)

**Comment by beatbrot** [comment]
You should have mail :)
