### ISSUE TITLE
Remove toasts

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#749]
We should review the wording of the toast/snackbar messages we show. Is there a list of all of them, and in which case they would appear? Currently lots of them seem to use very technical language.

Also, some of them shouldn’t even be shown. For example: "Unknown error occured" is not helpful and just makes people distrust the app. If the error is unknown even to the app, it doesn’t need to be shown to users.

cc @stefan-niedermann @korelstar

**Comment by stefan-niedermann** [comment]
If an unknown error appear, i would like to know *why*, because it isn't anything i expected, obviously.

There should be the option in the stacktrace to display details. Can you please post them so we can actual **fix** the error instead of **hide** it? 😉

**Comment by stefan-niedermann** [comment]
Error messages are here: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/res/values/strings.xml#L52

We already try to hint at a possible solution for the occured error, but as i mentioned: If you are getting an "Unknown Error" - show us the details :)

**Comment by korelstar** [comment]
I got this "Unknown Error", too. It was shown as Toast while the app was in background, so I wasn't able to copy the details. I just got that it has a package name with sso in it. It's likely that it was this one: https://github.com/nextcloud/Android-SingleSignOn/blob/0.5.0-rc3/src/main/java/com/nextcloud/android/sso/exceptions/UnknownErrorException.java

Looks like it is thrown on behalf on [`SSOException.parseNextcloudCustomException()`](https://github.com/nextcloud/Android-SingleSignOn/blob/0.5.0-rc3/src/main/java/com/nextcloud/android/sso/exceptions/SSOException.java#L105) in [`AidlNetworkRequest.performNetworkRequestV2()`](https://github.com/nextcloud/Android-SingleSignOn/blob/0.5.0-rc3/src/main/java/com/nextcloud/android/sso/exceptions/SSOException.java#L105).

You are calling the method here: https://github.com/stefan-niedermann/nextcloud-notes/blob/v2.10.3/app/src/main/java/it/niedermann/owncloud/notes/persistence/NotesClient.java#L163

But I have no idea where the Toast is generated. :confused:

**Comment by stefan-niedermann** [comment]
@jancborchardt has it been a snackbar or a toast when you saw it?

When we are synchronizing, we see whether the context is an activity (user has the app opened). In this case we display a **snackbar** which can provide more information.

If the context is not an activity, we cannot display a snackbar but only a **toast**. The only known case is when thr synchronization has been triggered e.g. by the new **background synchronization**.

I aggree that we probably can hide the Toasts at all because they don't provide much information and are pretty useless at all:

- If a background sync fails for whatever reasons one time, it will be executed the next time.
- If a background sync fails for whatever reasons every time, it will most likely also fail every time when the user has opened the app (in this case the user sees a detailled reason)

**Comment by jancborchardt** [comment]
You’re right of course! :) Got the error some more times, here:


Some points:
- Immediately after this error is shown, it syncs. There is no actual problem.
- Showing a Snackbar inside the app is ok as it provides a "More" link with a popover to copy the info. But a Toast showing when you are in other apps is confusing – not without a way of knowing which app it is from or how to resolve it – there is no link like in the Snackbar inside the app. I actually didn’t know for a long time that it was from Notes. :D
- For info: I'm always using latest Nextcloud dev client and latest Notes app from F-Droid.


Here’s 2 times it happened. `cloud.example.com` is replacing my domain, but I have no idea what the IP addresses are.

```
App Version: 2.10.3
App Version Code: 81
Files App Version Code: com.nextcloud.client

---

OS Version: 3.4.0-perf-g284400a(de8920e892)
OS API Level: 27
Device: FP2
Model (and Product): FP2 (FP2)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to cloud.example.com/217.70.186.101 (port 443) from /10.107.238.248 (port 48189) after 60000ms
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:163)
	at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:98)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:413)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:320)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:284)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```


Another time:

```
App Version: 2.10.3
App Version Code: 81
Files App Version Code: com.nextcloud.client

---

OS Version: 3.4.0-perf-g284400a(de8920e892)
OS API Level: 27
Device: FP2
Model (and Product): FP2 (FP2)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: Unable to resolve host "cloud.example.com": No address associated with hostname
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:163)
	at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:98)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:413)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:320)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:284)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by jancborchardt** [comment]
> I aggree that we probably can hide the Toasts at all because they don't provide much information and are pretty useless at all:

Yup, exactly! :) That would already be much better → you’ll see the error anyway the next time you open the app, and since it works offline, nothing should be lost.

**Comment by stefan-niedermann** [comment]
@jancborchardt did this happen when you had an unreliable internet connection like in an elevator or did you switch from wifi to mobile data in these scenarios?

**Comment by jancborchardt** [comment]
> @jancborchardt did this happen when you had an unreliable internet connection like in an elevator or did you switch from wifi to mobile data in these scenarios?

Yup, am in Indonesia at the moment with connectivity generally being a bit spotty. Generally I’m getting lots of different errors when you have spotty connectivity, making it look more broken than it is?

One popping up almost every time I open the app now is **Sync failed: Is the Notes app installed on the server?**

```
App Version: 2.10.3
App Version Code: 81
Files App Version Code: com.nextcloud.client

---

OS Version: 3.4.0-perf-g284400a(de8920e892)
OS API Level: 27
Device: FP2
Model (and Product): FP2 (FP2)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:163)
	at it.niedermann.owncloud.notes.persistence.NotesClient.putNote(NotesClient.java:107)
	at it.niedermann.owncloud.notes.persistence.NotesClient.editNote(NotesClient.java:122)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:318)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:284)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="de" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
		Nextcloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=1125420102">
		<meta name="theme-color" content="#0082c9">
		<link rel="icon" href="/apps/theming/favicon?v=6">
		<link rel="apple-touch-icon" href="/apps/theming/icon?v=6">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
		<link rel="manifest" href="/apps/theming/manifest?v=6">
		<link rel="stylesheet" href="/apps/deck/css/activity.css?v=1f9fea20-6">
<link rel="stylesheet" href="/apps/files_pdfviewer/css/style.css?v=ca9f0d77-6">
<link rel="stylesheet" href="/core/css/guest.css?v=098810f0-6">
		<script nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0=" defer src="/core/js/dist/main.js?v=098810f0-6"></script>
<script nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0=" defer src="/js/core/merged-template-prepend.js?v=098810f0-6"></script>
<script nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0=" defer src="/core/search/js/search.js?v=098810f0-6"></script>
<script nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0=" defer src="/apps/files_pdfviewer/js/previewplugin.js?v=098810f0-6"></script>
<script nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0=" defer src="/core/js/dist/share_backend.js?v=098810f0-6"></script>
<script nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0=" defer src="/apps/files_videoplayer/js/main.js?v=098810f0-6"></script>
<script nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0=" defer src="/apps/notifications/js/notifications.js?v=098810f0-6"></script>
<script nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0=" defer src="/core/search/js/searchprovider.js?v=098810f0-6"></script>
<script nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0=" defer src="/core/js/files/fileinfo.js?v=098810f0-6"></script>
<script nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0=" defer src="/core/js/files/client.js?v=098810f0-6"></script>
		<script defer src="/apps/accessibility/js/accessibility?v=0" nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0="></script><link rel="stylesheet" href="/apps/theming/styles?v=6"/><script defer src="/apps/theming/js/theming?v=6" nonce="K2hiTG9rOXAxWCszdDRlc2xOREM3UzdBdmtGQ0RaZXdCSVhwQUlGU00zWT06alh5S3hqZGVyQWpuL2M3bHhJZWFuUmExaGl4M2Q4WGhkZmZZVjlRQVh5Yz0="></script>	</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			This application requires JavaScript for correct operation. Please <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">enable JavaScript</a> and reload the page.		</div>
	</div>
</noscript>
				<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo">
								<h1 class="hidden-visually">
									Nextcloud								</h1>
															</div>
						</div>
					</header>
								<main>
					<div class="error error-wide">
	<h2>Internal Server Error</h2>
	<p>The server was unable to complete your request.</p>
	<p>If this happens again, please send the technical details below to the server administrator.</p>
	<p>More details can be found in the server log.</p>

	<h3>Technical details</h3>
	<ul>
		<li>Remote Address: 114.124.244.26</li>
		<li>Request ID: grywxbYYTI8oNvBGxEVs</li>
			</ul>

	</div>
				</main>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener" class="entity-name">Nextcloud</a> – a safe home for all your data			</p>
		</footer>
	</body>
</html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:438)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:135)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:118)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:134)
	at android.os.Binder.execTransact(Binder.java:697)

```

**Comment by stefan-niedermann** [comment]
So, Status Code says `500` which indicates a server problem. What does your server log say?

**Comment by jancborchardt** [comment]
Right, forgot to say that everything actually syncs alright except 1 note, which I then deleted after transferring the contents into another note.

This note indeed shows up in the log, as being locked (?):
```
Error | index | OCP\Lock\LockedException: "Notes/Nextcloud/☁ Nextcloud.md" is locked
```

And the file actually still shows up in the web interface. Trying to delete says "Error deleting file" and the log says:
```
OCA\DAV\Connector\Sabre\Exception\FileLocked: "Notes/Nextcloud/☁ Nextcloud.md" is locked
OCP\Lock\LockedException: "files/a7535b10fa767eab69a479187dd75cc6" is locked
```
That server is not on 18 yet so wasn’t locked via the interface, so I wonder how that happened? cc @rullzer maybe?

**Comment by stefan-niedermann** [comment]
Maybe @korelstar knows something about this, i saw some other issues related to Locked files in the server repo - i would say it was good that we displayed the snackbar and got a hint to the root cause of the sync issue 😜

**Comment by korelstar** [comment]
People have this `LockedException` from time to time. Currently, most of them come from the Ransomware Recovery App, see https://github.com/undo-ransomware/ransomware_detection/issues/26. Do you use this app, too?

Otherwise, I suggest to manually unlock that file: https://help.nextcloud.com/t/file-is-locked-how-to-unlock/1883 - the real root cause for a LockedException (except for Ransomware Recovery App) is typically an individual thing :worried:

**Comment by jancborchardt** [comment]
I don’t use the Ransomware recovery app, no.

Phew, that manual unlocking process sounds scary … :\
@rullzer especially since it seems to happen to so many people and is rather difficult to fix, shouldn’t we track it down?

**Comment by jancborchardt** [comment]
Also @stefan-niedermann since we do know what the issue is, the error could be more specific than a generic "Sync error" but more like:
> Could not sync locked file `filename`

**Comment by stefan-niedermann** [comment]
Nope, the server doesn't tell exactly what's going wrong. @korelstar would have to use another HTTP ststus for that case.
