### ISSUE TITLE
Split up NoteSQLiteOpenHelper ✂️

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#750]
The class has grown and become very large with over 1000 lines of code.

The class should therefore split up into

- one abstract class (`AbstractNotesDatabase`?) that does all the creation-, index- and upgrade stuff and
- one class (`NotesDatabase`?) that extends the first and adds the access-methods for manipulating the actual values

**Comment by beatbrot** [comment]
I think we could also think about migrating to [Android Room](https://developer.android.com/training/data-storage/room) in the long run.

I do get, that the effort of migrating to room would be colossal, but in return we'd get a more declarative view on the database with less code and more type safety.

But I agree, that splitting the class up would be a good first step and a way easier fix.

**Comment by stefan-niedermann** [comment]
Out of scope for this issue, especially because i have limited resources and there are way more important issues on the board :)

But in the long run: yes.
