### ISSUE TITLE
Removal of locally changed notes dangerous

### ISSUE THREAD

**Issue by markus2330** [stefan-niedermann/nextcloud-notes#751]
In general I like the functionality of that notes can be modified and removed even without having Internet connection.

**Is your feature request related to a problem? Please describe.**

My problem was that I was playing around what swiping left and right does. When doing so, I accidentally removed a note that was locally modified.

**Describe the solution you'd like**

That there is also a local copy of removed files that gets synchronized. Then accidental removing would not lead to lost changes.

**Describe alternatives you've considered**

Asking about if something should be really removed.

**Additional context**

**Comment by stefan-niedermann** [comment]
Hi @markus2330,

thank you for your feedback.

The [undo] toast works, even if one is offline and deletes a note.

Everything further should be covered by #238 (once this has been implemented).

Regards
