### ISSUE TITLE
Note editor - Dates in the DD.MM.YYYY notation are detected as enumerations

### ISSUE THREAD

**Issue by Geosearchef** [stefan-niedermann/nextcloud-notes#756]
When editing a note and typing a date in the DD.MM.YYYY notation, it is detected as an enumeration and therefore is indented. This indent can not be cancelled, new lines are automatically indentend and get assigned a number. 

1. Edit a note
2. Type a date like 04.03.2020
3. It should be indented, new line adds another enumteration point/numeral

**Expected behavior**
Nothing happens. 

**Screenshots**
![Screenshot_20200304-124050](https://user-images.githubusercontent.com/5748922/75876591-42216e00-5e16-11ea-95bc-ac34412cae28.png)

**Server**
 - Nextcloud-Version: 17.0.2
 - Nextcloud Notes-Version (server app): 
 - PHP-Version: not relevant

**Smartphone**
 - Nextcloud Notes-Version (android app): v2.10.3
 - F-Droid
 - Device: Honor 8
 - Android-Version: 7

**Comment by stefan-niedermann** [comment]
Thank you for the feedback.

This wi be fixed in https://github.com/stefan-niedermann/nextcloud-notes/issues/549

Regards
