### ISSUE TITLE
higher density on file list

### ISSUE THREAD

**Issue by marmouille** [stefan-niedermann/nextcloud-notes#760]
Hi everyone,
On my Samsung A5 the filelist displays only 6 items. Each Row contains 2 lines of text + one large spacer.

Isn't it a good idea to offer a more compact display option. By the way, files are sorted by creation date. It would be nice to give choice is sorting criteria (last editing for example).

Thank you for reading
Ciao

**Comment by stefan-niedermann** [comment]
Can you please provide a screenshot? The files are sorted by last modified, not creation date.

**Comment by marmouille** [comment]
`last modified` yep you're right, my mistake. I meant 'last opened'. As I write it I realize it must be more complicated that 'last modified' or 'last created'. Any way the main purpose of my post was the density of the file list.In a first approach, is it possible to reduce drastically the spacer between rows? Roughly 40% of the screen is empty space now.

**Comment by stefan-niedermann** [comment]
As i said: Can you please provide a screenshot?

**Comment by marmouille** [comment]
![Screenshot_20200311-083525_Notes](https://user-images.githubusercontent.com/16467263/76403072-a6977c80-6384-11ea-9bae-42f34cfd21dc.png)
Here is my situation now. I'm not sure this screenshot is very interesting and I have no way to modify the picture to show what I expected until a few days. Sorry. And thank you for your quick replies.

**Comment by stefan-niedermann** [comment]
Sorr, but this is by intention. If we increase the density, there would be more content visible, that's true, but it would be harder to scan the content and orientate, especially on the timeslots.
