### ISSUE TITLE
Adjust theme for each account

### ISSUE THREAD

**Issue by hitam4450** [stefan-niedermann/nextcloud-notes#762]
Hi,

To make the Look & Feel compatible with the nextcloud app, Theming should be included.

I do have multiple instances of Nextcloud running and each instance does have a separate theming color to be able to distinguish between the instances right at looking at the screen !

I am sure, this will be very helpful for the NextCloud Notes app as well !!

Best regards, hitam 4450

**Comment by stefan-niedermann** [comment]
Will be fixed starting with version `v2.13.0`.
