### ISSUE TITLE
Search on big notes does not work

### ISSUE THREAD

**Issue by chorus12** [stefan-niedermann/nextcloud-notes#769]
Search on big notes does not work

**To Reproduce**
Make a note with 10K+ characters and try making a search of a text in the note.
The interface freezes and you even can not type the word to search. 

**Server**
 - Nextcloud-Version: 16.0.1
 - Nextcloud Notes-Version (server app): 3.2.0
 - PHP-Version: PHP 7.3.6

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.5.0
 - F-Droid or Play Store: Play Store 19.2.24
 - Device: Moto Z2 play
 - Android-Version: 8

**Comment by chorus12** [comment]
updated to 2.11 - still freezes and even crashes.

**Comment by stefan-niedermann** [comment]
Well that's no excuse of course and i will try to find a way to make the search more performant, but are you sure you are using the right tool? What kind of notes do you use that take more then 10k characters? Are you writing a book with my app? 😄

**Comment by chorus12** [comment]
Danke. Kind of :) it's a file with daily notes

**Comment by chorus12** [comment]
And as a side note - a control that allows jumping to the end of file or a beginning would be very handy for big files.

**Comment by stefan-niedermann** [comment]
You can just use the upper control at the first occurrence. It will simply wrap back to the last occurrence, then you are at the end.

**Comment by Isaac-Graham** [comment]
Hello there. We are trying to fix this issue. Are there too many repeated search pattern in your note? This issue is reproduced only when the search pattern occurs too many times in the note on my phone/AVD.

**Comment by stefan-niedermann** [comment]
Will be fixed in `v2.11.11`, thanks @Isaac-Graham & team!

**Comment by Isaac-Graham** [comment]
u r welcome : )
