### ISSUE TITLE
In-note serch for big notes

### ISSUE THREAD

**Issue by chorus12** [stefan-niedermann/nextcloud-notes#770]
Hallo. 
At the moment the search in big notes does not perform well and the interface just highlights words inside a note and there is no way to cycle through all occurrences of a search word - you have to manually scroll the whole note. And if the note is 5k+ characters - it is not possible. 
Would be great if a search in Notes work like in a regular text editor - giving controls to jump to the next occurrence of a word. 
Regards.

**Comment by stefan-niedermann** [comment]
Hello,

which version of the Notes app are you using exactly, please? From F-Droid or Play Store?

**Comment by stefan-niedermann** [comment]
I am asking because the current version provides controls for jumping to the next / prev occurence of a word.

![photo6035005122414752070](https://user-images.githubusercontent.com/4741199/77247593-fb63ae80-6c32-11ea-9fcc-9851622627d3.jpg)

**Comment by chorus12** [comment]
I am using 2.5.0 from Play Store - I don't have those controls

**Comment by chorus12** [comment]
Sorry - I've updated to 2.11.3 and I can see the controls.

**Comment by stefan-niedermann** [comment]
Thank you for the feedback :) Just reopen if the issue occurs again.
