### ISSUE TITLE
Share note results in a link to "http://o.ä.,/"

### ISSUE THREAD

**Issue by KopfKrieg** [stefan-niedermann/nextcloud-notes#774]
**Describe the bug**
If I open the app, click on a note (edit mode), and then try to share it via the three-dot-menu, I get the following link: "http://o.ä.,/" (in Punycode: "http://o.xn--4ca.,/")

**To Reproduce**
1. Open the app
2. Click on a note
3. Click on the three-dot-menu on the top-right, then click share
4. Share/Open it in your browser
5. The browser tries to navigate to http://o.ä.,/

**Expected behavior**
A direct link to the note should be shared, either generated via the share option of Nextcloud or maybe just the internal link (e.g. "https://example.org/apps/notes/note/1234")

**Server**
 - Nextcloud-Version: 18.0.3
 - Nextcloud Notes-Version (server app): 3.2.0
 - PHP-Version: 7.3.16

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): v2.11.3
 - F-Droid or Play Store: F-Droid
 - Device: OnePlus 2
 - Android-Version: 9

**Comment by stefan-niedermann** [comment]
Hey, the "share"-function is supposed to share the complete text-content of the note to another app (not a link). It's more like a "send" - the result is not an URL or so, it's the *actual content of the note*.

What exactly is the content of the note you tried to share?

I guess you have somewhere in your note an URL which the browser tries to open.

**Comment by KopfKrieg** [comment]
😂 Oh my … it never occurred to me that it might share the content.

Unfortunately I can't give you the content of the note, as it contains private information. I'll close the issue. Sorry about that :)

**Comment by stefan-niedermann** [comment]
No problem^^
