### ISSUE TITLE
New empty notes are created massively

### ISSUE THREAD

**Issue by Toniozzzz** [stefan-niedermann/nextcloud-notes#778]
Describe the bug
When i created a new note and close the app, synching with the nextcloud server creates a lot of empty new notes (near 180 !).

Steps to reproduce 
- open Notes App
- create a note
- write something
- close the app  (it seems to be synching)
- reopen Notes app
- important number of new empty notes

I have the last version of Notes, downloaded from F-Droid.

**Comment by stefan-niedermann** [comment]
Do you have installed the Ransomware Detection app on your server?

**Comment by Toniozzzz** [comment]
Thanks for the quick answer.
Yes and i disabled it.
I forgot to tell you that i'm on the nextcloud 18 version (but i don't upgrade to the last stable release)

**Comment by stefan-niedermann** [comment]
The Ransomware Detection app has a known issue that blocks the Notes app from correct synchronizing.

Unfortunately there is nothing that we can do on our side, but you can watch this issue: https://github.com/undo-ransomware/ransomware_detection/issues/26

Regards

**Comment by Toniozzzz** [comment]
Hi,

Sorry you closed the issue but unfortunately i still have a lot of empty notes. 

Regards

**Comment by stefan-niedermann** [comment]
Well, delete them?

Or do you mean that after deactivating the Ransomware Detection app still new empty notes are created?

**Comment by Toniozzzz** [comment]
You're right, i didn't express myself very well. I have deleted a lot of notes after disabled the Ransomware Detection app but new ones appeared.
Do i need to delete the RD app ? Upgrade Nextcloud ?

**Comment by stefan-niedermann** [comment]
Yes, please try to completely delete the RD app and make sure you are using the latest versions of Nextcloud and the server side Notes app.

If it doesn't help, please create a test account and send the credentials with a link to this issue to me via E-Mail so i can reproduce the issue (info@niedermann.it)

**Comment by stefan-niedermann** [comment]
The issue was solved after deactivating an Antivirus and a PDF conversion app on the instance.
