### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by skarmoutsosv** [stefan-niedermann/nextcloud-notes#784]
When I select to add an account from the menu, the application shows at the center of the screen "Select account" and nothing more. If I press anywhere outside the message, the message disappears and a moving circle is shown for ever.

**Comment by stefan-niedermann** [comment]
Can you try to click in the bottom right corner of the dialog?

![Bildschirmfoto vom 2020-04-08 10-11-08](https://user-images.githubusercontent.com/4741199/78760440-79d58580-7981-11ea-9696-397576db54a6.png)

I guess there might be a **theming issue** in some Android versions. The confirm button have white text-color and might be invisible therefore.

Which Android version exactly are you using?

**Comment by skarmoutsosv** [comment]
I am using Android 6.0
DOOGEE-Shoot_1-Android6.0-20170118
![Screenshot_20200415-102458](https://user-images.githubusercontent.com/5363569/79311102-99325c80-7f05-11ea-9e35-0c56bd83b34c.png)

**Comment by stefan-niedermann** [comment]
1. Which version of the Notes app do you have installed?
2. Do you have it from F-Droid or from Google Play Store?
3. Which version of the [Nextcloud app](https://play.google.com/store/apps/details?id=com.nextcloud.client) do you have installed?
4. Do you have it from F-Droid or from Google Play Store?
5. Are you able to add your account in the Nextcloud app?

**Comment by skarmoutsosv** [comment]
Nextcloud Notes 2.11.8
Nextcloud 3.11.0

I really don't remember, probably both are installed from F-Droid (I don't know how to find the answer here).
Two possible installation scenarios are:
- FD inst-uninst, PS inst-uninst, FD inst. 
- PS inst-uninst, FD inst.

My Nextcloud app is working fine with my provider.

**Comment by stefan-niedermann** [comment]
Can you provide me a test account so i can reproduce this issue?
An also: can you please grab a logcat?

And can you also test another Single-Sign-On app like "Nextcloud News" or "Nextcloud Deck" (both on F-Droid for free)? Is the behavior the same or different?

**Comment by skarmoutsosv** [comment]
I tried Nextcloud Deck which has exactly the same behaviour.
In contrary, Nextcloud Talk lets me select an account and it works as expected.

**Comment by stefan-niedermann** [comment]
Okay, since the dialog is not created from Notes but from the main Nextcloud app we do not have any control about what is actually displayed
I would like to ask you to open a new issue in this repository: https://github.com/nextcloud/Android-SingleSignOn/issues

And provide all the information also there (App versions, Android versions, detailled information about your device, etc.). Please also mention that Notes **and** Deck, both have the same issue. I will watch your created issue and try to help.

Thank you
