### ISSUE TITLE
Loader doesn't stop

### ISSUE THREAD

**Issue by gundesli** [stefan-niedermann/nextcloud-notes#785]
**Describe the bug**
When I start application the loader icon turn infinitly. It doesn't desappear. I can add note without problem.

**To Reproduce**
1. Launch application

**Expected behavior**

**Screenshots**

**Server**
I have not informations immediatly.
 - Nextcloud-Version: 
 - Nextcloud Notes-Version (server app): 
 - PHP-Version: 

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: F-droid
 - Device: [e.g. Samsung Galaxy S10] Nokia 8 Sirroco
 - Android-Version: [e.g. 8] version 9

**Stacktrace**
There is not stacktrace.

**Comment by stefan-niedermann** [comment]
Hi @gundesli 

Can you please answer the following questions:

- Can you see any error message?
-Is the "Ransomware Detection"-app installed on your server?
- How many Notes (count and size) do you have?
- Did you try it via wi-fi and / or mobile data?
- Is there any error in your Nextcloud log?

Thank you

**Comment by gundesli** [comment]
Dear Stefan,

The problem is resolved, thank you for your response.

I don't know what's happened.

When i installed application there were not notes and i tested with wifi. No message error only loader during one day.

Thank you for this good application.

Best regards,
Eray

**Comment by stefan-niedermann** [comment]
You're welcome :) Have fun with the app.
