### ISSUE TITLE
Support API v1.0

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#786]
1. Add new field `apiVersion` to `Accounts`-table
2. Add `CapabilitiesWorker` which fetches the capabilities
3. If `capabilities` contain `notes`-entry, update `apiVersion` from step 1
4. If `account.apiVersion` is `null`, keep the current behavior
5. If `account.apiVersion` is not `null`, make use of the new features.

I think this will need some changes on the `NotesClient` - we will need to separate the business logic from the technical "connecting to SSO"-part.

**Comment by korelstar** [comment]
Please note, that every response (from Notes version 3.3) will send the HTTP header `X-Notes-API-Versions` which will give the same result like Capabilities API. Therefore, you can update `account.apiVersion` on every request without the need to make an extra request to the Capabilities API.

**Comment by stefan-niedermann** [comment]
Yes i noticed that and i will make use of it, but i will need the capabilities-request also for theming-support.

**Comment by korelstar** [comment]
... and it's definitely required for the first request after adding an account ...
