### ISSUE TITLE
Change the name of the app in the description

### ISSUE THREAD

**Issue by Valdnet** [stefan-niedermann/nextcloud-notes#797]
I suggest changing the name of the application in the description:

- If the issue persists, try to clear the storage of both apps: Nextcloud and Nextcloud Notes to solve this issue.

Because the app name in the settings is visible as "Notes".

![obraz](https://user-images.githubusercontent.com/47037905/79546397-a892e080-8092-11ea-97cd-b2fd9916497b.png)

Or change the source of the name to "Nextcloud Notes".

**Comment by stefan-niedermann** [comment]
Hmm, i think the other way around makes more sense. The app should be called "Nextcloud Notes" in the app view of the settings 🤔

**Comment by stefan-niedermann** [comment]
![grafik](https://user-images.githubusercontent.com/4741199/80869437-aa6abf80-8ca0-11ea-955a-0b96433cfb83.png)
