### ISSUE TITLE
Notes does not honor app PIN

### ISSUE THREAD

**Issue by trader2005** [stefan-niedermann/nextcloud-notes#798]
When you set an app pin for the main android nextcloud client, this will prevent entering the app without entering the pin, as it should of course.

However, if you also install the nextcloud notes app, this will open no matter what (without requesting the pin input) and will happily display all the notes of the respective account. 

This is of course a bit of security matter. Maybe this should be looked at. 

Thanks for the great app!

Regards.

**Comment by stefan-niedermann** [comment]
There is a window of 30 seconds after the Notes app has been fully stopped where no credentials are asked for to enhance the usability. Can you please check, that this is really a bug? Please close the app and wait 30 seconds. If it still does not ask for credentials, this is a bug.

Thank you for reporting.

**Comment by trader2005** [comment]
Thanks for this super-immediate reply!

Seems you are right. When I close the nextcloud main app (actually kill it) and than try to open nextlcoud notes app, the notes app requests the PIN. So I think I was getting this wrong, maybe due to the time window you described. 

Shall I close this thread? 

And beg you pardon, I think I was too quick to assume a bug.

Best.

**Comment by stefan-niedermann** [comment]
Absolutely no problem :) Feedback is always welcome.
