### ISSUE TITLE
Tablet Layout

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#8]
![mockup](https://cloud.githubusercontent.com/assets/4741199/10301812/5b58bc4a-6c06-11e5-9223-1d639db059b9.png)

**Comment by jancborchardt** [comment]
Roughly yeah. Basically just adapt the ownCloud Notes web app layout. Ideally the sidebar could be hidden (standard Android sidebar) so one can focus on writing.

**Comment by jancborchardt** [comment]
Also, we might even think about getting rid of the header so there’s more space for the notes. Or having it in a way that the header vanishes when scrolling down. Not sure what’s the best pattern there. cc @tobiasKaminsky @stoyicker @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Full ack on both ideas. Using a toolbar instead of a action should allow this effect which can also be seen in the play store app and series guide.

**Comment by stefan-niedermann** [comment]
:-1: for both ideas. why hiding the left list with notes? then we would have the same situation as now again^^. the idea of a seperate tablet layout was to provide him a quick way to navigate since he has more space as on a mobile device. why hiding the header? this is not a mobile phone browser - the header contains essential actions like share, delete, copy, ... also it's a well-known ux on android.

**Comment by AndyScherzinger** [comment]
Hmmm, would have to think a bit more and harder about this especially differentiating between portrait and landscape mode. I was looking at the notes app from a "reader" point of view so when scrolling down hiding the action bar for large context makes sense to me, when the focus is rather navigation between items and interaction with it than I don't see an immidiate need to hide the action bar when scrolling down and show it again when scrolling up. Will have a look at series guide and the play store which as far as I remember it do it in a similar way as discussed here.

**Comment by jancborchardt** [comment]
Because having the space for it does not mean we should show it. Taking notes, or writing, is also about having the free mental space to focus fully on the note at hand and not being distracted.

**Comment by stefan-niedermann** [comment]
After all i don't think we need a special layout for tablets.
