### ISSUE TITLE
Show images 🖼️ in view mode and searchable 🔎

### ISSUE THREAD

**Issue by bcharest** [stefan-niedermann/nextcloud-notes#807]
That will be great if the Android Notes app can show images in preview mode.

I'm using Android app Markor and in the preview mode you can see images. 

At the same time can be perfect to add in android app an OCC feature and make search engine able to search into images. This is a great feature that I was using before in Evernote. Bringing this feature into your app will make a nice implementation.

**Comment by stefan-niedermann** [comment]
Absolutely, but with the current (buggy and unmaintained) implementation of the Markdown-Editor this will be impossible. We already have an issue to replace the editor completely (which will likely still take some time).

The goal is, that the new editor will support displaying images out of the box, therefore i will close this issue in favor of #504 

Regards

**Comment by stefan-niedermann** [comment]
Fixed in `2.19.0`.
