### ISSUE TITLE
l10N: Resource "android-notes-plural" at Transifex should be merged into resource "android-notes"

### ISSUE THREAD

**Issue by rakekniven** [stefan-niedermann/nextcloud-notes#808]
Resource "android-notes-plural" contains one string.

Why not merging this into resource "android-notes"?

**Comment by korelstar** [comment]
I don't think that this is needed anymore. As far as I can see, the source file doesn't exists anymore. I'm pretty sure that this can be safely removed from Transifex.

Any doubts, @stefan-niedermann ?

**Comment by stefan-niedermann** [comment]
Phew, this something from a long time ago, but as @korelstar said, it doesn't exist anymore.

Remove it.

**Comment by rakekniven** [comment]
Thank you for your prompt response.

Removed resource from Transifex.
