### ISSUE TITLE
allow empty rows in tables

### ISSUE THREAD

**Issue by zeroepix** [stefan-niedermann/nextcloud-notes#809]
**Is your feature request related to a problem? Please describe.**
If I want related data with subheadings inside a table, I can't space it out nicely.

e.g. example (you can cut/paste to see):

```
Option | Pros | Cons
-|-|-
**option1**|it's cheap|it's slow
||it runs on a raspberry pi
**option2**|it's fast|it's expensive
|||the salesperson was rude
**option3**|decent speed|it's written in php
||can also re-program the kitchen sink|the manual is huge
```

**Describe the solution you'd like**
I'd like to be able to put a blank row in the rows above **option2** and **option3**.

**Describe alternatives you've considered**

I've tried creating separate tables for each, but the pros/cons columns don't line up nicely .e.g.:

```
**option1** | Pros | Cons
-|-|-
|it's cheap|it's slow
||it runs on a raspberry pi

**option2** | Pros | Cons
-|-|-
|it's fast|it's expensive
|||the salesperson was rude

**option3** | Pros | Cons
-|-|-
|decent speed|it's written in php
||can also re-program the kitchen sink|the manual is huge

```
I've tried just empty rows, but they don't seem to be read at all:

```
**option1**| **Pros** | **Cons**
-|-|-
||it's cheap|it's slow
||it runs on a raspberry pi
|||| 
**option2**| **Pros** | **Cons**
||it's fast|it's expensive
||the salesperson was rude
||||
**option3**| **Pros** | **Cons**
||decent speed|it's written in php
||can also re-program the kitchen sink|the manual is huge
```

Putting in a small character works, but it's ugly:
```
**option1**| **Pros** | **Cons**
-|-|-
||it's cheap|it's slow
||it runs on a raspberry pi
|>|||
**option2**| **Pros** | **Cons**
||it's fast|it's expensive
||the salesperson was rude
|-|||
**option3**| **Pros** | **Cons**
||decent speed|it's written in php
||can also re-program the kitchen sink|the manual is huge
```

**Additional context**
A couple of the above alternatives look fine with a handful of text and rows, but not so great when you have a lot. It becomes a wall of text and it's not easy to distinguish the options. There's probably a really easy way to do what I want already, but it doesn't seem obvious to me.

**Comment by stefan-niedermann** [comment]
This app does not yet support tables at all - are you sure you opened this issue in the correct repository?

**Comment by zeroepix** [comment]
nuuuuuuuuu yes you're entirely correct, it's meant for the other one...will close!
