### ISSUE TITLE
Normalize database

### ISSUE THREAD

**Issue by Isaac-Graham** [stefan-niedermann/nextcloud-notes#814]
Currently, the database is not normalized. The database should be normalized before fixing #603 .
This issue is proposed as a tag. I am trying to implement it.

**Comment by stefan-niedermann** [comment]
Concrete steps would be to create a new table `CATEGORIES` with the following columns:

- `ID` - Primary key
- `ACCOUNT_ID` - foreign key
- `TITLE`

This affects editing, removing and adding categories and moving categories to another account.

Do you agree @Isaac-Graham ?

**Comment by Isaac-Graham** [comment]
These are some basic columns. But these basic columns are not enough to fix #603 . What about a new column `SORT_ALGORITHM`? Or this column is posted when fixing #603 .

**Comment by stefan-niedermann** [comment]
Let's keep the steps small, otherwise we will end up in a huge PR which gets out of sync with the master and will be hard to review.

Especially as we are currently also doing some other heavy stuff with supporting a new API version.

So please do only the refactoring in this issue and let's add the new columns for #603 after finishing this issue.

**Comment by korelstar** [comment]
Why do you need a full normalized table? I suggest to leave the category column as is. Creating a separate table for categories would make things much more complicated. I don't think that we would really win something with this.

What's your motivation?

**Comment by Isaac-Graham** [comment]
Because it seems that the issue #603 cannot be fixed without a normalized database.

**Comment by korelstar** [comment]
Why that? #603 is just about sorting. All relevant columns are indexed and we use them for sorting already. What do you need to change exactly?

**Comment by Isaac-Graham** [comment]
@stefan-niedermann Stefan, could you please help me to explain it?

**Comment by stefan-niedermann** [comment]
@korelstar the issue is, that if we allow sorting, i want to **store what the last sorting in each category was**. This information belongs clearly into the database and it does not make sense to store this information in the `NOTES`-table. It belongs to a category table (which we do not yet have).

**Comment by korelstar** [comment]
Ah, I see. I didn't know that you want to save the ordering state. The problem with saving categories in another table is that you have to delete the entry, if no note uses that category anymore. So you must execute a respective query at some points, e.g. on synchronization.

**Comment by stefan-niedermann** [comment]
That's correct, we have to create and delete the categories. The safest would be to check for missing or abondened categories when updateing or deleting notes in the database.
