### ISSUE TITLE
Data loss after sync if note is opened via widget

### ISSUE THREAD

**Issue by Anrock** [stefan-niedermann/nextcloud-notes#821]
Opening a note via widget will lose freshly synced changes after switching to edit.

0. Create a single note widget on android 
1. Web UI: edit this note, for example add new item to a list
2. Android: tap on widget, see old content in note preview
3. Android: pull down to sync note
4. Android: see new content after successful sync
5. Android: tap pencil icon to edit note
6. Android: see that contents is old, just like sync didn't happen
7. Android: tapping back or closing app in anyway will sync back old content, effectively losing everything since before previous sync.

Note: opening same note via Notes app instead of a widget works as expected. App does a sync right after launch, new content already visible in note in a note list and after opening this note new content is immediately visible in preview and edit modes.

**Server**
 - Nextcloud-Version: 18.0.4
 - Nextcloud Notes-Version (server app): 3.3.0
 - PHP-Version: 7.2.30

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.11.12
 - F-Droid or Play Store: F-droid
 - Device: Planet Computers Cosmo
 - Android-Version: 9

**Comment by stefan-niedermann** [comment]
Funny thing, was reported just a few days ago and has been fixed today in https://github.com/stefan-niedermann/nextcloud-notes/commit/cefb6a9df26da332f78a2c6254793a85301d1faf

Just wait until `v2.12.0` arrives - might take some time though.

Please reopen in case something doesn't work as expected in `v2.12.0`.

Regards
