### ISSUE TITLE
Widget not working

### ISSUE THREAD

**Issue by kukukk** [stefan-niedermann/nextcloud-notes#822]
**Describe the bug**
I bought the app from Play Store, configured my account, made some modifications in the default settings and tried to add the the Note list widget. The widget location appears on the screen, but instead of showing the note list it says that it could not to load the widget. Sorry, I forgot the exact error message.

After uninstalling the Play Store version and installing the F-Droid version (2.11.12) with the same settings the widget works properly.

**To Reproduce**
1. Install version 2.11.13 from Play Store and set up the Nextcloud account
2. Set display mode to preview and switch to dark theme
3. Add Note list widget to homescreen with All notes
4. Could not load the widget

**Expected behavior**
The note list should appear

**Server**
 - Nextcloud-Version: 18.0.4
 - Nextcloud Notes-Version (server app): 3.2.0
 - PHP-Version: the one used by 18-apache Nextcloud docker

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.11.13
 - F-Droid or Play Store: Play Store
 - Device: Sony Xperia XZ1 Compact
 - Android-Version: Android 9 (Security path: 2019 September 1)

**Comment by stefan-niedermann** [comment]
@dan0xii this might be something for you?

**Comment by stefan-niedermann** [comment]
@kukukk for hunting down this bug: You modified some of the settings - is the behavior the same when you use the F-Droid version? (They are identically, so in theory the behavior *should* be the same). Can you reproduce this behavior after deleting the storage of the app (Android settings → Apps → Nextcloud Notes → Storage → Delete storage) and reimport your account *without* changing any of the default settings?

**Comment by kukukk** [comment]
I made the same modifications in the settings before trying to add the widget when I installed the F-Droid version.

Unfortunately, I no longer can do any more test with the Play Store version. My refund was approved, so I can't reinstall it.

**Comment by stefan-niedermann** [comment]
If you are still interested in hunting this bug down you can send me an e-mail at info@niedermann.it and i will send you a free Play Store voucher.

Otherwise just close this issue :slightly_smiling_face:

**Comment by kukukk** [comment]
Email sent with some details about my steps switching from F-Droid version to Play store version and back.

**Comment by stefan-niedermann** [comment]
> A small detail about what I did: I had an earlier version installed from F-Droid. I decided to buy it from Play Store. I uninstalled the F-Droid version and installed the Play Store version. Made the mentioned modification in the settings, and tried to add the widget. I problem appeared. After I saw that it is not working, I uninstalled the Play Store version (and received the refund). I installed back the F-Droid version, made the same modification in the settings, added the widget, and this time the widget worked.

**Comment by kukukk** [comment]
Hmm... I'm not able to reproduce the problem this time.

The difference was that the first time I had an older version installed from F-Droid: 0.22.x
Can it be caused by allowBackup and some no longer valid settings saved since that old version?

Btw, from my point of view the issue can be closed.

**Comment by stefan-niedermann** [comment]
Okay, might be possible that some kind of `allowBackup` caused this issue.

Just reopen if the issue occurs again 🙂
