### ISSUE TITLE
Error 302 when notes app is not installed on server

### ISSUE THREAD

**Issue by sebas891** [stefan-niedermann/nextcloud-notes#824]
**Describe the bug**

I installed Notes app (2.11.13) on Android 10 using froid, without having it installed before on the nextcloud server.  I got an error 302 without explanation on the client.

Here is the apache log on the server before installing.
`10.0.90.3 - user [10/May/2020:11:56:00 -0300] "GET /nextcloud/index.php/apps/notes/api/v0.2/notes?pruneBefore=0 HTTP/1.1" 302 967 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
`
After installing the app notes on the server I got an 200 .
`10.0.90.3 - user [10/May/2020:12:03:49 -0300] "GET /nextcloud/index.php/apps/notes/api/v0.2/notes?pruneBefore=0 HTTP/1.1" 200 1823 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
`

I was able to syncronise notes without problems after this.

**Expected behavior**

I would expect to get an error message saying the notes application is missing on the server.

**Screenshots**

**Server**
 - Nextcloud-Version: 18.0.3
 - Nextcloud Notes-Version (server app): 3.3.0
 - PHP-Version: 7.3

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.11.13
 - F-Droid or Play Store: F-Droid
 - Device:  
 - Android-Version: 10

**Comment by stefan-niedermann** [comment]
Unfortunately there are many error patterns which can occur when the notes app is not installed on the server depending on the environment, but it seems a good idea to add this as a hint for a possible cause. Thanks for the information.

**Comment by stefan-niedermann** [comment]
Next version will display a hint at an incoming `HTTP 302` to check whether or not the server app is installed.

**Comment by sebas891** [comment]
Super! Many thanks.

**Comment by summersab** [comment]
I have an idea for how to improve this, but I don't know if it's possible:
- Check to see if the network and NC instance is available to rule out a connection issue. If the connection is fine:
  - Check if the user is an admin or not.
    - User is not an admin: Show a message telling the user that Notes is either not installed or not available to them, and they should contact the administrator.
    - User is an admin: Show a message telling them that Notes is not enabled on the server and ask them if they want to install it. If yes, automatically install Notes on the server (not sure if this can be done).
- If the connection is broken, show the "Sync Error" message.

I don't know if it's possible to trigger a server-side app install, but this would make the user experience super-smooth.

**Comment by stefan-niedermann** [comment]
@summersab while it is possible in theory to trigger a server side app installation, i have scruple to do so from the Android app. I think users might be skeptical and consider this behavior as malicious. In my opinion it is way less invasive than the proposed solution.

Actually there should already be a visual hint / explanation about a missing app which provides a button that directly redirects a user to the Nextcloud app management:
https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/exception/tips/TipsAdapter.java#L92-L95
