### ISSUE TITLE
Add Text To Speech to notes

### ISSUE THREAD

**Issue by kai11** [stefan-niedermann/nextcloud-notes#836]
**Is your feature request related to a problem? Please describe.**
Some people prefer to read from screen, others prefer to listen audio. 
Id like to hear some of my notes while doing other stuff as a refresher of my decisions or play collection of text clips from web.

**Describe the solution you'd like**
- Add Speak button to 3 dots menu on note edit (near items like Pin to homescreen, Move, Cancel)
- On settings screen add button to open Android TTS settings.

**Describe alternatives you've considered**
Right now I share note text to https://f-droid.org/packages/com.danefinlay.ttsutil/
However, for it to work correctly I need to open this app, make it say some text and only then shared text will be voiced.

**Comment by stefan-niedermann** [comment]
As far as i know Android provides global accessibility tools. Isn't that an alternative?

Tap text to let your smartphone speak: 
https://www.businessinsider.de/international/how-to-use-google-text-to-speech/?r=US&IR=T

**Comment by kai11** [comment]
ok, that should be enough
