### ISSUE TITLE
Plain text file export/import

### ISSUE THREAD

**Issue by nanderer** [stefan-niedermann/nextcloud-notes#843]
Hi there,

thanks for the grate selfhosted open source cloud notes solution.
But in case you cant connect to your nextcloud ( like something bad happened to it ) it would be grate to provide also an plain text files (or .md in this case which is plain enough) import/export option in the settings to put them to sdcard and import into your next device. Just in case of youve got some problems like total net outage, hdd crash and unfunctional backup or just your phone memory is broken and you cant install update to app to get it syncing again.

Thanks a lot in advance and keep up the good work

**Comment by stefan-niedermann** [comment]
Thanks for the feedback!

In case your Nextcloud is only **temporarily not available**: Simply work on, as soon as the instance is available again, the apo will synchronize again

In case your Nextcloud **burned to the ground**: You can make use of those features already to save your notes:
- Share Note through Android sharing system to any other app like E-Mail or an Messenger or even another notes app
- Move notes to another Nextcloud instance (you need to add the second account first, of course)

I think a sync client cannot replace a backup strategy.
May i ask what you are doing with your other files in the mentioned bad situations? I am sure you have a backup plan for them, too. Since the notes are simply stored as text files on your server, they should be as safe as all your other files without any work.

**Comment by nanderer** [comment]
Thanks for that detailed reply. To answer your question: The other files are not a problem, there are two desktops, one has all files locally and also the calender and contacts can be exported to file using thunderbird and android. But the notes are nither files on any local disk but cal/carddav repositories acced by programms with local storage and export/import from file option. So i am using the app on droid and a web client on desktop. I of cause could touch all notes one by one and copy the text to file and copy it in again but it would not help me in doing an easy automated backup withot full root access to the server database/filesystem. A desktop client (some .jar that runs in terminal or as a service reading from some config file) that creates .md files and syncs there changes would be nice to....

**Comment by nanderer** [comment]
Oh i just noticed some new folder called notes appeared everywhere nextcloud is;) fine, fine fine. So forgett desktop version :)

**Comment by stefan-niedermann** [comment]
You can either use [QOwnNotes](https://www.qownnotes.org/) as a desktop client or use the [default Nextcloud desktop sync client](https://nextcloud.com/install/#install-clients). As you noticed, the Notes are all stored as plain text files within the desktop.

While i understand that it's not fun to share / copy each single note after a disaster recovery, it actually **is** an option to restore notes. How often are you planning to do this? Ideally not even once i guess :wink: After all this android app is not a backup solution, therefore sorry, this is out of scope for this app. :slightly_frowning_face:

**Comment by Jannik44** [comment]
Hello, similar problem, how are the notes stored on android? is there a filepath/ filepath to database file or some other way to recover the notes from the phone?

**Comment by stefan-niedermann** [comment]
They are stored within an `SQLite` database on the device. Note contents can be extracted when your device is rooted
However, given you mentioned in your other issue what you did, the database on your device is empty.

In the end the Notes Android client is **not a backup tool** and does **not free administrators to take care about a proper backup strategy** for their instance.

**Comment by Jannik44** [comment]
> In the end the Notes Android client is not a backup tool and does not free administrators to take care about a proper backup strategy for their instance.

sure, this was never my intended use, however the notes were locally altered while the server was down so i needed a way of restoring them to the new instance

**Comment by tcecyk** [comment]
althafvly implemented a json exporter (no import) via the settings in the /e/OS fork, see this PR https://gitlab.e.foundation/e/os/notes/-/merge_requests/62 and commit https://gitlab.e.foundation/e/os/notes/-/commit/c5c4aa6c8ab9c65b497bce470716cde3e6ec0f33 - it's pretty self-contained but the getNotesByAccountId() function for a merge.

Users ended up in scenarios where device-side notes weren't fully synced for various reasons (remote downtime), so an export put them on the safe side before ditching and re-adding the sync connection.
