### ISSUE TITLE
feature request android app: sync history/logfile

### ISSUE THREAD

**Issue by nanderer** [stefan-niedermann/nextcloud-notes#844]
No further text.

Thanks in advance

**Comment by stefan-niedermann** [comment]
For what purpose?

**Comment by stefan-niedermann** [comment]
What are you expecting to read there? Either there will be entries "Syned well" or "Synced with an error". But in error case you will also
- see a persistens sync icon at the note itself as a hint that this note has not yet been synchronized
- a snackbar with a detailed error message

**Comment by stefan-niedermann** [comment]
ping @nanderer
