### ISSUE TITLE
TokenMismatchException

### ISSUE THREAD

**Issue by mkjo** [stefan-niedermann/nextcloud-notes#856]
Hello, on my Tablet Nextcloud Notes crashes when an initial setup with the existing and working Nextcloud account is done.
The crash occurs after I confirm the access to the nextcloud account.
The normal Nextcloud App works fine.

Any Ideas what's wrong?

```
App Version: 2.12.2
App Version Code: 2012002
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 3.4.0-perf-gbe52486(2865764310)
OS API Level: 22
Device: SGP611
Manufacturer: Sony
Model (and Product): SGP611 (SGP611)

---

com.nextcloud.android.sso.exceptions.TokenMismatchException: Der Authentifizierungs-Token stimmt nicht überein oder dem Paketnamen fehlt die Berechtigung für diese Aktion
  at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
  at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
  at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
  at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:64)
  at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.lambda$null$13$NotesListViewActivity(NotesListViewActivity.java:717)
  at it.niedermann.owncloud.notes.android.activity.-$$Lambda$NotesListViewActivity$ApX5jZPpliFMx5irsu2MU1K_PSk.run(lambda)
  at java.lang.Thread.run(Thread.java:818)

```

**Comment by stefan-niedermann** [comment]
Hey,

can you please try to clear the storage of **both** apps: Nextcloud Android **and** Nextcloud Notes?

Android settings → Apps → Nextcloud / Notes → Storage → Clear storage

Then add your account again.

**Comment by mkjo** [comment]
Hi,
neither clearing the data for both apps, nor re-installing the apps does have an effect.
Same setup on a different phone works pefectly.

07.06.2020 1:29:29 nachm. Niedermann IT-Dienstleistungen <notifications@github.com>:

**Comment by stefan-niedermann** [comment]
After clearing the storage of both apps, did you add the account in the Nextcloud app or in the Notes app?

**Comment by mkjo** [comment]
I added it in the nextcloud app.
I try it in the reverse order and let you know.

Am 7. Juni 2020 22:17:21 MESZ schrieb Niedermann IT-Dienstleistungen <notifications@github.com>:

**Comment by chrikie** [comment]
same here.

```
App Version: 2.12.2
App Version Code: 2012002
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 4.14.116(10.0.0.195C431)
OS API Level: 29
Device: HWVOG
Manufacturer: HUAWEI
Model (and Product): VOG-L29 (VOG-L29EEA)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int)' on a null object reference
	at it.niedermann.owncloud.notes.persistence.NotesDatabase.addAccount(NotesDatabase.java:689)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.lambda$null$13$NotesListViewActivity(NotesListViewActivity.java:718)
	at it.niedermann.owncloud.notes.android.activity.-$$Lambda$NotesListViewActivity$ApX5jZPpliFMx5irsu2MU1K_PSk.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:929)

```

**Comment by stefan-niedermann** [comment]
@chrikie this is completely unrelated and has been fixed in the latest version. It should be available on F-Droid in a few days.

**Comment by mkjo** [comment]
Now it works after an F-Droid update this morning.
I guess it was the theming nullpointer fix which was mentioned in the release notes.

Am 7. Juni 2020 22:17:21 MESZ schrieb Niedermann IT-Dienstleistungen <notifications@github.com>:

**Comment by stefan-niedermann** [comment]
I don't think so, but thank you for the report though.

Glad to hear everything works for you know.

I will keep an eye for this `TokenMissMatch`-stuff, this happened way too often in the last time...

Just to gather some information:

- Did you use thr main Nextcloud Android app from f-doid, too?
- Do you have installed any of the apps from Play Store parallel?
- Have you update one of the apps recently?
- I think you already saif, that at least Notes was a fresh install, right?
- How many accounts do you have configured?
- Are you using another SSO app (Deck or News)? If yes: Did they work flawlessly?

**Comment by stemid** [comment]
I'm also getting this strange issue recently, seemingly out of the blue.

I tried forcing stop, clearing cache, storage, uninstalling both nextcloud and nextcloud notes, reboot phone, reinstalling both apps, login with qr code in nextcloud app and then still same exception in nextcloud notes.

Should I login to Notes first?
