### ISSUE TITLE
I18n - pun on tv show not universally understandable

### ISSUE THREAD

**Issue by p-bo** [stefan-niedermann/nextcloud-notes#866]
Hello,
because Nextcloud is supposed to be used around the globe, we cannot assume, that all people on planet know this tv show. I understand, that there in western culture is hard to imagine, that someone in world don't know it, but would be understandable for us puns on some bollywood movies for example?

Strings in question:

- Captain Janeway

Coffee. The finest organic suspension ever devised… I beat the Borg with it.

Maybe use something more universal please?

Thanks :)

**Comment by stefan-niedermann** [comment]
1. Well the text is directly copied from the Markdown description of GitHub flavored Markdown, so i didn't expect this kind of issues 😁
2. Also the content isn't that important, but the formatting options
3. I am a huge Star Trek fan 😄 🖖 

But if one really has problems understanding this text: Make a Pull Request and i will merge it if it fits.

**Comment by p-bo** [comment]
Well, I see.

It's hard to find quote from someone known everywhere in the world (and understandable there too). And it is inherited here from official documentation to markup language (but this isn't dogma, isn't it?).

So what about to try at least and use quote from someone more universally known, instead of some fictional character? And topic of quote, which is more universal, thus understandable in more cultures?

suggestions? For instance (randomly chosed):

>Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.
>- Albert Einstein

>Where there is love there is life.
>- Mahatma Gandhi

**Comment by p-bo** [comment]
Thanks for your understanding.
