### ISSUE TITLE
Option to disable / improve swipe to delete

### ISSUE THREAD

**Issue by Bleuzen** [stefan-niedermann/nextcloud-notes#884]
(from original issue https://github.com/stefan-niedermann/nextcloud-notes/issues/881)

I found this:
https://github.com/stefan-niedermann/nextcloud-notes/pull/665

So I understand if you don't want to fix it. I still did want to add it to the list.
Because of new Android 10 gesture / swipe navigation, this problem happens more often.
Swipe from right is going back. But it is also deleting a note.

Sure, there is an undo button. But for example earlier today I managed to accidental delete a note but until I processed what just happened and reached the bottom of the screen in one hand mode, the undo option was already gone. So I had to open the website, login, and restore from trash.

An easy way to make it a little better would be to show the undo option for a longer time. Currently it seems to be 3 seconds. Increasing it to like 5 seconds could already help a lot without new maintenance work.

**Comment by stefan-niedermann** [comment]
Do you know how GMail behaves at Android 10? They should have a similar issue i guess.

Increasing the timeout sounds like a good idea.

**Comment by Bleuzen** [comment]
Just tried it with GMail.

1) They are showing the undo option for a longer time, but hide it as soon as you start scrolling again.

(showing it longer sounds good, but I don't like the second behavior with hiding when starting to scroll)

2) They have an in-app archive / trash bin, so it is easier to restore.

**Comment by stefan-niedermann** [comment]
For reference regarding archive / trash: https://github.com/nextcloud/notes/issues/295 and https://github.com/stefan-niedermann/nextcloud-notes/issues/238

**Comment by Bleuzen** [comment]
Yes, this are good long term ideas for the future. But for now it would be nice if the timeout for the undo bar can be increased.

**Comment by stefan-niedermann** [comment]
I increased the timeframe for the `undo` action to `12 seconds` (previously it was depending on the android device round about `4 seconds`.

It has now the [same duration like the web app](https://github.com/nextcloud/notes/blob/32de460dd12386728b65a37cc62a14857031807c/src/App.vue#L261).

This change will be shipped with `v2.16.7`.

**Comment by Bleuzen** [comment]
Nice, thank you!
