### ISSUE TITLE
Start/end padding in lighter black that rest of appbar

### ISSUE THREAD

**Issue by thgoebel** [stefan-niedermann/nextcloud-notes#889]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

In dark mode, the padding at the start/end of the action bar has a slightly lighter color.

**To Reproduce**

1. Open the view/edit screen.

**Expected behavior**

Action bar should be the same color throughout.

**Screenshots**

<img src=https://user-images.githubusercontent.com/33295590/85209623-9efb5280-b339-11ea-8c81-6cba5c24ff08.jpg width=500>

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.16.2
 - F-Droid or Play Store: github
 - Android-Version: 10
 - Device: OnePlus 7

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Hmm, any idea what's causing it? It's also in `AboutActivity`, `PreferencesActivity` and so on... 

Even if i set `android:background="@color/primary"` on the `AppBar` directly, it has no effect...

**Comment by thgoebel** [comment]
If I had known immediately, I'd have send a PR :)

**Comment by stefan-niedermann** [comment]
Also affects the toolbar of the `NotesListViewActivity` as soon as one clicks on the `MaterialCard`.

**Comment by stefan-niedermann** [comment]
So, i found out that it works if i explicitly set the background color of the `AppBarLayout` programmatically.
This is good enough as a workaround for me, [i left a `FIXME` in the code](https://github.com/stefan-niedermann/nextcloud-notes/commit/07735922bada3583d702c3abf3bcf2c5f4e592ab#diff-20a39f1933af0977be2ea042436cf376R56) so one can have a closer look whenever one has time for racking brains why the hell android does not accept the declarative background color.... :confused: 

Thanks for reporting :slightly_smiling_face:
