### ISSUE TITLE
Grid view: no padding top on Recycler View

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#890]
![grafik](https://user-images.githubusercontent.com/4741199/85210066-331ae900-b33d-11ea-9c20-2c24412f64c8.png)

Happens on

- Oxygen OS (Android 10) on Oneplus 7 Pro.
- LG G4 with LineageOS 16.0 (Android 9)

**Comment by Bleuzen** [comment]
Also happens on Android 10 on emulated Pixel 2 in Android Studio.

**Comment by Bleuzen** [comment]
The issue goes away when you have at least one favourite note.
So to reproduce you have to un-fav all of your notes.

**Comment by stefan-niedermann** [comment]
Still cannot reproduce.
- What is the most top **visible** section? "Today", "Yesterday", ...?
- When have the samples at the screenshot been edited the last time?

**Comment by Bleuzen** [comment]
> What is the most top visible section? "Today", "Yesterday", ...?

There is no visible section if no note is favourite. If at least one is faved, the "Today" section becomes visible above all the un-faved notes.

> When have the samples at the screenshot been edited the last time?

Some minutes before the screenshot.

**Comment by stefan-niedermann** [comment]
I was able to reproduce and fix this issue finally :slightly_smiling_face: It will be fixed in `v3.2.4`. It only happend if one had absolutely no section (no favorites, no days older than one day), so probably not many users have been affected. Still thanks for reporting it and being patient @Bleuzen :slightly_smiling_face:
