### ISSUE TITLE
One line notes have no content preview in notes overview

### ISSUE THREAD

**Issue by Bleuzen** [stefan-niedermann/nextcloud-notes#891]
**Describe the bug**
When a note has only one line of content, the content is not displayed in the notes overview.
Example note:

![grafik](https://user-images.githubusercontent.com/12885163/85211327-4e3f2600-b348-11ea-8244-baa22a6950ed.png)

In list view it looks like this, only showing the title:
![grafik](https://user-images.githubusercontent.com/12885163/85211345-821a4b80-b348-11ea-9628-62e1e180d380.png)

Same in grid view:
![grafik](https://user-images.githubusercontent.com/12885163/85211337-6f077b80-b348-11ea-8ae5-60c17f8d4c24.png)

**To Reproduce**
1. Create a note with only one line
2. Edit the notes title to be something else than the first line
3. Look in notes overview

**Expected behavior**
First line of notes content should be displayed in notes overview.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): github master (https://github.com/stefan-niedermann/nextcloud-notes/commit/a3f157223f9591a17effbf01ad419d2b3cecf2f6)
 - F-Droid or Play Store: github
 - Android-Version: 10
 - Device: Android emulator, Oneplus 7 Pro

**Server**
 - Nextcloud version: 18.0.4
 - Nextcloud Notes version (server app): 3.5.1

**Stacktrace**
none

**Comment by stefan-niedermann** [comment]
Guess this happens only if the actual content has only one line?

Test which might be wrong: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/test/java/it/niedermann/owncloud/notes/util/NoteUtilTest.java#L67

Implementation: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/util/NoteUtil.java#L92

**Comment by Bleuzen** [comment]
> Guess this happens only if the actual content has only one line?
correct. Adding a second line shows the content again in the preview.

**Comment by stefan-niedermann** [comment]
Good catch 🙂
