### ISSUE TITLE
Grid view: 2-letter category title not center aligned

### ISSUE THREAD

**Issue by thgoebel** [stefan-niedermann/nextcloud-notes#893]
**Describe the bug**

In the grid view, the category tag for 2-letter categories is not center aligned. Notice how the left padding of "IT" is much smaller than that of "ETH".

**To Reproduce**

1. Enable grid view
2. Tag a note with a 2-letter category.

**Expected behavior**

2-letter categories should be centered, too.

**Screenshots**

<img src=https://user-images.githubusercontent.com/33295590/85218839-75284700-b39e-11ea-8a55-d3b1c553d97e.png width=500>

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.16.1
 - F-Droid or Play Store: F-Droid
 - Android-Version:
 - Device:

**Comment by stefan-niedermann** [comment]
Fixed, thank you.
