### ISSUE TITLE
Description of theme change

### ISSUE THREAD

**Issue by Valdnet** [stefan-niedermann/nextcloud-notes#896]
**Describe the solution you'd like**
Change the theme change function descriptions.

**Describe alternatives you've considered**
In my opinion, the description of the function to change the theme in the app settings should only have the description "Theme", because when choosing, we choose 3 different types of theme. This description can be when we use the switch to change the theme from light to dark.

![obraz](https://user-images.githubusercontent.com/47037905/85294228-aab45980-b49e-11ea-8e1d-8d3a5caedc37.png)

![obraz](https://user-images.githubusercontent.com/47037905/85294813-66758900-b49f-11ea-9039-c5585f75d5a8.png)

**Comment by stefan-niedermann** [comment]
Yes, do you want to create a PR? 🙂

**Comment by Valdnet** [comment]
Well. I will create PR :wink:.

**Comment by stefan-niedermann** [comment]
Thank you for your contribution! :rocket: :slightly_smiling_face:
