### ISSUE TITLE
No Markdown inside words

### ISSUE THREAD

**Issue by Buntbart** [stefan-niedermann/nextcloud-notes#901]
**Is your feature request related to a problem? Please describe.**

If there are no spaces before or after formatting characters, Markdown formatting should not be rendered. For example, there are problems displaying file lists in notes if the file names contain underscores. A filename like 2020_06_26_list1_file2_edited.txt would not be displayed meaningfully inside of a note.

**Describe the solution you'd like**

Nextcloud Notes should detect if there are spaces before and after formatting characters like the the underscore and only then display the formatting.

**Comment by stefan-niedermann** [comment]
You are absolutely right @Buntbart 

Unfortunately this is an issue of the upstream `RxMarkdown` which we can not fix directly.

We plan to replace the library (https://github.com/stefan-niedermann/nextcloud-notes/issues/549) as it has a large number of bugs and it is not really possible to fix them.

Please stay patient until we find a proper solution for this topic. You can watch the linked issue to get updates about our attempts to replace it with Markwon or another library.

Thank you for the report and sorry that i don't have better new for you.
