### ISSUE TITLE
"error_dialog_redirect" wrong translated (contains "Deck" instead of "Notes")

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#904]
@rakekniven sorry to bother you again.

I noticed that the translated files for `nl` and `es` both contain the word "Deck" instead of "Notes" in the string with the key `error_dialog_redirect`. The strings for the error messages are quite similar, i guess they have been copy & pasted.

- [NL](https://github.com/stefan-niedermann/nextcloud-notes/blob/214b69ce9d76edd62079a948640e5a4f20496b43/app/src/main/res/values-nl/strings.xml#L147)
- [ES](https://github.com/stefan-niedermann/nextcloud-notes/blob/214b69ce9d76edd62079a948640e5a4f20496b43/app/src/main/res/values-es/strings.xml#L147)

Might you have a look, please?

**Comment by rakekniven** [comment]
Fixed.
