### ISSUE TITLE
Error connecting to self-hosted Nextcloud instance

### ISSUE THREAD

**Issue by bes1967** [stefan-niedermann/nextcloud-notes#907]
Hi, 
I got the following error while trying to connect to self-hosted nextcloud instance version 19.0.0 with Notes v.3.6.0 installed :
```
App Version: 2.14.1
App Version Code: 2014001
App Flavor: play

Files App Version Code: 30120090

---

OS Version: 3.18.31-g9d6a405(C170B280)
OS API Level: 24
Device: HWKobe-Q
Manufacturer: HUAWEI
Model (and Product): KOB-L09 (KOB)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Не получен ответ от API приложения Файлы для Nextcloud. Сообщите об этой проблеме.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:64)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.lambda$null$16$NotesListViewActivity(NotesListViewActivity.java:713)
	at it.niedermann.owncloud.notes.android.activity.-$$Lambda$NotesListViewActivity$HvKm0MhYXSJxNRffQW5qOZh27Jc.run(lambda)
	at java.lang.Thread.run(Thread.java:776)
```
I will say that on another device the program works without errors. In addition, I can use other apps on  KOB-L09, that use the same account to connect to the same nextcloud instance. I followed the recommendations for stopping applications and clearing the cache, but that did not help. What else can I try to do to get the software work. 

Thank you.

**Comment by stefan-niedermann** [comment]
Dear @bes1967 

please see my comment here: https://github.com/stefan-niedermann/nextcloud-notes/issues/710#issuecomment-651078425

Regards

**Comment by bes1967** [comment]
Thank you very much, the proposed solution (disable battery optimization) helped me, but only after I stopped the application and cleared the data in the application settings (clearing only the cache did not help). So, in my case, the way to make things work was:
- disable battery optimization - there is still an error
- stop the application, clear the cache - the error still exists
- stop the application, clear data - everything works!

**Comment by stefan-niedermann** [comment]
Thank you very much for your feedback. 🙂 

I will add a few hints so other users can benefit from your experiences.

**Comment by stefan-niedermann** [comment]
@bes1967 we are trying to hunt down this nasty bug. Since battery optimization solved this issue after all:

Have you disabled it for

- both apps or¹
- only for Notes
- only for the main app?

Thank you in advance :slightly_smiling_face: 

¹ In this case: Would you mind to try disabling it only for one of the two apps and report us if the issue appears again? (Though it might take some time for the optimization system to react again and drop the connection)

**Comment by bes1967** [comment]
As I understand it, when you say “main application”, you mean the Nextcloud application, right? Well, I turned off battery optimization for both, but after that I still got the error. Then I cleared the cache and data only for the Notes application, and after clearing the data, the error disappeared. I should note that before disabling battery optimization, I even tried reinstalling the Notes application. And now, at your request, I turned on battery optimization for both applications, cleared the data for Notes and ... NO errors ... I know this is a terrible scenario to identify the causes of the error. I will leave the battery optimization off and watch how the application will behave... If you have any other suggestions, feel free to express them, I will try to test them ...

**Comment by stefan-niedermann** [comment]
Thank you!

> when you say “main application”, you mean the Nextcloud application, right?

Yes

> And now, at your request, I turned on battery optimization for both applications, cleared the data for Notes and ... NO errors ...

This doesn't surprise me because most optimizations are "watching" apps for much activity over a period of time. Just keep us updated if the error appears again :)

Thanks
