### ISSUE TITLE
Make it official?

### ISSUE THREAD

**Issue by rugk** [stefan-niedermann/nextcloud-notes#913]
Why is not this app official?

I searched for it in the [nextcloud org on GitHub](https://github.com/nextcloud?q=android&type=&language=), but could not find it.

Could not it be moved there?

(This is likely also bad for error reporting, as I guess people may report Android bugs in the [notes web issue tracker](https://github.com/nextcloud/notes/issues).)

**Comment by stefan-niedermann** [comment]
I am watching the notes repository issue tracker as well and redirect people to here or help them directly there if it isn't too much.

I am not related to the Nextcloud GmbH in any way. This is a pure community project.

I currently don't see a reason to move the repository, as the issue tracker is linked in the App stores as well as in the app itself 🙂 

But i will discuss the topic maybe at the next hackweek again. I don't think there's anything wrong with pure community projects :)

**Comment by rugk** [comment]
Hmm… still this app looks and feels very much "official". (See this as praise, if you want. :stuck_out_tongue_winking_eye: )

**Comment by stefan-niedermann** [comment]
Thank you very much! I try to be as close as possible to the official look and feel and i am in direct contact with the Nextcloud developers, so i hopefully can provide a professional look and feel also in the future 😉
