### ISSUE TITLE
Sometimes Widget is blank

### ISSUE THREAD

**Issue by BloodyIron** [stefan-niedermann/nextcloud-notes#914]
**Describe the bug**
Not always, but often, when I come back to my phone and look at the notes widget, it is blank, listing no notes. Rebooting my phone causes the widget to start showing content again.

**To Reproduce**
I do not yet know a pattern or how to reproduce this. It has been happening for many months, possibly over a year now.

**Expected behavior**
I would expect the notes widget to always show the most recent notes, as it normally does, instead of going blank.

**Screenshots**
Do not yet have screenshots.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): v0.21.0 (but has happened on earlier versions too)
 - F-Droid or Play Store: Google Play Store
 - Android-Version: v7.0.1
 - Device: LG v20 H918(10p)

**Server**
 - Nextcloud version: v18.0.4, but has spanned multiple previous major versions too
 - Nextcloud Notes version (server app): v3.5.1 (about to upgrade to v3.6.0 but has happened on multiple previous versions)

**Stacktrace**
I don't know how to acquire this in this circumstance.

**Comment by stefan-niedermann** [comment]
Please update to the current version, at least to `2.16.3`. `v0.21.0` is outdated for *years* and not supported anymore.

Let me know if the issues are still present.

**Comment by BloodyIron** [comment]
Egads, I must have missed it went to paid versions. Looks like that's the last $0 version, :/

My mistake.

**Comment by stefan-niedermann** [comment]
This app has *never* been for free at the Google Play Store. Really: never 🙂

It is available for free at [F-Droid](https://f-droid.org/), though.

Let me know if you are experiencing the issue in a current version, then i will have a more detailled look at it.

Regards
