### ISSUE TITLE
Datum einfügen

### ISSUE THREAD

**Issue by Achim222** [stefan-niedermann/nextcloud-notes#915]
Hi, tolle App!
gibt es eine Möglichkeit das Datum bei einer Notiz automatisch einzufügen ?

thanks

**Comment by stefan-niedermann** [comment]
Vielen Dank für das Feedback :slightly_smiling_face: 

Nein so etwas ist derzeit nicht vorgesehen.

Wir versuchen die App so schlank wie möglich zu belassen, sodass zwar für den ein oder anderen Anwendungszweck Features fehlen (ich nehme an, hier geht es um eine Art Tagebuch?), wir dies aber bewusst in Kauf nehmen, um sie nicht mit Buttons und Optionen zu überfrachten - Minimalismus wird bei uns groß geschrieben :wink: 

Sollte die Server-seitige App dies implementieren, würden wir die Entscheidung allerdings neu abwägen, um Feature-Gleichheit zu gewährleisten. Du darfst es daher gerne noch einmal [in deren Repository](https://github.com/nextcloud/notes/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=) versuchen, ich würde mir offen gestanden allerdings keine allzu großen Hoffnungen machen.
