### ISSUE TITLE
Change folder path to store notes

### ISSUE THREAD

**Issue by simon-77** [stefan-niedermann/nextcloud-notes#916]
Dear developers

I started using the Nextcloud Notes Android App recently and so far I really like it. I only have an issue / feature request using this App in my personal Nextcloud setup:

* I would like to share my notes with another person. The problem is that one account has the language set to English while the other is set to German. The default folder for Nextcloud Notes in English is ```Notes``` and in German it is ```Notizen```. The Nextcloud Notes App has the option to change the folder where the notes are stored in. It seems like the Nextcloud Notes Android App is lacking this feature.

* Additionally I would like to request a new feature where I could switch easily between different "Notes - Folders". For example to have one folder that holds notes which are shared with another person and to have a second folder which holds notes that I use for my own purpose only - each with it's own categories.

Kind regards
Simon

**Comment by stefan-niedermann** [comment]
@korelstar i think this is a general question: Should we make the server settings available via REST-API (this would also affect the `.txt` vs `.md` setting).

Design wise this would be a problem, therefore cc @jancborchardt :

- The settings in the Android Notes app are currently all global (affecting each account). This issue would introduce per-account settings. How and where should they displayed in the Android app?

**Comment by korelstar** [comment]
Personally, I don't see the necessity to be able to change the settings from the mobile app. However, I will not block this. Hence, if you want me to provide the settings over API, I'm open for an implementation.

In the Android app, the best place would be IMO in the manage accounts activity. There is a trash icon on the right, maybe you could put a settings icon besides which opens an activity for account specific settings?

----

@simon-77 : Regarding your second point (multiple notes folders in the same account): you can move the shared notes folder as sub-folder into your personal notes folder. You will still be able to use categories, they just move one level down.

**Comment by jancborchardt** [comment]
> In the Android app, the best place would be IMO in the manage accounts activity. There is a trash icon on the right, maybe you could put a settings icon besides which opens an activity for account specific settings?

Yep, agree on the placement there.

However, not sure about the necessity of this. All due respect @simon-77 so far you are the only one to request this, so I would say in the interest to not over-engineer the app, we should wait and see if this would actually be useful to further people.

Lastly, could you split the second feature request into a separate issue? That way we can organize the issues and requests better. Thanks! :)

**Comment by stefan-niedermann** [comment]
> so far you are the only one to request this

This is not true, i remember at least 2 more requests which we denied yet.

I will have a look and if it isn't too complicated, i think we should do it for the sake of feature parity.

**Comment by simon-77** [comment]
> Personally, I don't see the necessity to be able to change the settings from the mobile app. However, I will not block this. Hence, if you want me to provide the settings over API, I'm open for an implementation.
> 
> In the Android app, the best place would be IMO in the manage accounts activity. There is a trash icon on the right, maybe you could put a settings icon besides which opens an activity for account specific settings?
> 
> @simon-77 : Regarding your second point (multiple notes folders in the same account): you can move the shared notes folder as sub-folder into your personal notes folder. You will still be able to use categories, they just move one level down.

@korelstar 
Thank's for your advice. I did not know that shared folders could be moved in nextcloud. This approach is a satisfying workaround for me regarding my second feature request

**Comment by jancborchardt** [comment]
More input regarding the first issue:

Wouldn't this be fixed by the Notes app simply showing Notes from folders in that translated list (Notes, Notizen, etc) if they exist?

That is, if my language is set to English and I have a "Notes" folder but also a "Notizen" folder which got shared to me by someone else, the contents of both could show.

Additionally, inside the Notes app itself there could/should be an indicator on the note that it's shared, e.g. it could show the avatar of the person who shared it with us in the entries of those notes in the AppNavigation.

**Comment by simon-77** [comment]
I would like to provide my personal opinion to the discussion about my first feature request - the "configurable" nextcloud path for notes:

Like _stefan-niedermann_ said I would appreciate some feature parity between the _Nextcloud Notes App_ and the _Nextcloud Notes Andoid App_. I think the simplest and most elegant solution (from an user perspective) would be to simply take the _Folder to store your notes_ setting from the _Nextcloud Notes App_ to the _Nextcloud Notes Android App_ (like it is already done with the `.txt` vs `.md` setting).

In the end you would have a total of two settings regarding the _Nextcloud Notes App_ and for me it would be sufficient if these parameters could only be changed via the the _Nextcloud Notes App_ web interface and not via the _Nextcloud Notes Android App_:

- Folder to store your notes
- File extension for new notes

The advantage would be that whatever notes are shown in the _Nextcloud Notes App_ would also be shown in the _Nextcloud Notes Android App_, totally independent from any language set anywhere.

**Comment by stefan-niedermann** [comment]
After more and more requests, i would like to implement this feature.
@korelstar would you implement the API part for it?

I imagine something like

- `GET /config/folder`
  - **Response**: String, for example `/MyNotes`
- `PUT /config/folder`
  - **Body**: String, for example `/MyNotes`

---

- `GET /config/extension`
  - **Response**: String, for example `Notes`
- `PUT /config/extension`
  - **Body**: String, either `md` or `txt`, (Maybe empty body for "reset to default"?)
  - **Statuscode**: Can be something like `406` if the extension type is not supported
- `GET /config/extension/options` (not sure about this one)
  - **Response**: Array of Strings, for example `['txt', 'md']`

**Comment by stefan-niedermann** [comment]
Starting with Notes Android `3.4.11` it will be possible to change the notes folder and the file suffix from within the app. Notes server `4.1.0` is required for that.

**Comment by BlackLight** [comment]
A quick heads up: the feature is not working (using Android app 3.4.16, server app 4.2.0):

1. When opening the folder settings from the Android app, no keyboard is shown - it's almost like the field is not treated as a text field. The only way I've managed to modify it is by typing the new folder in some other app's text field, copy it and paste it into the app's settings.
2. When you choose a new folder and click "OK" it has no effect. The toast simply says "Notes folder changed to Notes".

**Comment by stefan-niedermann** [comment]
Indeed, let's reopen this issue as a bug... thanks for the pointer :)

**Comment by stefan-niedermann** [comment]
Fixed in 3.7.0
