### ISSUE TITLE
Selecting a note in the main note list highlights two notes

### ISSUE THREAD

**Issue by dan0xii** [stefan-niedermann/nextcloud-notes#920]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

Once you have a certain number of notes in the app (I don't know how many, more than five) using long-press to select them will result in two notes being selected for every one. If you attempt to de-select a note the row will sometimes return to the correct colour but the total will increase by 1.

**To Reproduce**
1. In the note list, long press to select a note
2. Scroll down and you'll see another note is highlighted but the total will say "1 selected"
3. Continue to select notes and notice the total increments but 2x the number of notes will be highlighted
4. De-selecting one of the unintended notes will treat them as now selected, i.e. add them to the total, but the row will be look as though it's de-selected.

**Expected behavior**

Single note is selected per tap.

**Screenshots**

![note-selection](https://user-images.githubusercontent.com/1926270/88174143-af923780-cc1b-11ea-9c39-5cfcfbde018a.gif)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.16.4
 - F-Droid or Play Store: F-Droid
 - Android-Version: 9.0 (Lineage 16)
 - Device: oneplus

*Also* occurs in current master on AVD.

**Server**
 - Nextcloud version: 18.0.7
 - Nextcloud Notes version (server app): 3.6.0

*and*

 - Nextcloud version: 19.0.1
 - Nextcloud Notes version (server app): 3.6.0

**Stacktrace**
N/A

**Comment by stefan-niedermann** [comment]
Thanks to @muety this will be shipped in version `2.17.0`.
