### ISSUE TITLE
GridView: Change to Preview Mode

### ISSUE THREAD

**Issue by tschoesi** [stefan-niedermann/nextcloud-notes#924]
Hi all!

I think it would be nice if the tiles in the grid view would be in preview mode i.e. render the markdown. 

Quick & dirty mockup of how it currently looks vs. how it could look.
![NextNotes](https://user-images.githubusercontent.com/55841607/88460276-546e7800-ce9b-11ea-9658-7d2174135e12.png)

**Comment by stefan-niedermann** [comment]
I originally implemented it in this way but eventually reverted it, because the performance was so bad (even on good devices) and everything lagged. I currently see no way to enable preview without having a much worse UX.

**Comment by tschoesi** [comment]
Okay, I see. Thanks! :)

**Comment by stefan-niedermann** [comment]
Yep, sorry, but the trade-off was too big :-/

**Comment by mbousq** [comment]
Hi!
Might be crazy but what if it was possible to generate an image preview (when the note is closed) and that preview is then displayed in the grid view ?

**Comment by stefan-niedermann** [comment]
@mbousq In theory this sounds possible, but it has several drawbacks, for example when you rotate your device from portrait to landscape, you need different  sizes of the preview images. If you work on your smartphone with splitscreen and two apps, you will need even more previews, so this solution doesn't scale after all :slightly_frowning_face: 

I will test the performance again once we have implemented the new [Markwon based viewer](https://github.com/stefan-niedermann/nextcloud-notes/issues/549). Maybe we can then activate the rendering.
