### ISSUE TITLE
Edit mode new line in nested lists missing a leading space

### ISSUE THREAD

**Issue by RussellAult** [stefan-niedermann/nextcloud-notes#929]
**Describe the bug**
Creating a new line by hitting the Enter key at the end of a line in a nested list does not add enough leading space characters to make the new line also part of the nested list (or even valid Markdown).

**To Reproduce**
1. Create a new note and enter edit mode.
2. Give the note a title on line 1 and hit Enter.
3. Leave line 2 blank by hitting Enter.
4. Create a list on line 3 by typing either a hyphen or an asterisk, type a space, type some text, and hit Enter.
5. The app will continue the list by starting line 4 with a hyphen/asterisk and a space. Add two space characters to the beginning of line 4 to create a nested list, then add some other text to the line, then hit Enter.

**Expected behavior**
The app should continue the nested list by starting line 5 with two spaces, a hyphen/asterisk, and another space.

```
Title

- list item 1
  - sublist item 1
  - |
```

**Actual behavior**
The app adds only a single space before the hyphen/asterisk, which is not enough to continue the nested listed and isn't valid Markdown.

```
Title

- list item 1
  - sublist item 1
 - |
```

**Smartphone**
 - Nextcloud Notes-Version (android app): 2.16.5
 - F-Droid
 - Android-Version: 10 (LineageOS 12.1 unofficial)
 - Device: Pixel 3a

**Server**
 - Nextcloud version: 18.0.7
 - Nextcloud Notes version (server app): 3.6.1

**Comment by stefan-niedermann** [comment]
This issue is well described and documented, but no longer valid after Notes Android `v3.0.0`. We changed the markdown rendering engine and while the indention is still wrong, it is no longer as described in this issue. Closing in favor of #1019 to still keep track of the issue.
