### ISSUE TITLE
Add plural form to string 

### ISSUE THREAD

**Issue by rakekniven** [stefan-niedermann/nextcloud-notes#931]
https://github.com/stefan-niedermann/nextcloud-notes/blob/88d72cc549a1db132ff207c55300a6b91d1f3425/app/src/main/res/values/strings.xml#L159

**Comment by rakekniven** [comment]
Reported at Transifex

**Comment by stefan-niedermann** [comment]
Could never happen, because in case of `1` item i will display `"%TITLE%" deleted`, `n > 1` will display `Deleted %NUMBER% notes`. Though i fixed it in case one uses this string in the future for `1` item.

**Comment by rakekniven** [comment]
👍

**Comment by stefan-niedermann** [comment]
Alright, didn't think about it in the future, thanks 👍

**Comment by kotyhoroshko2** [comment]
Could you please also add plural forms to:
- `bulk_notes_restored`
- `share_multiple`

**Comment by stefan-niedermann** [comment]
Sure :)
