### ISSUE TITLE
Creating and adding of lists/checkboxes no longer works

### ISSUE THREAD

**Issue by christianlupus** [stefan-niedermann/nextcloud-notes#937]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

The app allows to add lists and check boxed lists. The latter is even possible using the long-press context menu.

When one item has been entered, the user might press enter to type the next entry. I am pretty sure that the app automatically continued the list automatically in the next row. In my current installation after pressing enter, I am only getting an empty new line. This is especially tendious if editing a check-boxed list as the symbols on some keyboards are buried quite deeply (many modifier keys needed).

**To Reproduce**
1. Start the app
2. Open a new note
3. Put some useful text in the first line as file name, e.g. `Shopping list`
4. Type a first entry of a list (with or without check boxes), e.g. `Potatoes`
5. Hit Enter after the entry was entered

You have something like
```
Shopping list
- [ ] Potatoes
<cursor>
```

The cursor is in the next line where I wrote `<cursor>`.

**Expected behavior**

The app switches to the next line after `Potatoes` and adds the list markers `- [ ] ` to the beginning of the line

**Screenshots**

At the moment I am incapable to make a screen recording (which would be needed to show the effect live).

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: Play Store, can install F-droid if favorable
 - Android-Version: 10
 - Device: Xiaomi Mi A2 Lite

**Server**
 - Nextcloud version: 19.0.1
 - Nextcloud Notes version (server app): 3.6.1

**Stacktrace**
No stacktrace was output. If I need to dig into some files, please provide with the location to look for.

**Comment by stefan-niedermann** [comment]
> I am pretty sure that the app automatically continued the list automatically in the next row

Absolutely true, and this is what happens for me. I'm sorry, but i can't reproduce the issue in the current version `2.16.7`.

Which version of the Android app exactly are you using?
Are you using any custom ROM or so?

**Comment by christianlupus** [comment]
I am on 2.16.7. So it should work in general. 

You mean custom ROM of Android? No, a stock one. I am running off Google one which is a merely monthly updated Android with minor apps preinstalled. 

I have to admit that there was an update recently of the ROM...

**Comment by stefan-niedermann** [comment]
And does the auto-continuation work for notes which have already been created and synced? (open them again, put the cursor behind an item and press <kbd>enter</kbd>)

**Comment by christianlupus** [comment]
No, this is in fact how I discovered the bug. I wanted to add to a shipping list and was set aback when I had to continuously retype the list symbols. I then tried to track it down (maybe the file has a weird character that messes with the MD support, so start fresh) and created a minimal example for the bug report.

**Comment by christianlupus** [comment]
If it helps, I can offer to install a debug apk and see to get some information to you then. But honestly I do not know if you knew what to debug.

**Comment by stefan-niedermann** [comment]
If you know how to debug, this is the correct place: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/java/it/niedermann/owncloud/notes/edit/NotesTextWatcher.java#L67

If not, i can provide a debug version, but that will take some time, because i'm currently busy...

**Comment by stefan-niedermann** [comment]
Would be pretty interesting whether or not you are able to reproduce this issue in an emulated device or on another physical device (like your families or so). Could you try it on another device? Since F-Droid and Play versions are identical, just grab the F-Droid version to test.

**Comment by christianlupus** [comment]
I'm going on holidays end of next week so I doubt I can do much until then considering I need to pack my things still. 

I can try to test with my girlfriend's mobile phone is she let's me do it. I can also try to install a avd and test it with that.

**Comment by christianlupus** [comment]
OK, I got the phone of my girlfriend and installed the Fdroid version there. Just for reference: It's a Cubot X18 Plus with Android 8.0.0. The Notes app is also `2.16.7`. The interesting part the very **same effect happens** with this device. The lists are not to be continued.

The only thing as far as I can tell that are in common here are (besides of the app version) the NC server and the files we are working on (it is a shared folder). Nevertheless, I doubt this has something to to with the upstream server....

**Comment by stefan-niedermann** [comment]
Yes, just install Android Studio, clone the git repository and you are ready to debug. I can guide you via Skype or Telegram if it helps 🙂

**Comment by christianlupus** [comment]
OK, after my vacation, I tested a bit again and the problem is no longer reproducible on my installations. I do not know if this was due to an update or whatever.

Closing here. When the issue reappears, I will reopen.

**Comment by stefan-niedermann** [comment]
Thank you for the update! And yes, please feel free to reopen if the issue occurs again, of course. 🙂
