### ISSUE TITLE
Category label in grid view doesn't take highlight background colour upon selection

### ISSUE THREAD

**Issue by keunes** [stefan-niedermann/nextcloud-notes#945]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
Arguably not a bug, but an improvement request: the category label on a selected note in the Grid view does not take the same background colour as the rest of the card, but remains as it was (white, in my case, where the rest of the card is light grey). This _is_ the case in the list view, so I assume this is not on purpose.

**To Reproduce**
1. Enable Grid view in th settings
2. Add a category to a note
2. Long-press the note to select it

**Expected behavior**

Category label backround tskes the same colour as the rest of the card.

**Screenshots**

| 1 | 2 |
| --- | --- |
| ![Screenshot_20200828-161626.png](https://user-images.githubusercontent.com/11229646/91584359-d0545800-e952-11ea-931d-41bc5aea674f.png) | ![Screenshot_20200828-161543.png](https://user-images.githubusercontent.com/11229646/91584428-ea8e3600-e952-11ea-8419-b92bc7e7f12b.png) |

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: Play
 - Android-Version: 7.1.2
 - Device: FP2

**Server**
 - Nextcloud version: 19.0.2
 - Nextcloud Notes version (server app): ??

**Stacktrace**
N/a

**Comment by stefan-niedermann** [comment]
Will be fixed in `v3.2.5`
