### ISSUE TITLE
Allow to add note to category (or vice versa) in multi-select view

### ISSUE THREAD

**Issue by keunes** [stefan-niedermann/nextcloud-notes#946]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

I'm in the process of transferring from Omni Notes to Nextcloud notes. I'm manually copy-pasting my notes and re-applying categories. Applying the categories one by one is a bit annoying.

**Describe the solution you'd like**

Omni Notes allows one to apply one or more categories when multiple notes are selected. This is quite handy. This is also convenient when reorganising one's notes. An extra icon in the top bar would be great - tapping on it would open a modal to apply the category/-ies.

**Describe alternatives you've considered**

**Additional context**

![Screenshot_20200828-174057.png](https://user-images.githubusercontent.com/11229646/91586520-cb44d800-e955-11ea-80f1-a82340afdceb.png)

**Comment by stefan-niedermann** [comment]
Makes absolutely sense. As a workaround i recommend you to move the notes into a different folder via the Web interface (Files app, not Notes app) or using the default Nextcloud sync client (All notes are stored ad `.txt` / `.md` files in the file system and categories are folders)

**Comment by stefan-niedermann** [comment]
Will be shipped with `2.17.0`
