### ISSUE TITLE
List not correctly rendered

### ISSUE THREAD

**Issue by keunes** [stefan-niedermann/nextcloud-notes#947]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

When adding an MD list by using dashes (space dash space text), this doesn't get rendered as a list with dots (as I see it should be according to the 'formatting' screen) when closing the edit screen (so being in the preview screen.

I thought it might be related to #937, but that one doesn't affect me (well, new list asterixes don't appear on creation, but they do get added when reopening the note & continuing the list.

**To Reproduce**
1. Create a note
2. Start a list by adding space dash space on new lines, create a few entries
3. Tap on the icon for switching to the preview
4. See error: MD list not rendered, see raw text instead
5. Exit note
6. Enter note
7. Edit note
8. See error: MD-list is rendered in addition to raw text list

**Expected behavior**

Render dots in preview screen, don't when reopening the note.

**Screenshots**

Add note with list:
![Screenshot_20200828-175232.png](https://user-images.githubusercontent.com/11229646/91591921-03e8af80-e95e-11ea-9c83-e60dc59bb752.png)

Preview note:
![Screenshot_20200828-175240.png](https://user-images.githubusercontent.com/11229646/91591966-182cac80-e95e-11ea-9422-c374fd0acaf0.png)

Edit note again:
![Screenshot_20200828-175400.png](https://user-images.githubusercontent.com/11229646/91592032-30043080-e95e-11ea-97f3-c7e84b460557.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.16.7
 - F-Droid or Play Store: Play
 - Android-Version: 7.1.2
 - Device: FP2

**Server**
 - Nextcloud version: 19.0.2
 - Nextcloud Notes version (server app): ??

**Stacktrace**
N/A

**Comment by stefan-niedermann** [comment]
Yep, sorry about this one, but there is nothing we can do in the short term unfortunately. It is caused by our no-longer maintained markdown rendering engine "RxMarkdown" which we plan to replace in the long term (see https://github.com/stefan-niedermann/nextcloud-notes/issues/549). We make only slow progress there because of limited time and the huge amount of work. (you are welcome to contribute at the PR 🙂)

**Comment by keunes** [comment]
Ok, thanks for the quick reply. Might the issue with links not being rendered stem from the same problem? I can't contribute code, unfortunately. Wish I had the skills 😉

**Comment by stefan-niedermann** [comment]
links are renderes in the preview mode (the 👁️ icon in the top right) - if not please share a note sample where it doesn't work, in this case it's a bug.
