### ISSUE TITLE
Support www links without protocol in preview mode

### ISSUE THREAD

**Issue by keunes** [stefan-niedermann/nextcloud-notes#949]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

After adding a link, they get rendered as raw text rather than as a link in the preview mode.

**To Reproduce**
1. Open/edit a note
2. Add a link in MD
3. Open preview
4. See error: no link rendered

**Expected behavior**

Render link

**Screenshots**

![Screenshot_20200830-111823.png](https://user-images.githubusercontent.com/11229646/91655668-897d7400-eab2-11ea-8fd8-ec5cd8af12bf.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.16.7
 - F-Droid or Play Store: Play
 - Android-Version: 7.1.2
 - Device: FP2

**Server**
 - Nextcloud version: 19.0.2
 - Nextcloud Notes version (server app): ??

**Stacktrace**
N/A

**Comment by stefan-niedermann** [comment]
Ah, can you try to add `http://` / `https://` in front of the link?

**Comment by keunes** [comment]
Ah, that works. If it would recognise `www.` as the start of a URL as well that'd be great. If not with the current lib, then for the new one :)

**Comment by stefan-niedermann** [comment]
Thanks to @muety this will be shipped in version `2.17.0`.

**Comment by keunes** [comment]
Thanks @muety !
