### ISSUE TITLE
offline: no sync indicator.

### ISSUE THREAD

**Issue by LyrixCaz** [stefan-niedermann/nextcloud-notes#951]
The app when not connected to n internet/wifi connection it tries to sync but upon doing that it shows the circular indicator. Its trying to find the server whenbthe phone os offline. Itll be nice if that circle will go away since it obstructs the note's view.

**Comment by stefan-niedermann** [comment]
Please fill in [the complete issue template](https://github.com/stefan-niedermann/nextcloud-notes/issues/new?labels=bug&template=bug_report.md). I can not reproduce the loading indicator to stay when one is offline (if this is what you mean).

**Comment by stefan-niedermann** [comment]
[Why this issue has been closed](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed).
