### ISSUE TITLE
Support for wikilinks

### ISSUE THREAD

**Issue by spitlo** [stefan-niedermann/nextcloud-notes#954]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

I use Nextcloud to sync notes between a mac and an android. On the mac, I use [nvAlt](https://brettterpstra.com/projects/nvalt/) for notes. nvAlt supports linking to other notes in the same folder with what’s often referred to as _wikilinks_, like this: `[[Another note]]`. It seems this is also a pretty popular format in the [Zettelkasten](https://zettelkasten.de/) community, since it’s a very simple way to create connections between notes. It would be nice if this was supported by the Nextcloud Notes Android app as well.

**Describe the solution you'd like**

A minimal support case would be rendering the `[[Wikilink]]` in view mode as a link that would open the linked note, also in view mode. Ideally, it would also be supported during editing, like in nvAlt, where typing the `[[` would create a closing bracket pair after your cursor, and let you start typing letters to narrow down a selection of possible links (I hope I’m describing this in an understandable way, please see screenshot of nvAlt below for a visual explanation).

If/once the switch from RxMarkdown to Markwon is done, it should be possible to at least support the minimal case by using the [Simple Extension](https://noties.io/Markwon/docs/v4/simple-ext/). I’m not a java developer, but I would be willing to give it a try if this is something you would consider implementing.

**Describe alternatives you've considered**

Since the wikilinks are displayed as-is, you still get a visual cue of the connection to another note, so not supporting wikilinks is an _ok_ alternative. Another alternative would be for me to reformat all links in a markdown-compatible way, but I don’t  really see it as an option since the wikilinks work so well in nvAlt and a lot of other note-taking software.

**Additional context**

![image](https://user-images.githubusercontent.com/1446850/92313098-cde3a500-efc7-11ea-8806-dec7b63d6f5e.png)

**Comment by stefan-niedermann** [comment]
Dear @spitlo,

thank you for the proposal. Please see [my response](https://github.com/nextcloud/notes/issues/616#issuecomment-699512420) in the server repository. [We plan to change the editor of the Android client, too](https://github.com/stefan-niedermann/nextcloud-notes/issues/549). We will therefore not add support for any new syntax before we made this huge change. We can think about adding support later, but for now this request is not on our roadmap for the near future.

Regards
