### ISSUE TITLE
Insert the current date and time

### ISSUE THREAD

**Issue by kstlv** [stefan-niedermann/nextcloud-notes#955]
Button for inserting the current date and time into the body of the note. For example, in the format: `yyyy-MM-dd HH:mm`. Like in [Markor](https://github.com/gsantner/markor).

**Comment by kstlv** [comment]
If anything, then I have a Java implementation of this function. I can send the code here.

**Comment by kstlv** [comment]
In the above code snippet, I was trying to find a potential solution.

**Comment by stefan-niedermann** [comment]
Yeah, it's no matter of `how`, actually it's pretty easy to implement. I am struggling with whether or not we actually do *want* this feature and if, where to place it.

What's the use case? How are you using the Notes app? How often will you need this function and for what purpose?

**Comment by kstlv** [comment]
@stefan-niedermann I will be happy to answer your questions.

> What's the use case?

Let me give you an example. I want to record the date and time when I watched the movie so that later I can implement a personal database to track movies.

> How are you using the Notes app?

I write down almost everything. I create a knowledge base: I write down problems and their solutions. Or, as I wrote above, just to insert a date for a specific event that happened in your life.

> How often will you need this function and for what purpose?

I very often come across the fact that I need to insert the current date and/or time. This is necessary to solve my problems.

**Comment by kstlv** [comment]
This action can be inserted into the menu (three dots at the top right of the screen) while editing a note.

**Comment by stefan-niedermann** [comment]
> This action can be inserted into the menu (three dots at the top right of the screen) while editing a note.

No, it's already too crowded. *If*, then it should go into the contextual action menu (pressing the cursor, next to `Cut`, `Copy` & `Paste`, because there are all actions which modify the editors content).

Let me think about it.

**Comment by kstlv** [comment]
@stefan-niedermann Rather yes, you are absolutely right.

**Comment by stefan-niedermann** [comment]
Sorry, but this is nothing we plan to implement. The visual noise in the ([as mentioned](https://github.com/stefan-niedermann/nextcloud-notes/issues/955#issuecomment-694754139)) already crowded menus will not be worth the comparatively small benefit of avoid typing the few digits yourself.

**Comment by johnmcd88** [comment]
Hi,

I'd like to re-visit this feature request - I also rely heavily on metadata such as date/time when taking notes, since I take so many of them. I do understand the issue of the interface being too noisy, but how about a configuration option to automatically insert the date/time stamp (e.g. YYYY-MM-DD:HH:MM:SS, or something similar) as text when creating a new note?

Thanks for the continuing great work on this app!

John
