### ISSUE TITLE
Using Android App without Nextcloud Notes App enabled, does not tell the user that it is not working

### ISSUE THREAD

**Issue by SilPan** [stefan-niedermann/nextcloud-notes#956]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**
I wanted to use this awesome app together with my already existing NextCloud, but for some reason nothing was syncing.
After some digging it turns out it needs the NextCloud Notes App  enabled (server side), which makes perfect sense and is even documented here [https://apps.nextcloud.com/apps/nextcloud_notes_android_app](https://apps.nextcloud.com/apps/nextcloud_notes_android_app).

The synchronization icon stayed as a circle-arrow thingy, which I first interpreted as 'is was synchronized', because it never changed.

Sometimes it says `Synchronization failed: No network connection`, which is not true, the problem is the missing notes app on the server.

**Describe the solution you'd like**
In my opinion the Android App should detect if the app on the server is missing and inform the user about that exact issue, "Notes can not be synchronized because Nextcloud Notes is not enabled on the Nextcloud server you are connected to, please talk to your Nextcloud admin about this!"

**Additional context**
I do not administer the Nexctloud server I am using myself and therefore did not know about Nextcloud apps before I dug into this. And it took me some time to figure out what the issue was.

My point is, a regular user, who has a nexctloud account somewhere already, might just find this awesome app on f-droid/play and want to use it, but then has to wonder why it is not working.

So this is just an itzy bitzy tiny enhancement feature, but it save some people from a little frustration.

**Comment by stefan-niedermann** [comment]
It actually tries to detect a missing Notes installation (see corresponding error messages for [various (1)](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/res/values/strings.xml#L183) [cases (2)](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/res/values/strings.xml#L56)).

There are various different server setups and Nextcloud versions which all behave a little bit different.

Besides the technical detection it is explained and linked in the app store description.

If you have any further setup which is not covered by those cases, i would appreciate a Pull Request to cover it - as i told, i already tried what came to my mind and crossed my road, but i can't possibly know each constellation 🙂
