### ISSUE TITLE
Move favourite (star) button in context menu of notes

### ISSUE THREAD

**Issue by SamuXzX** [stefan-niedermann/nextcloud-notes#958]
**Is your feature request related to a problem? Please describe.**
At the left of every note, in the list view, there's the button to place the note in the favourites list. This is comfortable and helps distinguish every row like in an unordered list, but it takes a lot of space that could be used to display more characters of the title and of the first line of the note.

**Describe the solution you'd like**
Why not moving said button to the context menu (the one you see when long pressing on the note)? And not only in the menu of the single note, but in the multiple selection too.

**Describe alternatives you've considered**
It could be decided in the options of the app which layout (star at the left of the note or in the context menu) to use, but I suppose there's no need to such variety.

**Comment by stefan-niedermann** [comment]
We thought about it and talked in the past. We will keep the star as it provides an often used quick action. It also provides some kind of recognition as it is also there in the web ui of the files app etc.
