### ISSUE TITLE
Notes not syncing

### ISSUE THREAD

**Issue by thisIsMeHello** [stefan-niedermann/nextcloud-notes#968]
**Android version:** 10 Lineage OS 17.1

**Device**: Xiaomi Poco F1

**System language**: English (UK)

**App version:** 2.16.7 (Nextcloud 3.13.1)

**App source:** F-Droid

**Steps to reproduce:**

Write note, note appears in app, little blue syncing circle shows in notes list but doesn't go away, note doesn't sync. Have checked to make sure everything else - instant upload for photos/files etc all working fine. (Thanks for this great app, it is a core part of my life!)

**Comment by stefan-niedermann** [comment]
Hi, please try [these steps from our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error) for troubleshooting.

Does any error message appear when you pull to refresh?

**Comment by thisIsMeHello** [comment]
No error msg. 
I cleared storage and it's working again. Thanks.
