### ISSUE TITLE
Synchronisation fails

### ISSUE THREAD

**Issue by JensThanx** [stefan-niedermann/nextcloud-notes#972]
**Android version:** 10 (Kernel 4.9.218-perf+)

**Device**: Fairphone 3

**System language**: German

**App version:** v2.16.7

**App source:** F-Droid

**Steps to reproduce:**

1.   Have no or little internet connection (in my case WAN)
2.   open the app
3.  change a note (it will show as not synched)
4.   reconnect internet connection (in my case WLAN)
5.   open the app again
6.   error message: "Synchronisierung fehlgeschlagen: keine Netzwerkverbindung"
7.  try to force synch by pulling from above with same result

**Describe the bug**
Notes are not synched correctly. The error message (in German) says: "Synchronisierung fehlgeschlagen: keine Netzwerkverbindung", although both WLAN and WAN network are working.

**Expected behavior**
Synchronisation while network is available

**Workaround**
I force the app to stop in the Android settings. Afterwards the synchronisation worked well so far.

**Server**
Nextcloud 17.0.9

**Comment by stefan-niedermann** [comment]
Will be fixed with `2.17.0`, for more information see https://github.com/stefan-niedermann/nextcloud-notes/issues/537#issuecomment-674877453
