### ISSUE TITLE
display notes without titles - titles shouldn't be essential

### ISSUE THREAD

**Issue by furkanunluturkk** [stefan-niedermann/nextcloud-notes#974]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by stefan-niedermann** [comment]
I have absolutely no idea what you are trying to tell me. Try it again with a full sentence and fill the issue template.

[Why this issue has been closed](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed).
