### ISSUE TITLE
extension .md as default

### ISSUE THREAD

**Issue by markushub** [stefan-niedermann/nextcloud-notes#984]
**Is your feature request related to a problem? Please describe.**
Open notes files on pc - opens it in normal text viewer as normal text because of the extension .txt (no markdown format)

**Describe the solution you'd like**
Use .md for markdown as default extension for all new created notes

**Describe alternatives you've considered**
- change every notes title 
- manually rename later
- option [md, txt]

**Additional context**
If you need backward compatibility, create an option for default extension in settings.

**Comment by stefan-niedermann** [comment]
Theren is an option in the bottom left of the Web UI. The default has to be discussed in the repository of the web app. The android client is in fact not even aware of a file extension.

Web app issue tracker: https://github.com/nextcloud/notes/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=
