### ISSUE TITLE
Display confirm dialog when deleting an account with unsynchronized changes

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#989]
Given a user is on the "Manage accounts" activity
When he presses the :wastebasket: icon to delete an account
Then a confirm dialog should pop up in case there are any Notes with the database state `LOCAL_EDITED` to warn the user that the account has not synchronized changes.

**Comment by AlpAcA0072** [comment]
It will judged whether it is synchronized with the cloud before deleting it. If it is not synchronized, a confirmation confirm dialog will pop up and it would be deleted only after the user confirms it twice.
May I ask whether this idea is feasible?

**Comment by stefan-niedermann** [comment]
@AlpAcA0072 this is *exactly* what i described above 🙂

**Comment by AlpAcA0072** [comment]
@stefan-niedermann 
Hi, I'm struggling with this issue right now. I wonder if the method `onAccountDeleted` located in `MainActivity.java` is the method performing the function to delete a account. If it's not, what is the right approach?
Thanks a lot!

**Comment by stefan-niedermann** [comment]
@AlpAcA0072 i don't exactly understand what you want to know? Are you planning to provide a Pull Request to fix this issue? (In this case you should code against the `831-room` branch which contains a quite big refactoring and will (hopefully) get merged soon. Otherwise we will risc a few bad conflicts.

There the deletion starts in the `ManageAccountsActivity`. 🙂

**Comment by stefan-niedermann** [comment]
Will be fixed in `v3.4.1`
