### ISSUE TITLE
Matched content does not been rendered while search

### ISSUE THREAD

**Issue by Isaac-Graham** [stefan-niedermann/nextcloud-notes#999]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

When search some keywords in notes, the matched content will be rendered as blue.

However, when the content has been rendered,  if some new content, which matched the search keywords, is input, then the new input content does not been rendered.

For example:

I search "(" in the search input.
![image](https://user-images.githubusercontent.com/45254932/102710063-a7354a00-42ea-11eb-97de-692b05597006.png)
Then the corresponding matched contents are rendered. 

However, if I put some more matched content, then the new content does not be rendered.
![image](https://user-images.githubusercontent.com/45254932/102710114-0abf7780-42eb-11eb-8257-dbcff57eb4cb.png)

**To Reproduce**

1. Click one notes
2. Search some keywords
3. Add new content matched keywords
4. New content does not be rendered

**Expected behavior**

New contents are also rendered

**Screenshots**

Attached above

**Smartphone (please complete the following information):**

 - Nextcloud Notes-Version (android app):  dev
 - F-Droid or Play Store:  Self-compile
 - Android-Version: 29
 - Device: Pixel 3a AVD

**Server**

 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Confirmed. Side note: In the new Markwon based editor, this already behaves as expected.

**Comment by stefan-niedermann** [comment]
Fixed in `2.19.0`.
